### ISSUE TITLE
object position coordinates are always 0.0

### ISSUE THREAD

**Issue by fabiotarantino** [Rajawali/Rajawali#1014]
Hi,
i'm trying to retrieve the position of specific child object in the world coordinates. 
Maybe it's my fault, but everytime i call getPosition().x, getPosition().x, getPosition().y for every child (or parent) object, the value 0.0 is returned...
The same result with getX() or getWorldPosition().x or getScenePosition().x ...
What am i missing here?

thanks!

Fabio

**Comment by jwoolston** [comment]
Closing as duplicate of #1596. Progress will be reported there.
