### ISSUE TITLE
Main Activity lost GL Context

### ISSUE THREAD

**Issue by Ayrton81** [Rajawali/Rajawali#1026]
I have main activity that execute new rajawali activities (like the old Rajawali examples), but when the app come back to the main activity, the graphics context is gone but the activity work (with black screen).

**Comment by jjfster** [comment]
Just started using this project.  Thanks.

Was there ever a better solution to this problem/bug?

I have an app that plays HLS videos in one activity, so I need acceleration, but if I enable acceleration for this activity, then after coming from another section/activity of the app where Rajawali is used, this project has the black screen.

I disable hardware acceleration in the manifest, then enable it for just the one HLS activity btw.

**Comment by jwoolston** [comment]
There are some serious bugs in the material/texture lifecycle management that may be responsible for this. When you come back to the activity, try calling `GLES20#glIsProgram()` with the Material program handle and see what the result is.
