### ISSUE TITLE
Slow getObjectAt()

### ISSUE THREAD

**Issue by kostik1337** [Rajawali/Rajawali#1027]
I am using ObjectColorPicker on device Samsung Galaxy S4 GT-I9500 and I get getObjectAt(x, y) method very slow. I found that method GLES20.glReadPixels() at ObjectColorPicker.java, line 128 takes about 700 ms to get executed. On device Samsung Galaxy S4 GT-I9505 it all works OK. These devices have different GPUs - PowerVR SGX544MP3 and Adreno 320 respectively. Can someone help me with this?

**Comment by jwoolston** [comment]
Closing as wont-fix. This issue has been tracked to a OpenGL ES call. We can do nothing about the performance of reading back pixels as it is known to be slow in some cases, depending on what the manufacturer implements.
