### ISSUE TITLE
Object picking on .OBJ Object3D

### ISSUE THREAD

**Issue by Vballest** [Rajawali/Rajawali#1028]
Hello,
I am using the methods that let you know which object is selected.
In all cases it works perfectly but when I try to select an object loaded from an obj not working properly.

This is the code I'm using:

public void nuevaHoja (Object3D _seccionOriginal,
_escalaForzada float)
{
_escalaForzada = 1;
Random r = new Random ();
if (isMoving == false)
{
LoaderOBJ objParserNew = new LoaderOBJ (mContext.getResources () mTextureManager, R.raw.hoja_obj);
Object3D Object3D Sheet = new ();
try {
objParserNew.parse ();
Hoja = objParserNew.getParsedObject ();
} Catch (ParsingException e1) {
e1.printStackTrace ();
}
DiffuseMaterial DiffuseMaterial materials = new ();
material.setUseSingleColor (true);
Hoja.setMaterial (material);
Hoja.setColor (0x333333 + (int) (Math.random () * 0xCCCCCC));
Hoja.addLight (MLight);

Hoja.setX (_seccionOriginal.getX ());
Hoja.setY (_seccionOriginal.getY ());

mPicker.registerObject (Hoja);
 
Apparently it's the same code I use for objects "base" as spheres or cubes and works well.
I reviewed the examples and it seems it should work

Anyone know what I'm doing wrong and can help me?

Thank you very much,
Victor B

**Comment by jwoolston** [comment]
This is likely resolved as of #1614. Please create a new ticket if issues persist.
