### ISSUE TITLE
Tie animation to a seekbar

### ISSUE THREAD

**Issue by omnimethod** [Rajawali/Rajawali#1049]
Each frame in an md2 model has to be labeled so:
float animation = (float)animationSeekBar.getProgress();
if animation = 1 {
myMD2Object.play("frame1", false);
}else if(animation = 2){
myMD2Object.play("frame2", false);
}
and so on...
If there is an easier way maybe creating a function and calling it onEventChange?

**Comment by jwoolston** [comment]
Closing as not an issues as this is better suited to the community.
