### ISSUE TITLE
Can't get new scene to work in dev branch code

### ISSUE THREAD

**Issue by guavadrone** [Rajawali/Rajawali#1050]
I'm not using 0.9 because I wanted to use the new Scene features.

Basically I want to be able to completely build a new scene and replace the old one every time the user completes a task. I have a method to do this which is called from the main activity. It runs successfully (at least it runs all the way through), but after it has done so I get an error in logcat of the form 

09-10 16:26:26.084: A/libc(2838): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 2855 (Thread-7788)

the app freezes and then closes. I'm not at all familiar with the form of that error to know where to start.

the method, with most of the actual world building trimmed out (I've left the skysphere in there to show how I'm adding the children to the world)

    	public void createHoops(	){
		
		Log.d(TAG, "making new scene");
		RajawaliScene newScene = new RajawaliScene(this);
		
		Sphere mSphere = new Sphere(400, 8, 8);
		
        SimpleMaterial skyMaterial = (new SimpleMaterial());
        try {
			skyMaterial.addTexture(new Texture(R.drawable.skysphere));
		} catch (TextureException e) {
			e.printStackTrace();
		}
        mSphere.setMaterial(skyMaterial);
        mSphere.setDoubleSided(true);
        newScene.addChild(mSphere);
				
		Camera newCamera = new Camera();
		newCamera.setFarPlane(1000f);
		newScene.replaceAndSwitchCamera(newScene.getCamera(), newCamera);
		
		addScene(newScene);
		
		Log.d(TAG, "switching to new");
		RajawaliScene oldScene = getCurrentScene();
		switchScene(newScene);
		
		Log.d(TAG, "switched, destroying old");
		oldScene.destroyScene();

	}

**Comment by jwoolston** [comment]
I have not been able to reproduce this error. If a debuggable sample apk is available, I can look into it further.
