### ISSUE TITLE
Out Of Memory Errors

### ISSUE THREAD

**Issue by tenaciousRas** [Rajawali/Rajawali#1059]
branch:  master/80b26393af198f1514be0218da488037c0bc56b4
related(?):  https://github.com/MasDennis/Rajawali/issues/799

I'm writing a GCode parser for Android with Rajawali.  I'm getting out-of-memory errors when trying to build the 3d object.  It's early to say whether this is an actual problem, since the code is fresh, but I encountered this stack trace and I wanted to ask the team.

1)  Why does Object3D use CopyOnWriteArrayList for the class field "mChildren"?  Object3D's implementation never uses synchronized blocks as the Java spec recommends.  I'm not sure how to analyze this fact - is that proper?

2) #1 is probably related to #799.  When the mChildren arraylist becomes large, CopyOnWriteArrayList requires 2x the memory!

3)  Can we refactor Object3D to use a plain ArrayList, and can anybody offer guidance on edge cases for thread locking?

===================================
09-15 08:56:35.840: E/AndroidRuntime(30145): FATAL EXCEPTION: Thread-24122
09-15 08:56:35.840: E/AndroidRuntime(30145): java.lang.OutOfMemoryError
09-15 08:56:35.840: E/AndroidRuntime(30145): 	at java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:267)
09-15 08:56:35.840: E/AndroidRuntime(30145): 	at java.util.Collections$SynchronizedCollection.add(Collections.java:380)
09-15 08:56:35.840: E/AndroidRuntime(30145): 	at rajawali.Object3D.addChild(Object3D.java:502)
09-15 08:56:35.840: E/AndroidRuntime(30145): 	at rajawali.parser.LoaderGCode.readGCode(LoaderGCode.java:585)
09-15 08:56:35.840: E/AndroidRuntime(30145): 	at rajawali.parser.LoaderGCode.parse(LoaderGCode.java:473)
09-15 08:56:35.840: E/AndroidRuntime(30145): 	at com.terawattindustries.android.print3r.fragment.ThreeDObjViewerFragment$1.run(ThreeDObjViewerFragment.java:398)

**Comment by jwoolston** [comment]
Closing this issue as stale/abandoned. If it is still relevant, let me know.
