### ISSUE TITLE
Rajawali library - Texture is not loading through .obj

### ISSUE THREAD

**Issue by Dhrupal** [Rajawali/Rajawali#1064]
Hello,

I am struggling to render texture using this library. 
My Code is below,

ObjParser objParser = new ObjParser(mContext.getResources(), mTextureManager, R.raw.objtest);
objParser.parse();
mObjectGroup = objParser.getParsedObject();

Same as specified in sample. 

As specified in tutorial I have moved all images into nodpi folder. obj and mtl files are in raw folder.

I have exported obj from blender using right checked images. It is rendering texture properly in blender with "Render Images Option", but it is not able to render texture when i use option for "open GL render image"

Though with same approach Rajawali sample if loading texture properly. 

Is this seems to be a problem with obj file or way I am rendering the obj?

Please suggest.

**Comment by SarbarthaSengupta** [comment]
Hi, I am getting the same problem and I am using 512x512 images still no texture showing

import android.content.Context;
import android.util.Log;
import android.view.MotionEvent;

import org.rajawali3d.Object3D;
import org.rajawali3d.lights.ALight;
import org.rajawali3d.lights.DirectionalLight;
import org.rajawali3d.loader.LoaderOBJ;
import org.rajawali3d.loader.ParsingException;
import org.rajawali3d.materials.Material;
import org.rajawali3d.materials.methods.DiffuseMethod;
import org.rajawali3d.materials.textures.ATexture;
import org.rajawali3d.materials.textures.Texture;
import org.rajawali3d.math.vector.Vector3;
import org.rajawali3d.primitives.Sphere;
import org.rajawali3d.renderer.RajawaliRenderer;

import java.util.List;

public class Renderer extends RajawaliRenderer {
    private final Context context;
    private DirectionalLight directionalLight;
    private Object3D tableObj;
    private Sphere earth;
    private LoaderOBJ table;
    private  Material tableM;
    public Renderer(Context context) {
        super(context);
        this.context = context;
        setFrameRate(60);
    }

    @Override
    protected void initScene() {
        directionalLight = new DirectionalLight(0f, 5f, 0f);
        directionalLight.setLookAt(0,0,1);
        directionalLight.setColor(1.0f, 1.0f, 1.0f);
        directionalLight.setPower(2);
        getCurrentScene().addLight(directionalLight);

        try {
            loadTable();
        } catch (ParsingException e) {
            e.printStackTrace();
        }

        //earth = new Sphere((float) 0.5, 24, 24);
        //earth.setMaterial(material1);
       // getCurrentScene().addChild(earth);
        getCurrentCamera().setX(15f);
        getCurrentCamera().setZ(0f);
        getCurrentCamera().setY(15.2f);
        getCurrentCamera().setLookAt(0,0,1);
    }

    private void loadTable() throws ParsingException {
        Material material1 = new Material();
        material1.enableLighting(true);
        material1.setDiffuseMethod(new DiffuseMethod.Lambert());
        material1.setColor(0);
        table = new LoaderOBJ(this,R.raw.table_obj);
        table.parse();
        tableObj= table.getParsedObject();
        tableM = new Material();
        tableObj.setMaterial(material1);
        getCurrentScene().addChild(tableObj);
    }
    @Override
    public void onRender(final long elapsedTime, final double deltaTime) {
        super.onRender(elapsedTime, deltaTime);
//       tableObj.rotate(Vector3.Axis.Y, 1.0);

    }
    @Override
    public void onOffsetsChanged(float v, float v1, float v2, float v3, int i, int i1) {

    }

    @Override
    public void onTouchEvent(MotionEvent motionEvent) {

    }
}
