### ISSUE TITLE
Load MD2 textures from sdcard

### ISSUE THREAD

**Issue by omnimethod** [Rajawali/Rajawali#1068]
I cannot load any md2 models from the sdcard.
I can however load the md2 model from the sdcard 
but the .jpg / .tif / whatever must be in the res directory.

Why you no add the same code for loading  md2 materials from sdcard as you did the actual model?

**Comment by jwoolston** [comment]
Closing as stale/not an issue. Please open a new issue with more detail if you are still having problems.
