### ISSUE TITLE
How to make objects glow

### ISSUE THREAD

**Issue by fgnm** [Rajawali/Rajawali#1078]
Hi everyone, i'm a newbie in this fantastic world but i really like it :D
I nave a question : it's possible to make objects glow?
I think yes because i read some issue about this but i don't understend how do this.... i read something about two texture one for the object and the second for the glow effect but i don't understend how i can inseret them in a sphere for example 
Thanks in Advance ;-)

**Comment by ln206** [comment]
@alenko
Im trying to make an atmosphere as well. Could you please explain more about this solution? Thanks.
