### ISSUE TITLE
LoaderAWD - Models are mirrored

### ISSUE THREAD

**Issue by jawinn** [Rajawali/Rajawali#1084]
-Exported an AWD file from Away Builder
-Parsed and displayed w/ textures correctly
-Issue: Model is rotated 180 degrees on the Y, and mirrored. Rotation is not a big issue because I can do obj.setRotY(180), but I do not see a function to fix the mirroring.

**Comment by jwoolston** [comment]
Looking it to this, it is caused by the AWD coordinate system having -Z defined as "Forward" while we use +Z like OpenGL. A fix is coming.

**Comment by ToxicBakery** [comment]
Nice
