### ISSUE TITLE
Bug in setOrientation with Camera

### ISSUE THREAD

**Issue by grassick** [Rajawali/Rajawali#1088]
If camera.rotateAround is used to set the view direction, all objects disappear. This is because the mRotationMatrix is never initialized.

Changing code to add the last 3 lines in Camera.java seems to fix it.
```java
		if (mUseRotationMatrix == false && mRotationDirty) {
				setOrientation();
				mOrientation.toRotationMatrix(mRotationMatrix);
				mRotationDirty = false;
			}
			else if (mUseRotationMatrix == false) {
				mOrientation.toRotationMatrix(mRotationMatrix);
			}
```

Am I doing something wrong?

**Comment by jwoolston** [comment]
Closing as no longer relevant. The source is in a very different state from before. Please create a new issue if this problem still persists.
