### ISSUE TITLE
colorPickerTexture NullPointerException during Initalize as mType in RenderTargetTexture null.

### ISSUE THREAD

**Issue by leeicmobile** [Rajawali/Rajawali#1109]
The color Picker Texture uses the name only constructor  RenderTargetTexture(String textureName)

This does not set the mType property and subsequently a crash occurs when the RenderTargetTexture:add method is called at

GLES20.glTexImage2D

We are using the Master codeline as we are interested in scene switching and using the Vuforia library integration.

Switching the ObjectColorPicker to using RenderTargetTexture(String textureName, int width, int height) solved the NullPointerException it also allowed picking to occur however ever time any object in the scene is touched it evaulates to the 1st color index.

Any help would be appreciated, guidance about wither my approach was sound or if there was a certain reason the name only constructor was intended to be called.

Thanks,

Lee

**Comment by jwoolston** [comment]
This should be resolved as of #1614. Please create a new ticket if issues persist.
