### ISSUE TITLE
ObjectColorPicker always returns index 0 when any object picked

### ISSUE THREAD

**Issue by leeicmobile** [Rajawali/Rajawali#1110]
After applying the fix for #1109 you will find that anytime an object is picked the color index returned to ObjectColorPicker is 0.

It seems like during the refactor of Object3D some Picker Material setup was ommited.
Adding the lines indicated below appears to restore color picking functionality.

*Warning I am a novice in OpenGL and only recognised the pattern of API calls on the material, whilst reviewing 0.9 and the latest on Master, this may not be optimal and could have other unforseen knock on effects.

			if (pickerInfo != null && mIsPickingEnabled) {
				Material pickerMat = pickerInfo.getPicker().getMaterial();
				pickerMat.useProgram();
				----->>setShaderParams(camera);
				pickerMat.setColor(mPickingColorArray);
				          pickerMat.setVertices(mGeometry.getVertexBufferInfo().bufferHandle);
				----->>pickerMat.applyParams();
				----->>pickerMat.bindTextures();

**Comment by jwoolston** [comment]
Should be resolved as of #1614
