### ISSUE TITLE
Difficulty with RajawaliRenderer lifecycle

### ISSUE THREAD

**Issue by tenaciousRas** [Rajawali/Rajawali#1124]
I'm having a tough time getting a RajwaliRenderer to restore its state in my Fragment.  The renderer does its job fine when the fragment is first loaded - well specifically it is invoked by the main FragmentActivity but not shown until UI interaction occurs.  But then, if I unload the fragment in my FragmentActivity (note, I am not saying RajawaliFragment) and attempt to reload it again:  the RajawaliScene(s) will render again but scene animations or other behaviors cease to render.

Apparently when the Fragment is placed in the layout for the 2nd+ time, onDrawFrame() is only called twice.  Apparently RajawaliRenderer#startRendering() thinks that RajawaliRenderer#mTimer is non-null, so it doesn't do anything.  However, mTimer does not seem to be issuing RequestRenderTask() Runnables, or if it is -- then somehow #surfaceView became null so the issued Runnables have no effect.

All of this made me double-check how I'm handling what I'll call the Rajawali Lifecycle.

It appeared to me that I needed to invoke onVisibilityChanged(...) in onPause/onResume().  However, when I do this, I get some very strange destruction of the UI engine - the OS doesn't like it at all.

I've tried other techniques including things like surfaceView.resume(), surfaceView.pause(), surfaceView.onSurfaceDestroyed() -- but they don't work.  Don't work = the animation/interaction is not restored as expected; or the UI is hosed, or in the case of onSurfaceDestroyed -- that just leads to exceptions and seems like it's not really intended for the use-cases in my app.

RajawaliExamples does not have an example of what I'm trying to do.  That app's Activity does not cache the fragments or scenes; it just loads, unbinds/destroys, and re-loads them as the user navigates the app.  Ideally, a RajawaliExample that would work for me would be something like:  RajawaliExamples loads the Earth upon startup; user browsers to another example/fragment; user navigates back to Earth and it starts spinning from the same spot it was at when they left.  In this example the Earth animation might have to be slower to notice the position of the globe.

Does such an example exist or any suggestions for writing one?

**Comment by jwoolston** [comment]
Connecting this issue with #1394

**Comment by jwoolston** [comment]
The root issue has been resolved so I am closing this issue. The issue connection will serve to document other possible needs.
