### ISSUE TITLE
isInFrustum() not working

### ISSUE THREAD

**Issue by ghost** [Rajawali/Rajawali#1125]
I made a small program in which I have to know if a certain object is in Frustum or not.
After reading the issue #364 "Check if a model outside of the window" I tried to modify the BasicFragment.java in the RajawaliExamples to see if it works, but it still doesn't work

So as you suggested, I've added 2 lines in initscene() to the default BasicFragment.java:
mSphere.getGeometry().getBoundingBox();
mSphere.setFrustumTest(true);
and in the onDrawFrame:
if (mSphere.isInFrustum()) Log.d("test","IS IN FRUSTUM");
else Log.d("test","NOT IN FRUSTUM");
I've also tried with .getBoundingSphere();
The result is no matter if the sphere is visible or not, with the .getBoundingSphere() is always IN FRUSTUM and with .getBoundingBox() is never IN FRUSTUM
I worked with Rajawali master library and Rajawali Examples both released in 25.10.2013
Hope it helps

Thank you

**Comment by jwoolston** [comment]
I need to verify that this change has been merged in.

**Comment by jwoolston** [comment]
I can verify that this is not yet resolved.

**Comment by jwoolston** [comment]
I am moving this to `v1.1` because the fix exists with the scene graph which will be finished then.

**Comment by jwoolston** [comment]
The fix for this is long overdue and needs to be addressed ASAP

**Comment by jwoolston** [comment]
This is resolved in Camden Hells.
