### ISSUE TITLE
Uncaught Exceptions in RajawaliRenderer

### ISSUE THREAD

**Issue by tenaciousRas** [Rajawali/Rajawali#1126]
Rajawali depends on a task-based architecture for many things, such as RajawaliScene management.  Because of the task-based architecture, exceptions may be deferred until the task is executed.  This causes runtime exceptions and indefinitely expands the regression-testing surface-area.  In practice, tasks can be submitted that are invalid, and they will cause a runtime error.

Take, for example, RajawaliScene#internalReplaceScene.  In the current master branch the implementation is:

<code>
	private void internalReplaceScene(AFrameTask scene, RajawaliScene replace, int index) {
		if (index != AFrameTask.UNUSED_INDEX) {
			mScenes.set(index, replace);
		} else {
			mScenes.set(mScenes.indexOf(scene), replace);
		}
	}
</code>

Above will throw an uncaught exception with the following statement if the oldScene has already been removed (i.e., index != -1 but scene is already removed -- code falls into else clause).  This can happen, for example, if an earlier task replaced the same scene, whereas the caller has no way of knowing this and mistakenly issues a second invocation.  In such a case, this simple call will crash the Android app:
replaceScene(oldScene, newScene);

This strategy is adopted throughout RajawaliRenderer, and elsewhere in the SDK, so there are at least several edge-cases to watch out for.  A defensive-coding practice in this instance is to avoid NPE and IndexOutOfBounds exceptions and log them, exiting gracefully whenever possible.

Here's a potential fix for one method in RajawaliRenderer using try/catch - although a fix that checks the sizes/indexing of the lists would be more efficient:

<code>
	private void internalReplaceScene(AFrameTask scene, RajawaliScene replace, int index) {
		try {
			if (index != AFrameTask.UNUSED_INDEX) {
				mScenes.set(index, replace);
			} else {
				mScenes.set(mScenes.indexOf(scene), replace);
			}
		} catch (ArrayIndexOutOfBoundsException e) {
			RajLog.e(new StringBuilder().append("could not perform internal scene task\n")
					.append(Log.getStackTraceString(e)).toString());
		}
	}
</code>

**Comment by jwoolston** [comment]
Sometime in March/April of 2015 it appears I fixed this by wrapping the execution method of `AFrameTask` in a `try-catch` block and logging any exceptions.
