### ISSUE TITLE
V 9.0 Particles with a plane in the background

### ISSUE THREAD

**Issue by crescento** [Rajawali/Rajawali#1130]
Hi Friends,

I am trying to create a wallpaper where I have particle effects and a plane with a custom shader. The particles should float on the background plane with a custom shader.

What I find is that when I enable particles the shader on my background plane does not move with time.
But If I disable the particle emitter, the shader looks ok .
The shader that I am using is the simple one in the example section 

https://github.com/MasDennis/Rajawali/wiki/Tutorial-09-Creating-a-Custom-Material---GLSL-Shader

Regards,
Steve

**Comment by jwoolston** [comment]
Closing this issue as stale/abandoned.
