### ISSUE TITLE
Master - Memory Leaks on LWP

### ISSUE THREAD

**Issue by Bratanov** [Rajawali/Rajawali#1138]
First of all, thank to everyone for the good work on the library.
The problem is on the master branch, here's how to reproduce it:
Get the master branch and the LWP master branch tutorial.
Run it, start rotating from portrait to landscape mode. After 2-3 minutes I get the out of memory error:
```
11-24 00:14:36.003: D/memalloc(15321): /dev/pmem: Unmapping buffer base:0x520c5000 size:770048 offset:0
11-24 00:14:36.003: D/memalloc(15321): /dev/pmem: Mapped buffer base:0x5fc19000 size:1540096 offset:770048 fd:61
11-24 00:14:36.013: I/Adreno(15321): ioctl code 0xc00c092f (IOCTL_KGSL_GPMEM_ALLOC) failed: errno 12 Out of memory
11-24 00:14:36.013: I/Adreno(15321): ioctl code 0xc00c092f (IOCTL_KGSL_GPMEM_ALLOC) failed: errno 12 Out of memory
11-24 00:14:36.023: E/Adreno200-ES20(15321): <qgl2DrvAPI_glTexImage2D:433>: GL_OUT_OF_MEMORY
11-24 00:14:36.023: A/libc(15321): Fatal signal 11 (SIGSEGV) at 0x000002f4 (code=1)
```
Then the wallpaper restarts. Another way to reproduce this is if you set as wallpaper and check the memory usage it's 11MB, then you go in wallpaper preview mode, let it load and just close it, memory used is now 15MB and so on..
The device I'm using is Galaxy S Duos and it's bearable, I get more issues however when viewed on a tablet (TF300T), I could not hook the tablet to LogCat because it's not here (and I couldn't test the example on it), but that's the error I could log from my app:
```
java.lang.RuntimeException: OpenGL Error: out of memory 1285
at rajawali.renderer.RajawaliRenderer.onDrawFrame(RajawaliRenderer.java:509)
at com.bratanovinc.wallpaper.tardis.Renderer.onDrawFrame(Renderer.java:685)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1244)
```
The error is produced on rotating the screen when the wallpaper is set, rotating in preview mode seemed to work fine, but first or second rotation after setting the wallpaper produces this along with a black screen, sometimes the wallpaper manages to restart.
I'm aware the master branch is work in progress, but I quite like the recent changes. I built my app around the master branch, made a custom shader with the new generator and so on, migrating to 0.9 would be a pain and would probably cost some performance and features.
I'm looking for an advice on how to deal with the problem, is it the textures getting set into memory more than once, can I somehow keep a reference and clear them manually (there are no more than 4 textures), or is that not the problem and if so, how can I deal with it and patch it up?

**Comment by jwoolston** [comment]
I have tried to reproduce this and profiled it extensively. I created a test app that changes the texture and deletes the old one once per frame and could not reproduce this issue. As before, if someone wants to send me a debuggable apk demonstrating the problem, I can look into it further. Until then I am considering this to not be an issue with the library.
