### ISSUE TITLE
Keyframed animation, what the best for it?

### ISSUE THREAD

**Issue by lacasrac** [Rajawali/Rajawali#1139]
I have an animation in 3ds max, I use only Rajawali v0.9 at the moment. My question is: my file is 4000 triangle and 20 keyframe.

This is a memory killer when I load it in my live wallpaper in md2 or in my own filetype. (my own filetype memory is about 7 MB*2 because the Live wallpaper 2 instances)

So my questions are simple:

Is there a newer/faster/memory friender class/file type to handle animation meshes at the moment in Rajawali? I need a lot of frame later. So 4000 Triangle and 300 keyframe.

**Comment by jwoolston** [comment]
Closing this issue as stale. Please create a new issue with updated information if the problem still persists.
