### ISSUE TITLE
Problem loading OBJ from sdcard

### ISSUE THREAD

**Issue by lfrodrigues** [Rajawali/Rajawali#1141]
I want to render an OBJ that my app downloads from the web. But when I try to load it from the filesystem with: 
```
File f = new File(context.getExternalFilesDir(null), "golf1/3d/golf_obj");
LoaderOBJ objParser = new LoaderOBJ(this, f);
```
It loads the OBJ and MTL but then I get: 
```
[rajawali.materials.Material] Could not compile fragment shader: Shader log: 0:3: L0001: Expected token ';', found '.'
[rajawali.materials.Material] Could not compile fragment shader: Shader log: 0:4: L0001: Expected token ';', found '.'
```
And the app crashes. 

If I load from the resources with:
```
LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(), mTextureManager, R.raw.golf_obj);
```
It works fine.

The mtl, obj and jpg are all in the same directory (...)/golf1/3d/golf_obj and all of the them are read with no problems.

Can anyone please help me?

**Comment by jwoolston** [comment]
Closing this issue as stale. Please create a new issue if problems still persist with details relevant based on the latest master branch.
