### ISSUE TITLE
Is there any way to overlay 3D object upon camera preview ? 

### ISSUE THREAD

**Issue by hashmedia** [Rajawali/Rajawali#1145]
Hi.

I am new to RAJAWALI FRAMEWORK. Please Help me with the issue. I want to overlay 3D sphere over camera preview in android. Please Help me.

**Comment by bakedCouchPotato** [comment]
I would like to reopen this issue - this does not work.
Look at the [new issue](https://github.com/Rajawali/Rajawali/issues/1560) I posted.

**Comment by PerunServer** [comment]
Solved by:

https://github.com/Rajawali/Rajawali/blob/master/examples/src/main/java/org/rajawali3d/examples/examples/ui/TransparentSurfaceFragment.java

& 

https://github.com/Rajawali/Rajawali/blob/master/examples/src/main/java/org/rajawali3d/examples/examples/AExampleFragment.java
