### ISSUE TITLE
spritesheet frame error

### ISSUE THREAD

**Issue by bdcorps** [Rajawali/Rajawali#1158]
This is a very weird issue and I cannot find how it is happening. I have a sprite that 4X4 and the sprites iterate while misplacing a frame.
![sheet](https://f.cloud.github.com/assets/6132555/1818214/afba9ffc-6fea-11e3-8710-83b27380244c.png)
The iterate in this sequence: 1 2 3 4 <b>1</b> 6 7 8 <b>5</b> 10 11 12 <b>9</b> 14 15. Maybe someone here can explain the issue to me. This is the code I am using:
<code>
                        PointSprite pointSprite = new PointSprite(1, 1);
		        getCurrentScene().addChild(pointSprite);
			Material material = new Material();
			material.addTexture(new Texture("sheet", R.drawable.sheet));
			SpriteSheetMaterialPlugin spriteSheet = new                   SpriteSheetMaterialPlugin(
					4, 4, 1, 16);
			material.addPlugin(spriteSheet);
			material.setColorInfluence(0);
			spriteSheet.play();
			pointSprite.setMaterial(material);</code>

**Comment by jwoolston** [comment]
Closing as stale/abandoned. Please create a new issue with updated details if the problem still persists.
