### ISSUE TITLE
Rajwali Object Surface View in ANDROID XML LAYOUT

### ISSUE THREAD

**Issue by hashmedia** [Rajawali/Rajawali#1160]
I want to render 3D object render in Android XML Layout. Please suggest me solution. How to incorporate android XML layout and Rajwali Rederer.

**Comment by ParagRKadam** [comment]
@jwoolston : The link is broken ,can you please give a solution of how to insert the renderer in the layout. Thanks.

**Comment by ToxicBakery** [comment]
https://github.com/Rajawali/RajawaliExamples/blob/master/examples/src/main/java/com/monyetmabuk/rajawali/tutorials/examples/ui/UIElementsFragment.java

Everything is still in the examples just in new packages
