### ISSUE TITLE
Billboarding with setLookAt (on Rajawali version 9)

### ISSUE THREAD

**Issue by sanjith11** [Rajawali/Rajawali#1161]
Hi Friends,

I am trying to billboard a plane with an image.
What I have is a plane at (0,0,10) and the camera is at (0,0,-12)
Now to bill board what I have done is setting setLookAt to the camera position as below

this.plane.setLookAt(this.getCamera().getPosition())

Now on doing this what I have seen is that the plane is rotating on the z axis by 90 degrees.( the image is rotated by 90 degrees)If I remove the above line the plane looks fine.

Please let me know why is this behavior this way.
I don't see this going away even after rotating plane/camera.

Please help.

Thanks,

**Comment by jwoolston** [comment]
Closing as wont fix. We do not have the man power to devote to the v0.9 tag at present.
