### ISSUE TITLE
Couldn't Load materail (.mtl) file while importing obj file

### ISSUE THREAD

**Issue by hashmedia** [Rajawali/Rajawali#1164]
Hello,

I am importing fan_obj file and it has fan_mtl file. the file is exported from 3DS MAX and It has generated map folder which has 3 jpg file.

here is how directory structure.

raw/fan_obj
raw/fan_mtl
raw/maps/a.jpg
raw/maps/b.jpg
raw/maps/c.jpg

when importing to obj parser it does not load material from image files to the object 
please give me the solution

Thank you

**Comment by jwoolston** [comment]
Closing this issue as resolved.
