### ISSUE TITLE
Objet dissapears after rotateOver

### ISSUE THREAD

**Issue by semenoh** [Rajawali/Rajawali#1176]
I'm implementin rotation on touch functionality.
Issue described here https://github.com/MasDennis/Rajawali/issues/346#issuecomment-12956091 I solved with rotateOver(Vector3, angle) method and everithing worked well while I rotated it over X and Y axises separately. But now I'm going to do it with single rotation Over perpendicular vector to finger move like this:

mSphere.rotateAround(new Vector3(1, -dx/dy,0), dx+dy);

and my Sphere dissapears after the first rotation.

**Comment by jwoolston** [comment]
Closing this issue as no longer relevant. The transformation code is in a very different state now. Please try the latest master and open a new issue if problems arise.
