### ISSUE TITLE
Objects are always rotated befor scaled

### ISSUE THREAD

**Issue by NeroCor** [Rajawali/Rajawali#1178]
I cant define that I want to scale a Object befor rotating it.
So if I define a Cube like:

			mCube = new Cube(1);
			mCube.setMaterial(material);
			addChild(mCube); 
			mCube.setScale(1, 2, 1);

I get this (which is OK):
![screenshot_2014-01-30-14-33-39](https://f.cloud.github.com/assets/1777837/2040419/83310486-89b6-11e3-9a4a-1d5d185e47ad.png)

Now i want to Rotate it.
Code looks now like this:

			mCube = new Cube(1);
			mCube.setMaterial(material);
			addChild(mCube); 
			mCube.setScale(1, 2, 1);
			mCube.setRotZ(75);

What I expect:
![goal](https://f.cloud.github.com/assets/1777837/2040432/b302c1ae-89b6-11e3-9f08-7cbc5ef64cfd.png)

What I get:
![screenshot_2014-01-30-14-34-20](https://f.cloud.github.com/assets/1777837/2040464/2d162378-89b7-11e3-8c5b-8c9972918fa8.png)

So I think the vertices are being rotated befor scaled. 
But how can I Change this?

**Comment by jwoolston** [comment]
Model matrix calculation has been resolved. Closing as not relevant anymore. Please create a new issue if the latest master is causing problems still.
