### ISSUE TITLE
How do you create a rectangular box?

### ISSUE THREAD

**Issue by Tobiasartz** [Rajawali/Rajawali#1190]
I see that there is a Cube primitive, but that only allows me to create a perfect square box. How would I create a rectangular box where width, height and depth are different from each other?

**Comment by shayRom** [comment]
You can create a box using the cube primitive. you just need to change the scale of the appropriate axis. 
for example, creating a box that is 1 unit wide 2 units tall and 0.8 units in depth:
Cube box = new Cube(1);
box.setScaleX(1);
 box.setScaleY(2);
 box.setScaleZ(0.8);
