### ISSUE TITLE
Changing the Color of an Object happens not in the same Frame

### ISSUE THREAD

**Issue by NeroCor** [Rajawali/Rajawali#1199]
I noticed that if you change the Color of an Object with:

	Object3D cube= new Cube(1);
	...
	cube.setColor(Color.rgb(255, 255, 255));		

That this change is only shown in the next Frame, not the current.
(It also results in some strange behaviors if Objects share the same Material)

To Solve this I changed the order of some Code in the Object3D Class.

Object3D.java (Line 303) from:

				mMaterial.applyParams();
				if(mOverrideMaterialColor)
					mMaterial.setColor(mColor);

to:

				if(mOverrideMaterialColor)
					mMaterial.setColor(mColor);				
				mMaterial.applyParams();
				
I hope that helps some People with the same Problem.

**Comment by jwoolston** [comment]
Closing this issue as stale/abandoned.
