### ISSUE TITLE
Changing texture black screen

### ISSUE THREAD

**Issue by bdcorps** [Rajawali/Rajawali#1202]
This is a weird problem. I have a bitmap texture. I need to change it in onSurfaceChanged(). The code I am using is below:
<code>
	@Override
	public void onSurfaceChanged() {
  mPit.removeTexture(texture);
				texture = new Texture("texture", BitmapFactory.decodeResource(mContext.getResources(), R.drawable.pit_4));
				try {
					mPit.addTexture(texture);
				} catch (TextureException e) {
					e.printStackTrace();
				}}
</code>
<code>
	@Override
	public void onSurfaceDestroyed() {
		super.onSurfaceDestroyed();
		mPit.removeTexture(texture);}</code>

But this works the first time I open the wallpaper. The second time I just get a black screen. What is the correct way to change a bitmap texture?

PS: I also tried mTextureManager.replaceTexture(), but it produced same result.

**Comment by jwoolston** [comment]
Closing as resolved.
