### ISSUE TITLE
How to add texture at runtime?

### ISSUE THREAD

**Issue by anticafe** [Rajawali/Rajawali#1203]
I have downloaded an image from server. After finish, I pass its bitmap to the Renderer to  dynamically create and add a Plane to SurfaceView.

However, at this time I notice `mTextureManager` is NULL. It seems there is no way to add texture at runtime? Can you tell me how to bypass it?

**Comment by flankechen** [comment]
try to make the material in initialization. attach "blank" texture to it.
when your get desired image. 
try removeTexture/addTexture

**Comment by jwoolston** [comment]
Async management of objects/materials has been added to the library. Please reopen if this is still a problem with the latest master.
