### ISSUE TITLE
Problem in Camera Rotation v0.9

### ISSUE THREAD

**Issue by detonator123** [Rajawali/Rajawali#1214]
I need to give a complete 360 degree view in my live wallpaper so that the user can have a view in any direction of his choice. I was able to implement this very easily in Master branch just by using these 2 lines:

setLookAt(0,0,0);
mCamera.setRotation(0,xOffset,yOffset);

But then I switched to v0.9 branch and now the above code doesn't work. So,to find out the problem,I tried to check out rotation individually along each axis. I used 

setRotY(xOffset)
mCamera.setLookAt(0,0,0);

to rotate my camera along Y axis based on x axis swipe. But instead of rotating Camera around Y axis keeping my focus on origin, the camera started to rotate around an Axis parallel to Y axis but passing a bit above the location of my camera. Say my camera is at 0,0,6 so it started rotating around an axis parallel to Y but passing through 0,0,8.

So instead of using the rotate function, I thought of calculating co-ordinates and changing position of camera. I used,

mCamera.setPosition(6*(float) Math.sin(Math.toRadians(xOffset)),0,6*(float) Math.cos(Math.toRadians(xOffset)));

This code worked well while rotating on in horizontal plane ie about Y axis and I got complete 360 degree rotation but while using same approach along Y axis I got perfect rotation upto 90 degree(offset) but just above that, my Camera suddenly got inverted. So say at 89 degree the camera is looking from top of origin then just at above 90, say 91 the camera went below the origin. What could really be the issued behind this inversion?

And how can I rotate the camera along both axes X and Y so that the user is free to move his view in any direction?

**Comment by jwoolston** [comment]
Closing as wont fix. We do not have the man power to devote to the v0.9 tag at present.
