### ISSUE TITLE
Loading MD2 in different thread issue

### ISSUE THREAD

**Issue by sohamdutta13** [Rajawali/Rajawali#1215]
When i load a md2 file in an async task, everything works fine except for the animation function. The application closes when i use the LoaderMD2 to parse the md2 file from my sdcard in an async task runInBackground(). And once its loaded i try using the .play() function to start its animation. but the application closes after saying fatal signal.

**Comment by jwoolston** [comment]
Async Parsing has been added to the library. If the problem persists with the latest master, using the async parsing, please create a new issue with updated information.
