### ISSUE TITLE
Rotate Camera from touch

### ISSUE THREAD

**Issue by emanuelvaz** [Rajawali/Rajawali#1218]
Hi, I´m trying to write a sample code where I rotate the camera on my view by touching on the screen and moving, defining a simple orientation vector. I could make all the geometrical and mathematical calculations and apply the rotation transformation to the câmera, but I was thinking if there's alreay a simple and more practical way of doing it on Rajawali. 

Thanks for your atention, 

Regards, 

Emanuel

**Comment by jwoolston** [comment]
Closing as not an issue.
