### ISSUE TITLE
load an obj file with moving background in live wallpaper

### ISSUE THREAD

**Issue by Shima-Eslamifar** [Rajawali/Rajawali#1220]
I loaded an object in my live wallpaper using rajawali and it is static. I want to set an image as background that moves from right to left.
I'm very new to rajawali... I think that I should use Plane for it but I'm not sure!
and I wanted to try it but Plane.addTexture doesn't work!
can anyone help me to this?

**Comment by jwoolston** [comment]
Closing as not an issue. Please create a new issue with more details if you are still having problems.
