### ISSUE TITLE
Texture disappears after onSurfaceDestroyed() called

### ISSUE THREAD

**Issue by semenoh** [Rajawali/Rajawali#1229]
I've been getting OOM exception after few (4-5) surface changes until I set `shouldRecycle` to `true` but now texture disappears after surface is destroyed. After it is created again model becomes completely black. Here is my code:
```Java
	sphereMaterial = new Material();
	spheretexture = new Texture("earth", R.drawable.earthtr);
	spheretexture.shouldRecycle(true);
	sphereMaterial.addTexture(spheretexture);
```

`onSurfaceCreated()`, `onSurfaceChanged()` and `onSurfaceDestroyed()` are not overridden in my renderer.

**Comment by jwoolston** [comment]
Being black after a context loss is to be expected because it was unable to reload the texture. As for the out of memory exception, prior fixes and incoming ones will resolve.
