### ISSUE TITLE
Scene appears on screen with bigger deley after each next surface change

### ISSUE THREAD

**Issue by semenoh** [Rajawali/Rajawali#1230]
I've been getting OOM exception after few (4-5) surface changes until I set `shouldRecycle` to `true` (now texture disappears after surface is destroyed but it's another issue). Now app does not crash but picture appears on the screen each time with bigger delay after each surface change. While profiling this issue i figured out that the biggest part of time is used by `Geomerty3D.createBuffer` method while scene is reloading. The most interesting thing is that this method is caled the same amount times but each time it runs for a longer. For example on the second time surface changed it runs for `501.460 Incl Cpu Time and 203.317 Incl Real Time` but after the 7'th time it runs for `919.896 Incl Cpu Time and 946.354 Incl Real Time` and it's called for 869 times.

Here are a screenshots: 
![degradatin_2th](https://cloud.githubusercontent.com/assets/1703646/2682639/119cfbde-c19e-11e3-8aa3-17ae141ecb3d.png)

![degradatin_7th](https://cloud.githubusercontent.com/assets/1703646/2682640/15d82d22-c19e-11e3-90ff-bd422c7f06ca.png)

**Comment by jwoolston** [comment]
#1282

**Comment by jwoolston** [comment]
Using the latest version of Rajawali, I am not able to reproduce this. What I do see are large spikes during the transition before Android's GC runs. If you can send me and APK which demonstrates this, I can take a look at it further.
