### ISSUE TITLE
wrong drawerlayout after lock-unlock device.

### ISSUE THREAD

**Issue by efrencampillo** [Rajawali/Rajawali#1241]
Hi Every one, I'm developing with rajawali+vuforia example, I integrated this to my app, I have a inflated drawerlayout added to the UI.

from super class rajawali activity, we have :

protected FrameLayout mLayout;

this is on line 44, so in my activity extended from RajawaliVuforiaActivity, that extends from that class, i add a new view:

mLayout.addView(myInflatedView , new LayoutParams(LayoutParams.FILL_PARENT, LayoutParams.FILL_PARENT));

I put this addView inner InitRajawali() method, after the super.setRenderer() method.

to reproduce this you only need to lock and unlock device while you are on the app. this causes that drawer layout gets wrong paint. this doesn't happens when application  stops and resume with home button, or starting another activity, only when lock and unlock the app.

have any one some idea about it?

**Comment by jwoolston** [comment]
This is an issue with android UI not Rajawali.
