### ISSUE TITLE
Problem when repeating textures. 

### ISSUE THREAD

**Issue by RKanzler** [Rajawali/Rajawali#1243]
Hi, 

I've noticed a problem when i want to repeat a texture into the UVs. The problem consists in a pixalation of the texture repeated. It seems that is preserved just one instance of the texture, the other repetitions are all pixelate. It can be using ".setRepeat" into eclipse or importing an UV with repetitions from Blender. 

Any help?

**Comment by jwoolston** [comment]
Information is missing from this issue, perhaps a link has been broken. Closing the issue for now. Please update if problems still persist.
