### ISSUE TITLE
LensFlare Problem 

### ISSUE THREAD

**Issue by RKanzler** [Rajawali/Rajawali#1244]
Hi,
I'm a designer and i'm learning programming. I'm sorry if my questions are basic, but i'm really excited to learn more of Rajawali.

I'm having a problem whith the LensFlare plugin. When i install my LWP is unpredictable when i'm gonna see the Lensflare. I've noticed it changes always when the app restarts. For instance, the first time that the app runs i see it. Then i go to settings menu and come again and i dont see it any more. I set the Wallpaper and i see it again but with 50% of opacity. I run another app and come again and the flare is gone. If i run another app and come again and again the lens flare appears and dissapears. Sometimes it appears with semitransparency. 

Someone has seen this problem? 

I would appreciate some help.

**Comment by jwoolston** [comment]
There are no concrete details here to go off of. We would need to see some source code to determine if you are doing something wrong, as well as knowing which version of the library you are using. Closing for now. If you provide more information we can reopen the issue.
