### ISSUE TITLE
Lens dirt 

### ISSUE THREAD

**Issue by RKanzler** [Rajawali/Rajawali#1245]
I want to attach an image like this to my 3d camera lens to produce the effect of lens dirt in my Wallpaper. 

![lensdirt](https://cloud.githubusercontent.com/assets/7461290/2908756/327e4668-d62b-11e3-91bf-910ef4150a85.jpg)

I've read about some possibilities to do this like UI or  FBO, but i don´t know  which is the best one and how these work. 

What do you advise me?

**Comment by jwoolston** [comment]
Closing as resolved/abandoned.
