### ISSUE TITLE
Rajawali 3D object render different position and Rotation  independent from Phone gyroscope

### ISSUE THREAD

**Issue by f33744k** [Rajawali/Rajawali#1251]
i'm implementing 3D reconstruction of an architectural model, i'm trying to render my 3d Object at different position and rotated on my target, but when i run  my program, my 3D object at the correct position but its rotation depends on phone gyroscope.
 if i write as shown;
                       myObject.setVisible(true);
			myObject.setPosition(position);
			myObject.setOrientation(orientation);
3D object appear on target, and i can look at around 3D object independent from Gyroscope    

When i try to render as;
                       myObject.setVisible(true);
			myObject.setPosition(position.x-3,position.y+5,position.z-4);
			myObject.setOrientation(orientation);

or try to
                        myObject.rotateAround(new Vector3(2, 2, 2) , 90, true);            

My 3D object renders different position and rotated, but it's not stable, its moved and rotated dependent direction of view of camera, simply i cant look at around my 3D Object  independent from Gyroscope. 

Sorry for my bad english, i hope my question is clear.

 Any help is greatly appreciated!

fesih

**Comment by jwoolston** [comment]
It is not really clear what the issue here is. Please make an effort to clarify the problem vs. the expected behavior. Perhaps pictures will help with the language barrier. We will reopen the issue once you update it.
