### ISSUE TITLE
improve videoTexture quality

### ISSUE THREAD

**Issue by bdcorps** [Rajawali/Rajawali#1254]
Is there any way to improve the quality of a videoTexture. This is what I have:
<code>
 mVideoTexture = new VideoTexture("VideoLiveWallpaper", mMediaPlayer);</code>
<code>Config bitmapConfig =Config.RGB_565;</code>
<code>mVideoTexture.setBitmapConfig(bitmapConfig);</code>
        <code>mVideo = new Material();</code>
        <code>mVideo.setColorInfluence(0);</code>

[IMG]http://i62.tinypic.com/289lwg7.png[/IMG]
The left is actual video still and on the right is what it looks like on the phone.

**Comment by jwoolston** [comment]
The link no longer appears to work. Closing this issue as no longer valid. Please create a new issue if you are still having problems.
