### ISSUE TITLE
AResourceManager and multiple RajawaliRenderer instances

### ISSUE THREAD

**Issue by jreich888** [Rajawali/Rajawali#1256]
Hi, 
I'm trying to build an app with two simultaneous Rajawali fragments running in it.  If I only show a single fragment, each works fine.  However, when I use both, I get GL errors (GL_INVALID_VALUE) and will crash if I don't catch and ignore the RuntimeException thrown in RajawaliRenderer:OnDrawFrame() ("OpenGL Error: invalid value 1281").

If I catch the exception, the two views mostly work, but the textures only work in one of the views.  In the other, it looks like the materials/textures are invalid and the objects using them are rendered black.  

In my investigation, it seems that the AResourceManager is not handling two instances well; there are singletons of the MaterialManager and TextureManagers so all textures/materials from both fragments are going through the same objects.  That's fine, but...

The AResourceManager looks like it has half an implementation for dealing with multiple renderers.  It has a a single "mRenderer" field, and also a List "mRenderers".  However, almost all processing ends up going through the first mRenderer field.  Thus I suspect the textures from fragment B were setup by renderer A, and thus are invalid when renderer B tries to use them.  At least that's my working theory.

So how well does the master branch support multiple Rajawali Fragment instances, and do you have any suggestions for how to support this better?  Is this an area that is being worked on?

Thanks you for any advice you can give.

**Comment by jwoolston** [comment]
Closing this issue as abandoned. Please comment if the problem still persists.

**Comment by adamantivm** [comment]
Just wanted to add for the record that I believe this is an issue worth digging into further. I posted a related question in #1518. For one of my particular needs, I produced a "multi-scene renderer" of sorts: #1544 but now I'm faced with a different situation in which I again need to have more than one view.

**Comment by paulpv** [comment]
I think this is still a big problem.
If there is more than one rendered registered, as can happen in a ViewPager, then the last registered renderer wins.
A ViewPager typically loads the visible page, and then the immediately adjacent pages.
The off-screen pages are registered last, resulting in all texture and material tasks getting targeted to that off-screen renderer; the visible on-screen rendered never gets the textures/materials.

I think Rajawali's intention is that there is only one active renderer at a time.
The renderer is typically activated in onResume and deactivated in onPause.
However, even the non-active renderers need to load textures.

It seems to me that the basis of the TextureManager and MaterialManager is flawed.
The intention seems to be that multiple renderers can efficiently add duplicate textures and materials to the respective manager, and a single instance of those textures/materials will be saved.
The flaw is that those textures/materials are only added to the currently active renderer, when they should be available to all renderers.
