### ISSUE TITLE
Problem with VertexAnimationObject3D

### ISSUE THREAD

**Issue by tao05009** [Rajawali/Rajawali#1268]
I tried to add VertexAnimationObject3D into the scene using LoaderMD2. Then when I call ObjectColorPicker.getObjectAt(x, y), the exception is thrown (showing below).

07-01 14:57:20.073: W/Adreno-ES20(4287): <__load_uniform_float:815>: GL_INVALID_OPERATION
07-01 14:57:20.113: W/dalvikvm(4287): threadid=11: thread exiting with uncaught exception (group=0x415c5ba8)
07-01 14:57:20.113: E/AndroidRuntime(4287): FATAL EXCEPTION: GLThread 11020
07-01 14:57:20.113: E/AndroidRuntime(4287): Process: com.monyetmabuk.rajawali.tutorials, PID: 4287
07-01 14:57:20.113: E/AndroidRuntime(4287): java.lang.RuntimeException: OpenGL Error: invalid operation 1282
07-01 14:57:20.113: E/AndroidRuntime(4287): 	at rajawali.renderer.RajawaliRenderer.onDrawFrame(RajawaliRenderer.java:387)
07-01 14:57:20.113: E/AndroidRuntime(4287): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
07-01 14:57:20.113: E/AndroidRuntime(4287): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by jwoolston** [comment]
Closing this issue as stale/abandoned.
