### ISSUE TITLE
Matrix transpose bug in v0.9

### ISSUE THREAD

**Issue by bastei** [Rajawali/Rajawali#1269]
There was a fix for a bug in the matrix transpose function: https://github.com/MasDennis/Rajawali/issues/967

But unfortunately this bug is still in v0.9. As the readme of Rajawali says "use the v0.9 tag if you need a stable version" it would be good to provide a backport for this version.

**Comment by jwoolston** [comment]
Closing as wont fix. We do not have the man power to devote to the v0.9 tag at present.
