### ISSUE TITLE
Invalid Bitmap Format

### ISSUE THREAD

**Issue by JithinSunny** [Rajawali/Rajawali#1271]
I am trying to create bitmap from png images with option
 options.inPurgeable = true;
                    options.inInputShareable = true;
                    options.inSampleSize = sampleSize;
                    options.inDither = false;
                    options.inScaled = false;
                    options.inPreferredConfig=Bitmap.Config.RGB_565; 
since i think it reduces memory usage.But it cause a error at
 GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, mBitmapFormat, mBitmap, 0); in the class ASingleTexture;

But if i remove    options.inPreferredConfig=Bitmap.Config.RGB_565;  then no error occur but use high memory.How to solve this issue

**Comment by jwoolston** [comment]
Recent commits should have resolved this issue. Please create a new issue if the problem persists.
