### ISSUE TITLE
Unable to load background image in LWP 

### ISSUE THREAD

**Issue by senthamilthendral** [Rajawali/Rajawali#1275]
Hi,

    I am creating a wallpaper in android using rajawali framework.I can load the .obj file and rotate it perfectly.But now I am trying to place the background to that. For that I created one plane but it does not reflect. I am getting blank screen but the object was rendering without any problem.

    This is the code I am trying,

      public void initScene() {
		ALight light = new DirectionalLight();
		light.setPower(1);
		light.setPosition(0, 0, -4);
		mCamera.setPosition(0, 0, -7);
		mCamera.setLookAt(0, 0, 0);

		SimpleMaterial material = new SimpleMaterial();
		material.setUseColor(true);

		Plane	mPlaneLeft = new Plane(1, 1, 1, 1);
		mPlaneLeft.setMaterial(material);
		mPlaneLeft.setTransparent(true);
		mPlaneLeft.setColor(0x000000);
		mPlaneLeft.setZ(0.1f);
		mPlaneLeft.setX(0.25f);
		addChild(mPlaneLeft);
	
	    SimpleMaterial material1 = new SimpleMaterial();
	    Plane localPlane1 = new Plane(1,1,1,1);
	    localPlane1.setRotZ(-90.0F);
	    localPlane1.setScale(3.7F);
	    localPlane1.setPosition(1.0F, 1.0F, 20.0F);
	    localPlane1.setMaterial(material1);
	    localPlane1.setZ(17);
	    addChild(localPlane1);
		ObjParser parser = new ObjParser(this.mContext.getResources(), mTextureManager,R.raw.camaro_obj);
		try {
		parser.parse();
		} catch (ParsingException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
		}
		glob = parser.getParsedObject();
		glob.setMaterial(material1);
		addChild(glob);
	
		Number3D axis = new Number3D(3, 1, 6);
		axis.normalize();
		mAnim = new RotateAnimation3D(Axis.Y, 360);
		mAnim.setDuration(8000);
		mAnim.setRepeatCount(Animation3D.INFINITE);
		mAnim.setInterpolator(new AccelerateDecelerateInterpolator());
		mAnim.setTransformable3D(glob);
	}

**Comment by jwoolston** [comment]
This looks to be a very old version of the master branch. Closing as no longer relevant. Please try the latest master and create a new issue if the problem persists.
