### ISSUE TITLE
createContext() failed

### ISSUE THREAD

**Issue by xroberx** [Rajawali/Rajawali#128]
Hello, I got this error report from the developer console: 

java.lang.RuntimeException: createContext failed
at net.rbgrn.opengl.EglHelper.start(EglHelper.java:88)
at net.rbgrn.opengl.GLThread.guardedRun(GLThread.java:156)
at net.rbgrn.opengl.GLThread.run(GLThread.java:93)

The code works fine (with no errors) on more than 10000 devices, so I can't reproduce the error. Any idea why this happens ? The user told me the error is triggered when he tries to set the wallpaper... you know, the "Set as wallpaper..." button in the wallpaper preview.

**Comment by mandarini** [comment]
Same problem here, and I must say that it is device-capability specific. I get this error when I run my application on my Sony Xperia LT30p with backround processes disabled, the minimum pre-installed apps running and nothing more. I have about 300MB free of RAM. Still, when I run the application this error shows up.

I ran the application with no problem whatsoever on a Samsung Galaxy Tab 4 and on a Nexus device.

I have not found a solution and have tried a lot of suggestions.
