### ISSUE TITLE
Rajawali Memory (de)Allocation

### ISSUE THREAD

**Issue by StScAllen** [Rajawali/Rajawali#1282]
I have written a small test program to make sure I am doing resource allocation/destruction correctly and either there is a bug or I am doing something seriously wrong here.  Is there anyone who is willing to review my test code?  Its pretty small - just four classes and a couple pngs.  I'm basically just creating a plane and attaching a large texture, then every second I am destroying the object and reloading it with a different large texture.  After about 30 secs Debug.getNativeHeapAllocatedSize() goes from 6mb to 172mb, then about 30 secs later it shoots to 300, then to ~500, then it just crashes for out of memory.  Might help with ongoing efforts to track down memory leaks, but mostly I am concerned I am doing something wrong.

Thanks!

**Comment by jwoolston** [comment]
Adding to version `1.1 Bombshell` with the other memory leak issues.

**Comment by jwoolston** [comment]
#1610

**Comment by jwoolston** [comment]
Closing this as semi-resolved. Changes have been made to improve things on this front, however fully automatic behavior is not going to be possible with the current design of the engine. See #1610 for more information here.
