### ISSUE TITLE
SphereMapMaterial can't be applied  to sphere

### ISSUE THREAD

**Issue by fulean** [Rajawali/Rajawali#1286]
in the example 28: "Sphere Mapping, if  the origin SerializedObject3D jet1 be replaced by a sphere created by new Sphere(...),and don't touch anything other of  the source code,the apperance of sphere don't have the smooth and specular effect which origin case have,what's may cause this issue ? and how i can make a sphere with beautiful specular and smooth appearance ? thanks.

**Comment by jwoolston** [comment]
How many sections did you build your sphere with? Odds are if it is not as smooth as you want, there were not enough triangles defined.

**Comment by jwoolston** [comment]
Closing as stale/abandoned. Please comment if problems persist.
