### ISSUE TITLE
Problems creating video plane :(

### ISSUE THREAD

**Issue by theChumpus** [Rajawali/Rajawali#1290]
Hi there,

Firstly, thanks for all your efforts - this library has helped me immensely so far!

I'm trying to create a video plane using the VR library but for some reason every time I create a plane, it doesn't show on screen. No errors in the log, just doesn't show.

If I create another object (such as a cube or sphere) the video displays on the object with no problem!

Can you think of any reason why this could be? I'm using the developer library (rather than v0.9) due to needing the SideBySideRenderer but other than that, not sure. The fact that it works fine on other objects makes me think I've just missed something when it comes to the Plane.

Here is my initScene, if it helps:

```
public void initScene() {
    try {
        mLight = new DirectionalLight(0, 0, 1);
        mLight.setPower(2);
        getCurrentScene().addLight(mLight);

        getCurrentCamera().setZ(4.2f);

        // Create media player
        mMediaPlayer = MediaPlayer.create(getContext(), R.raw.sintel);

        // Create video texture and apply to material
        mVideoTexture = new VideoTexture("VideoTexture", mMediaPlayer);  
        Material mVideo = new Material();
        mVideo.setColorInfluence(0);
        mVideo.addTexture(mVideoTexture);

        // Create object
        Object3D object = new Cube(3f);
        //Object3D object = new Plane(3f,3f,1,1,1); // DOESN'T WORK!
        object.setMaterial(mVideo);
        object.setZ(-6);
        object.setRotZ(180f); //  Rotate as video texture displays up-side-down
        getCurrentScene().addChild(object);

        mMediaPlayer.start();

    } catch (TextureException e) {
        e.printStackTrace();
    }

    super.initScene();
}
```

Thanks for any help!

**Comment by jwoolston** [comment]
Are you calling updateTexture in your render loop?

**Comment by jwoolston** [comment]
Closing this issue as stale/resolved.
