### ISSUE TITLE
Question about ChaseCamera

### ISSUE THREAD

**Issue by HihoHa** [Rajawali/Rajawali#1294]
Hi. I am trying to use chase camera in a game and I just don't know how to use it properly. What I want to do is to develop a third person game with rajawali. But when I use the chase camera, the resulted view is a side view of the main character. The chasing functionality is fine, but I just want to have the camera behind the character like any other third person game, not beside it. Many thanks for your help.
By the way, thank you very much for making such a great library.

**Comment by jwoolston** [comment]
Closing as stale/abandoned. Please comment if the problem persists.
