### ISSUE TITLE
How create automatically moving plane (moving image)?

### ISSUE THREAD

**Issue by unknowpc90** [Rajawali/Rajawali#1296]
Hi all,
I' beginner with Rajawali. I'm working project that have a soccer ball and goal. I had created a soccer ball completely (Sphere). Now, I want to create a automatically moving goal (it is on top of screen) and it moving from left and right and reverse. How i create it (create it by Plane?)? Futhermore, I want to process collision between soccer ball and goal, if ball contact goal, ball will get first positon. How code it? Thanks

**Comment by jwoolston** [comment]
Any of the animations can be used to accomplish this task. Take a look at the examples to see many of them in use. The wiki also includes a how to regarding animations for both the `v0.9` tag and the `master` branch.
