### ISSUE TITLE
[Tag v0.9] Picking(Color Picking) does not work properly when app is not fullscreen

### ISSUE THREAD

**Issue by abhishekBansal** [Rajawali/Rajawali#1302]
Hi, 

ObjectColorPicking gives unexpected results when app is not full screen. It does not take actual size of GLSurfaceView in account. It can be reproduced with following code
https://github.com/abhishekBansal/Android_Experiments/tree/master/3DGraphics/Rajawali/RajawaliPickingTest

In RajawaliExampleActivity.java if following two lines are commented in OnCreate() picking gives wrong results. I am printing picked object coordinates as Log.
requestWindowFeature(Window.FEATURE_NO_TITLE);
getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

Thank You
-Abhishek Bansal

**Comment by jwoolston** [comment]
Since this is a bug in the `v0.9` tag and we are trying to focus on development of the next release, I don't see anyone taking the time to fix this in the tree. Closing as a wont-fix.
