### ISSUE TITLE
Changing material uniforms on runtime only updates for object which was drawn in last (Verified with official example with V0.9)

### ISSUE THREAD

**Issue by abhishekBansal** [Rajawali/Rajawali#1304]
Hi,

If scene is containing multiple objects with same material and in `onDrawFrame()` new values for uniforms are set. That will only reflect on the object which was added in scene in last. I made following changes in `CustomMaterial/Shader` example.

new variables
```Java
private BaseObject3D mSphere2;
private CustomMaterial mCustomMaterial2;
```

```Java
initScene () {
...
..

		mCustomMaterial = new CustomMaterial();
		mCustomMaterial2 = new CustomMaterial();
...
...		
		mSphere2 = new Sphere(2, 32, 32);
		mSphere2.addLight(mLight);
		mSphere2.setMaterial(mCustomMaterial2);
		mSphere2.setY(-2);
		addChild(mSphere2);
...
...
}
```

in onDrawFrame()

```Java
public void onDrawFrame(GL10 glUnused) {
...
...

mCustomMaterial2.setTime(mTime);
		mSphere2.setRotX(mSphere.getRotX() + 1);
		mSphere2.setRotY(mSphere.getRotY() + 1);
...
}
```

Surprisingly only second sphere gets time updates after this. First sphere material will be static. I have tested on multiple devices. I have been struggling with this in one of my projects  from quite sometime. It seems a bug in framework itself now.

**Comment by jwoolston** [comment]
This likely is a bug, but we are far removed from handling updates to the v0.9 tag as we just dont have the manpower. If you want to fix it and submit a pull request, we will happily accept it. Closing as wont fix.
