### ISSUE TITLE
OpenGL Error: invalid operation 1282

### ISSUE THREAD

**Issue by whymoon** [Rajawali/Rajawali#1317]
I imported an obj file in project RajawaliVuforiaExample, the file was exported with blender.

LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(), mTextureManager, R.raw.a_obj);
objParser.parse();
mObject = objParser.getParsedObject();
getCurrentScene().addChild(mObject);

I traced the error:
in RajawaliRenderer.java file
in public void onDrawFrame(GL10 glUnused) method
near this lines:

    public void onDrawFrame(GL10 glUnused) {
        performFrameTasks(); //Execute any pending frame tasks
        synchronized (mNextSceneLock) { 
            //Check if we need to switch the scene, and if so, do it.
            if (mNextScene != null) {
                switchSceneDirect(mNextScene);
                mNextScene = null;
            }
        }

        final double deltaTime = (SystemClock.elapsedRealtime() - mLastRender) / 1000d;
        mLastRender = SystemClock.elapsedRealtime();

        onRender(deltaTime);

        ++mFrameCount;
        if (mFrameCount % 50 == 0) {
            long now = System.nanoTime();
            double elapsedS = (now - mStartTime) / 1.0e9;
            double msPerFrame = (1000 * elapsedS / mFrameCount);
            mLastMeasuredFPS = 1000 / msPerFrame;

            mFrameCount = 0;
            mStartTime = now;

            if(mFPSUpdateListener != null)
                mFPSUpdateListener.onFPSUpdate(mLastMeasuredFPS); //Update the FPS listener
        }

        int error = glUnused.glGetError();

        if(error > 0)
        {
            if(error != mLastReportedGLError)
            {
                mLastReportedGLError = error;
                throw new RuntimeException("OpenGL Error: " + GLU.gluErrorString(error) + " " + error);
            }
        } else {
        mLastReportedGLError = 0;
        }
    }
Can someone help me?
Thanks!

**Comment by jwoolston** [comment]
Closing as stale/abandoned. Please comment if you are still having trouble.
