### ISSUE TITLE
Obj parsed object not cloned

### ISSUE THREAD

**Issue by JakubDziworski** [Rajawali/Rajawali#1321]
Object3D mShoeRight;
			Object3D mShoeLeft;

			LoaderOBJ shoeParser = new LoaderOBJ(mContext.getResources(),
					mTextureManager, R.raw.shoe);
			try {	
				mShoeRight = shoeParser.getParsedObject();
				mShoeRight.setPosition(2,0,-15);
				getCurrentScene().addChild(mShoeRight);
				
				mShoeLeft = mShoeRight.clone(true);
				mShoeLeft.setPosition(-2,0,-15);
				getCurrentScene().addChild(mShoeLeft);

			} catch (ParsingException e) {
				e.printStackTrace();
			}

Using this code I can only see shoeRight. Why it wont clone?

**Comment by jwoolston** [comment]
Closing this as abandoned/resolved. Please comment if the issue still persists.
