### ISSUE TITLE
validate_display:256 error 3001 (EGL_NOT_INITIALIZED)

### ISSUE THREAD

**Issue by changjiashuai** [Rajawali/Rajawali#1322]
VideoTexture example hava  a problem validate_display:256 error 3001 (EGL_NOT_INITIALIZED) and the video can not play?

**Comment by jwoolston** [comment]
Please provide a complete stack trace of the issue so we can better see what is happening.

**Comment by jwoolston** [comment]
Closing as stale/abandoned. Will reopen if more information is provided.
