### ISSUE TITLE
Object color picking not working with object hierarchies in the Master branch

### ISSUE THREAD

**Issue by mofr108** [Rajawali/Rajawali#1325]
Hi everyone :-)

It seems that using ObjectColorPicker only works on objects direcly add to the
scene, and not if the objects are child objects of a parent which is added to the scene.

A small change in the Examples ObjectPickingFragment.java illustrates this:

Instead of adding  mMonkey1,.. mMonkey4 direcly to the current scene, they are added as children of
a group-object, which is then added to the scene. If this group object is not registered with mPicker,
no picking accurs. If the group is registered with mPicker, then the hole group is selected when clicking
the first of the monkeys, and not the others.

Object3D group = new Object3D();

mMonkey1 = new Object3D(serializedMonkey);
(...)
group.addChild(mMonkey1);

mMonkey2 = mMonkey1.clone();
(...)
group.addChild(mMonkey2);

mMonkey3 = mMonkey1.clone();
(...)
group.addChild(mMonkey3);

mMonkey4 = mMonkey1.clone();
(...)
group.addChild(mMonkey4);

mPicker.registerObject(mMonkey1);
mPicker.registerObject(mMonkey2);
mPicker.registerObject(mMonkey3);
mPicker.registerObject(mMonkey4);

mPicker.registerObject(group);
getCurrentScene().addChild(group);

Am I missing something ?

As I build my scenes using different groups of objects it would be very helpfull if the picking also
could be used on individual child objects.

Thanks for answers.... :-)

**Comment by jwoolston** [comment]
Moving to anchor steam for a review look.

**Comment by jwoolston** [comment]
Should be fixed as of #1614
