### ISSUE TITLE
How to change the texture of a 3D model from an onClick event in RajawaliVuforia?

### ISSUE THREAD

**Issue by SarahPotter** [Rajawali/Rajawali#1330]
I have a "Change Color" option in the action bar of the "RajawaliVuforiaExampleActivity" class. When I click on that option, a sub-menu appears with two color options (color1 and color2). When I click on color1, I want the texture of the 3d model displayed on the screen to change based on that selected option. How do I do that ?

Knowing that the 3d object is ini awd format.

**Comment by jwoolston** [comment]
TextureManager has methods to update the contents of a texture. If you want to leave the old texture intact you can simply update the texture on the object's material to the new texture.
