### ISSUE TITLE
Rotation of part of Object3D around its center

### ISSUE THREAD

**Issue by jhavelik** [Rajawali/Rajawali#1331]
Hi, I would like to rotate part of Object3D (one of childen of parsed OBJ file) around its object center. For example if i have airplane with rotor(propeller) whitch is not in center of whole OBJ object I want rotor to rotate around its center in one of the axis (Z for example).
So far i have tried RotateAroundAnimation3D, RotateAnimation3D and RotateOnAxisAnimation with no good result (it seems to rotate always around point 0,0,0).

Anyone knows proper way to do this?

**Comment by jwoolston** [comment]
This *should* be possible in the current form. If it is not, it is a bug and an issue demonstrating that should be opened instead.
