### ISSUE TITLE
Change material color on Obj object?

### ISSUE THREAD

**Issue by jloffredo** [Rajawali/Rajawali#1332]
I have an OBJ with 4 materials. Is it possible to change those materials colors after the model has been parsed and loaded?

Thanks!

**Comment by jwoolston** [comment]
The methods exist on the `Material` class. Have you even tried them?

**Comment by jloffredo** [comment]
But how do I identify each material?

**Comment by jwoolston** [comment]
You will have to change the material on the resulting objects. Typically OBJ files should have the child objects named, so you  can find the objects by name and apply whichever new material you wish. Rajawali does not track materials other than by the object(s) they are attached to. Perhaps an argument could be made for a String keyed map. For what you want though, you can simply `Object3D.getMaterial()` to get the material and then change the color from there.

**Comment by jwoolston** [comment]
Closing as stale/resolved. Please comment if you are still having issues.
