### ISSUE TITLE
Damping for Catmull Rom Spline

### ISSUE THREAD

**Issue by kuoliangkwong** [Rajawali/Rajawali#1333]
Hi,

Does rajawali's Catmull Rom Spline come with physics damping? If no, is there anyway to implement it?

**Comment by jwoolston** [comment]
I'm going to assume you are referring to damping an animation over the spline. The spline itself is nothing more than a definition of a path. If you animate over it with the current animation framework, you could use/implement an Android Interpolator which will simulate whatever physics you want based on time. Optionally, you could use the new frame callback system (see `ASceneFrameCallback`) to simulate your physics. 

If you are referring instead to using a Catmull-Rom spline to simulate a damped sine wave, then the answer is still no, but you could easily create a point generator to feed damped points to the spline or damp the amplitude after the fact.

**Comment by jwoolston** [comment]
Closing as stale/resolved. Please comment if you are still having issues.
