### ISSUE TITLE
StringIndexOutOfBoundsException when trying to load FBX

### ISSUE THREAD

**Issue by paulcanning** [Rajawali/Rajawali#1334]
I get "rajawali.parser.ParsingException: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=1" when trying to use my own FBX file in the FBX example loader.

LoaderFBX parser = new LoaderFBX(this, R.raw.myfbx);
				parser.parse();
				Object3D o = parser.getParsedObject();
				o.setScale(0.5);
				getCurrentScene().addChild(o);

Error is at "rajawali.parser.fbx.LoaderFBX.parse(LoaderFBX.java:139)"

**Comment by jwoolston** [comment]
See my response to #1335
