### ISSUE TITLE
FBX requirements?

### ISSUE THREAD

**Issue by paulcanning** [Rajawali/Rajawali#1335]
I am having issues trying to use my own FBX files.

The example file works fine, but when I try to import the example FBX into my 3D application, it fails to open. It even fails in Autodesk FBX Viewer.

My FBX files load fine in this viewer, but do not load in Rajawali.

Can anyone shed some light on this?

**Comment by jwoolston** [comment]
The FBX loader is the least reliable loader in the library. FBX is technically a closed format, in spite of it being an ASCII file. Until someone wants to try to decode the format, its support will be limited. Efforts will be expended on open source formats such as AWD and DAE in the future. In the meantime, you can use the Away3D Away Builder tool to convert the file to AWD.
