### ISSUE TITLE
Transparent mSurfaceView background problem

### ISSUE THREAD

**Issue by oakraw** [Rajawali/Rajawali#1340]
![image](https://cloud.githubusercontent.com/assets/5005318/5694072/28fa0784-9972-11e4-92fb-1c34f5d6cad0.png)

I'm a beginner for Rajawali. I need to make a game that render a model on camera view. The problem is when I set setGLBackgroundTransparent(true), it will set mSurfaceView to top. That make all models overlap my interface such as a button at right bottom corner. I want mSurfaceView to Transparent but don't want to overlap ui so how can I fix this.

Sorry for my bad English.

**Comment by jwoolston** [comment]
Try using the new `RajawaliTextureView` and setting the view alpha to be transparent.

**Comment by jwoolston** [comment]
Closing issue as stale/abandoned.
