### ISSUE TITLE
[Help] Rotating the Camera in place.

### ISSUE THREAD

**Issue by mcteo** [Rajawali/Rajawali#1346]
Not an issue, but just wondering how it is done.

I have a 3D scene rendered, and set the position of the camera offset from the origin (e.g. set to (10, 1, 10)).

Is it possible to rotate the camera without changing its position? Maybe I'm misunderstanding, but how would say a user controlled view move around the 3D environment? Should the camera swivel, or the world move around while the camera remains fixed? I've tried a few different methods, but while something like:
```
obj.setRotY(obj.getRotY() + 1);
```
 works for a Object3D, it rotates the camera relative to the origin.

Also, it would be really handy to have something in the documentation that shows the format of angles, for example, is it Radians, Degrees, or Degrees normalised to [0, 1], or even [-1, +1]?

**Comment by jwoolston** [comment]
The javadoc of the relevant methods should state the units. If a particular function does not, then its simply a matter of having missed it. You can file a specific issue against each one, or better yet submit a pull request fixing it. That aside, `Camera` like `Object3D` inherits from `ATransformable3D`, therefore it can be moved and rotated like any other object. Note though that if you move or rotate the camera, its look at target will have changed and if you want it to stay oriented at a particular point in space, you will need to call `Camera.lookAt()` after to motion.

**Comment by jwoolston** [comment]
Closing as stale/resolved. Please comment if you are still having trouble.
