### ISSUE TITLE
Dynamically load new texture for Object3D

### ISSUE THREAD

**Issue by RootSoft** [Rajawali/Rajawali#1350]
I'm having trouble loading a new texture for an Object3D object on runtime.
I create my Object and Material on initScene and when i trigger an event, i want to dynamically change the Texture of the object. I get it working with the following code:

    public void changeImage(String drawable) {
        if (!isVideo) {

            for (ATexture texture : imageMaterial.getTextureList()) {
                imageMaterial.removeTexture(texture);
                texture = null;

            }

            try {
                Texture t = new Texture("sphereTexture", getContext().getResources().getIdentifier(drawable, "drawable", getContext().getPackageName()));
                t.shouldRecycle(true);
                imageMaterial.addTexture(t);
            } catch (ATexture.TextureException e) {
                Log.i(TAG, "Texture error: " + e.getMessage());
            } catch (OutOfMemoryError oom) {
                Log.i(TAG, "Out Of Memory error: " + oom.getMessage());
            }
        }
    }

This works for me, but results in an OOM (Out Of Memory Exception) after a couple of triggers. So i'd like to know what the best practice is for changing the texture of an object dynamically

**Comment by jwoolston** [comment]
What resolution are the textures you are using?

**Comment by jwoolston** [comment]
Closing as stale/abandoned. Please comment if you are still having problems.

**Comment by SarbarthaSengupta** [comment]
he posted the problem in Feb23 and you are replying on mar1 ... how can you expect him to be around??? Anyway I am also having the same issue ... 

I have posted it in several thrads of yours ... still no response from any owners I got :(

**Comment by jwoolston** [comment]
I asked a follow up on the 12th (not 1st) and closed it on the 22nd. Experience has shown if people who post a question don't respond within 10 days, they aren't going to, and if they do, we can always re-open.

**Comment by ParagRKadam** [comment]
I am also facing the same problem. I want to change the texture of a sphere ,dynamically triggered by an event. Please tell me the best practice to use in order to achieve it , Thanks in advance  :)

**Comment by ParagRKadam** [comment]
RootSoft's code is perfectly working for me...but it is not giving me OOM exception after 2 triggers rather i am getting that exception after 30-40 triggers. Which is not a big concern for me,
Did you get any solution for this problem though?

**Comment by dcerisano** [comment]
Tracing the flow of material.removeTexture(), does not call   gl_deleteTexture to free GL memory.
You must also call texture.remove() to do this.

**Comment by jwoolston** [comment]
@dcerisano's response is correct. Closing this issue as resolved/wont-fix. While we could (and plan to) attempt to determine when the developer has abandoned a texture, it is not simple and will always have some tradeoffs to deal with. The issue he describes with textures being shared between materials has at least one open ticket for eventual resolution but the developer will always need to be careful about what they use for textures.
