### ISSUE TITLE
Animated GIF & Alpha Channel

### ISSUE THREAD

**Issue by venomouswaste89** [Rajawali/Rajawali#1355]
Hi,

Currently i'm working on a live wallpaper project and i'm using animated gifs with alpha channel. i successfully added gifs with making the plane's transparency's true. but when i update the gif i see a strange behaviour. it renders the animated gif over and over frame by frame on the stage and it does't clear the previous frame. it's like making the onion skin property on in adobe flash professional program. 

here is the render of a scene :  
![2015-03-07-15-24-28](https://cloud.githubusercontent.com/assets/11364524/6541945/8cb65548-c4f1-11e4-802d-f6c331e2ed92.jpg)

**Comment by jwoolston** [comment]
Adding bug tag and removing support as it looks like a user was able to reproduce and fix this issue.
