### ISSUE TITLE
Projection matrix of camera should be set when the scene switches cameras

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1370]
@kiranpradeep discovered that the projection matrix of a camera is only set in `onSurfaceChanged()`. This is problematic when creating a new camera and switching without a surface change event. This needs to be corrected by updating the projection matrix during the camera switch: https://github.com/MasDennis/Rajawali/blob/master/rajawali/src/main/java/rajawali/scene/RajawaliScene.java#L720.

**Comment by jwoolston** [comment]
Fixed via 25188708c6351b6f8bb489367c796a04ad1e68b8. Thanks to @kiranpradeep for discovering this.

**Comment by kiranpradeep** [comment]
@jwoolston  If user had earlier set a projection matrix on `OrthographicCamera`, wouldn't it be lost when camera switches ?

**Comment by jwoolston** [comment]
Yes. I am assuming the camera should always be based on the viewport dimensions. I had not considered other use cases, but am open to discussing them if you have one.

**Comment by kiranpradeep** [comment]
@jwoolston When not going full screen ( with 2d arena dimensions ) as in this breakout example - https://code.google.com/p/android-breakout/source/browse/src/com/faddensoft/breakout/GameSurfaceRenderer.java#119.

**Comment by jwoolston** [comment]
alright. Should be a simple fix if we add a few custom parameters to the scene

**Comment by jwoolston** [comment]
@kiranpradeep I have implemented this in another branch, though in testing it i was not able to achieve a difference between the projection matrix and viewport dimensions. I'll have to do some debugging to see whats going on.

**Comment by kiranpradeep** [comment]
@jwoolston I could be wrong. Just letting you know my thoughts.
- Shouldn't it be user's responsibility to set camera's projection matrix in `initScene()` rather than Rajawali taking care of it in `RajawaliRenderer::setViewport` and then during camera switch ? 
- Is  `RajawaliScene::updateProjectionMatrix` a must ? Who ever wants to set the projection matrix, should set it directly on camera.
- In `RajawaliRenderer::onSurfaceChanged()`, call `setViewPort()` before `initScene()` so that if user wishes, he could have set a different viewport from `initScene()` itself.

**Comment by jwoolston** [comment]
> Shouldn't it be user's responsibility to set camera's projection matrix in initScene() rather than Rajawali taking care of it in RajawaliRenderer::setViewport and then during camera switch ?

I think perhaps it should be done through a method which can be overridden. The whole idea with Rajawali is to free users from having to think about things like this, but allow them to do so if they choose. 

> Is RajawaliScene::updateProjectionMatrix a must ? Who ever wants to set the projection matrix, should set it directly on camera.

See the above response, but yes. I agree its not common, but some people may want to.

> In RajawaliRenderer::onSurfaceChanged(), call setViewPort() before initScene() so that if user wishes, he could have set a different viewport from initScene() itself.

I may have misunderstood your goal before. Are you looking to set a viewport dimension different from the surface view dimensions that android has set, or are you looking to modify the projection matrix that is applied?

**Comment by kiranpradeep** [comment]
@jwoolston  I was feeling like too many things were being done in Rajawali just to free the user setting  Camera dimensions during a camera switch. Also was feeling like projection matrix is property of camera and not RajawaliScene for it to have a member like `updateProjectionMatrix()`.
I hadn't earlier understood the idea was to free user from that kind of thoughts. Thanks for the clarity.

About 3rd point, yes, I was thinking of a case when viewport dimensions was different from surfaceview dimensions as in the breakout example mentioned in an above post.

**Comment by jwoolston** [comment]
@kiranpradeep That clarifies things. I agree with your case for the 3rd point and I can modify my changes to accommodate that. In the process, I will make sure the API is present for the user to not need to worry about projection matrix stuff but I will provide a means for the behavior to be overriden by a user who wishes to.

**Comment by jwoolston** [comment]
This will be taken care of as part of #1404 due to the changes in surface view/texture view.

**Comment by kiranpradeep** [comment]
@jwoolston Thanks. That texture view addition will be awesome.

**Comment by jwoolston** [comment]
@kiranpradeep yea, in your case you would likely want to just use the texture option. The real problem is that surface view is counted as another window to android and so weird things happen if you arent full screen.

**Comment by jwoolston** [comment]
Fixed in branch `issue-1404`. Will be merged in soon.
