### ISSUE TITLE
Possible bug in rendering 2D planes with materials.

### ISSUE THREAD

**Issue by mcteo** [Rajawali/Rajawali#1374]
Hey guys, I think I found a bug when rendering a array of Planes.

Can someone else run the following code with the master branch, and see is the result as expected?

The expected outcome is that all the raised parts, should be the same colour, but instead I get all the colours offset by one. This seems to happen with planes next to any other primitive too.

From investigating this a bit, I think the answer might be in the Lambert Diffuse Shader, since the same problem doesn't seem to occur with the Toon Shader.

![RenderBug](https://cloud.githubusercontent.com/assets/700257/6647529/1e03b2e6-c9c7-11e4-9535-bd95e028bfdf.png)

```java
public class MyRenderer extends RajawaliRenderer {
    public MyRenderer(Context context) {
        super(context);
        setFrameRate(60);
    }
/*
    Renders the below image using 2D planes, with the Pattern coloured, and raised.
    ..........
    .########.
    .#......#.
    .###..###.
    ...#..#...
    ...#..#...
    ...#..#...
    ...#..#...
    ...####...
    ..........
*/  
    public void initScene() {
        getCurrentScene().setBackgroundColor(Color.LTGRAY);

        ALight mLight = new PointLight();
        mLight.setPosition(0f, 1f, 0f);
        mLight.setPower(5.0f);
        getCurrentScene().addLight(mLight);

        getCurrentCamera().setPosition(0f, 15f, 5f);
        getCurrentCamera().setLookAt(0f, 0f, 0f);

        Material material = new Material();
        material.enableLighting(true);
        material.setDiffuseMethod(new DiffuseMethod.Lambert());

        int[] red = new int[]{11, 12, 13, 14, 15, 16, 17, 18, 21, 28, 31, 32, 33, 36, 37, 38, 43, 46, 53, 56, 63, 66, 73, 76, 83, 84, 85, 86};

        StringBuilder sb = new StringBuilder();

        for (int i = -5; i < 5; i++) {
            for (int j = -5; j < 5; j++) {
                Object3D plane = new Plane(1f, 1f, 1, 1, Vector3.Axis.Y);
                plane.setPosition(i, 0f, j);
                plane.setMaterial(material);

                int color = 0xff00ff00;
                char icon = '.';
                for (int k = 0; k < red.length; k++) {
                    if ((((i + 6) * 10) + j - 5) == red[k]) {
                        plane.setPosition(i, +1f, j);
                        color = 0xffff0000;
                        icon = '#';
                        break;
                    }
                }
                plane.setColor(color);
                sb.append(icon);
                getCurrentScene().addChild(plane);
            }
            sb.append("\n");
        }
        System.out.println(sb.toString());
    }

    @Override
    public void onDrawFrame(GL10 unused) {
        super.onDrawFrame(unused);
        getCurrentCamera().setRotY((getCurrentCamera().getRotY() + 1) % 360.0);
    }
}
```

**Comment by jwoolston** [comment]
@mcteo I will try later tonight/tomorrow.

**Comment by mcteo** [comment]
I am on a pretty tight deadline for a project, so I investigated this a bit more myself. It works okay if I use a separate material for the raised planes, than the lower planes. So it could be something with how the materials and the colours of the objects interact? Which would probably mean a shader problem?

**Comment by jwoolston** [comment]
Yes, it would seem that when the shader program is loaded, it is receiving the wrong color information based to its input. If you can move forward, I am removing the support label but will file this as a bug against the current development.

**Comment by mcteo** [comment]
Hey, just wondering, but is there any known problems with using more than one material? For some reason when I use more than one different materials, it seems to turn off light diffusion on them all?

**Comment by jwoolston** [comment]
I am not currently aware of one. If you have some code which can demonstrate this (or if the code above does) then we can continue to look into it more.

**Comment by jwoolston** [comment]
I can confirm this bug and we can move forward looking into it. Given some of the previous issues which have been fixed, it seems reasonable that there may be an index issue here.

**Comment by jwoolston** [comment]
Turns out this was a simple issue - the material was having its parameters set prior to the color, so each object was getting the color of the object before it.
