### ISSUE TITLE
Panoramic view with skybox?

### ISSUE THREAD

**Issue by uzman** [Rajawali/Rajawali#1375]
Hi,
i am newbie for rajawali.
what do you advise for a panoramic screen? i use skybox method for it.

getCurrentScene().setSkybox(R.drawable.posx, R.drawable.negx, R.drawable.posy, R.drawable.negy, R.drawable.posz, R.drawable.negz);

when i try to use 2MB image file, it gives out of memory. is it normal or what is the optimum size for panoramic view?

thanks...

**Comment by jwoolston** [comment]
2MB is a huge texture. Most GPUs only have room for a few 2048x2048 sized textures. As for optimum size, that can only be defined as the "minimum size to show the level of detail you need." You should also use ETC1 texture compression, especially in this case since transparency is not needed.

**Comment by jwoolston** [comment]
Closing as stale/resolved. Please comment if you are still having issues.
