### ISSUE TITLE
Convert RajLog to use resource based enable/disable

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1389]
Change all RajLog calls to use resource based checks for function calls to help prevent unnecessary string creation.

**Comment by ToxicBakery** [comment]
Didn't even buy me dinner first.. 
![tumblr_inline_mjtpe6cd2s1qz4rgp](https://cloud.githubusercontent.com/assets/1614281/6702132/198f7040-ccfd-11e4-8ebc-f5bc7f2ce958.gif)

**Comment by jwoolston** [comment]
@ToxicBakery just make it happen :facepunch:

**Comment by StScAllen** [comment]
I did some work on RajLog last year and would be happy to work on this task if you could provide more information. Unless @ToxicBakery really wants it. :)

**Comment by jwoolston** [comment]
@StScAllen The idea is that if a value resource such as a boolean is true, logging should be eneabled, and if false, disabled. Then, in the gradle build script, we can have that boolean set to true for snapshots/debug builds and false for published builds. Additionally, consuming developers could override the resource value.

**Comment by ToxicBakery** [comment]
![img_20150408_202659](https://cloud.githubusercontent.com/assets/1614281/7058392/43ee0340-de2f-11e4-91dc-d3a3d7b66dd9.jpg)

Alright, I'm ready.

**Comment by jwoolston** [comment]
I approve.

**Comment by ToxicBakery** [comment]
Decided against the resource based checking as mentioned and instead just cleaned up logging. Performance critical areas like loops now avoid string generation entirely if logging is off.
