### ISSUE TITLE
ObjParser unhandeled exception

### ISSUE THREAD

**Issue by NinjaSkillZ** [Rajawali/Rajawali#1390]
Hi,
I got difficulties getting the ObjParser to work. To be more specific in this code:

		ObjParser ParserObj = new ObjParser(mContext.getResources(), mTextureManager, R.raw.grey);
		ParserObj.parse();
		BaseObject3D mGrey = ParserObj.getParsedObject();
		addChild(mGrey);

I get "Unhandled exception type Aparser.Parsingexception" error message on the second line ( ParserObj.parse(); )

Can anyone suggest whats the problem please ?

Thanks in advance for your effort

**Comment by jwoolston** [comment]
The exceptions are intentionally unhandled, allowing the developer to find problems in their models. Since you are using the `ObjParser`, most likely the model is not in a format compatible with Rajawali's OBJ parser. This is a common occurrence as the OBJ specification has numerous issues and leaves a lot open to interpretation. Instructions for making the model compliant with our parser exist on the wiki.

**Comment by ToxicBakery** [comment]
http://docs.oracle.com/javase/tutorial/essential/exceptions/definition.html

**Comment by NinjaSkillZ** [comment]
@jwoolston 
Well, so as the file was from 3Dmax I tried to re-export it thru Blender with the recommended settings - unfortunately with the same error. I also tried to create brand new OBJ file in blender containing simple torus just to be sure if there is not any other problem with the OBJ and still the same error occurs.

I thought that the parser runs when the application is run, so I thought that the app should crash when the parser fail to parse the OBJ file, but I get the error on the line in eclipse before I can even run the app so it seems much more like a code error to me, but I dont know where the error could be as it is from tutorial.

@ToxicBakery 
Im not sure why u put link to the definition of an exception, maybe I missed something ?
I mean, I know what is an exception, but I dont understand why such a simple code from tutorial doesnt work and also I dont know how to find what is the reason of the exception.

Also can I ask why you close my issue if it was not solved yet ?

**Comment by ToxicBakery** [comment]
I closed this issue as its not an engine problem, this is a problem of not catching the exception which is a static code compilation issue.

```
try {
    ObjParser ParserObj = new ObjParser(mContext.getResources(), mTextureManager, R.raw.grey);
    ParserObj.parse();
    BaseObject3D mGrey = ParserObj.getParsedObject();
    addChild(mGrey);
} catch (Exception e) {e.printStackTrace()};
```

The issues for actual engine issues not general help. Please use the G+ community or the stackoverflow Rajawali tag for general issues.

**Comment by NinjaSkillZ** [comment]
@ToxicBakery 
Great, thank you very much for the explanation and for the code, now it works without any exception.
