### ISSUE TITLE
Implement use of Android's GLDebugHelper

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1397]
Android includes a handy class `GLDebugHelper` ([see here](http://developer.android.com/reference/android/opengl/GLDebugHelper.html)). It works by wrapping the GL context with a special debugging one. We should implement a debug mode where we automatically apply this to provide an easy to use way of debugging things, instead of the one check for GL errors at the end of the frame.

**Comment by ToxicBakery** [comment]
Just make sure its optional for places that the context is not available like the current Wear API.

**Comment by jwoolston** [comment]
> Just make sure its optional for places that the context is not available like the current Wear API.

No. You get no options here! :smile: It would always be optional. It would require the user to explicitly call some code during the setup process.
