### ISSUE TITLE
Should RajawaliActivity be eliminated

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1398]
I am opening a discussion about whether or not it makes sense to eliminate`RajawaliActivity` in `Anchor Steam` which is now `v1.0` instead of `v0.10`. I would like input especially from the other devs, but also from anyone who uses the library. 

I feel it is time to eliminate the class as it fills no need that I can conceive of which can not be handled by `RajawaliFragment` or `RajawaliSupportFragment` and it is another life cycle element which needs to be maintained. At this point, it is slated to be removed by me, unless some reasonable arguments can be made to keep it.

**Comment by ToxicBakery** [comment]
I'm against it as I have lately been completely against fragments.

**Comment by jwoolston** [comment]
@ToxicBakery perhaps a better solution then would be extending `GLSurfaceView` and adding a basic life cycle interface to it, eliminating all higher level items all together?

**Comment by ToxicBakery** [comment]
That's more agreeable if it can work properly like that between both activities and fragments

**Comment by jwoolston** [comment]
I see no reason why it cant. All the surface view needs is to know when it needs to pause/resume. With fragments which are in a complex layout such as a view pager thats a bit tricky because fragments often have `onResume()` called even when they are not visible to the user. If we were only concerned about wrapping up a view then this wouldnt matter to us. As it is right now, we have essentially the same code in 3 classes - `RajawaliActivity`, `RajawaliFragment` and `RajawaliSupportFragment`, but with a few subtle differences. In the case of the two fragments, they are literally identical except for the class they extend from. Since Activities and Fragments have slightly different lifecycles, the differences between the activity and fragment implementations in Rajawali are small, but enough to make updating for bugs a major pain. I can't really get behind providing an activity implementation without fragments, but I could agree to removing both and making a more encapsulated `GLSurfaceView` descendant.

**Comment by ToxicBakery** [comment]
What about need to use textureview instead. A dedicated wrapper to either might be better.

**Comment by jwoolston** [comment]
TextureView is a Canvas based surface isnt it? Do you mean SurfaceTexture instead?

**Comment by MasDennis** [comment]
It makes sense to do this. So it will be in a new class that can be instantiated by a Fragment or an Activity?

**Comment by ToxicBakery** [comment]
@jwoolston Nope

"Unlike SurfaceView, TextureView does not create a separate window but behaves as a regular View. This key difference allows a TextureView to be moved, transformed, animated, etc."

**Comment by jwoolston** [comment]
> It makes sense to do this. So it will be in a new class that can be instantiated by a Fragment or an Activity?

Yes. It would be no different than adding any other view to a layout. With the exception of what Ian points out of course.

**Comment by dcerisano** [comment]
Since the first thing most people do is subclass the RajawaliActivity class due to the naming requirement in the manifest, and there not much going on there that cannot be handled in the RajawaliFragment class, it may indeed be a good idea to deprecate it.

The RajawaliActvity subclass RajawaliVRActivity will then have to be rebased. This would be a good test of any new design.

Just a "headsup", (pun intended).

**Comment by jwoolston** [comment]
Sounds like the general consensus is not against it. I will create a new ticket to outline the changes.
