### ISSUE TITLE
Cloned Object3Ds don't have names

### ISSUE THREAD

**Issue by C0br4** [Rajawali/Rajawali#1399]
When an `Object3D` is cloned from another `Object3D`, the name attribute should be cloned too.

This is very problematic if you want to get Childs of a cloned `Object3D` as you can't use `getChildByName()` anymore.

**Comment by jwoolston** [comment]
@C0br4 I assume you will be submitting a pull request and I have just encountered this issue early?

**Comment by C0br4** [comment]
@jwoolston Yes that was my intention. Feel free to dismiss it and make the change yourself.

**Comment by jwoolston** [comment]
@C0br4 wouldn't dream of it. I have no intention on stomping on someone else's name coming into the tree. By encountering early I meant seeing the issue in the list before you sent the pull request.
