### ISSUE TITLE
How to know if user looks at specific point/area?

### ISSUE THREAD

**Issue by uzman** [Rajawali/Rajawali#1402]
Hi,
i want to change the skybox photo if user looks at the area (that i define before) for a two seconds.
is it possible?

**Comment by jwoolston** [comment]
Yes of course it is possible. You will need to implement your logic to detect the event and then changing the skybox is as simple as asking `RajawaliScene` to switch to your new skybox. Closing as not an issue.

**Comment by uzman** [comment]
thanks.
but i don't know how to detect the event. is there any sample or code snippet?

**Comment by ToxicBakery** [comment]
When you rotate a camera you mathematically know what you are looking at. Rajawali does not have any function to indicate if the camera center intersects an object in space so you would have to write this logic yourself.
