### ISSUE TITLE
Eliminate RajawaliActivty and RajawaliFragment

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1404]
## Background/Goal

Following the discussion in #1398, and coinciding with #1394 and #1395, we will be removing `RajawaliActivity`, `RajawaliFragment` and `RajawaliSupportFragment`. In their place will be two new classes:

- `RajawaliSurfaceView`: This would most often be the view to use. 
- `RajawaliTextureView`: This is very useful if you wish to apply standard Android API view transformations on the view. 

These classes can be handled like ordinary views in Android, being added anywhere to a layout - Ideally we will have them support XML layout as well.

Per #1394/#1395, `RajawaliRenderer` needs to be simplified to remove its dependence on `GLSurfaceView`. The interface methods required of `GLSurfaceView.Renderer` and `TextureView.SurfaceTextureListener`, while having different signatures, accomplish the same task. To this end, a unified interface for these callbacks can be created, and a delegate used to invoke them on `RajawaliRenderer`. There would be two of these delegate classes:

- `RajawaliSurfaceView.RendererDelegate`: This would implement `GLSurfaceView.Renderer` and be registered with `RajawaliSurfaceView.setRenderer(...)`
- `RajawaliTextureView.RendererDelegate`: This would implement `TextureView.SurfaceTextureListener` and be registered with `RajawaliTextureView.setSurfaceTextureListener(...)

## The Common Interface: `IRajawaliSurfaceRenderer`

- `void onRenderSurfaceCreated(EGLConfig config, Object surface, int width, int height)`: This corresponds to `TextureView.SurfaceTextureListener.onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height)` and `GLSurfaceView.Renderer.onSurfaceCreated (GL10 gl, EGLConfig config)`. Unused params would just be passed as `null` or 0. The `surface` param would need to be cast by the delegate to either `SurfaceTexture` or `GL10` as appropriate.

- `boolean onRenderSufaceDestroyed(SurfaceTexture surface)`: This corresponds to  `boolean TextureView.SurfaceTextureListener.onSurfaceTextureDestroyed(SurfaceTexture surface)` and has no use in from `GLSurfaceView.Renderer`.

- `void onRenderSurfaceSizeChanged(Object surface, int width, int height)`: This corresponds to `void TextureView.SurfaceTextureListener.onSurfaceChanged(SurfaceTexture surface, int width, int height)` and `void GLSurfaceView.onSurfaceChanged (GL10 gl, int width, int height)`. The `surface` param would need to be cast by the delegate to either `SurfaceTexture` or `GL10` as appropriate.

- `void onDrawFrame(Object surface)`: This corresponds to `void TextureView.SurfaceTextureListener.onSurfaceTextureUpdated(SurfaceTexture surface)` and `void GLSurfaceView.Renderer.onDrawFrame (GL10 gl)`. The `surface` param would need to be cast by the delegate to either `SurfaceTexture` or `GL10` as appropriate.

## The Outcome
To this end, `RajawaliRenderer` and its subclasses would break all dependency on `GLSurfaceView` and have simple lifecycle callbacks which could be used in any situation, even without a screen. When a `RajawaliRenderer` is registered with either `RajawaliSurfaceView` or `RajawaliTextureView`, it will automatically create and set the appropriate delegate. At this point the work flow should be no different to the developer. 

## Steps

1. [x] Implement `RajawaliSurfaceView` and its delegate, converting `RajawaliRenderer to use it`
2. [x] Implement `RajawaliTextureView`
3. [x] Make `RajawaliRenderer` properly handle the cases when it matters if the view is a surface view vs. texture view
4. [x] Add custom attributes for configuring the views - includes frame rate
5. [x] Wrap up lifecycle from RajawaliFragment
6. [x] Implement fix for #1370
7. [x] Add example demonstrating texture view usage.
8. [x] Debug
9. [x] Cleanup

**Comment by MasDennis** [comment]
Looks like a good solution to me. Go for it! :+1:

**Comment by jwoolston** [comment]
Done. On to the cleanup.
