### ISSUE TITLE
Is it possible for a child object have setLoookAt working?

### ISSUE THREAD

**Issue by minimalviking** [Rajawali/Rajawali#1405]
I have sphere, create several objects and place them on the sphere's surface and add them as the sphere's children (so when the sphere is rotated/scaled they stay in correct place on the sphere's surface)

Now the complicated part: is it possible for those objects to __also always face the camera__ (camera is static, never moves)? I tried calling `setLookAt(camera.getPosition());`  before adding as a child / after adding as a child / every frame - none of them has any effect.

Is it possible to achieve this? (I'm using master from about 2 weeks ago)

**Comment by jwoolston** [comment]
You need to call that at the start of each onDrawFrame() in your Renderer subclass.

**Comment by jwoolston** [comment]
BTW, this need is considered a problem and is in the process of being resolved any day now.

**Comment by minimalviking** [comment]
That's awesome, thanks!

**Comment by jwoolston** [comment]
Closing as resolved.
