### ISSUE TITLE
Eliminate SerializedObject3D

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1410]
As part of the on-going cleanup, I would like to eliminate `SerializedObject3D`. Initially it served a vital purpose - binary model loading. AWD can accomplish this now and more, and the recent package name change demonstrates the fragile nature of the serialized objects. I am planning to remove this unless @MasDennis vetos it. @ToxicBakery is already on board.

**Comment by MasDennis** [comment]
Do it.

![Woolston Rampage](https://i.imgflip.com/jal26.jpg)

**Comment by jwoolston** [comment]
@MasDennis I'm saving that one. :+1:

**Comment by dcerisano** [comment]
SerializedObject3D is/was useful for handling various 3D object formats after import since it is/was the common superclass.

Noticing that AnchorSteam is really going to be a completely different beastie than the existing stable release. There is going to be an enormous amount of work to migrate existing apps to it.

I really think there has to be a migration guide to assist in this. For example, when deprecating classes, there should be a migration example given.

**Comment by ToxicBakery** [comment]
The migration example is simple, rewrite the application. v0.9 was just that, a pre-release. After 1.0 api changes will make broader attempt to avoid breaking changes.

**Comment by jwoolston** [comment]
AnchorSteam got its start because several features were piling up that required fundamental changes to the inner workings of the library. We decided that as part of that, we wanted the freedom to rework the public API completely. We had several discussions about that publicly and it was well received by those users who commented at the time. As for a migration guide, I have tried and continue to try to keep CHANGLOG.md up to date, as well as write wiki pages when I can, but given that I am at present the only active dev adding new features, I feel my time is more valuable spent on the features. Working examples can always be seen in the Rajawali Examples application and I feel like especially recently, I have been very open about announcing them.

**Comment by jwoolston** [comment]
@dcerisano Regarding your feelings about this issue:

> SerializedObject3D is/was useful for handling various 3D object formats after import since it is/was the common superclass.

Can you provide an example of how this is more useful than AWD?

**Comment by dcerisano** [comment]
@jwoolston I was not comparing the usefulness of one approach to another, just inquiring as to the migration path of this and other deprecated classes.

@ToxicBakery thanks for the straight forward answer. There is no migration path.

**Comment by jwoolston** [comment]
I wouldn't say there is no path, just that its more re-writing than refactoring. In the case of the activities/fragments, I have apps which are basically copy and past of the fragment code because of the need to extend other classes. Similar approaches could be used. There is no reason why you couldn't keep the serialized object yourself if you wanted. Thus far, most if not all other changes have been documented and demonstrated.

**Comment by dcerisano** [comment]
No need to be defensive. This is to be expected from a major version upgrade from the last stable branch. Without the resources required to be backward compatible, migration work is inevitable.
I am using RajawaliVR myself, which depends on the master branch and is already very up to date. I don't expect much effort to do the final migration.
