### ISSUE TITLE
Dynamically loading STL file from sd card. 

### ISSUE THREAD

**Issue by abhijeetdutta** [Rajawali/Rajawali#1416]
Hi 

I am working on an app which downloads stl file from server and I am trying to render it. I tried LoaderSTL. 
But I am not able to load, 
![app2 - dandroidstudioprojectsapp2 - app - appsrcmainjavacomdf3dapp2renderer java - android studio 1 1 0](https://cloud.githubusercontent.com/assets/6577008/6867228/ccdf7d48-d4a5-11e4-8962-dba43eb4aa23.jpg)

Please help.

**Comment by ToxicBakery** [comment]
```This object can't render because there's no material attached to it.```

Sounds like you did not attach a material to it.

**Comment by abhijeetdutta** [comment]
@ToxicBakery Following is my code 

LoaderSTL stlParser = new LoaderSTL(this, "filename.stl");

        try{
            stlParser.parse();
            mObjectGroup = stlParser.getParsedObject();
            Material material = new Material();
            material.setColorInfluence(1);
            getCurrentScene().addLight(light);
            super. getCurrentScene().addChild(mObjectGroup);
        } catch (ParsingException e){
            e.printStackTrace();
        }

Can you please tell me is it a correct way of adding material?

**Comment by ToxicBakery** [comment]
You did not attach the material to the object.

https://github.com/Rajawali/Rajawali/wiki/Tutorial-03-Materials

**Comment by jwoolston** [comment]
Closing as resolved. Attaching a material to the object will fix this.
