### ISSUE TITLE
Fix Shadow Mapping and Render To Texture

### ISSUE THREAD

**Issue by MasDennis** [Rajawali/Rajawali#1430]
Shadow mapping and Render to Texture broke for some reason. Might have something to do with the changes in lighting.

**Comment by jwoolston** [comment]
My bad :smile:

**Comment by MasDennis** [comment]
I'm not sure if I can forgive you.

**Comment by jwoolston** [comment]
At least some of this seems to be related to the view port dimensions being messed up.

**Comment by jwoolston** [comment]
Fixed via aac513c
