### ISSUE TITLE
Bounding volumes lag one frame behind object position

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1433]
Bounding volumes are drawn by the rajawali render loop, but need to be updated by the user. This causes them to lag one frame behind in position. We should decide if we should expect the user to resolve this themselves via the frame callbacks (requiring us to add a post animation callback) or if we should transform the bounding volumes of all objects which have them automatically.

**Comment by ToxicBakery** [comment]
I would expect the volumes to be calculated automatically. It would be awkward to add the volume then be held responsible to deal with its updates yourself if you want their updates to sync with the visuals.
