### ISSUE TITLE
live wallpaper slow back from sleep

### ISSUE THREAD

**Issue by NinjaSkillZ** [Rajawali/Rajawali#1437]
Hi,
Im working on live wallpaper based on rajawali template and as the title says, when my device wakes up from sleep, its most likely loading all the objects again, as it takes the same time like loading the preview. I think I dont need to say that its quite unwanted to wait seconds before your wallpaper appears as well as illogical to load again something that just loaded and remains loaded even if I run another apps.

It was already mentioned here:
https://github.com/Rajawali/Rajawali/issues/18
But the issue was closed as it is solved, but it was more likely solution to this:
https://github.com/Rajawali/RajawaliVuforia/issues/18

I also tried some investivation on google but I had no luck to find anything useful, just that it maybe have something to do with opengl loosing context, however ppl were mostly complaining only about textures and I dont have any in my scene yet.

Have anyone solved this problem or at least have some idea please? Any help is highly appreciated.

**Comment by jwoolston** [comment]
If we loose the GL context, there is little we can do about it. The new views have the potential to better hold onto the EGL surface but I can tell you that their lifecycle right now will also loose them because of the dettatch event. The issues you referenced have nothing to do with what is currently going on. I will look into this issue when I update the wallpaper template anyway. In the meantime, using binary formats such as AWD or asyncronous loading will alleviate the effects of your issue.

**Comment by NinjaSkillZ** [comment]
Thank you for your reply and the tips with AWD formats and async loading, ill look into it.
I also found some thread about the context loosing which seems to have some solution, however im quite new to android java so Im not sure what is meant by "move eglcontext upward and make it static".  Here is the link so maybe you can check it out and tell your opinion if it can solve my issue ;)
http://gamedev.stackexchange.com/questions/12629/workaround-to-losing-the-opengl-context-when-android-pauses

**Comment by jwoolston** [comment]
Yes, we have discussed implementing that but it has never been a priority due to the changes it would require. Now that I have converted the library to only provide surface and texture views, it might be a good time to start thinking about that again.

**Comment by NinjaSkillZ** [comment]
You mean its too much work to implement that? I think it would be a significant improvement. Maybe if you can tell closer what is needed to be done, I could try to help, as the original description is very brief for me.
About that AWD format, I had not time to test it yet, but Im curious if it is faster to parse AWD than use serialized models?

**Comment by ToxicBakery** [comment]
AWD is orders of magnitude faster than any of the other parsers. The more complex the model the faster AWD will parse in comparison to the other formats.

**Comment by jwoolston** [comment]
> You mean its too much work to implement that?

No I mean we don't have enough people with the skill and time to do it AND all the other important tasks.

**Comment by NinjaSkillZ** [comment]
@Toxicbakery
Sounds like a must try, thank you for the explanation.

@Jwoolston
Ok ok, Ill hope it will get priority soon, meanwhile Ill try the tips u provided, if it will be not satisfying enough Ill maybe try on my own. Thanks you for your patience.

**Comment by jwoolston** [comment]
Closing this issue as stale/resolved.
