### ISSUE TITLE
Adding Simple Sphere

### ISSUE THREAD

**Issue by uzman** [Rajawali/Rajawali#1438]
Hello,
i read the tutorials, but i think it is an old document.
there are codes about Materials: https://github.com/Rajawali/Rajawali/wiki/Tutorial-03-Materials

i wanted to use below code. but there is no SphereMapMaterial class. 

			SphereMapMaterial material = new SphereMapMaterial();
			material.setSphereMapStrength(2);
			material.setUseColor(true);

			Bitmap sphereMap = BitmapFactory.decodeResource(mContext.getResources(), R.drawable.my_sphere_map);

			myObject.setMaterial(material);
			myObject.setColor(0xFF999999);
			myObject.addLight(mLight);
			myObject.addTexture(mTextureManager.addTexture(sphereMap, TextureType.SPHERE_MAP));

how can i add a simple sphere to specific point?

**Comment by jwoolston** [comment]
It looks like you are trying to use `v0.9`, so those docs you linked should be appropriate. The older version does not have a sphere mapping material like the new one does.
