### ISSUE TITLE
Add Spheres to Scene.

### ISSUE THREAD

**Issue by uzman** [Rajawali/Rajawali#1439]
Hi,
i want to a simple app that shows panorama photos.
i made panorama with setSkybox method. it is ok.

but i couldn't make below:
- Adding simple sphere to scene
- Selecting sphere by looking at it then loads new panorama photo.

there is an app Orbulus (https://play.google.com/store/apps/details?id=com.VRCraftworks.Orbulus).
it does same things.

can you guide me or give simple code snippets?

(i read the all tutorials. but i didn't run some codes. for example; there is no SphereMapMaterial)

**Comment by jwoolston** [comment]
You should look at the examples app. There are plenty of examples there which load spheres and skyboxes. If you are wanting to use `v0.9` then simply look for a commit from the examples around the day the tag was made.
