### ISSUE TITLE
Add First Person Camera

### ISSUE THREAD

**Issue by thebradbain** [Rajawali/Rajawali#1449]
It's easy to set a camera's position via setPosition.
And it's easy to set a camera's rotation via setRotation.
But is it easy to move a camera in the direction it's facing (e.g. forward being the direction it's facing)?

I guess I'm asking if there's any simple method or combination thereof that would allow one to simulate a basic first person camera, ideally whereby rotating the camera and then adding to its z-component for position would advance the camera toward where it's looking. If no such way exists (as I suspect), how would I go about moving the camera in the position it's looking? 

## Feature List (Added by @jwoolston)

- [x] Link the object to another `ATransformable3D` with an offset. The camera will then always maintain this offset from the specified object. This is not the same as a chase camera as the orientation will be unaffected.
- [x] Orientation should always match parallel to the objects orientation (if present) + the camera's local orientation.
- [x] Camera which implements methods to move in the cameras local coordinate system. This will be in the underlying `ATransformable3D` class. 
- [x] Methods which allow for easy local rotations (these are already present, but perhaps better docs/method signatures would help)

**Comment by jwoolston** [comment]
This is an interesting request, and perhaps appropriate. @MasDennis is currently creating an arcball camera, perhaps a first person camera would round things out. To answer things immediately, the answer is fairly simple:

1. Start with a unit vector for the natural forward direction. Typically this would be the world coordinates, in this case `<0, 0, 1>`. 
2. Rotate this vector with the same rotation as your model. This is simply the objects orientation quaternion times the vector.
3. Scale this vector by the number of units to move.
4. Add this vector to the position.

Some untested code which should work (this would be a member of `ATransformable3D`):

```java
public void moveForward(double units) {
    final Vector3 movement = WorldParameters.FORWARD_AXIS.clone();
    movement.rotateBy(object3D.getOrientation()).multiply(units);
    setPosition(getPosition().add(movement));
}
```

That should get you started in the meantime, but tomorrow I will work on adding a camera to the framework that does this.

**Comment by thebradbain** [comment]
Ah, such a simple solution! Thanks for the fast reply. Glad to see I inspired the development of a new feature in some small way ;)

**Comment by jwoolston** [comment]
@thebradbain No problem. Always happy to help with well formulated questions.
