### ISSUE TITLE
Adding UI Elements to RajawaliSideBySideRenderer.

### ISSUE THREAD

**Issue by uzman** [Rajawali/Rajawali#1461]
Hi,
When i add ui elements to RajawaliRenderer it displays properly.
i used same code in this tutorial: https://github.com/Rajawali/Rajawali/wiki/Tutorial-08-Adding-User-Interface-Elements
but  when i use a renderer extended from RajawaliSideBySideRenderer it gives error sometimes.

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

code:

        mRenderer = new MyVRRenderer(this);
        mRenderer.setSurfaceView(mSurfaceView);
        setRenderer(mRenderer);

        if(displayLocation){
            LinearLayout ll = new LinearLayout(this);
            ll.setOrientation(LinearLayout.VERTICAL);
            ll.setGravity(Gravity.CENTER);
            location1 = new TextView(this);
            location1.setText("TEST");
            location1.setTextSize(20);
            location1.setGravity(Gravity.CENTER);
            location1.setHeight(100);
            ll.addView(location1);
            mLayout.addView(ll);
        }

Also there is something about camera. 
if i use RajawaliRenderer below code works. but if i use RajawaliSideBySideRenderer it does nothing.
        public void onDrawFrame(GL10 glUnused) {
            super.onDrawFrame(glUnused);
            getCurrentCamera().rotate(Vector3.Axis.Y, -0.2);
        }

i think there is something weird about RajawaliSideBySideRenderer. Or i miss something.

thanks...

**Comment by jwoolston** [comment]
The error message is quite clear. It is not a Rajawali error but rather you doing something wrong in android. Please google the error. Closing as not an issue.

**Comment by uzman** [comment]
you always close my issue :). just kidding.
i already googled it.
all codes are same. i just changed RajawaliRenderer to RajawaliSideBySideRenderer.
when i add ui elements, it crashes. (log is above).

- also camera rotating is not working on onDrawFrame method. (RajawaliSideBySideRenderer)

public void onDrawFrame(GL10 glUnused) {
super.onDrawFrame(glUnused);
getCurrentCamera().rotate(Vector3.Axis.Y, -0.2);
}

**Comment by MasDennis** [comment]
@jwoolston was just trying to say that it is not a Rajawali issue.
Google it and you'll find a solution for it.

What are you using `RajawaliSideBySideRenderer` for? RajawaliVR?

**Comment by uzman** [comment]
yes, for RajawaliVR.

**Comment by MasDennis** [comment]
Why do you want to rotate the camera manually?
The whole point of virtual reality is that it is controlled by motion.
What is it that you're trying to accomplish?

**Comment by jwoolston** [comment]
Additionally, one issue per ticket please.

**Comment by thebradbain** [comment]
@MasDennis a question I have, even  if tangentially related, is why separate RajawaliSideBySideRenderer and RajawaliVR into completely different repositories if there is currently no other conceivable use for SideBySideRenderer than for VR?

**Comment by uzman** [comment]
yes, you are right. 
at first i thought if the phone is stable, i wanted to rotate it automatically.
now it is not very important. 

but occurring crash when i add ui elements is weird. if you have time can you please check? can you try add a simple textview on the scene (RajawaliSideBySideRenderer)? it is not urgent.
RajawaliRenderer works good.

thanks...

**Comment by MasDennis** [comment]
@thebradbain I guess you're right, it could move to the RajawaliVR repository.

**Comment by jwoolston** [comment]
> but occurring crash when i add ui elements is weird.

Its not weird, its exactly what should happen. You cant add UI elements from the GL thread, only the UI thread. This is at the core of how android works.

**Comment by MasDennis** [comment]
@uzman the ui elements issue is not Rajawali related. It is an Android issue that you can easily fix by searching Stack Overlow for a solution.

**Comment by uzman** [comment]
i think i didn't express myself. 
this link is just related about Android?
https://github.com/Rajawali/Rajawali/wiki/Tutorial-08-Adding-User-Interface-Elements

if you have time, just try to do same thing with RajawaliSideBySideRenderer.

(thanks for your great framework. you saved my life yesterday)

**Comment by jwoolston** [comment]
The code you reference there is not to be placed in `RajawaliRenderer`. It clearly states in the tutorial to place it in the activity.

**Comment by uzman** [comment]
@jwoolston yes, i know. i am also adding TextView in my activity.
mRenderer = new UIExampleRenderer(this);

UIExampleRenderer is derived from RajawaliRenderer.

**Comment by ToxicBakery** [comment]
Clearly there is some confusion here so lets clarify it. Please create an example project demonstrating the issue. A demonstration of a problem is going to be significantly more concise than snippets of information.
