### ISSUE TITLE
Material not displaying properly when loading STL asynchronously

### ISSUE THREAD

**Issue by AridEyes** [Rajawali/Rajawali#1466]
Previously I loaded the STL file normally using the LoaderSTL in initScene, the material was fine. When I changed to loading it asynchronously, it doesn't have the material defined (specular and diffuse). 

Previous load stl

    LoaderSTL stlParser = new LoaderSTL(mContext.getResources(), resid);
    stlParser.parse();
    mCurrentObject = stlParser.getParsedObject();
    mCurrentObject.setDrawingMode(GLES20.GL_TRIANGLES);
    getCurrentScene().addChild(mCurrentObject);

Then set material

    Material material = new Material();
    material.enableLighting(true);
    material.setDiffuseMethod(new DiffuseMethod.Lambert());
    material.setSpecularMethod(new SpecularMethod.Phong());
    mCurrentObject.setMaterial(material);

Current load stl

    LoaderSTL stlParser = new LoaderSTL(mContext.getResources(), resid);
    loadModel(stlParser, this, resid);

In onModelLoadComplete

    LoaderSTL stlParser = (LoaderSTL) loader;
    stlParser.parse();
    mCurrentObject = stlParser.getParsedObject();
    mCurrentObject.setDrawingMode(GLES20.GL_TRIANGLES);
    getCurrentScene().addChild(mCurrentObject);

Then set material

    Material material = new Material();
    material.enableLighting(true);
    material.setDiffuseMethod(new DiffuseMethod.Lambert());
    material.setSpecularMethod(new SpecularMethod.Phong());
    mCurrentObject.setMaterial(material);

Is this a bug, or am I doing something wrong? Thanks.

**Comment by jwoolston** [comment]
It shouldn't make a difference, but for the purposes of debugging, could you try setting the material before adding the object to the scene?

**Comment by AridEyes** [comment]
Yeah tried that, still the same issue. 

Another issue I found is while using loadModel but with the reflection option (LoaderSTL.class), it just doesn't work with LoaderSTL because it doesn't have the matching constructor. 

    final Constructor<? extends ALoader> constructor = loaderClass.getConstructor(Resources.class,
                TextureManager.class, int.class);

**Comment by AridEyes** [comment]
Whops, sorry accidentally closed.

**Comment by jwoolston** [comment]
Alright. Please create a new ticket for the constructor related bug. I am getting ready to put a branch into final review for bugs for the `v1.0` release so the more bugs we can identify the better. As for this, I don't believe you are doing anything wrong, I'll mark it to look into. Probably wont get to it until tomorrow evening (UTC-8).

**Comment by AridEyes** [comment]
Thanks! I'll create a new issue for the constructor bug.
