### ISSUE TITLE
Change pivot to center of the object.

### ISSUE THREAD

**Issue by abhijeetdutta** [Rajawali/Rajawali#1469]
I am working on an app which downloads and renders stl from server, the problem is when i am rotating the object it is rotating around its top left corner but it should rotate around center.

My Code :

mRenderer.mObjectGroup.setRotX(mRenderer.mObjectGroup.getRotX()+touchOffsetY);
mRenderer.mObjectGroup.setRotY(mRenderer.mObjectGroup.getRotY()+touchOffsetX);

Please help!

**Comment by MasDennis** [comment]
Any way you can center the object in a program like 3DS Max or Blender?
Otherwise you can put in it an empty `Object3D`, then offset your stl model and then rotate the empty.

**Comment by abhijeetdutta** [comment]
@MasDennis Can you please share some code for the above solution you suggested.

Many thanks.
