### ISSUE TITLE
Stable versions missing in Maven-repository?

### ISSUE THREAD

**Issue by tobi512** [Rajawali/Rajawali#1483]
Hi there, 
i just wanted to integrate your library into my project and didn't find any stable versions in mavenCentral(), just some snapshots in the Sonatype snapshot-repository. I'd like to have access to v0.9 as aar, is there any chance to upload it?!

Thanks in advance!

-Tobias

**Comment by ToxicBakery** [comment]
0.9 is for Eclipse, there is no stable version currently but one will exist soon.

**Comment by tobi512** [comment]
Hi and thanks for your quick answer!

My project is a bit older and I would need v0.9 since there seem to be lots of changes in newer versions and its the only stable version atm, any chance of building an AAR anyway?! If not, is there a documentation of the changes from 0.9 to the current base, so I could migrate it easily?

Greetings, 
Tobias

**Comment by jwoolston** [comment]
With some minor tweaks it should be possible to use the gradle scripts. As for documentation of the changes, see [CHANGELOG](https://github.com/Rajawali/Rajawali/blob/anchor-steam-review/CHANGELOG.md)

**Comment by hurzl** [comment]
I find nothing in Maven, neither on the site nor in android studio. 
http://mvnrepository.com/search?q=raja
