### ISSUE TITLE
New GitHub release

### ISSUE THREAD

**Issue by jitpack-io** [Rajawali/Rajawali#1485]
Hi!

The last GitHub release was a while back: https://github.com/Rajawali/Rajawali/releases
How about a new release? Would also make it easier to grab Rajawali using JitPack.

Cheers

**Comment by jwoolston** [comment]
It's on its way. The only thing really holding it up is documentation and prep of the other libraries to match. I was working on this but I'm currently trying to buy a house which is consuming a lot of my time.

**Comment by jitpack-io** [comment]
Good luck!
