### ISSUE TITLE
Using an interface inside Renderer class

### ISSUE THREAD

**Issue by billyjoker** [Rajawali/Rajawali#1489]
I have an Android fragment based project which sets a live wallpaper. So, i communicate my fragments through a interface likes the official documentation does, so, i defined a InterfaceFragments to communicate them through my activity:

```java
public class GeneralActivity extends FragmentActivity implements InterfaceFragments{
```

My problem comes with my next action, i set a live wallpaper through a service like follows:

```java
    if (Build.VERSION.SDK_INT >= 16) 
    {

        //Open live wallpaper preview (API Level 16 or greater).
        intent.setAction(WallpaperManager.ACTION_CHANGE_LIVE_WALLPAPER);
        intent.putExtra(WallpaperManager.EXTRA_LIVE_WALLPAPER_COMPONENT,
                new ComponentName(getActivity(), Service.class));

        Log.i("tag", "Build.VERSION.SDK_INT >= 16");
    } else 
    {
        //Open live wallpaper picker (API Level 15 or lower).
        //Display a quick little message (toast) with instructions.
        intent.setAction(WallpaperManager.ACTION_LIVE_WALLPAPER_CHOOSER);
        Resources res = getResources();
        String hint = res.getString(R.string.picker_toast_prefix)
                + res.getString(R.string.lwp_name)
                + res.getString(R.string.picker_toast_suffix);
        Toast toast = Toast.makeText(getActivity(), hint, Toast.LENGTH_LONG);
        toast.show();
        Log.i("tag", "Build.VERSION.SDK_INT < 16");
    }
```

As results, a Renderer class is executed:

```java
public class Renderer extends RajawaliRenderer{ 

    public Renderer(Context context) {
        super(context);
        this.context = context;
    }
```

As consecuence of this, i've lost my Activity reference, needed to use my interface as i did inside the fragments:

```java
@Override
public void onAttach(Activity activity) {
    super.onAttach(activity);

    interfrag = (InterfaceFragments)activity;

}
```

So, how could i recover my interface to use in the Renderer class?

**Comment by ToxicBakery** [comment]
Yeah so the official docs are more of instructions of what you can do not really what you should do. Using interfaces you are tightly coupling your fragments and activities and making them both difficult to change later which defeats the entire purpose of the fragments. You would be wise to avoid this with delegation, broadcasts, event bus, etc. Practically anything other than what you are doing now will be a more disconnected and thus better approach.

In your situation a broadcast would probably work fine and you wont need any additional libraries.

**Comment by billyjoker** [comment]
Many thanks for your reply, i will do as you say.
