### ISSUE TITLE
Yaw definition may be confusing

### ISSUE THREAD

**Issue by adamantivm** [Rajawali/Rajawali#1491]
I apologize if this should be submitted elsewhere. I would appreciate guidance in that case.

I just spent quite a few hours trying to use Rajawali's math library to project a 3D rotation to 2D space by getting the Yaw until I finally figured out that [Rajawali defines the Yaw as the rotation about the Z axis](https://github.com/Rajawali/Rajawali/blob/ae3367c44d619ef8e59e6dadfb9eff0d708abe84/rajawali/src/main/java/org/rajawali3d/math/Quaternion.java#L977)

This is very different to how the [yaw axis is conventionally defined](http://en.wikipedia.org/wiki/Axes_conventions), which is about the Z (up) axis.

I figure this has to do with how the axis are defined in Rajawali.

I think making it clearer where deviations from known conventions would increase usability of the library considerably.

**Comment by jwoolston** [comment]
Rajawali uses the conventions of open gl, not the math/physics community.

**Comment by ToxicBakery** [comment]
This looks resolved, please reopen if needed.

**Comment by adamantivm** [comment]
I agree it was merely my confusion by coming into this from a different area (robotics).

Perhaps for potential future people who may be confused like me, [here is one quick explanation of OpenGL convention about rotation axis names](http://www.songho.ca/opengl/gl_anglestoaxes.html) to contrast against what is being used in other areas of the physical world.
