### ISSUE TITLE
md5 issue

### ISSUE THREAD

**Issue by zafyraminx** [Rajawali/Rajawali#1492]
i try to create my own md5 to play with your library, before i tried to use different engine and rajawali is the best engine that i can use now in my project. at first i try using my own model then it has error with weight of the vertices so I try to use the bob sample, I download it then i try to import it in the project but it has this issue

01-23 14:47:34.860: W/System.err(6445): org.rajawali3d.loader.ParsingException: org.rajawali3d.loader.ParsingException: Couldn't find texture bob_body

and I try using the default md5mesh in that zip but still it is not working

**Comment by ToxicBakery** [comment]
The error is pretty specific in this case, the texture applied to the mesh is missing. Where did you put it if anywhere at all?

**Comment by zafyraminx** [comment]
Ahh i see it's okey now. I just make some reseach and testing and now i get it how to work with the md5. thanks for your answer anyway. Your Library is really cool!!
