### ISSUE TITLE
How destroy the Service by pressing "Settings" in the preview visualization?

### ISSUE THREAD

**Issue by billyjoker** [Rajawali/Rajawali#1493]
Hi, i'd like to disable the "Settings" button in the preview. I mean, instead calling the Settings class (which extends PreferenceActivity), i'd like to destroy the preview and go back my main Activity. I've tried changind the wallpaper.xml redirecting to my activity, but an instance of the preview is yet in the background.

Another thing i've tried is stopping the wallpaper service and calling my Activity, with the same effect which retain the instance of the preview:

       @SuppressWarnings("deprecation")
       public class Settings extends PreferenceActivity implements
		SharedPreferences.OnSharedPreferenceChangeListener {

	protected void onCreate(Bundle icicle) {
		super.onCreate(icicle);
		getPreferenceManager().setSharedPreferencesName(
				Wallpaper.SHARED_PREFS_NAME);
		addPreferencesFromResource(R.xml.settings);
		getPreferenceManager().getSharedPreferences()
				.registerOnSharedPreferenceChangeListener(this);
	
		
		Intent intent2 = new Intent(this, Service.class);
		stopService(intent2);

		Intent intent = new Intent(Settings.this, SplashActivity.class);
		intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
		intent.putExtra("backsetting", true);
		startActivity(intent);
		finish();

	}
       ...

How could i do this?

**Comment by ToxicBakery** [comment]
Wallpapers are not normal services you have control over. You can not stop a wallpaper service gracefully.

From http://developer.android.com/reference/android/service/wallpaper/WallpaperService.html
```
This service object itself does very little -- its only purpose is to generate instances of WallpaperService.Engine as needed.
```
