### ISSUE TITLE
Replace Loaded Model On Scene

### ISSUE THREAD

**Issue by sanjhapps** [Rajawali/Rajawali#1496]
Newbie in Rajawali
I want to change the object which is already loaded on scene and update the current scene,

public void initScene() {
	getCurrentScene().setBackgroundColor(220,220,220,1);

			LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(),
					mTextureManager, R.raw.body1_obj);
			LoaderOBJ objParserTop = new LoaderOBJ(mContext.getResources(),
					mTextureManager, R.raw.tshirt_obj);
			LoaderOBJ objParserBottom = new LoaderOBJ(mContext.getResources(),
					mTextureManager, R.raw.jeans_obj);		

}
i have succesfully loaded and parsed all the objects in the current scene mean while on button click i want to change one of the parsed object 

I tried calling the method from onclick as

                       public void LoadObject() throws ParsingException {			
			LoaderOBJ objParser1 = new LoaderOBJ(mContext.getResources(),
					mTextureManager, R.raw.shirt_obj);
			objParser1.parse();
			avatarTop = objParser1.getParsedObject();
			avatarTop.setPosition(5f, 0f, .3f);

			getCurrentScene().addChild(avatarTop);

		}

But it still loading the initscene();

**Comment by flankechen** [comment]
Much of my experiences, don't try to replace objects/materials on the fly.
try to set up things while initscene(); and use .setvisiable() to control them.

**Comment by SanjayHansraj** [comment]
Hey flankechen
Thanks for the reply but my requirement is like that , i have to render the object onclick as you can see its all human bodypart objects and cloth .

Is there any another way where i can change obj dynamically.

**Comment by sanjhapps** [comment]
Hey flankechen
Thanks for the reply but my requirement is like that , i have to render the object onclick as you can see its all human bodypart objects and cloth .

Is there any another way where i can change obj dynamically.

**Comment by UnnikrishnanMR** [comment]
@sanjhapps did you solved the problem? I too face similar situation. If you have solved it can you please share it with me

**Comment by sanjhapps** [comment]
As a matter of fact i did resolved the issue by importing Obj from SDcard and replace child on ButtonClick

Please Follow:
http://stackoverflow.com/questions/30839053/parsing-obj-model-from-sd-card-rajawali/30950309#30950309

**Comment by UnnikrishnanMR** [comment]
@sanjhapps Thanks for the fast reply. Got it working.
