### ISSUE TITLE
ObjectColorPicker is not working in master branch !

### ISSUE THREAD

**Issue by abhishekBansal** [Rajawali/Rajawali#1498]
I was trying to make ObjectPicking work in one of my projects then I just ran Rajawali Example project and Picking example is no more working. Any ideas/workaround for this ? Device on which I ran sample is MotoG Second Generation.

**Comment by selop** [comment]
try to set the framework dependency to this version:

'org.rajawali3d:rajawali:1.0.261-SNAPSHOT@aar'

**Comment by abhishekBansal** [comment]
@selop thanks for ur reply !
I am already using the version u mentioned.

**Comment by abhishekBansal** [comment]
ok so I tried to break into the code and I suspect that following piece of code in `RajawaliScene` is culprit 

     synchronized (mChildren) {
			for (int i = 0, j = mChildren.size(); i < j; ++i) {
				Object3D child = mChildren.get(i);
				boolean blendingEnabled = child.isBlendingEnabled();
				if(pickerInfo != null && child.isPickingEnabled()) {
					child.setBlendingEnabled(false);
					pickerInfo.getPicker().getMaterial().setColor(child.getPickingColor());
				}
                // Model matrix updates are deferred to the render method due to parent matrix needs
				child.render(mCamera, mVPMatrix, mPMatrix, mVMatrix, sceneMat);
				child.setBlendingEnabled(blendingEnabled);
			}
		}

Here my scene has one root node and nine other children (and thus `mChildren` is 1). Root node is not registered in picker and only child nodes are. `child.isPickingEnabled()` always returns false as its not registered in picker.

**Comment by jwoolston** [comment]
#1607

**Comment by jwoolston** [comment]
Should be resolved as of #1614
