### ISSUE TITLE
RajawaliRenderer ctor error message

### ISSUE THREAD

**Issue by rpicolet** [Rajawali/Rajawali#1503]
Getting an Error message from RajawaliRenderer constructor, not sure if it matters otherwise...  Seems to be from calling through to setViewport()/glViewport()

Snapshot 267

...
06-06 16:28:18.084      341-341/shgames.stu I/Rajawali﹕ Rajawali | Anchor Steam | v1.0
06-06 16:28:18.084      341-341/shgames.stu E/libEGL﹕ call to OpenGL ES API with no current context (logged once per thread)
...

**Comment by ToxicBakery** [comment]
Yep, that's normal.

**Comment by rpicolet** [comment]
Great, thanx!
