### ISSUE TITLE
"createContext  failed: EGL_BAD_ATTRIBUTE" exception on Samsung S3

### ISSUE THREAD

**Issue by rpicolet** [Rajawali/Rajawali#1504]
master Snapshot 267

When the GL thread starts up, it throws an exception (stack trace below).  It appears to be caused by Capabilities.getGLESMajorVersion() returning version 3 (instead of version 2), as I can make the 
problem go away by replacing RajawaliSurfaceView with a version that hard-codes 		setEGLContextClientVersion(2);

Don't know if it's related, but prior to the GLThread start [after setSurfaceRenderer() during onCreateView()], a warning appears (also pasted below) from the Adreno driver about  "not forcing ES30"...

== Exception stack ==

06-07 18:30:51.200  19489-19524/shgames.stu W/Adreno-EGL﹕ <qeglDrvAPI_eglCreateContext:2407>: EGL_BAD_ATTRIBUTE
06-07 18:30:51.200  19489-19524/shgames.stu W/dalvikvm﹕ threadid=19: thread exiting with uncaught exception (group=0x41734da0)
06-07 18:30:51.210  19489-19524/shgames.stu E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 14532
    Process: shgames.stu, PID: 19489
    java.lang.RuntimeException: createContext failed: EGL_BAD_ATTRIBUTE
            at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1202)
            at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1193)
            at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1043)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1410)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)

==== Adreno Warning ====

06-07 18:30:50.319  19489-19489/shgames.stu W/Adreno-GSL﹕ <get_panel_settings:3802>: Android framework reported version 2. So, don't force ES30
06-07 18:30:50.329  19489-19489/shgames.stu I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018_msm8960_KK_2.7_RB1_CL3869936_release_AU (CL3869936)
    OpenGL ES Shader Compiler Version: 17.01.10.SPL
    Build Date: 12/09/13 Mon
    Local Branch: mybranch2092625
    Remote Branch: quic/kk_2.7_rb1.15
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018 +  NOTHING

**Comment by rpicolet** [comment]
Forgot to say, it's Android 4.4.2.

**Comment by dcerisano** [comment]
Probably related to:
https://github.com/Rajawali/Rajawali/issues/1383

There is a PlayStore Market Filter to restrict deployment by GLES version that should always be used when publishing GLES apps.

   <uses-feature    android:glEsVersion=  "0x00020000"    android:required="true"/>

**Comment by rpicolet** [comment]
Right, thanks. I do have that filter string in my manifest already. I believe it is interpreted as meaning the minimum version, not the only version.

I don't think this is a string parsing error as in #1383; it seems to be a logic error in Capabilities that returns version 3, which then results in RajawaliSurfaceView trying to use GLES3 features that are not actually available...

**Comment by jwoolston** [comment]
@rpicolet can you please provide the String that is reported so I can verify that it is not the cause of this issue?

**Comment by rpicolet** [comment]
`Capabilities.getGLESMajorVersion()` returns an int, so I just stepped into `checkGLVersion()` and grabbed a couple screen shots of the Debugger Variables window at two points, right after the call to `eglChooseConfig()`, and after `mGLESMajorVersion` is finally assigned (both included below);  in a nutshell, `eglChooseConfig()` returns 10 matching configs, so `mGLESMajorVersion` is set to 3.

I won't pretend to understand completely, but I did look up the EGL spec:

https://www.khronos.org/registry/egl/extensions/KHR/EGL_KHR_create_context.txt

It seems to indicate that EGL1.4 is required to use `EGL_OPENGL_ES3_BIT_KHR`, but the version returned on my S3 appears to be 1.0, so maybe that is part of the problem??


============================================================================
Variables window after stepping past:

     egl.eglChooseConfig(display, configAttribs, configs, 10, num_config);

statics
 instance = null
 mEGLMajorVersion = 1
 mEGLMinorVersion = 0
 mGLESMajorVersion = 0
 sGLChecked = false
egl = {com.google.android.gles_jni.EGLImpl@830035708520} 
 mContext = {com.google.android.gles_jni.EGLContextImpl@830035708544} 
 mDisplay = {com.google.android.gles_jni.EGLDisplayImpl@830039406800} 
  mEGLDisplay = 1
 mSurface = {com.google.android.gles_jni.EGLSurfaceImpl@830035708648} 
  mEGLSurface = -1
  mNativePixelRef = 0
display = {com.google.android.gles_jni.EGLDisplayImpl@830039406800} 
version = {int[2]@830039407824} 
configAttribs = {int[9]@830039436224} 
configs = {javax.microedition.khronos.egl.EGLConfig[10]@830039437160} 
 0 = {com.google.android.gles_jni.EGLConfigImpl@830039438256} 
  mEGLConfig = 1
 1 = {com.google.android.gles_jni.EGLConfigImpl@830039438272} 
  mEGLConfig = 4
 2 = {com.google.android.gles_jni.EGLConfigImpl@830039438288} 
  mEGLConfig = 2
 3 = {com.google.android.gles_jni.EGLConfigImpl@830039438304} 
  mEGLConfig = 3
 4 = {com.google.android.gles_jni.EGLConfigImpl@830039438320} 
  mEGLConfig = 13
 5 = {com.google.android.gles_jni.EGLConfigImpl@830039438336} 
  mEGLConfig = 16
 6 = {com.google.android.gles_jni.EGLConfigImpl@830039438352} 
  mEGLConfig = 14
 7 = {com.google.android.gles_jni.EGLConfigImpl@830039438368} 
  mEGLConfig = 15
 8 = {com.google.android.gles_jni.EGLConfigImpl@830039438384} 
  mEGLConfig = 25
 9 = {com.google.android.gles_jni.EGLConfigImpl@830039438400} 
  mEGLConfig = 28
num_config = {int[1]@830039437656} 
 0 = 10
num_config[0] = 10
mGLESMajorVersion = 0
sGLChecked = false

==============================================================================

Variables window after stepping past:

     mGLESMajorVersion = num_config[0] > 0 ? 3 : 2;

statics
 instance = null
 mEGLMajorVersion = 1
 mEGLMinorVersion = 0
 mGLESMajorVersion = 3
 sGLChecked = false
egl = {com.google.android.gles_jni.EGLImpl@830035708520} 
 mContext = {com.google.android.gles_jni.EGLContextImpl@830035708544} 
  mGLContext = {com.google.android.gles_jni.GLImpl@830035708568} 
  mEGLContext = -1
 mDisplay = {com.google.android.gles_jni.EGLDisplayImpl@830039406800} 
  mEGLDisplay = 1
 mSurface = {com.google.android.gles_jni.EGLSurfaceImpl@830035708648} 
  mEGLSurface = -1
  mNativePixelRef = 0
display = {com.google.android.gles_jni.EGLDisplayImpl@830039406800} 
 mEGLDisplay = 1
version = {int[2]@830039407824} 
 0 = 1
 1 = 0
mGLESMajorVersion = 3
sGLChecked = false

**Comment by jwoolston** [comment]
Your assertion of a logic error would seem to be correct then. We request a 3.0 EGL surface and if we get one, assume 3 is supported. Something seems to be going wrong there.

**Comment by rpicolet** [comment]
Maybe the request itself is only legit if EGL 1.4 is used to make it? In other words, if the available  EGL version is less than 1.4,  perhaps the EGL_OPENGL_ES3_BIT_KHR attribute is simply unrecognized/ignored and the returned configs represent the remainder of the attributes? If so, then it would just be a matter of also checking that the EGL version is at least 1.4 before making the request.  

But this all just a guess; perhaps there is some way to examine the returned configs themselves to see if they actually support EGL_OPENGL_ES3_BIT_KHR?  Not as a solution, just to test out the theory.  I can look into this if you think that might be useful...

**Comment by jwoolston** [comment]
Honestly based on what I have seen in the past, I would venture that the S3 is erroneously returning EGL 1.0 when it is actually something else like 1.2. In either case, the situation could be handled better. This would definitely be useful and I do not have an S3 to test with so if you feel like looking into it, it would be appreciated.

**Comment by rpicolet** [comment]
I'll give it a shot, see if I can learn something that will make progress... May take a day or two.

**Comment by jwoolston** [comment]
I think your idea of checking the EGL version first merits following so I would explore that route if I were you.

**Comment by rpicolet** [comment]
I've run a quick test where I inserted code to check the actual `EGL_RENDERABLE_TYPE` attribute value for the configs returned by `eglChooseConfig()` and stepped thru it, and all 10 configs return a value of 7, which is the combination of `EGL_OPENGL_ES_BIT` (bit 0/value 1), `EGL_OPENVG_BIT` (bit 1/value 2), and `EGL_OPENGL_ES2_BIT`(bit 2/value 4). So even though the attribute value passed in `eglChooseConfig()` was `EGL_OPENGL_ES3_BIT_KHR` (bit 6/value 64), it appears to have been ignored.

Also, the S3 is clearly using an Adreno chip that supports EGL1.4 (as reported in my logcat at the start of every run) even though `eglInitialize()` reports 1.0. So even if the S3 reported 1.4 (maybe it's drivers only support 1.0?), I think it could still give a false positive for GLES3. Similarly, relying on the EGL version could yield false results (positive or negative) on other devices, so I am not inclined to that approach.

To minimize confusion and bad effects of other potentially different device behaviors, I think it may be best for `Capabilities.checkGLVersion()` to just use `eglGetConfigs()` to get all available configs, and directly check them for the ES3 bit, rather than rely on `eglChooseConfig()` and `eglInitialize()` to both behave "well" (assuming my interpretation of the spec is even correct) on all devices...

I could code that up pretty quickly I think, and test it on the S3, but someone else would need to test it on some GLES3 devices to make sure it still works on those.  I would need some guidance on forking or branching, though, since my local repo main branch is currently occupied with all the #1586 changes. If helping me with that guthub stuff sounds more efficient than coding it yourself, let me know how to proceed... If not, no problem.

**Comment by jwoolston** [comment]
I can test the ES 3 capability. As for the git stuff, just do a checkout from the current `master` head and call it something else.

**Comment by jwoolston** [comment]
@rpicolet Sorry I got a phone call as I was typing that. To be clear, `git fetch origin` followed by `git checkout -b <branch_name> origin/master` where `origin` is the Rajawali repo.

**Comment by rpicolet** [comment]
I coded, tested, committed, and pushed my changes to Capabilites, but I think I missed something git-wise in your directions above (perhaps not replacing "origin" with the full github path to Rajawali?)...

In any case, git status says I'm on branch issue-1504 locally, and that the branch is up to date with origin/master.  On my github Rajawali fork, I still see only a master branch, even though the changes to Capabilities are there, so I'm not sure how to form a proper PR just for this fix. Happy to try again if you have a suggestion... I'm clearly still confused about github workflows.

**Comment by dcerisano** [comment]
The real problem here is Android's GLSurfaceView which Rajwali uses. The GLSurfaceView is incompatible with OpenGLES 3.0.

**Comment by jwoolston** [comment]
> The real problem here is Android's GLSurfaceView which the Rajawali Renderer class uses

Our `SurfaceView` class which extends Android's `GLSurfaceView` uses a custom implementation of the `EGLConfigChooser` which does not allow the surface view to do the picking anyway. Any issue caused by Android would be in its implementation of the `EGLDisplay` class, something we have no control over. Given Samsung's history of GPU related discrepancies relative to the Khronos Group standards, I am not surprised one of their devices is actually EGL 1.4 but reports 1.0 - its just another in a long list of things Samsung has "improved" in Android while trying to rebrand it as their own.

In anycase, we also use a `TextureView` based implementation which makes your argument about the `GLSurfaceView` being the sole root of the issue invalid anyway.

**Comment by jwoolston** [comment]
@rpicolet There is also the issue of using constants in `RajawaliEGLConfigChooser` that are only available in certain API levels in an unsafe manner given the declared min API of Rajawali which needs to be corrected (see #1589). What is the API level of your S3?

**Comment by rpicolet** [comment]
4.4.2/KITKAT/19

**Comment by jwoolston** [comment]
OK so it's not from sending some constant that got non oped by Dex. Sounds like the route you went down is still on track.

**Comment by dcerisano** [comment]
GL APIs are not backward compatible, a perfectly valid and known issue that needs to be addressed. All 1.4 calls should be removed.
