### ISSUE TITLE
Garbage collection called too much 

### ISSUE THREAD

**Issue by nguyenkims** [Rajawali/Rajawali#1505]
Hi,

I'm using Rajawali to load a 3D object of 3MB with a texture image of 300K and see a lot of GC calls in the log as you can see below. I think this slows down the loading of the object in the scene. For information, the loading takes 5-10 seconds on a Nexus 4 which is quite a lot in my opinion.

Does anyone have an idea on how to solve the problem or reduce the loading time ?

Thanks,
Son.

> 
06-08 15:10:06.694  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 52789(1824KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 16MB/17MB, paused 7.294ms total 39.707ms
06-08 15:10:06.999  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 14032(484KB) AllocSpace objects, 0(0B) LOS objects, 3% free, 17MB/17MB, paused 5.188ms total 18.739ms
06-08 15:10:07.807  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 305197(11MB) AllocSpace objects, 0(0B) LOS objects, 29% free, 19MB/27MB, paused 7.294ms total 151.472ms
06-08 15:10:08.409  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 243260(8MB) AllocSpace objects, 0(0B) LOS objects, 17% free, 22MB/27MB, paused 9.583ms total 199.572ms
06-08 15:10:10.152  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 122626(4MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 24MB/27MB, paused 5.707ms total 103.219ms
06-08 15:10:10.675  25671-25681/com.fitle.andproject.debug W/art﹕ Suspending all threads took: 38.669ms
06-08 15:10:10.698  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 108507(3MB) AllocSpace objects, 0(0B) LOS objects, 11% free, 24MB/27MB, paused 9.827ms total 102.517ms
06-08 15:10:11.073  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 83860(2MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 24MB/27MB, paused 5.646ms total 52.372ms
06-08 15:10:11.636  25671-25681/com.fitle.andproject.debug W/art﹕ Suspending all threads took: 7.355ms
06-08 15:10:11.987  25671-25686/com.fitle.andproject.debug I/art﹕ Background partial concurrent mark sweep GC freed 121257(6MB) AllocSpace objects, 2(512KB) LOS objects, 39% free, 22MB/37MB, paused 11.262ms total 187.059ms
06-08 15:10:13.365  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 441804(14MB) AllocSpace objects, 0(0B) LOS objects, 24% free, 24MB/32MB, paused 11.963ms total 170.608ms
06-08 15:10:13.999  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 282191(9MB) AllocSpace objects, 0(0B) LOS objects, 23% free, 24MB/32MB, paused 7.599ms total 138.501ms
06-08 15:10:14.667  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 245524(8MB) AllocSpace objects, 0(0B) LOS objects, 19% free, 25MB/32MB, paused 6.958ms total 146.833ms
06-08 15:10:15.146  25671-25681/com.fitle.andproject.debug W/art﹕ Suspending all threads took: 11.445ms
06-08 15:10:15.200  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 203617(6MB) AllocSpace objects, 0(0B) LOS objects, 18% free, 26MB/32MB, paused 8.026ms total 112.650ms
06-08 15:10:15.464  25671-28123/com.fitle.andproject.debug I/Rajawali﹕ Parsing object: Object4051
06-08 15:10:15.659  25671-25686/com.fitle.andproject.debug W/art﹕ Suspending all threads took: 22.829ms
06-08 15:10:15.662  25671-25686/com.fitle.andproject.debug I/art﹕ Background sticky concurrent mark sweep GC freed 4(256B) AllocSpace objects, 0(0B) LOS objects, 0% free, 34MB/34MB, paused 24.172ms total 34.701ms
06-08 15:10:15.670  25671-28123/com.fitle.andproject.debug I/Rajawali﹕ Object4051 has no material definition.
06-08 15:10:15.917  25671-25686/com.fitle.andproject.debug I/art﹕ Background partial concurrent mark sweep GC freed 742021(15MB) AllocSpace objects, 5(4MB) LOS objects, 34% free, 30MB/46MB, paused 2.807ms total 149.458ms
06-08 15:10:16.098  25671-28123/com.fitle.andproject.debug D/Fitle3DRenderer﹕ on render frame
06-08 15:10:16.116  25671-28123/com.fitle.andproject.debug E/Rajawali﹕ Getting location of uniform: uModelMatrix returned -1!
06-08 15:10:16.116  25671-28123/com.fitle.andproject.debug E/Rajawali﹕ Getting location of uniform: uTime returned -1!
06-08 15:10:16.182  25671-28123/com.fitle.andproject.debug E/Rajawali﹕ Getting location of uniform: uModelMatrix returned -1!
06-08 15:10:16.182  25671-28123/com.fitle.andproject.debug E/Rajawali﹕ Getting location of uniform: uTime returned -1!
06-08 15:11:02.628  25671-28584/com.fitle.andproject.debug E/BaseWorker﹕ finishing Problem communicating with API

**Comment by ToxicBakery** [comment]
Yes, do not use OBJ or other ASCII formats. This is the side effect of all the string initialization. AWD for instance will load almost instantly with hardly any wasted objects.

**Comment by nguyenkims** [comment]
Thanks. Will take a look at AWD then.
