### ISSUE TITLE
AFrameCallback.onPreDraw() not called

### ISSUE THREAD

**Issue by rpicolet** [Rajawali/Rajawali#1511]
master snapshot 267

Even though callPreDraw() returns true, onPreDraw() is not invoked.

Desk check of RajawaliScene.render() shows the likely culprit - using i < preCount instead of i < preRenderCount in the for condition:

       final int preRenderCount = mPreDrawCallbacks.size();
        if (preRenderCount > 0) {
            synchronized (mPreDrawCallbacks) {
                for (int i = 0; i < preCount; ++i) {
                    mPreDrawCallbacks.get(i).onPreDraw(ellapsedTime, deltaTime);
                }
            }
        }

**Comment by ToxicBakery** [comment]
If you submit a pull request for that I'll accept it.

**Comment by rpicolet** [comment]
Thanx Tox. I will do that once I figure out how to keep Android Studio from re-formatting and re-ordering stuff I didn't change...
