### ISSUE TITLE
I would like to have built-in DebugAxis object to display X, Y, Z axis

### ISSUE THREAD

**Issue by anticafe** [Rajawali/Rajawali#1513]
I notice in `DebugVisualizer`, we can add a `GridFloor` Object3D to display coordinate grid.
Could we also have a `DebugAxis` Object3D to display X, Y, Z axis?

**Comment by ToxicBakery** [comment]
That's a good idea.

**Comment by jwoolston** [comment]
@MasDennis already has this planned, it just hasnt been done yet.
