### ISSUE TITLE
Shader building errors when using multiple renderers

### ISSUE THREAD

**Issue by adamantivm** [Rajawali/Rajawali#1518]
I would like to request advice for some errors I'm seeing in our app. It could either be due to bugs on Rajawali (we're using bleeding edge) or a problem in how we architected our app.

Our app is using two Rajawali renderers and corresponding SurfaceViews. Each of them has very few very simple objects and are running at 30fps. Our app creates and adds new objects when the user clicks a button, i.e.: once ever a few dozen seconds, not very frequently. When that happens, a very few new objects are created in both renderers.

Relatively frequenty, when the objects are created, an error occurs when creating or linking the shaders for the materials (they are all as basic as they could be materials). I added extra logging to Material.java when the errors happens to see what is going on and found several different error modes, such as [this](https://gist.github.com/adamantivm/b1c895fe00247006518e), [this](https://gist.github.com/adamantivm/330c58a34e2a1ec42516) or [this](https://gist.github.com/adamantivm/cbe5f0c46be4941cbde5)
There doesn't seem to be any correlation on when or why these happen so I'm starting to doubt whether running two renderers concurrently is supported on the latest Rajawali master? Or maybe there is some particular consideration to take into account to make it work properly?

As additional background, there is a third non-Rajawali GLSurfaceView (a camera renderer) running on the app, could that be another cause of the problems we're seeing?

Any advice would be appreciated.

**Comment by MasDennis** [comment]
Hi @adamantivm I've never used multiple renderers myself.
Have you considered using multiple scenes?
Could you maybe shine some light on why you are using multiple renderers?

**Comment by adamantivm** [comment]
They are rendering different things. One is a top down view of a model and
the other is a first person view superimposed over a camera preview. They
render different things, at the same time. Does that make sense?

**Comment by MasDennis** [comment]
Have you considered rendering to textures and using those textures on screen quads?

**Comment by adamantivm** [comment]
@MasDennis I appreciate the suggestion. I admit I didn't consider that possibility simply because I didn't know it was a possibility and wouldn't know how to do it.
Could you please share any pointers or hints about how would I go about re-architecting my two renderers to an approach like you describe? It sounds promising.

**Comment by MasDennis** [comment]
So if you have two completely different things you want to render you could create two separate `RajawaliScene` instances.
Then you can render them separately into textures.
Then use these textures on `ScreenQuad` objects. `ScreenQuad` scales to full screen by default but you can scale them down and position them.

Please take a look at `RajawaliSideBySideRenderer` to see how to work with `RenderTarget`, `ScreenQuad` and multiple scenes:

https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/main/java/org/rajawali3d/renderer/RajawaliSideBySideRenderer.java

**Comment by adamantivm** [comment]
Just for the record I am still in the process of trying this out. It is becoming a longer and bumpier road than I would like, but it seems I'm almost there.
If this works out well and there is any interest, I could contribute back a sort of multi-renderer which can make it easier to render multiple scenes using this technique.

**Comment by MasDennis** [comment]
Sure, pull requests are always welcome!

**Comment by paulpv** [comment]
I added comments to the closed issue #1256, but I will post my concerns here too:

If there is more than one rendered registered, as can happen in a ViewPager, then the last registered renderer wins.
A ViewPager typically loads the visible page, and then the immediately adjacent pages.
The off-screen pages are registered last, resulting in all texture and material tasks getting targeted to that off-screen renderer; the visible on-screen rendered never gets the textures/materials.

I think Rajawali's intention is that there is only one active renderer at a time.
The renderer is typically activated in onResume and deactivated in onPause.
However, even the non-active renderers need to load textures.

It seems to me that the implementation of the TextureManager and MaterialManager is flawed.
The intention seems to be that multiple renderers can efficiently add duplicate textures and materials to the respective manager, and a single instance of those textures/materials will be saved.
The flaw is that those textures/materials are only added to the currently active renderer, when they should be available to all renderers.

**Comment by jwoolston** [comment]
@adamantivm Sorry for the long lag on this issue, but what is the current state in your end?

**Comment by adamantivm** [comment]
@jwoolston I sent the "multi-renderer" think a while back, it's in #1543 referenced above.

**Comment by jwoolston** [comment]
Ok. I have created a new issue specifically about the material handling to fix it and will be closing this one
