### ISSUE TITLE
Load multiple serialized object

### ISSUE THREAD

**Issue by fgnm** [Rajawali/Rajawali#1522]
Hi, I've successfully serialized my objs into .ser. There are 13 objects in my scene, two of that are quite big (7-8MB). When I try to load all objects together the app freezes, but after a while starts correctly. It's not a big problem but I ask if there is a better way to do this, thank you

this is my code
```
public void initScene() {
//================This code is repeated 13 times for each ser I have=====
		try {
			ObjectInputStream ois;
			ois = new ObjectInputStream(mContext.getResources().openRawResource(R.raw.right_h));
			rightH = new BaseObject3D((SerializedObject3D) ois.readObject());
			((MainActivity) mContext).setPercentage("10");
			ois.close();
		} catch (Exception e) {
		    e.printStackTrace();
		}
//=============================================================
. . .
}
```

The Rajawali version I use is the v0.9 tag

**Comment by jwoolston** [comment]
Serialized objects and `v0.9` support in general has been discontinued.
