### ISSUE TITLE
ObjectColorPicker always picks an object in RajawaliVuforia irrespective of touch

### ISSUE THREAD

**Issue by kirankiru** [Rajawali/Rajawali#1523]
i am trying to implement picking and dragging of 3d model(Object3d) in rajawali vuforia using ObjectColorPicker. i am following this tutorial(https://github.com/Rajawali/Rajawali/wiki/Tutorial-12-Object-Picking) .i want my 3dmodel to move only if i touch the model.if i press my finger anywhere on the screen the 3d model moves irrespective of touch.
am i missing something??
Any help is appreciated

**Comment by kirankiru** [comment]
No one faced this issue ??

**Comment by topolyai5** [comment]
Hi, I have a same problem. What was the solution?

**Comment by kirankiru** [comment]
@topolyai5  didn't find any solution
