### ISSUE TITLE
RajawaliSurfaceView#setTransparent is not effect

### ISSUE THREAD

**Issue by htoooth** [Rajawali/Rajawali#1527]
In RajawaliExamples, TransparentSurfaceFragment can't transparent why ?
![screenshot_2015-07-10-17-18-06-65](https://cloud.githubusercontent.com/assets/1717023/8615733/0b6db08c-2728-11e5-96a3-1a9736050275.png)

**Comment by jwoolston** [comment]
I am not sure what version of android you are using or what manufacturer this is from but the examples work fine on all the testing devices we have, including the transparent surface view. If you can provide any log details or information about the particular device having the problem, we can look into it further, in the meantime I am closing this issue.
