### ISSUE TITLE
Roate a 3D Object around its Center

### ISSUE THREAD

**Issue by cuttingedge03** [Rajawali/Rajawali#1528]
I have loaded an Obj model. I want to rotate the object onTouch. I am able to detect touch but I am unable to rotate the Object perfectly. I watched some of the issues too. But still I couldn't solve it. Any help would be appreciated.

**Comment by cuttingedge03** [comment]
I am able to rotate the object now but the object always rotates in a circle with a radius. Here is the code to rotate the object.

        mDegrees += touchOffset / 36;
        float x = (float) (mRadius * Math.sin(Math.toRadians(mDegrees)));
        float z = (float) (mRadius * Math.cos(Math.toRadians(mDegrees)));
        loadModelRenderer.getCurrentCamera().setPosition(curX,
        loadModelRenderer.getCurrentCamera().getY(), z);

The object rotates but with a radius tha is "mRadius". I just want to rotate around Y axis which passes through the object's center.

**Comment by ToxicBakery** [comment]
You likely need to wrap the object in a container so you can center it on an axis. This is because the 0,0,0 of an object is going to be a corner so the rotation you are seeing is on its 0,0,0 axis I would imagine.

**Comment by cuttingedge03** [comment]
@ToxicBakery How do you wrap an object in a container to center it on an axis? Some code on it will be helpful.

**Comment by ToxicBakery** [comment]
All objects are containers in the engine so simply creating a new Object3D then putting your module inside at a position that is model.getWidth() * -0.5, model.getHeight * -0.5 etc.

**Comment by raghav71094** [comment]
I think this issue has been fixed and you can do
mObject.rotate(Axis.Y, ANGLE);
to do rotation.
Please refer: https://github.com/Rajawali/Rajawali/issues/1017#issuecomment-22472707

**Comment by jwoolston** [comment]
Closing this issue as resolved/stale.
