### ISSUE TITLE
Sphere Render Issue on Samsung Galaxy S6 

### ISSUE THREAD

**Issue by j-mcmillan** [Rajawali/Rajawali#1529]
I am running a simple render of several spheres, some overlapping and am getting a jittery render.  

I am currently using EllipticalOrbitAnimation3D on my main camera which rotates around the central objects. I am not sure if this is causing the problem but it seems like the intersect ray bounces back and forth between hitting the nearest sphere or the one behind it when the spheres overlap.  

Possibly this is an issue with the ray intersect returning the wrong t value for which object it intersected that is nearest to the camera.  Maybe more of an openGL ES issue.

**Comment by j-mcmillan** [comment]
Would appear that only an intersect boolean is returned: https://github.com/Rajawali/Rajawali/blob/36034cad8fcf1ae82d2e2640860846f02d6a78ad/rajawali/src/main/java/org/rajawali3d/util/Intersector.java#L107

**Comment by ToxicBakery** [comment]
EllipticalOrbitAnimation3D takes a focal point to perform calculations of the periapsis and apoapsis radius. Given this I am not sure what you comment about ray intersections relates to.

As for the issue, sample code is the best way to evaluate issues.

**Comment by j-mcmillan** [comment]
In thinking about it, it is most likely an issue with hardware/openGL ES since it is handling the ray casting.

The problem doesn't occur in simulation, on a Galaxy S3, or a nexus 5.

Going to close this since it probably isn't actually something that can be solved in Rajawali.
