### ISSUE TITLE
Texture not working in obj loading.

### ISSUE THREAD

**Issue by SarbarthaSengupta** [Rajawali/Rajawali#1530]
I have exported an obj (with all the necessary flags set in blender). But when I import it in rajawali texture is not coming. if I import it into blender again, its working perfectly.

code: 
```
 package com.nightowl.five60;

 import android.content.Context;
 import android.view.MotionEvent;

 import org.rajawali3d.Object3D;
 import org.rajawali3d.lights.DirectionalLight;
 import org.rajawali3d.lights.PointLight;
import org.rajawali3d.loader.LoaderOBJ;
import org.rajawali3d.loader.ParsingException;
import org.rajawali3d.materials.Material;
import org.rajawali3d.materials.methods.DiffuseMethod;
import org.rajawali3d.math.vector.Vector3;
import org.rajawali3d.primitives.Sphere;
import org.rajawali3d.renderer.RajawaliRenderer;

/**
 * Created by Sarbartha on 21-07-2015.
 */
public class Renderer extends RajawaliRenderer  {
    private final Context context;
    private DirectionalLight directionalLight;
    private PointLight pLightLH;
    private Object3D tableObj;
    private Sphere earth;
    private LoaderOBJ table;
    private  Material tableM;
    public Renderer(Context context) {
        super(context);
        this.context = context;
        setFrameRate(60);
    }

    @Override
    protected void initScene() {
        directionalLight = new DirectionalLight(0f, 15f, 3f);
        pLightLH = new PointLight();
        pLightLH.setPower(12f);
        pLightLH.setPosition(-15, 12, 5);
        getCurrentScene().addLight(pLightLH);
       // directionalLight.setLookAt(0,0,1);
        directionalLight.setColor(1.0f, 1.0f, 1.0f);
        directionalLight.setPower(12);
        getCurrentScene().addLight(directionalLight);

        try {
            loadTable();
        } catch (ParsingException e) {
            e.printStackTrace();
        }

        //earth = new Sphere((float) 0.5, 24, 24);
        //earth.setMaterial(material1);
       // getCurrentScene().addChild(earth);
        getCurrentCamera().setX(15f);
        getCurrentCamera().setZ(0f);
        getCurrentCamera().setY(5.2f);
        getCurrentCamera().setLookAt(0,0,0);
    }

    private void loadTable() throws ParsingException {
        table = new LoaderOBJ(this,R.raw.table);
        table.parse();
        tableObj= table.getParsedObject();
        tableObj.setDoubleSided(true);
        getCurrentScene().addChild(tableObj);
    }
    @Override
    public void onRender(final long elapsedTime, final double deltaTime) {

        super.onRender(elapsedTime, deltaTime);
       tableObj.rotate(Vector3.Axis.Y, 1.0);

    }
    @Override
    public void onOffsetsChanged(float v, float v1, float v2, float v3, int i, int i1) {

    }

    @Override
    public void onTouchEvent(MotionEvent motionEvent) {

    }
}
```
obj file: 

```
# Blender v2.75 (sub 0) OBJ File: ''
# www.blender.org
mtllib table1.mtl
o Cylinder.000_Cylinder.004_top.010
v -0.820283 3.032353 -5.121859
v -0.664405 3.032353 -5.087827
```

mtl file:
```
# Blender MTL File: 'None'
# Material Count: 1

newmtl top
Ns 96.078431
Kd 0.640000 0.640000 0.640000
Ks 0 0 0
Ka 0 0 0
illum 2
map_Kd wood.jpg
```

When I load it in blender its showing as 
![blander](https://cloud.githubusercontent.com/assets/10404697/8815829/3e394734-303c-11e5-9491-8680c2a99bb7.png)
But when I render it in rajawali I get this:
![rajawali](https://cloud.githubusercontent.com/assets/10404697/8815839/6928d090-303c-11e5-8e4e-f5031c3fa440.jpg)

Can anyone help me to figure out the problem?

**Comment by SarbarthaSengupta** [comment]
Getting these in the log:

```
07-22 21:18:46.429  25554-25593/? I/Rajawali﹕ Parsing object: table.003
07-22 21:18:46.446  25554-25593/? E/addEtc1Texture﹕ Not a PKM file.
07-22 21:18:46.460     778-1614/? W/libprocessgroup﹕ failed to open /acct/uid_10114/pid_24909/cgroup.procs: No such file or directory
07-22 21:18:46.665  25594-25615/? W/Settings﹕ Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
07-22 21:18:46.700  25594-25594/? V/IPC﹕ Current service version 51033587, last check version 51033587
07-22 21:18:46.940  25554-25593/? D/String﹕ Falling back to uncompressed texture
```

**Comment by SarbarthaSengupta** [comment]
Even the developers of Rajawali doesn't bother to reply ... thats sad ...

**Comment by SMalpica** [comment]
take into account that they do this in their free time and for nothing. They might be bussy with other important things. I'm also having similar problem with a sphere. Have you tried to reattach the texture once you've already loaded the object? or exporting to .awd? be more patient and in the meanwhile try different ways to solve it.

**Comment by jwoolston** [comment]
> take into account that they do this in their free time and for nothing. They might be bussy with other important things.

Exactly. Thanks @SMalpica. In my case I just bought 2 acres of massively overgrown land in California which you may or may not know is in a drought never seen in recorded history. I spend all my free time right now trying to keep my property and house from bursting into flames while we are in wild fire season.

**Comment by SarbarthaSengupta** [comment]
I understand that. But its just frustrating me :( .. I am trying to solve it in many ways. none are working.
I changed the "." into "_" even for the png file. But its not working. 

 I tried to put the png in drawable folder also. nothing is working for me :(

I am still trying to figure it out. I also tried to reattach the texture. Its giving run time error.

**Comment by jchristof** [comment]
These changes to LoaderObj allow me to load an obj file from sd:

    String materialLibPath = parts.nextToken();//.replace(".", "_");
...

    mat.addTexture(new Texture(getFileNameWithoutExtension(getOnlyFileName(matDef.diffuseTexture)), BitmapFactory.decodeFile(filePath)));

Also, I think documentation mentions power of 2 sized textures.

**Comment by jwoolston** [comment]
Closing this issue as resolved/stale. Please create a new issue detailing the current problems if they persist.
