### ISSUE TITLE
does rajawali support shadowing ?

### ISSUE THREAD

**Issue by fulean** [Rajawali/Rajawali#1532]
does rajawali has shadowing implementation already ?  I found no examples show how  to create a shadow , could anyone give some suggestion on this topic,  thanks !

**Comment by fulean** [comment]
i found the ShadowEffect class has no effect completely  , when moving the direction of the DirectionLight , can't cast shadow on any object, casting shadow dynamically  doesn't  implemented at this point,right ?

**Comment by jwoolston** [comment]
It does, but it is known to be broken at the moment. Closing as not an issue.
