### ISSUE TITLE
Transformable3D Euler-based getters/setters

### ISSUE THREAD

**Issue by rpicolet** [Rajawali/Rajawali#1534]
Transformable3D setRotX/Y/Z() use Quaternion fromEuler() [which assumes degrees] to set the angles, and use Quaternion getRotX/Y/Z() [which return radians] to get/set the two values not being changed, so radians are passed in to fromEuler() for the unchanged values. 

Also, the implementations of Transformable3D setRotation/RotX/RotY/RotZ() appear to conflict with the documented usage of Quaternion fromEuler() [which correlates yaw to the y-axis, pitch to the x-axis, and roll to the z-axis]; the Transforemable3D implementations appear to swap pitch and roll from that usage...

Pretty sure these are both bugs, but I'm not at all sure what the best fixes would be from a library perspective; seems like APIs/interfaces may need to change...

**Comment by rpicolet** [comment]
Forgot to say main branch, and of course it's ATransformable3D...

**Comment by rpicolet** [comment]
And they use getYaw(), getPitch(), and getRoll() from Quaternion [rather than getRotX/Y/Z() as I erroneously described...]

**Comment by rpicolet** [comment]
Also, probably why ObjectPickingExample doesn't rotate anymore...

**Comment by jwoolston** [comment]
Yes this is all one big bug.

**Comment by jwoolston** [comment]
I will take care of this sometime next week.

**Comment by rpicolet** [comment]
No hurry from this end, I was just looking at the ObjectPicking example, and somehow remembered that I had posted this a while back and wanted document it in case someone came at it from that direction, so they wouldn't have to rediscover stuff.

In my app, I sub-classed Object3D and put temp fixes in there; I can share those if you want, but they're pretty straightforward.
