### ISSUE TITLE
How to draw a plane which would fit the entire screen irrespective to the screen size?

### ISSUE THREAD

**Issue by ParagRKadam** [Rajawali/Rajawali#1535]
I am trying to create a Plane object to which I am setting a Material and adding image texture to the material.
I have seen similar examples like this but I couldn't use them because most of the classes being used in those examples are no more in use(Ex. SimpleMaterial) as I am using the latest Rajawali version.
I am getting what i want using a Sphere but i want the same to happen using Plane. 
The working code for sphere is as follows,

public void initScene()
    {
        Sphere sphere = createPhotoSphereWithTexture(new Texture("newImage",R.drawable.image));
        getCurrentScene().addChild(sphere);
        getCurrentCamera().setPosition(Vector3.ZERO);
        getCurrentCamera().setFieldOfView(75);
        setFrameRate(60);
}

private static Sphere createPhotoSphereWithTexture(ATexture texture) {
        Material material = new Material();
        material.setColor(0);
        try {
            material.addTexture(texture);
        } catch (ATexture.TextureException e) {
            throw new RuntimeException(e);
        }
        Sphere sphere = new Sphere(50, 64, 32);    //Should be replaced by a equivalent plane instead.
        sphere.setScaleX(-1);
        sphere.setMaterial(material);
        return sphere;
    }

**Comment by jwoolston** [comment]
You can use the `ScreenQuad` class for this.
