### ISSUE TITLE
Drawing a simple bitmap to the screen

### ISSUE THREAD

**Issue by skmlcd** [Rajawali/Rajawali#1536]
Is there any simple way to add a bitmap to the screen? I'm looking at [Tutorial 32](https://github.com/Rajawali/Rajawali/wiki/Tutorial-32-Using-Canvas-for-Textures) and code example doesn't work.

I have successfully drew a 3D object, but don't know how to draw additional bitmap above this object.

I already have a method that generates and returns a bitmap, called _textAsBitmap()_ which takes a String. The majority of code below is taken from 32 tutorial.

```
// Create a bitmap
final Bitmap generatedBitmap = textAsBitmap("Lorem Ipsum");

final SimpleMaterial simpleMaterial = new SimpleMaterial();
simpleMaterial.addTexture(mTextureManager.addTexture(generatedBitmap));

final Plane largeCanvasPlane = new Plane(2, 2, 2, 2);
largeCanvasPlane.setZ(-0.75f);
largeCanvasPlane.setMaterial(simpleMaterial);

getCurrentScene().addChild(largeCanvasPlane);
```

Android Studio gives me error on these lines:
```
final SimpleMaterial simpleMaterial = new SimpleMaterial();
simpleMaterial.addTexture(mTextureManager.addTexture(generatedBitmap));
```

A generic error on ```SimpleMaterial```: _Cannot resolve symbol 'SimpleMaterial'_. And below on ```.addTexture``` it says: _Cannot resolve method 'addTexture'_.

It does not suggest to import anything. What is the problem? Is this a correct way to draw a bitmap to the screen? I'm using stable release.

**Comment by chr314** [comment]
use can Material
example:

Material material = new Material();
pln.setMaterial(material);
material.addTexture(texture);
getCurrentScene().addChild(pln);

**Comment by skmlcd** [comment]
Thank you for your help! Currently I have put my project on hold,  so I will test your suggestion later. I will close this issue for now and reopen it later to give some feedback info.
