### ISSUE TITLE
GSL MEM ERROR on master

### ISSUE THREAD

**Issue by jchristof** [Rajawali/Rajawali#1537]
The following code produces an app crash with the message:

08-06 12:01:47.004    3347-3372/com.example.jm.myapplication E/Adreno-GSL﹕ <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
08-06 12:01:47.005    3347-3372/com.example.jm.myapplication A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3372 (GLThread 84907)

Still looking into why, but here's the code to reproduce in case someone has some insight that will help. Takes about 1 minute of rendering before the crash on my lgg2:

    public class MainActivity extends AppCompatActivity {
    RajawaliRenderer renderer;
    IRajawaliSurface surface;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        renderer = new RajawaliRenderer(this, true) {
            @Override
            protected void initScene() {
                renderer.getCurrentScene().getCamera().setPosition(0, 0, 10);
            }

            Material material = new Material();
            void debugInit(){
                for(int i = 0; i< 1000; i++) {
                    Cube c = new Cube(1);
                    c.setPosition(new Vector3(5 - (Math.random() * 10), 5 - (Math.random() * 10), -Math.random() * 5));
                    c.setMaterial(material);
                    c.setColor(new Vector3(Math.random(), Math.random(), Math.random()));
                    renderer.getCurrentScene().addChild(c);
                }
            }

            void removeSceneChildren(){
                ArrayList<Object3D> children = renderer.getCurrentScene().getChildrenCopy();
                for(Object3D child:children){
                    renderer.getCurrentScene().removeChild(child);
                }
            }

            int renderloops = 0;
            boolean add = true;
            @Override
            public void onRender(final long elapsedTime, final double deltaTime) {
                super.onRender(elapsedTime, deltaTime);
                if(renderloops++ == 10){
                    if(add)
                        debugInit();
                    else
                        removeSceneChildren();

                    add = !add;
                    renderloops = 0;
                }
            }

            @Override
            public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {}
            @Override
            public void onTouchEvent(MotionEvent event) {}
        };

        surface = new RajawaliSurfaceView(this);
        surface.setFrameRate(60);
        surface.setRenderMode(IRajawaliSurface.RENDERMODE_WHEN_DIRTY);
        surface.setSurfaceRenderer(renderer);
        addContentView((RajawaliSurfaceView) surface, new ActionBar.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT));
    }

**Comment by jchristof** [comment]
The issue is that Object3D.destroy() isn't called automatically when the object is removed from the scene. I could make a pull for the changes I've made, but I'm not set on if this should be the default behavior. For clearing all children, it probably should be since it's not removing based on someone else managing the Object3D.

Maybe the geometry buffer creation and destroy calls should be book ended in the calls to add and remove a child from the scene to help prevent the leaks rather than creating the buffers on object initialization:

	public boolean addChild(final Object3D child) {
        final AFrameTask task = new AFrameTask() {
            @Override
            protected void doTask() {
				child.construct();
                mChildren.add(child);
                if (mSceneGraph != null) {
                    //mSceneGraph.addObject(child); //TODO: Uncomment
                }
                addShadowMapMaterialPlugin(child, mShadowMapMaterial == null ? null : mShadowMapMaterial.getMaterialPlugin());
            }
        };
        return internalOfferTask(task);
	}

	public boolean removeChild(final Object3D child) {
        final AFrameTask task = new AFrameTask() {
            @Override
            protected void doTask() {
                mChildren.remove(child);
				child.destroy();
                if (mSceneGraph != null) {
                    //mSceneGraph.removeObject(child); //TODO: Uncomment
                }
            }
        };
        return internalOfferTask(task);
	}

**Comment by jwoolston** [comment]
@jchristof There is no bug here, everything is functioning as designed, and for the reason you point out. We would however not be opposed to adding an overloaded remove method that automatically destroys the object, giving the user the option to manage it themselves or fire and forget. As for the VBO creation, you can already optionally delay creation until first render of the object.

**Comment by jwoolston** [comment]
Per the reasoning of #1610, we will be doing nothing with this. The onus will be on developers to properly manage the lifecycle to promote flexibility and efficiency.
