### ISSUE TITLE
shadowmap works abnormaly when material contains a texture  

### ISSUE THREAD

**Issue by fulean** [Rajawali/Rajawali#1539]
I tested the shadowmap in the 2014 version, the effect works normally when a material don't have any texture , otherwise the casting shadow on an object with a materials which contains a texture will be distortion.I pasted four shaders as below, the first two shaders produce shadow abnormally, with texture used.the last two shaders works perfect,with no texture used,could you help me out, thanks !

abnormal effect :

 precision mediump float;
 const mat4 cBiasMatrix = mat4(0.5,0.0,0.0,0.0,
 0.0,0.5,0.0,0.0,
 0.0,0.0,0.5,0.0,
 0.5,0.5,0.5,1.0);
 uniform vec3 uLightColor0;
 uniform vec3 uLightDirection0;
 uniform mat4 uMVPMatrix;
 uniform vec3 uLightPosition0;
 uniform float uLightPower0;
 uniform mat4 uModelMatrix;
 uniform mat3 uNormalMatrix;
 uniform mat4 uModelViewMatrix;
 uniform vec3 uAmbientIntensity;
 uniform vec4 uColor;
 uniform vec3 uAmbientColor;
 uniform mat4 uLightMVPMatrix;
 attribute vec3 aNormal;
 attribute vec2 aTextureCoord;
 attribute vec4 aPosition;
 varying vec3 vAmbientColor;
 varying vec3 vNormal;
 varying vec4 vShadowTexCoord;
 varying vec4 vColor;
 varying vec4 vEye;
 varying float vLightAttenuation0;
 varying vec2 vTextureCoord;
 varying vec3 vEyeDir;
 vec4 gColor;
 vec4 gPosition;
 vec3 gNormal;
 float gLightDistance;
 vec2 gTextureCoord;
 void main() {
 gPosition = aPosition;
 gNormal = aNormal;
 gTextureCoord = aTextureCoord;
 gColor = uColor;
 vShadowTexCoord = uLightMVPMatrix * uModelMatrix * aPosition;
 vShadowTexCoord = cBiasMatrix * vShadowTexCoord;
 vEye = (uModelMatrix * gPosition);
 vAmbientColor.rgb = uAmbientColor.rgb * uAmbientIntensity.rgb;
 vLightAttenuation0 = 1.0;
 gl_Position = uMVPMatrix * gPosition;
 vNormal = normalize(uNormalMatrix * gNormal);
 vTextureCoord = gTextureCoord;
 vColor = gColor;
 vEyeDir = vec3(uModelViewMatrix * gPosition);
 }
 
  precision mediump float;
 const float cShadowBias = 0.005;
 uniform vec3 uLightColor0;
 uniform vec3 uLightDirection0;
 uniform sampler2D wallNormalTex;
 uniform vec3 uLightPosition0;
 uniform float uColorInfluence;
 uniform float uInfluencewallNormalTex;
 uniform float uLightPower0;
 uniform vec2 uRepeat0;
 uniform float uShadowInfluence;
 uniform sampler2D uShadowMapTex;
 uniform float uInfluencewallDiffuseTex;
 uniform vec3 uShadowLightDir;
 uniform sampler2D wallDiffuseTex;
 varying vec3 vAmbientColor;
 varying vec3 vNormal;
 varying vec4 vShadowTexCoord;
 varying vec4 vColor;
 varying vec4 vEye;
 varying float vLightAttenuation0;
 varying vec2 vTextureCoord;
 varying vec3 vEyeDir;
 float gShadowValue;
 float gSpecularValue;
 float NdotL0;
 vec4 gColor;
 vec3 gNormal;
 vec2 gTextureCoord;
 void main() {
 gNormal = normalize(vNormal);
 gTextureCoord = vTextureCoord;
 gColor = uColorInfluence * vColor;
 gShadowValue = 0.0;
 gSpecularValue = 1.0;
 gTextureCoord *= uRepeat0;
 vec4 texColor = texture2D(wallDiffuseTex, gTextureCoord);
 texColor *= uInfluencewallDiffuseTex;
 gColor += texColor;
 vec3 texNormal = vec3(texture2D(wallNormalTex, gTextureCoord));
 texNormal = texNormal.rgb * 2.0;
 texNormal -= 1.0;
 texNormal = normalize(texNormal);
 gNormal = normalize(texNormal + gNormal);!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 vec4 lightDepthCol = texture2D(uShadowMapTex, vShadowTexCoord.xy);
 float shadowLightAngle = dot(gNormal, uShadowLightDir);
 if(lightDepthCol.z<vShadowTexCoord.z - cShadowBias&&shadowLightAngle<=-0.15)
 {
 gShadowValue = uShadowInfluence;
 gSpecularValue = 0.0;
 }
 vec3 lightDir0 = normalize(uLightDirection0 * -1.0);
 vec3 diffuse = vec3(0.0);
 float power = 0.0;
 NdotL0 = max(dot(gNormal, lightDir0), 0.1);
 power = uLightPower0 * NdotL0 * vLightAttenuation0;
 diffuse += uLightColor0 * power;
 gColor.rgb = (diffuse * gColor.rgb) + vAmbientColor;
 gColor.rgb = gColor.rgb * (1.0 - gShadowValue);
 gl_FragColor = gColor;
 }

and this is the normal effect, note that no texture added into the material:

 precision mediump float;
 const mat4 cBiasMatrix = mat4(0.5,0.0,0.0,0.0,
 0.0,0.5,0.0,0.0,
 0.0,0.0,0.5,0.0,
 0.5,0.5,0.5,1.0);
 uniform vec3 uLightColor0;
 uniform vec3 uLightDirection0;
 uniform mat4 uMVPMatrix;
 uniform vec3 uLightPosition0;
 uniform float uLightPower0;
 uniform mat4 uModelMatrix;
 uniform mat3 uNormalMatrix;
 uniform mat4 uModelViewMatrix;
 uniform vec3 uAmbientIntensity;
 uniform vec4 uColor;
 uniform vec3 uAmbientColor;
 uniform mat4 uLightMVPMatrix;
 attribute vec3 aNormal;
 attribute vec2 aTextureCoord;
 attribute vec4 aPosition;
 varying vec3 vAmbientColor;
 varying vec3 vNormal;
 varying vec4 vShadowTexCoord;
 varying vec4 vColor;
 varying vec4 vEye;
 varying float vLightAttenuation0;
 varying vec2 vTextureCoord;
 varying vec3 vEyeDir;
 vec4 gColor;
 vec4 gPosition;
 vec3 gNormal;
 float gLightDistance;
 vec2 gTextureCoord;
 void main() {
 gPosition = aPosition;
 gNormal = aNormal;
 gTextureCoord = aTextureCoord;
 gColor = uColor;
 vShadowTexCoord = uLightMVPMatrix * uModelMatrix * aPosition;
 vShadowTexCoord = cBiasMatrix * vShadowTexCoord;
 vEye = (uModelMatrix * gPosition);
 vAmbientColor.rgb = uAmbientColor.rgb * uAmbientIntensity.rgb;
 vLightAttenuation0 = 1.0;
 gl_Position = uMVPMatrix * gPosition;
 vNormal = normalize(uNormalMatrix * gNormal);
 vTextureCoord = gTextureCoord;
 vColor = gColor;
 vEyeDir = vec3(uModelViewMatrix * gPosition);
 }
 ==============dump vertex shader string end================
 ==============dump fragment shader string start==============
  precision mediump float;
 const float cShadowBias = 0.005;
 uniform vec3 uLightColor0;
 uniform vec3 uLightDirection0;
 uniform vec3 uLightPosition0;
 uniform float uColorInfluence;
 uniform float uLightPower0;
 uniform float uShadowInfluence;
 uniform sampler2D uShadowMapTex;
 uniform vec3 uShadowLightDir;
 varying vec3 vAmbientColor;
 varying vec3 vNormal;
 varying vec4 vShadowTexCoord;
 varying vec4 vColor;
 varying vec4 vEye;
 varying float vLightAttenuation0;
 varying vec2 vTextureCoord;
 varying vec3 vEyeDir;
 float gShadowValue;
 float gSpecularValue;
 float NdotL0;
 vec4 gColor;
 vec3 gNormal;
 vec2 gTextureCoord;
 void main() {
 gNormal = normalize(vNormal);
 gTextureCoord = vTextureCoord;
 gColor = uColorInfluence * vColor;
 gShadowValue = 0.0;
 gSpecularValue = 1.0;
 vec4 lightDepthCol = texture2D(uShadowMapTex, vShadowTexCoord.xy);
 float shadowLightAngle = dot(gNormal, uShadowLightDir);
 if(lightDepthCol.z<vShadowTexCoord.z - cShadowBias&&shadowLightAngle<=-0.15)
 {
 gShadowValue = uShadowInfluence;
 gSpecularValue = 0.0;
 }
 vec3 lightDir0 = normalize(uLightDirection0 * -1.0);
 vec3 diffuse = vec3(0.0);
 float power = 0.0;
 NdotL0 = max(dot(gNormal, lightDir0), 0.1);
 power = uLightPower0 * NdotL0 * vLightAttenuation0;
 diffuse += uLightColor0 * power;
 gColor.rgb = (diffuse * gColor.rgb) + vAmbientColor;
 gColor.rgb = gColor.rgb * (1.0 - gShadowValue);
 gl_FragColor = gColor;
 }

**Comment by fulean** [comment]
resolved!

**Comment by jwoolston** [comment]
Closing this issue as resolved.
