### ISSUE TITLE
Object3D.setScreenCoordinates() anomaly?

### ISSUE THREAD

**Issue by rpicolet** [Rajawali/Rajawali#1550]
For this method to correctly display an Object3D at screen coordinates (x, y) it seems to be necessary to specify the y complement of the screen height, in other words (x, viewportHeight - y), undoing the same expression in the method's implementation...

Not sure if this is intentional, and easy enough to workaround, just thought I'd point it out in case the API needs to change...

org.rajawali3d:rajawali:1.0.279-SNAPSHOT@aar

**Comment by jwoolston** [comment]
I believe it is unintentional as I encountered some odd behavior with that function recently. Ill bump this to a bug to look into it at some point. Thanks.

**Comment by rpicolet** [comment]
This should obviously be low priority.

Thanks for all your hard work and continued support, I know many of us users can seem pretty demanding without contributing all that much.

**Comment by jwoolston** [comment]
> Thanks for all your hard work and continued support, I know many of us users can seem pretty demanding without contributing all that much.

As long as the requests/bug reports that come in are politely worded, it doesn't bother me. Obviously there is only so much that can be done in our limited time. The ones that annoy me are when no attempt has been made to ensure that there is actually a bug or when they are worded to imply we must fix it immediately because of some timeframe applying to the OP. In this case, the workaround you present indicates it clearly is not functioning as intended.

**Comment by jwoolston** [comment]
I took a closer look at this today an I believe it is functioning as intended. The reason being, Open GL uses a different coordinate system than Android screen points. In OpenGL, +Y is at the top of the screen, while in Android it is at the bottom. Were you taking this into account?

**Comment by rpicolet** [comment]
No, I was confused and just asking the question.  A javadoc update would work fine to clarify.  As with a number of methods, it's not always clear to a newbie like me which coordinate system/units/constraints are assumed.  So in your copious free time... 

Just kidding.  Not sure what the plans are for docs, but I would consider pitching in for a beer or two...

**Comment by jwoolston** [comment]
The plans for docs are, well, wishful thinking. Development tends to take precedence. Some of the devs and I meet up in SF from time to time for beers. I'll have to get you on the next email chain for it.

**Comment by rpicolet** [comment]
Sounds good, I'm gettin' a little thirsty...

**Comment by ToxicBakery** [comment]
We gladly accept pull requests for documentation ;)
