### ISSUE TITLE
Optimization : Can't resolve symbol 'ExportType'

### ISSUE THREAD

**Issue by YangSupelec** [Rajawali/Rajawali#1554]
Hi, recently, I try to reduce the time of parsing model obj to improve the performance of my app and I do as the instruction https://github.com/Rajawali/Rajawali/wiki/Tutorial-04-Optimization. But every time I type 
       MeshExporter exporter = new MeshExporter(myBaseObject3D);
       exporter.export("myBaseObject3Dname", ExportType.SERIALIZED);
there will be always the problem as Can't resolve symbol 'ExportType'
I don't know why and how to fix it.
Do you have any suggestion ?

**Comment by jwoolston** [comment]
Which version of Rajawali were you trying to use?

**Comment by jwoolston** [comment]
Closing this issue as stale. I suspect it is for `v0.9` anyway.
