### ISSUE TITLE
use other shader

### ISSUE THREAD

**Issue by YangSupelec** [Rajawali/Rajawali#1556]
how can I use other shader except VertexShader and FragmentShader ? In addition, how can I create a custom FragmentShader and VertexShader for the latest version Rajawali ? Thanks in advance for anyone's suggestion

**Comment by jwoolston** [comment]
This example shows how to inject custom code into the preconfigured shaders: https://github.com/Rajawali/RajawaliExamples/blob/master/examples/src/main/java/com/monyetmabuk/rajawali/tutorials/examples/materials/CustomMaterialShaderFragment.java

This example shows how to use a raw shader text you provide yourself: https://github.com/Rajawali/RajawaliExamples/blob/master/examples/src/main/java/com/monyetmabuk/rajawali/tutorials/examples/materials/RawShaderFilesFragment.java
