### ISSUE TITLE
load texture from json or web server?

### ISSUE THREAD

**Issue by power7714** [Rajawali/Rajawali#1557]
Can anyone provide an example on how to load a texture from server or web source? If we can get an example on how to do this, I can add this to the wiki as well for future users. This is important for my project and I'm sure there will be other users that would find this useful. Thank you.

**Comment by jwoolston** [comment]
This is out of scope of these issues directly. Once downloaded, adding the texture to rajawali would be not different than from any other source. I personally use Ion in my apps to fetch the image and decode it into a bitmap in one line.
