### ISSUE TITLE
Loaders Not Working In Mali GPU

### ISSUE THREAD

**Issue by UnnikrishnanMR** [Rajawali/Rajawali#1558]
While i was working i came across this situation where loaders are not working on mali gpu. They works perfectly fine in other gpus.  I have even tried running the Rajawali examples which also produce the same result. However there are no errors but the models are not being disaplyed. I tried it with Micormax Bolt and also Micormax Unite 2, both produce the same result. They works perfectly fine in the simple Sphere example. Is this an isolated issue or is it a problem on all devices with mali GPU?

**Comment by spacemase** [comment]
Rajawali uses high precision in its shaders - https://www.opengl.org/wiki/Type_Qualifier_(GLSL)#Precision_qualifiers

Not all Mali GPU support highp (Mali 450 and older do NOT), not certain when support was added to Mali for highp.

**Comment by spacemase** [comment]
edit ^

I am no longer certain it is the high precision shader.  I reduced my textures enough to display on Mali 450 GPU.  Examine MAX_RENDER_BUFFER_SIZE on the devices that work and those that do not.

**Comment by spacemase** [comment]
my hero!
