### ISSUE TITLE
Transparent RajawaliSurfaceView

### ISSUE THREAD

**Issue by bakedCouchPotato** [Rajawali/Rajawali#1560]
I am trying to develop an augmented reality app. (not with Vuforia)
To do this I have a camera preview and a RajawaliSurfaceView for the augmentation.

I managed to render the RajawaliSurfaceView in front of the CameraPreview with `rajawaliSurfaceView.setZOrderOnTop(true);`, but I can't find a working tutorial on removing the background from the scene.

I tried this:
`rajawaliSurfaceView.setEGLConfigChooser(8, 8, 8, 8, 16, 0);
//rajawaliSurfaceView.getHolder().setFormat(PixelFormat.RGBA_8888);//rajawaliSurfaceView.getHolder().setFormat(PixelFormat.TRANSLUCENT);
rajawaliSurfaceView.setBackgroundColor(Color.TRANSPARENT);`

But it allways clears the entire SurfaceView, not just the background.

In [this question](https://github.com/Rajawali/Rajawali/issues/1340?_pjax=%23js-repo-pjax-container) a method called `setGLBackgroundTransparent(true);` is mentioned.
This seems like something I need, however I can not find a class that has this function.

I also tried it with a RajawaliTextureView and using the method `setAlpha(255)`, but the outcome was the same as with the RajawaliSurfaceView.

**Comment by bakedCouchPotato** [comment]
OK - `rajawaliSurfaceView.setBackgroundColor(Color.TRANSPARENT);` did not work because it's a method of the super class `View`.

Note: Still unresolved

**Comment by dcerisano** [comment]
Do not use overlayed views. Do not ever use overlayed views. Use rajawali for everything.
Render the camera as a video texture for a screenquad.
Make sure the screenquad is the first object added to your scene graph.

**Comment by cheong12001** [comment]
can you explain more? i have experienced the exactly problem, so i switch to the RajawaliTextureView instead. although the textureview support z-order, the blackground is appeared as black which is the same as RajawaliSurfaceView. Thanks in advanced.

**Comment by bakedCouchPotato** [comment]
I use the [Google Vision API](https://developers.google.com/vision/face-detection-concepts?hl=en) to detect faces and their position relative to camera preview (SurfaceView).

I want to display a 3d object, say a pair of glasses, on the detected faces.
My previous attempt was to render a Rajawali Scene (RajawaliSurfaceView) over the camera preview.

Apparently this won't work.

I usually work with Unity3d and am used to the [WebCamTexture](http://docs.unity3d.com/ScriptReference/WebCamTexture.html)

Is there something like that in Rajawali? What would I have to do to make the Video Texture display the front camera preview?

**Comment by cheong12001** [comment]
i am seeking for a way too. i have tried a lot of ways but with null result.

**Comment by dcerisano** [comment]
pipeline

**Comment by bakedCouchPotato** [comment]
I have another idea:

The rendering in Rajawal is probably like this...

    1. Render skybox
    2. Render object
    3. Render object
    4. Render object
    ....

right?

This would mean that by inserting `gl.glClearColor(0,0,0,0);` between 1. and 2. I could make a transparent RajawaliSurface, but still be able to see the scene.

Please tell me if this would work and in which class I have to look for this.

**Comment by dcerisano** [comment]
pipeline.

**Comment by adamantivm** [comment]
I think I have a way to get what you need to work.
Did you try doing this

I was able to get this to work once in the past. I don't remember exactly how it was but it required doing things like:

 - Setting rajawaliSurfaceView.setZOrderOnTop(false) in onCreate
 - Defining the RajawaliSurfaceView earlier in the layout than the camera preview
 - Configuring the RajawaliSurfaceView with isTransparent = true (I did that in the layout markup in my case)

I hope it's not too late to help.

**Comment by jwoolston** [comment]
All you need to do is call `RajawaliScene#setBackgroundColor(int, int, int, int)`

**Comment by huylv177** [comment]
Sorry everyone but i still cant do that, anyone give me an example project please? Thank you

**Comment by ramesh130** [comment]
Below is my configuration that worked. version 1.0.325

`RajawaliSurfaceView rjSurfaceView = (RajawaliSurfaceView) findViewById(R.id.rajawali_surface_view);`
`rjSurfaceView.setFrameRate(60);`
`rjSurfaceView.setRenderMode(IRajawaliSurface.RENDERMODE_WHEN_DIRTY);`
`rjSurfaceView.setTransparent(true);`
`rjSurfaceView.setSurfaceRenderer(new Rajawali3DRenderer(this));`
