### ISSUE TITLE
Creating custom material with diffuse lighting

### ISSUE THREAD

**Issue by mukulabdagiri** [Rajawali/Rajawali#1562]
Hello,

I was able to use a custom material (extending simple material) with no lights.
This was a helpful link:
https://github.com/Rajawali/Rajawali/wiki/Tutorial-09-Creating-a-Custom-Material---GLSL-Shader

How can I make a custom material with lights enabled on a 3d object.
I tried to extend DiffuseMaterial, but I see no lights and the behavior is same as SimpleMaterial and this is what i see:

![lightsoff](https://cloud.githubusercontent.com/assets/8483720/10992796/977e9086-848f-11e5-8317-44b2b6f14eb2.jpg)

I want to show a 3d object fading in with directional lights casting on it, like this:
![lightson](https://cloud.githubusercontent.com/assets/8483720/10992791/88436150-848f-11e5-8f46-09a79cafffba.jpg)

How can I achieve this? Any help is appreciated.

Thanks,
Mukul

**Comment by jwoolston** [comment]
If you are making a custom glsl material, this is out of scope of this issue board. You will need to find help at a more general GLSL forum. If you are trying to use Rajawali's shader builders, the examples give ample example of how to add lights to materials.
