### ISSUE TITLE
Labeling parts of 3D model

### ISSUE THREAD

**Issue by medonja** [Rajawali/Rajawali#1563]
I have imported a model (e.g. a teapot) using Rajawali into my scene. What I would like is to label parts of the model (e.g. the lid, body, foot, handle and the spout) using plain Android views, but I have no idea how this could be achieved. Specifically, positioning the labels on the right place seems challenging. The idea is that when I transform my model's position in the scene, the tips of the labels are still correctly positioned

Rajawali tutorial show how Android views can be placed on top of the scene here https://github.com/Rajawali/Rajawali/wiki/Tutorial-08-Adding-User-Interface-Elements . I also understand how using the transformation matrices a 3D coordinate on the model can be transformed into a 2D coordinate on the screen, but I have no idea how to determine the exact 3D coordinates on the model itself. The model is exported to OBJ format using Blender, so I assume there is some clever way of determining the coordinates in Blender and exporting them to a separate file or include them somehow in the OBJ file (but not render those points, only include them as metadata), but I have no idea how I could do that.

Any ideas are very appreciated! :)

**Comment by PerunServer** [comment]
Any progress ?

**Comment by contriteobserver** [comment]
One method of identifying parts of a model is to give each part it's own material, LoaderOBJ will then load each part as a child mesh. Then one can calculate the hollow centroid of each part.
```
    private class ObjRenderer extends Renderer {

        public ObjRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);;

                DirectionalLight key = new DirectionalLight(2,2,2);
                key.setPosition(-2,-2,-2);
                key.setPower(1);
                getCurrentScene().addLight(key);

                DirectionalLight fill = new DirectionalLight(-2,-2,2);
                fill.setPosition(2,2,-2);
                fill.setPower(0.125f);
                getCurrentScene().addLight(fill);

                LoaderOBJ loader = new LoaderOBJ(this, R.raw.teapot01_obj);
                loader.parse();
                Object3D object = loader.getParsedObject();
                for(int i=0; i< object.getNumChildren(); i++) {
                    Log.d(getLocalClassName(), "found child named: " + object.getChildAt(i).getName());
                    Log.d(getLocalClassName(), "child centroid: " + hollow_centroid(object.getChildAt(i).getGeometry()));
                }

                getCurrentScene().addChild(object);

                getCurrentCamera().setPosition(9,9,9);
                getCurrentCamera().setLookAt(object.getPosition());
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }
        }

        Vector3 hollow_centroid(Geometry3D g) {
            Vector3 centroid = new Vector3();
            FloatBuffer vertices = g.getVertices();
            IntBuffer indices = (IntBuffer)g.getIndices();

            float x = 0;
            float y = 0;
            float z = 0;
            for(int i=0; i<g.getNumIndices(); i++) {
                int index = indices.get(i);
                centroid.x += vertices.get(3*index+0);
                centroid.y += vertices.get(3*index+1);
                centroid.z += vertices.get(3*index+2);
            }
            if(g.getNumIndices()>0) centroid.multiply(1/(double)g.getNumIndices());
            return centroid;
        }
        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```

**Comment by jwoolston** [comment]
Closing this issue as resolved/stale. Thankyou @contriteobserver .
