### ISSUE TITLE
Best method to add plane at runtime

### ISSUE THREAD

**Issue by conect** [Rajawali/Rajawali#1565]
Hello, could you tell me which is the best method to add a new plane() at the runtime within my MainActivity.
I've got an Object which extends Object3D and this object should consist out of planes.
During runtime I want to add new Planes() with certain height width and position and orientation and add them to my Object.

How can I synchronize the adding without interfering with the renderer thread?

Thanks a lot.

**Comment by conect** [comment]
?

**Comment by jwoolston** [comment]
If you are adding them as children to an existing object, currently there is no way without overriding the addChild method of Object3D completely. If you are adding them to the scene, Rajawali already handles that for you.

**Comment by conect** [comment]
Well it only works, if I create another independent thread in which I call addChild();.

**Comment by jwoolston** [comment]
Define "only works". There is no indication here to describe what your problem might be. There is no reason why you should need to create a new thread to call addChild, though it would be the better way to do it anyway to avoid impacting the render thread.

**Comment by conect** [comment]
If I use a OnClick Event from the Android-UI-Thread I cannot add a new object3d to the scene. It only works if I create a new Thread.

**Comment by jwoolston** [comment]
I cant help you unless you are more descriptive about what is not working. Is there a crash? A stack trace? Does nothing happen? What code are you using to add the object? For all I know you are adding an object without specifying a material for it. I can't see what you do, so you need to tell me about what you are seeing.

**Comment by conect** [comment]
Within the on clickroutine I'm creating an cube and a Material for it if i create and add the cube within an anonymous thread it works fine.

**Comment by jwoolston** [comment]
I am closing this issue until you provide more details that make it possible for me to assist you.
