### ISSUE TITLE
Setting up a customized shader for material

### ISSUE THREAD

**Issue by conect** [Rajawali/Rajawali#1567]
Hi I'd like to setup a customized shader for rendering a pointcloud.
The points should be colored differently depending on the position of the scene.
The code for the setup comes from here:
https://github.com/googlesamples/tango-examples-java/blob/master/TangoUtils/app/src/main/java/com/projecttango/rajawali/renderables/primitives/Points.java

I tried following code:

 private static final String sVertexShaderCode = "uniform mat4 uMVPMatrix;"
                + "attribute vec4 vPosition;" + "varying vec4 vColor;"
                + "void main() {" + "gl_PointSize = 5.0;"
                + "  gl_Position = uMVPMatrix * vPosition;"
                + "  vColor = vPosition;" + "}";
 private static final String sFragmentShaderCode = "precision mediump float;"
                + "varying vec4 vColor;"
                + "void main() {"
                + "  gl_FragColor = vec4(vColor);" + "}";

see line 38 in the Points.java
Material m = new Material(new VertexShader(sVertexShaderCode), new FragmentShader(sFragmentShaderCode));
setMaterial(m);

But the point cloud is colored red instead of having different colors. Apparently the shaders aren't used at all, which commands do I have to execute to get the shaders working.

Thanks very much.

**Comment by conect** [comment]
anyone?

**Comment by adamantivm** [comment]
I'm also interested in how to get this to work. bump?

**Comment by conect** [comment]
bump?

**Comment by jwoolston** [comment]
Do you see any error logs related to the shader programs?

**Comment by jwoolston** [comment]
Closing this issue as stale. Please comment if you continue to have troubles.
