### ISSUE TITLE
Cannot display RajawaliTextureView inside a ScrollView

### ISSUE THREAD

**Issue by mbt-vincent-r** [Rajawali/Rajawali#1570]
Following a recommendation on my StackOverFlow Question, I post here my issue.

Following the first tutorial, I would like to display the rotating Earth inside a ScrollView so that I can see how it handles a scroll event.

This is required for a project I am working where I might have to display multiple small TextureView inside a ScrollView. The number of TextureView can vary,

Thanks for the help.

Related SO question : http://stackoverflow.com/questions/34174163/android-how-to-add-a-textureview-inside-a-scrollview

**Comment by jwoolston** [comment]
I have not tried using the TextureView inside a scroll view. I will try and remember to take a look and see what I can find out.

**Comment by jwoolston** [comment]
@mbt-vincent-r :point_up: I just added an example of this. You can find it here: https://github.com/Rajawali/Rajawali/blob/master/examples/src/main/java/org/rajawali3d/examples/examples/ui/ScrollingTextureViewFragment.java

Closing this issue as resolved for now. I will re-open if you are still having problems.
