### ISSUE TITLE
How to achieve camera positioning for dynamic 3d models ?

### ISSUE THREAD

**Issue by DDM1** [Rajawali/Rajawali#1573]
Hello,
I have scene where I load 3d objects dynamically from sd card. Currently I am trying to set position of arcball camera according to size of 3d object. So, for all sizes view looks similar. 

In libgdx, I can get depth of bounding box and use that to position camera like :

```
float maxDistance = boundingBox.getDepth();
cam.position.set(0f, 0f,maxDistance * 2);
```

I want to do same in Rajawali to set position of camera properly for dynamic models. Is there any other idea for setting camera position to show 3d model dynamically. Anyway, here is my code I am trying. 

```
   //--- OBJ Part  ----
            LoaderOBJ objParser = new LoaderOBJ(this, "Download/small_car_obj");
            try {
                objParser.parse();
                mObjectGroup = objParser.getParsedObject();

                Material material = new Material();
                material.enableLighting(true);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());

                mObjectGroup.setMaterial(material);
                mObjectGroup.setShowBoundingVolume(true);
                getCurrentScene().addChild(mObjectGroup);
            } catch (ParsingException e) {
                e.printStackTrace();
            }


            //------- Camera part ---
            BoundingBox boundingBox;
            if(mObjectGroup.getGeometry().hasBoundingBox()){
                boundingBox = mObjectGroup.getGeometry().getBoundingBox();
                boundingBox.transform(mObjectGroup.getModelMatrix());
            }

            arcball = new ArcballCamera(mContext, ((Activity)mContext).findViewById(R.id.drawer_layout));
            arcball.setPosition(0,0,550);  //--How can I get depth of boundarybox here and use in z-axis--
            arcball.setTarget(mObjectGroup);
            arcball.setFarPlane(800);

            getCurrentScene().replaceAndSwitchCamera(getCurrentCamera(), arcball);
```

**Comment by contriteobserver** [comment]
using BoundingSphere.getRadius() should get you there:
`            //--- OBJ Part  ----
            LoaderOBJ objParser = new LoaderOBJ(this, R.raw.teapot);
            try {
                objParser.parse();
                mObjectGroup = objParser.getParsedObject();

                Material material = new Material();
                material.enableLighting(true);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());

                for(int i=0; i<mObjectGroup.getNumChildren(); i++) {
                    Object3D child = mObjectGroup.getChildAt(i);
                    child.setMaterial(material);
                    child.setMaterial(material);
                    getCurrentScene().addChild(child);
                }
            } catch (ParsingException e) {
                e.printStackTrace();
            }

            //------- Camera part ---
            double radius = 0;
            for(int i=0; i<mObjectGroup.getNumChildren(); i++) {
                Object3D child = mObjectGroup.getChildAt(i);
                BoundingSphere boundingSphere = child.getGeometry().getBoundingSphere();
                boundingSphere.transform(child.getModelMatrix());
                if(boundingSphere.getRadius()>radius) radius = boundingSphere.getRadius();
            }

            arcball = new ArcballCamera(mContext, ((Activity)mContext).findViewById(R.id.rajawali_surface));
            arcball.setPosition(0,0,radius*2);  //--How can I get depth of boundarybox here and use in z-axis--
            arcball.setTarget(mObjectGroup);
            arcball.setFarPlane(800);

            getCurrentScene().replaceAndSwitchCamera(getCurrentCamera(), arcball);
`

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
