### ISSUE TITLE
How to get a texture from framebuffers

### ISSUE THREAD

**Issue by Pytimo** [Rajawali/Rajawali#1578]
I want to create a water scene in rajawali...so am faced with a task of getting textures from framebuffers to implement reflections on the water....any help will be highly appreciated Thanks Timothy

**Comment by jwoolston** [comment]
Take a look at this example: https://github.com/Rajawali/RajawaliExamples/blob/master/examples/src/main/java/com/monyetmabuk/rajawali/tutorials/examples/postprocessing/RenderToTextureFragment.java

**Comment by jwoolston** [comment]
Closing this issue as stale. Please add additional info if this is still a problem.
