### ISSUE TITLE
Relocate and Update RajawaliExamples for Material UI

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1579]
With the stabilization of the Android Design Libraries and increasing uptake of Lollipop and later devices, we should update the Examples app to utilize Material UI concepts.

Additionally, as we slowly improve our CI setup, it makes the most sense to relocate all the various libraries into modules within this one repository. Tickets for each will be created but this will serve as the relocation ticket for the examples app. The old repositories will stay for posterity and be marked as inactive.

**Comment by ToxicBakery** [comment]
Mmm Bombshell.. it's almost time for the Newcastle summer ale's.

**Comment by jwoolston** [comment]
This should include updating the example links.

**Comment by jwoolston** [comment]
As of #1590, the examples are now in the main repository.
