### ISSUE TITLE
surfaceview flickers on scene color change

### ISSUE THREAD

**Issue by omiu** [Rajawali/Rajawali#1584]
When i set current scene color to white, when activity starts i got this flickering from black to white. how can i avoid this?

**Comment by jwoolston** [comment]
Without any detailed information it is not possible to determine the cause of your issue. Testing it myself, adding `getCurrentScene().setBackgroundColor(Color.WHITE);` in `RajawaliRenderer#initScene()` worked fine.

**Comment by jwoolston** [comment]
In the future, please follow the guidelines provided in the issue template.

**Comment by omiu** [comment]
i think i found the problem, someone set a directional light to scene the change scene background. Thanks a lot

**Comment by omiu** [comment]
A question: it is possible to have 2 surface view in the same layout?
