### ISSUE TITLE
2 Surface View in same layout

### ISSUE THREAD

**Issue by omiu** [Rajawali/Rajawali#1585]
It is possible to add 2 surface view in the same layout?

if not, how can i add two 3d objects to the scene?

**Comment by jwoolston** [comment]
It is not possible to have two surface views. Two texture views however are possible but not recommended unless you have a strong reason for it. As for adding multiple 3d objects to the scene, thats what this method is for: https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/main/java/org/rajawali3d/scene/RajawaliScene.java#L467

**Comment by jwoolston** [comment]
Closing this issue as stale/resolved. Please add additional info if this is still a problem.
