### ISSUE TITLE
Help with LoaderSTL

### ISSUE THREAD

**Issue by RockySteveJobs** [Rajawali/Rajawali#1591]
I use the class of LoaderSTL load object but can't work , RajawaliExamples does not the example of load the STLObject, how should i do ?

**Comment by jwoolston** [comment]
All Rajawali loaders use the same interface. The AWD loading example should work if you replace LoaderAWD with LoaderSTL and choose an appropriate file.

**Comment by RockySteveJobs** [comment]
#### Thank your answer !   I try it again just as you said ,however, it can't work ! 

my code as follows:

                final LoaderSTL parser = new LoaderSTL(mContext.getResources(), mTextureManager,                             R.raw.common_maliao_model);
                parser.parse();
                final Object3D obj = parser.getParsedObject();
                obj.setPosition(0, -3, 0.0);

                obj.setScale(1f);
                Material material = new Material();
                material.setColorInfluence(0);
                obj.setMaterial(material);

                getCurrentScene().addChild(obj);

                final Animation3D anim = new RotateOnAxisAnimation(Vector3.Axis.Y, -360);
                anim.setDurationDelta(4d);
                anim.setRepeatMode(Animation.RepeatMode.INFINITE);
                anim.setTransformable3D(obj);

                anim.play();
                getCurrentScene().registerAnimation(anim);

**Comment by jwoolston** [comment]
Where are you calling this code? Do you have a stack trace to provide?

**Comment by RockySteveJobs** [comment]
#### I'm calling this code in initScene method 《the LoaderOBJ do work (load .obj file) ，but the LoaderSTL  do not  work (load .stl file)》 my logcat as follows。

03-08 21:46:51.491  17021-17021/? I/Rajawali﹕ Rajawali | Anchor Steam | v1.0
03-08 21:46:51.491  17021-17021/? E/libEGL﹕ call to OpenGL ES API with no current context (logged once per thread).
03-08 21:46:51.551  17021-24911/? I/Rajawali﹕ StlPaser: Reading Binary
03-08 21:46:51.571  17021-17021/? I/AssistantService﹕ public int onStartCommand(Intent intent, int flags, int startId) {
03-08 21:46:51.641  17021-24911/? D/dalvikvm﹕ GC_FOR_ALLOC freed 4823K, 23% free 21808K/28252K, paused 11ms, total 11ms
03-08 21:46:51.641  17021-24911/? E/Rajawali﹕ Getting location of uniform: uModelMatrix returned -1!
03-08 21:46:51.641  17021-24911/? E/Rajawali﹕ Getting location of uniform: uTime returned -1!
03-08 21:47:07.031  17021-24911/? D/dalvikvm﹕ GC_FOR_ALLOC freed 3334K, 29% free 20115K/28252K, paused 26ms, total 28ms

**Comment by jwoolston** [comment]
The problem appears to be related to your material.

`Material material = new Material();
 material.setColorInfluence(0);
 obj.setMaterial(material);`

You are telling the material to ignore the color of the object but you are not specifying a texture to use in its place. Try replacing `material.setColorInfluence(0)` with `material.setColor(0xffff00ff)`. That should render your object as purple.

**Comment by RockySteveJobs** [comment]
#### oh，thank you very much , it worked !

**Comment by jwoolston** [comment]
Closing this issue as resolved.
