### ISSUE TITLE
When will to add OpenGL ES 3.0?

### ISSUE THREAD

**Issue by wangcan26** [Rajawali/Rajawali#1593]
just one Question:
     Rajawali3D is truly a wonderful 3D Engine.  Since Rajawali3D has Labeled it as a OpenGL ES 2.0/3.0 Engine for Android,  when will it support OpenGL ES 3.0 features?
     The OpenGL ES3.0 on Android 4.3 and later versions added some important features.
     These features may improve the rendering qualities for Virtual Reality (VR) such as:
      Instancing for VR stereoscopic rendering,
      Multi-sampling (Anti-aliasing technology) for rendering to texture of each (left/ight) view.

**Comment by jwoolston** [comment]
It does currently support 3, but only minimally. If your device allows use of 3.0, it will request a 3.0 compatible EGL surface. With this, you could then use any of the 3.0 features on your own, most of which are in the shader code. We will eventually get around to adding some of these ourselves, but our time is short and our backlog long.

**Comment by jwoolston** [comment]
Closing this issue as resolved/stale.
