### ISSUE TITLE
Child object position don't change according to parent

### ISSUE THREAD

**Issue by PeterYan-UW** [Rajawali/Rajawali#1596]
#### Rajawali Version 
1.1.337

#### Device
 Samsung Note4  Android 5.1.1

#### Summary
Child object position don't change according to parent
````java
        mRaptor = new Cube(100);
        mRaptor.setColor(Color.BLACK);
        Material m = new Material();
        m.enableLighting(true);
        mRaptor.setMaterial(m);
        mRaptor1 = new Cube(100);
        mRaptor1.setPosition(new Vector3(0,0,1500));
        mRaptor1.setColor(Color.BLUE);
        mRaptor1.setMaterial(m);
        mRaptor.addChild(mRaptor1);
        getCurrentScene().addChild(mRaptor);
        Log.v("mRaptor W position", mRaptor.getWorldPosition().toString());
        Log.v("mRaptor1 W position",mRaptor1.getWorldPosition().toString());

        mRaptor.moveUp(move.y);
        mRaptor.moveRight(-move.x);

        Log.v("mRaptor W position", mRaptor.getWorldPosition().toString());
        Log.v("mRaptor1 W position", mRaptor1.getWorldPosition().toString());
````

log:
````
V/mRaptor W position: Vector3 <x, y, z>: <0.0, 0.0, 0.0>
V/mRaptor1 W position: Vector3 <x, y, z>: <0.0, 0.0, 1500.0>
V/mRaptor W position: Vector3 <x, y, z>: <70.5, -16.5, 0.0>
V/mRaptor1 W position: Vector3 <x, y, z>: <0.0, 0.0, 1500.0> 
````
mRaptor position changed, but mRaptor1 position does not change.

**Comment by PeterYan-UW** [comment]
the child object is moving according it's parent's object, but child object's getWorldPosition() and getPosition() function's data doesn't change

**Comment by jwoolston** [comment]
@PeterYan-UW correct. I have observed and confirmed this issue. It is related to the lazy calculations that are done for model matrices. I am trying to determine an efficient fix that fits with future plans.

**Comment by jwoolston** [comment]
`Object3D.getWorldPosition()` should now work as expected.

**Comment by shaji-Dev** [comment]
Object3D.getWorldPosition() returns the same position for all children that are in different positions in the parent object. We need the real center position of the Object3D in the the scene space. Thank you.
