### ISSUE TITLE
build failed.

### ISSUE THREAD

**Issue by huzhenjie** [Rajawali/Rajawali#1598]
```
Error:Execution failed for task ':vuforia:ndkBuild'.
> A problem occurred starting process 'command 'ndk-build''
```

**Comment by jwoolston** [comment]
I havnt updated the docs yet but I addressed this last night. Make sure you have the ndk installed via the SDK manager and that there is an entry called ndk.dir in your local.properties file that points to the ndk (just like the sdk.dir entry), Also that you have the master `HEAD` as of last night: `7c6737f`

**Comment by jwoolston** [comment]
Closing as resolved. Post here if you continue to have problems.
