### ISSUE TITLE
Mismatched viewport calls in Scene.render() mNextCameraLock block?

### ISSUE THREAD

**Issue by rpicolet** [Rajawali/Rajawali#1605]
#### Rajawali Version or Branch
master

#### Summary
Is this the intended code? Seems like the default value should be used for both or neither, maybe it doesn't matter, maybe there's a reason, maybe it's a potential problem, just asking....

    mCamera.setProjectionMatrix(mRenderer.getViewportWidth(), mRenderer.getDefaultViewportHeight());

**Comment by jwoolston** [comment]
This is not intended. Both should be using getViewportWidth(). I think this was a merge conflict that was improperly resolved.
