### ISSUE TITLE
Load .obj. Unexpected syntax error

### ISSUE THREAD

**Issue by itslayo** [Rajawali/Rajawali#1606]
Rajawali ver. 1.1.346-SNAPSHOT
Xiaomi Redmi Note 2. Android 5.0.2

I'm trying to load OBJ. I got following error
```
[org.rajawali3d.materials.Material] Could not compile fragment shader: 
Shader log: Compile failed.
  ERROR: 0:3: Unexpected syntax error;
  ERROR: main() function is missing.
  ERROR: 2 compilation errors. No code generated.
```
.blend and textures files are from there http://www.blenderguru.com/tutorials/create-a-realistic-earth/

Here is a gist with .obj, .mtl and initScene() method

https://gist.github.com/itslayo/c9c19dbd1475c35bbde4

texture files are placed in drawable-nodpi folder (clouds.png and color_map.jpg)

**Comment by jwoolston** [comment]
Call `RajLog.setDebugEnabled(true)` and post the output of the generated shaders.

**Comment by itslayo** [comment]
Here it is
https://gist.github.com/itslayo/a088b2c3f07d6fc0a319

**Comment by jwoolston** [comment]
For some reason I can't find documentation of this but I am fairly certain the problem you are seeing stems from the names of referenced files. `Clouds_Sphere.001clouds` contains a `.` character which is illegal in the GLSL program and confusing the compiler. You need to edit the files coming out of blender to remove these periods. Replace them with any letter/number/underscore to your liking. Then when Rajawali imports the OBJ, the periods wont exist in the uniform names of the constructed shader programs.

**Comment by itslayo** [comment]
This error has gone. But It doesn't render anything (I see blank surface) and no other errors in a log. Can it be something wrong with .obj or .mtl file?

**Comment by jwoolston** [comment]
To test, try commenting out the material lines in the OBJ file and applying a simple color material after loading. If they render, then there is a problem with your materials.

**Comment by itslayo** [comment]
Aha. It works. Smth bad with materials( Thanks!

**Comment by jwoolston** [comment]
If you figure out what is in the materials that rajawali is not supporting, please post an issue about that specifically so we can fix it.
