### ISSUE TITLE
Combining object color picking and post-processing

### ISSUE THREAD

**Issue by rpicolet** [Rajawali/Rajawali#1607]
[This ticket originated from discussions after #1586 was closed; this post is a partial copy from there.]

...

It's probably better to start by nailing down the basic goals/requirements. I propose that these are:
* to allow all 4 combinations of the two features to inter-operate reliably: default rendering, default rendering plus color picking, post-processing, and post-processing plus color-picking.
* to better isolate the very different "never visible" color-picking GL render details from those of the "visible" renders, and so make it easier to test/maintain both, and to add new features to either
* to minimize changes to the client API for both features,
* within reason, to maximize code re-use and minimize the code footprint

I'll wait to get some feedback on these goals before doing anything more on this. I should say, even if most everyone agrees with these as the goals, I haven't really yet thought of an approach that accomplishes all of them well, so getting some sense of relative priorities would also help me a lot in proposing a design.

...

**Comment by jwoolston** [comment]
These goals all seem reasonable. I am not sure where the best approach here would be but perhaps something along the lines of:

- When color picking is activated on a scene, have it add a private post processing manager to itself. This manager will only have a color picking pass added to it
- The `Scene` class will then manage whatever is necessary to make the two render passes for each call to its render method.

**Comment by rpicolet** [comment]
@jwoolston:
* Good to hear the goals sound reasonable, but I'm not sure they are mutually compatible. I think something has to give, which is why I'm also asking for feedback about priorities.
* Per your suggestion, I guess we could try something like:
``` 
Renderer.onRender()
        Renderer.render()
                [current]Scene.defaultRender() [new]
                         [scene's]PostProcessingManager.render()
                                [ColorPicking]IPass.render() [if requested/enabled, new]
                                         [current]Scene.doColorPicking() [to texture, new]
                                [RenderPass]IPass.render()
                                        [current]Scene.render() [to screen]
```
* However, the usage model for post-processing effects seems to require something like this pattern:
```
[overridden]Renderer.onRender()
        [effect's]PostProcessingManager.render() [for example:]
                [RenderPass]IPass.render()
                        [current]Scene.render() [to texture]
                [EffectPass]IPass.render() [with mixing shader]
                        [ScreenQuad]Scene.render() [to screen] 
```
* If an app does this, then I'm not sure how both the scene and effect `PostProcessingManager` instances get triggered, or how to avoid double rendering of the `[current]Scene` if they do. 

To me, this seems to strongly suggest there could be some benefits to a central control that can adapt appropriately to dynamic combinations of features/render passes, and the `Renderer` seems like the natural location. This is why I originally suggested subsuming the `PostProcessingManager` functions directly into the `Renderer`. In addition to integrating the render pass logic, such an approach would also:
* Relieve apps from the need to override `Renderer.onRender()` or to instantiate a `PostProcessingManager` in the first place; apps could just call the same methods (add/removePass etc.) directly on the Renderer
* Allow a `ColorPickingPass` to be added whenever an `ObjectColorPicker` is created, and to be enabled in response to a picking request, which requires no changes to that usage model
* Enable separate implementations for both types of `Scene` and `Object3D` renders (with common code factored into shared methods), and remove render pass logic from `Scene` and `Object3D` altogether, 

Some questions for the team that might help me better understand the problem:
* Are there any post-processing scenarios where the `currentScene` gets rendered more than once, or not at all? 
* Is it always the case that the `currentScene` gets rendered exactly once during post-processing? 
* Similarly, must there always be a `RenderPass` for an effect?  

Thanks, please critique/challenge/suggest!

**Comment by jwoolston** [comment]
> I think something has to give

Something always has to give. In this case the code reuse should be the one to give first followed by no API change. The other two requirements are pretty absolute. Let me get some coffee and go through the rest of your outline and I will give you some more feedback.

**Comment by jwoolston** [comment]
Lets not feel confined to the current usage pattern. Now is the time to correct any places that are restrictive. I'm not much of a fan of giving more code back to the `Renderer` class. I still would even like to see some code removed from this in the future. 

I am perfectly happy to see modifications to `PostProcessingRenderer`, even large ones, but I think the responsibility of render passes needs to stay there. The color picking process can be entirely automated and the user not need to know about it. 

> Enable separate implementations for both types of Scene and Object3D renders (with common code factored into shared methods), and remove render pass logic from Scene and Object3D altogether,

While I am on board with this, I think it exceeds the scope we should confine this initial effort to. I have hopes of down the road having a centralized GL state manager that batches all the gl calls per frame, automatically removing redundant calls.

> Are there any post-processing scenarios where the currentScene gets rendered more than once, or not at all?

Yes, although one is broken. Shadow maps require this. The VR process also requires this along with the side by side and PIP renderers (if using the same scene).



> Is it always the case that the currentScene gets rendered exactly once during post-processing?

No, see above.

> Similarly, must there always be a RenderPass for an effect?

In the current implementation, no, it is only required for rending whatever the render buffer should display. There are plenty of procedural effects you could generate without a render pass and could be consumed by other passes down the line.

**Comment by rpicolet** [comment]
@jwoolston Thanks for the insightful responses!

>In this case the code reuse should be the one to give first followed by no API change. The other two requirements are pretty absolute. 

That's the guidance I was looking for; the first two are must-haves, the others aren't. 

>I am perfectly happy to see modifications to PostProcessingRenderer, even large ones, but I think the responsibility of render passes needs to stay there. 

OK, that does make sense. Instead, what if the `Renderer` simply instantiates/publishes a `PostProcessingManager` "singleton" that apps would use for post-processing?  Then we could re-direct frame renders to that instance, instead of the current default `Render.render()`:
```
mRenderer.onRender()
        mPostProcessingManager.render()
```
Apps would just get the `PostProcessingManager` instance from the `Renderer` if they need it, and would no longer need to override `Renderer.onRender()`.  An `ObjectColorPicker` would use the same instance to install/enable its `ColorPickingPass`, and the `PostProcessingManager.render()` method would be where we centralize the `IPass` management across scenarios. That _is_ more modular and has a smaller footprint than putting it all in the `Renderer`, and it still appears to have all of the same benefits...

>> Enable separate implementations for both types of Scene and Object3D renders (with common code factored into shared methods), and remove render pass logic from Scene and Object3D altogether,

>While I am on board with this, I think it exceeds the scope we should confine this initial effort to. I have hopes of down the road having a centralized GL state manager that batches all the gl calls per frame, automatically removing redundant calls.

I'm not sure I can figure out how else to accomplish the second "pretty absolute" goal (isolate "never visible" color-picking renders from normal "visible" renders). Ignoring the "factoring out common code into shared methods" phrase for a moment, what I meant by this is to do something similar to what I did in my original PR, where I moved (almost) all of the object-picking code out of Scene.render() into Scene.doColorPicking(). If your concern here mostly with factoring out shared methods, I can certainly see/support that, as it re-introduces the possibility of undesired couplings (and might yet prove to be part of why I haven't been able to get post-processing working with my old implementation). So to be more concrete, how about something like this:
```
RenderPass.render()[e.g.] or Renderer.render()
        Scene.render() [same as now, minus color picking code]
                Object3D.render() [same as now, minus color picking code]
```
and 
```
ColorPickingPass.render()
        Scene.doColorPicking() [new, dedicated/optimized]
                Object3D.renderColorPicking() [new, dedicated/optimized]
```
with no new shared code?  

I don't know how centralizing GL state might be affected by this, or whether this fully addresses your other concerns, so please feel free to suggest/specify something different...

>Yes, although one is broken. Shadow maps require this. The VR process also requires this along with the side by side and PIP renderers (if using the same scene).

Oh, right. Hadn't even considered/looked at the other Renderer classes. After a quick scan, it looks like:
* `VuforiaRenderer` calls `Renderer.onRender()`, so it would automatically incorporate any post-processing renders if we proceed (as described above) to hook into `onRender()`...
* Unless I'm missing something, it looks like neither `PipRenderer` nor `SideBySideRenderer` are curently aware of/designed to interoperate with any post-processing, and like neither would get plugged into/be affected by the changes under discussion...

Do we need to explore/address further how this effort should interact with these Renderer subclasses? 

>In the current implementation, no, it is only required for rending whatever the render buffer should display. There are plenty of procedural effects you could generate without a render pass and could be consumed by other passes down the line.

OK, so the main problem I am trying to get a handle on with these questions is this: 

How can a centralized render pass manager - `PostProcessingManager.render()` in the above proposal - know if it needs to add/remove the default render of the currentScene?  

For example, could we add a single constant boolean to each IPass type that indicates whether it obviates the need for a default currentScene render?  Or, could it be as simple as checking if any of the added IPass instances renderToScreen? If either of these could work, then the necessary pass management logic seems pretty straightforward. If not, I'm open to suggestions about other ways to make the decision. 

And either way, are there any other issues that need to be addressed here by a centralized render pass manager, or by this enhancement effort as a whole? Any input from other team members?

**Comment by jwoolston** [comment]
> How can a centralized render pass manager - PostProcessingManager.render() in the above proposal - know if it needs to add/remove the default render of the currentScene?

I Think I would handle this by having two post processing managers. One that is exclusively for color picking and automatically generated by the renderer as needed. The other(s) would be handled by the users as they are now and contain the necessary post processing effects to accomplish whatever they want. We shouldnt make the post processing manager a singleton because I can conceive of reasons why you might want to have different post processing sequences set up. This gets rid of the need for any detection of render pass needs...if you are doing color picking, no. If it is the post processing system we have now, leave it up to the user. 

> what I meant by this is to do something similar to what I did in my original PR, where I moved (almost) all of the object-picking code out of Scene.render() into Scene.doColorPicking().

I have no objection to this approach.


> I don't know how centralizing GL state might be affected by this, or whether this fully addresses your other concerns, so please feel free to suggest/specify something different...

Don't worry about this. The nature of how it will be constructed means it should work fine everywhere, no matter what you do (it will capture GL calls in a static manner since thats how the GLES bindings work.

> Any input from other team members?

I'm sure, but they are likely to agree with whatever direction you decide to go and address things in the PR. I have prodded them a few times privately to chime in, so they will if/when they can.

**Comment by rpicolet** [comment]
After thinking about everything we've discussed, I propose the following approach: 
* factor color-picking code out of Scene.render() (with the exception of a single one-shot check for a pending picking request) into Scene.doColorPicking(), and
* add Object3D.renderColorPicking() to do the recursive color-picking rendering needed to address the original #1387 bug.

Kinda like so:
```
Scene.render(...) {
    ....
    if (mPickerInfo != null) {
        doColorPicking(...);
        mPickerInfo == null;
   }
   ...
}

Scene.doColorPicking(...) {
    ...
    for {Object3D child : mChildren} {
        child.renderColorPicking(...);
    }
    ...
    mPicker.pickObject();
}

Object3D.renderColorPicking(...) {
    // cut/paste of Object3D.render(), with appropriate optimizations
}
```
No impact to any post-processing code, the Renderer, or Object3D.render(), and - assuming any use of post-processing will eventually call Scene.render() - I think it hits all the important goals...

If this sounds more like it, then great! If not, I'm all ears.

**Comment by jwoolston** [comment]
Nice and simple. I'm on board.

**Comment by rpicolet** [comment]
Cool!  I'll start coding, shouldn't take long unless I hit a bug...
