### ISSUE TITLE
render plane on top of rectangle in rajawali

### ISSUE THREAD

**Issue by shripadashtekar** [Rajawali/Rajawali#1608]
I have an image in android with a rectangle on it. I have found the coordinates of that rectangle which is in the following format.

rect(left,top,right,bottom)
I have created a plane in rajawali and I want to render/draw the plane exactly on top of the original rectangle.

How do I render the plane, because rect method gives coordinates in different coordinate system and rajawali uses different coordinate system to render objects.

How do I map the rect coordinates to rajawali coordinates?

**Comment by jwoolston** [comment]
This sounds like you want to render over a section of an android native view. Is this correct?

**Comment by shripadashtekar** [comment]
Yes . I want to render it on android surface view.

**Comment by jwoolston** [comment]
Well you have a few options. You could either use android's layout system to confine the surface view to the area you wish to render, or you can do an inverse projection to map the screen coordinates to GL coordinates. Similar to how `Object3D#setScreenCoordinates()` works. Note that that method works on the object's centroid location only and not the bounds like you are discussing, so you will need to do some work to do it for the 4 corners you are interest in and determine how to use that to adjust your render objects.

**Comment by shripadashtekar** [comment]
Thanks for your reply. But I am using Rajawali for the first time.
Can you give me some link where i can learn how to do inverse projection in Rajawali?

**Comment by jwoolston** [comment]
We do not have a tutorial or example of this. Google "GLU unproject" or look at how the method I pointed out works. You don't need to understand how Rajawali or the GLU unproject methods work to be able to use them.

**Comment by shripadashtekar** [comment]
I tried to use setScreenCoordinates() method like this

`front.setScreenCoordinates(0.205f,0.045f,720,1280,0f); // front is a plane which i want to render on top of rectangle`

but it gives me following errors 

java.lang.IllegalArgumentException: array == null
            at android.opengl.Matrix.multiplyMM(Native Method)
            at android.opengl.GLU.gluUnProject(GLU.java:221)

Do I need to find those "model view projection" matrices by myself or are those calculated internally?

**Comment by jwoolston** [comment]
What version of rajawali are you using? Looking at the current 
code, there is no possible way for a null array to be passed in.

**Comment by shripadashtekar** [comment]
I am using version 0.9.

**Comment by shripadashtekar** [comment]
Here is the link to the code.
[https://github.com/Sher-lock/IndiAR/blob/master/app/src/main/java/rocks/rishi/iar/Renderer.java](url)

please tell me how to integrate setScreenCoordinates() method in the above code.

**Comment by jwoolston** [comment]
Version 0.9 has been unsupported for some time now. To be honest I can't even remember how some of it worked. The Google Plus community will have users who are more familiar with the 0.9 version than I am at this point. Since this issue is related to an unsupported version, I am closing the ticket.
