### ISSUE TITLE
Scene.removeChild(Object3D child)

### ISSUE THREAD

**Issue by jonr79** [Rajawali/Rajawali#1609]
Whichever version comes with the code you get from Google when you download their Project Tango examples.

Using a Project Tango tablet

#### Summary
Make this call. It doesn't work
getCurrentScene().removeChild(myObject)

When I went to see how it was done in the code I found that line 533 is commented out with a TODO that says only "Uncomment"

So, whatever version of Rajawali google is using and is up on github right now will not remove an object from the scene.

Thoughts?

#### Trace or Log Output
None

**Comment by jwoolston** [comment]
The commented bit is only for removing from the scene graph which is incomplete. The object should have been removed from the scene, though it wont occur until the next frame.

**Comment by jwoolston** [comment]
What behavior are you seeing to suggest that it wasn't removed?

**Comment by jonr79** [comment]
The object is still being rendered.

**Comment by jwoolston** [comment]
No no, it should have been removed. I will look into it.

**Comment by jwoolston** [comment]
The latest version does not exhibit this bug. I will work on getting the tango demos updated.
