### ISSUE TITLE
Vector3 cross uses reverse order from expected

### ISSUE THREAD

**Issue by aharmat** [Rajawali/Rajawali#1616]
#### Rajawali Version or Branch
1.1.418 Master

#### Summary
Vector3.cross(other) computes `other x this`, when I think `this x other` would be expected, given the documentation for the function and the behavior of other functions in Vector3 like add and subtract.

**Comment by jwoolston** [comment]
Agreed, I'll fix it. I'm sure its going to blow up some examples too.
