### ISSUE TITLE
ObjectPicker buggy.

### ISSUE THREAD

**Issue by conect** [Rajawali/Rajawali#1621]
The Objectpicker seems to be buggy. When I create an Nprism and tap on the rajawalisurface view, it works in most of the cases but sometimes an object is picked, although I've clicked on a totally different position. Could somebody tell me what might be the reason. I'm absolutely sure, that the position where I clicked is correct.

BTW: I am using "org.rajawali3d:rajawali:1.0.325@aar"

**Comment by jwoolston** [comment]
There were problems with the colorpicking that were recently fixed in the latest version of Rajawali.

**Comment by conect** [comment]
It seems that colorpicking only works if the clickinginterval doesn't fall below a certain amount of time. I would guess at least 100ms is that correct?

**Comment by jwoolston** [comment]
Post processing being the exception (see #1615), color picking in the examples works as fast as i can physically tap the screen.
