### ISSUE TITLE
Problem with latest build

### ISSUE THREAD

**Issue by lfrohman** [Rajawali/Rajawali#1628]
I just pulled the latest "1579 examples update #1626" into Android Studio.
For vuforia/build.gradle, I get:

Error:(74, 0) Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
	[class java.lang.String, class java.lang.String]
	[class java.io.File, class java.lang.String]
<a href="openFile:C:\workspace\Rajawali\vuforia\build.gradle">Open File</a>

**Comment by ToxicBakery** [comment]
Please use the issue templates.

You do not have the `ndk.dir` set in your local.properties.

**Comment by lfrohman** [comment]
never mind
