### ISSUE TITLE
Recent changes have inverted the ArcballCamera

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1629]
#### Rajawali Version or Branch

[describe the precise release version or branch and commit id, feature requests can simply specify master]
`master`
#### Device and Android Version

[list at least one device and the version number that produced a stace trace if applicable]
#### Summary

[describe the issue or feature]
The Arcball example demonstrates this. Moving on the screen now moves the camera in the direction of finger motion, which is counter intuitive, but potentially useful. Rather than reverse the behavior, we should add a flag that determines if the touch input is inverted or not.
#### Steps to Reproduce

[Describe reproducable steps and sample code]
#### Trace or Log Output

[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by contriteobserver** [comment]
This got addressed in #1868, the current default behavior is correct, and apparent when the camera is moving inside an environment that gives movement context. However, it is true that when the camera rotates about an object without a defining environment, it appears that the camera remains still and the object (virtual relativity) appears in a direction opposite to what is expected.

To accommodate both (with and without environment context) use cases, pull request #1877 was submitted to add a  `ScreenMappingRatio` setter and getter that can be used to adjust the ratio of the screen to camera movement mapping between 1 and -1.
