### ISSUE TITLE
Wrong file names during loading .obj models

### ISSUE THREAD

**Issue by karunass** [Rajawali/Rajawali#1646]
#### Rajawali Version or Branch
I use version 1.1.337 from mavenCentral
(compile 'org.rajawali3d:rajawali:1.1.337@aar' in my build.gradle)

#### Device and Android Version
Samsung GT-N5100, Android 4.2.2

#### Summary
I tried to load .obj model with .mtl file from sdcard, but get exeption during loading .mtl

#### Steps to Reproduce
I use this code:

```
LoaderOBJ objParser = new LoaderOBJ(this, "/models/bnp3d.obj");
objParser.parse();
```
In my bnp3d.obj i have this line

"mtllib bnp3d.mtl"

but LoaderOBJ try to load file with name "bnp3d_mtl".
So i have my model without materials.

#### Trace or Log Output

E/Rajawali: [org.rajawali3d.loader.LoaderOBJ.MaterialLib] Could not find file.
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/models/bnp3d_mtl: open failed: ENOENT (No such file or directory)

**Comment by ToxicBakery** [comment]
This is working as intended

https://github.com/Rajawali/Rajawali/wiki/Tutorial-17-Importing-.Obj-Files  
> The Android SDK ignores file extensions so it’ll regard the .obj and .mtl files as duplicates. The way to fix this is to rename the files. For instance:
> 
> myobject.obj > myobject_obj
> myobject.mtl > myobject_mtl

**Comment by karunass** [comment]
> The Android SDK ignores file extensions

I know it, but i store my files on sdcard, not in “res/raw” folder. Can you proceed this case in different way, without renaming?

**Comment by ToxicBakery** [comment]
Glancing at the Loader implementation I do not see anyway around it. If you want to modify the behaviour we accept well formatted PR's.

The easier suggestion, without knowing your requirements so it may be invalid, is to use the AWD utility to create AWD objects from your OBJ objects. This will compress the object, materials, and textures into a single binary file that will load significantly faster compared to an OBJ.

**Comment by karunass** [comment]
I think, simple way to workaround is to add flag to LoaderOBJ:

`private boolean mNeedToRenameMtl = true;`

change constructor:

```
public LoaderOBJ(Renderer renderer, String fileOnSDCard) {
    	super(renderer, fileOnSDCard);
        mNeedToRenameMtl = false;
    }
```
in "public LoaderOBJ parse()" write:

```
else if (type.equals(MATERIAL_LIB)) {
    if(!parts.hasMoreTokens()) continue;
    String materialLibPath = mNeedToRenameMtl 
                                    ? mparts.nextToken().replace(".", "_") : mparts.nextToken();
```
    
I'll try to test this variant later.

**Comment by jwoolston** [comment]
@karunass After testing if you wish to submit a PR for it we can take a look at getting it merged into the library.

**Comment by karunass** [comment]
ok

**Comment by ToxicBakery** [comment]
@karunass when you commit your changes please tag them against #1648 for tracking purposes.
