### ISSUE TITLE
Renderer's switchScene modifies camera's projection matrix

### ISSUE THREAD

**Issue by aharmat** [Rajawali/Rajawali#1652]
#### Rajawali Version or Branch
Master

#### Summary
Renderer.switchSceneDirect calls `mCurrentScene.getCamera().setProjectionMatrix(mOverrideViewportWidth, mOverrideViewportHeight);` which sets the camera's projection matrix to a 1:1 aspect ratio unless the override width and height are set, even if the camera's projection matrix has been set up differently beforehand. Should check the override variables for -1, just like the beginning of Renderer.onRenderSurfaceSizeChanged.

**Comment by jwoolston** [comment]
Pushing a fix for this now. Ultimately, each scene should probably possess the ability to control the viewport it wants.
