### ISSUE TITLE
Duplicate Audio.jar and libvraudio_engine.so

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [Rajawali/Rajawali#1655]
#### Rajawali Version or Branch
[master]

#### Device and Android Version
Note 5 SM-N920I

#### Summary
Duplicate Audio.jar and libvraudio_engine.so

#### Steps to Reproduce
I don't know how to product it because it happend suddenly 
but this is my Top-Level gradle 
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

apply from: 'deps.gradle'
if (file('local.gradle').exists()) {
    apply from: 'local.gradle'
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.google.gms:google-services:1.3.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}

def isReleaseBuild() {
    return isTag() && !isSnapshot()
}

def isSnapshot() {
    return version.contains("SNAPSHOT")
}

boolean isTravis() {
    return System.getenv('TRAVIS_BUILD_NUMBER') ? true : false
}

boolean isTag() {
    def tag = System.getenv('TRAVIS_TAG')
    return !(tag == null || tag.isEmpty())
}

def buildNumber() {
    return System.getenv('TRAVIS_BUILD_NUMBER') ?: "0"
}`
and this is app gradle 
`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'

    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'android-apt'
allprojects {
    repositories {
        jcenter()
    }
}
repositories {
    maven { url 'https://maven.fabric.io/public' }
}

android {
    signingConfigs {
    }
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    defaultConfig {
        applicationId 'com.taskspotting'
        minSdkVersion 17
        targetSdkVersion 23
        versionCode 21
        versionName "2.0"
        multiDexEnabled true
    }
    repositories {
        mavenCentral()
//        maven { url 'http://maven.livotovlabs.pro/content/groups/public' }
    }
    packagingOptions {
        exclude 'LICENSE.txt'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
//        exclude 'lib/armeabi-v7a/libvraudio_engine.so'
//        exclude 'lib/armeabi-v7a/libvrtoolkit.so'
    }
    dexOptions {
        jumboMode = true
        javaMaxHeapSize "4g"
    }
    buildTypes {
        release {
            minifyEnabled false
            //shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {

        }
    }
    productFlavors {
        dev {
            minSdkVersion 21
        }
        prod {
            minSdkVersion 17
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':taskspottingsdk')
    compile project(':viewPagerIndicatorLib')
    compile 'com.android.support:cardview-v7:23.0.1'
    compile 'com.google.maps.android:android-maps-utils:0.4+'
    compile project(':audio_recorder')
    compile project(':material_dialogs_library')
    compile project(':better_pickers_library')
    compile ('eu.livotov.labs.android:CAMView:2.0.1@aar') {transitive=true}
    compile project(':wScratchViewLibrary')
    compile project(':drag-sort-listview')
    compile project(':mobihelp_sdk_android_v1.5.4')
    compile('org.apache.httpcomponents:httpmime:4.3.6') {
        exclude module: 'httpclient'
    }
    compile 'org.apache.httpcomponents:httpclient-android:4.3.5'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.facebook.android:facebook-android-sdk:4.6.0'
    compile 'com.sromku:simple-fb:4.1.1'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    compile 'com.adjust.sdk:adjust-android:4.1.3'
    compile 'com.android.support:design:23.1.1'
    compile 'com.github.hotchemi:permissionsdispatcher:2.0.1'
    apt 'com.github.hotchemi:permissionsdispatcher-processor:2.0.1'
    compile 'com.android.support:multidex:1.0.1'
    compile('com.twitter.sdk.android:twitter:1.13.0@aar') {
        transitive = true;
    }
    compile project.depAndroidSupport
    compile project.depAppCompat
    compile project.depRecycler
    compile project.depGSON
    compile project.depIon
    compile project(':rajawali')
    compile project(':vr')
    compile project(':video360lib')

}
also I removed 
`//String getVersionString() {
//    String v = VERSION_NAME.replaceAll(".(0)\$", "." + buildNumber())
//    v = isTag() ? v : v + "-SNAPSHOT"
//    return v
//}

//group = GROUP
//version = getVersionString()

//if (isReleaseBuild()) {
//    status = 'release'
//} else {
//    status = 'integration'
//}`
from vr and rajawali gradle files but they didn't work too 

#### Trace or Log Output
Error:duplicate files during packaging of APK D:\Work\TaskSpotting\TaskSpottingV2\taskspotting-android\app\build\outputs\apk\app-dev-debug-unaligned.apk
	Path in archive: lib/armeabi-v7a/libvraudio_engine.so
	Origin 1: D:\Work\TaskSpotting\TaskSpottingV2\taskspotting-android\app\build\intermediates\exploded-aar\taskspotting-android\vr\unspecified\jars\libs\audio.jar
	Origin 2: D:\Work\TaskSpotting\TaskSpottingV2\taskspotting-android\app\build\intermediates\exploded-aar\taskspotting-android\vr\unspecified\jni\armeabi-v7a\libvraudio_engine.so
You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'lib/armeabi-v7a/libvraudio_engine.so'
	  }
	}
Error:Execution failed for task ':app:packageDevDebug'.
> Duplicate files copied in APK lib/armeabi-v7a/libvraudio_engine.so
	File 1: D:\Work\TaskSpotting\TaskSpottingV2\taskspotting-android\app\build\intermediates\exploded-aar\taskspotting-android\vr\unspecified\jars\libs\audio.jar
	File 2: D:\Work\TaskSpotting\TaskSpottingV2\taskspotting-android\app\build\intermediates\exploded-aar\taskspotting-android\vr\unspecified\jni\armeabi-v7a\libvraudio_engine.so

**Comment by jwoolston** [comment]
You are using an outdated version of the Android Gradle plugin.
