### ISSUE TITLE
Cube with different textures on each of it's faces

### ISSUE THREAD

**Issue by maverickkanthi** [Rajawali/Rajawali#1659]
I'm Using rajawali 1.0.186

I'm new to Rajawali. I've followed the tutorials on creating simple materials. What i want now is to create a cube with different images on each of it's face. Kindly help me. All I see is a red coloured cube. 
Below is the code.

```
        int[] cubeMaps = new int[6];
        cubeMaps[0] = R.drawable.faceone;
        cubeMaps[1] = R.drawable.facetwo;
        cubeMaps[2] = R.drawable.facethree;
        cubeMaps[3] = R.drawable.facefour;
        cubeMaps[4] = R.drawable.facefive;
        cubeMaps[5] = R.drawable.facesix;

        CubeMapTexture cubeMapTexture = new CubeMapTexture("cubemaps",cubeMaps);
        cubeMapTexture.isEnvironmentTexture(true);
        Material cubeMaterial = new Material();
        cubeMaterial.enableLighting(true);
        cubeMaterial.addTexture(cubeMapTexture);

        myCube = new Cube(1,true,false);
        myCube.setMaterial(cubeMaterial);
        myCube.setDoubleSided(true);
        myCube.setTransparent(true);
        getCurrentScene().addChild(myCube);
```

**Comment by wangcan26** [comment]
May be  you should add the following code to the cubeMaterial  
  cubeMaterial.setColorInfluence(0);

**Comment by maverickkanthi** [comment]
Yeah tried that.... but no use. nothing shows up if i use that statement.

**Comment by contriteobserver** [comment]
V1.0.325 was able to run the following code and shows the textures, oriented to the environment, as `cubeMapTexture.isEnvironmentTexture(true)` 

`        protected void initScene() {
            mLight = new DirectionalLight(-1,-1,-1);
            mLight.setPosition(3,3,3);
            mLight.setColor(1.0f, 1.0f, 1.0f);
            mLight.setPower(2);
            getCurrentScene().addLight(mLight);

            int[] cubeMaps = new int[6];
            cubeMaps[0] = R.drawable.faceone;
            cubeMaps[1] = R.drawable.facetwo;
            cubeMaps[2] = R.drawable.facethree;
            cubeMaps[3] = R.drawable.facefour;
            cubeMaps[4] = R.drawable.facefive;
            cubeMaps[5] = R.drawable.facesix;

            CubeMapTexture cubeMapTexture = new CubeMapTexture("cubemaps",cubeMaps);
            cubeMapTexture.isEnvironmentTexture(true);
            Material cubeMaterial = new Material();
            cubeMaterial.enableLighting(true);
            try {
                cubeMaterial.addTexture(cubeMapTexture);
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }

            myCube = new Cube(1,true,false);
            myCube.setMaterial(cubeMaterial);
            myCube.setDoubleSided(true);
            myCube.setTransparent(true);
            getCurrentScene().addChild(myCube);

            getCurrentCamera().setZ(4.2f);
        }`

**Comment by haohongxian77** [comment]
rajawali 1.0.325,the cube is never be seen......if do as contriteobserver instruct

**Comment by haohongxian77** [comment]
when we want to put different img to each of faces ,we need to insure that the Horizontal and vertical ratio in pic should be the same with the face of 3DObject.

**Comment by contriteobserver** [comment]
If the aspect ratio of the texture images does not match that of the object, the texture is stretched to fit.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
