### ISSUE TITLE
updateTexImage: GLConsumer is abandoned

### ISSUE THREAD

**Issue by damengzai** [Rajawali/Rajawali#1662]
#### Summary
[describe the issue or feature]
I used rajawali3d to built a 3D video,encapsulate a view to show  
view.But when I add my view to one FrameLayout from another FrameLayout,something wrong.

#### Trace or Log Output

##updateTexImage: GLConsumer is abandoned
##StreamingTexture.java:115
##mSurfaceTexture.updateTexImage();

no image, no sound.
I do not know why,do you?

**Comment by ToxicBakery** [comment]
Not enough information, please use the entire issue template otherwise it is impossible to understand the issue.

**Comment by damengzai** [comment]
[unnamed-9931-0] updateTexImage: GLConsumer is abandoned!
W/System.err: java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
W/System.err:     at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
W/System.err:     at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:240)
W/System.err:     at com.vr.sdk.vrlib.VRStreamingTexture.update(VRStreamingTexture.java:114)
W/System.err:     at com.vr.sdk.vrlib.VRVideoRender.onRender(VRVideoRender.java:71)
W/System.err:     at org.rajawali3d.renderer.RajawaliRenderer.onRenderFrame(RajawaliRenderer.java:388)
W/System.err:     at com.vr.sdk.rajawali.RajawaliCardboardRenderer.onNewFrame(RajawaliCardboardRenderer.java:39)
W/System.err:     at com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.nativeOnDrawFrame(Native Method)
W/System.err:     at com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.access$3200(CardboardViewNativeImpl.java:52)
W/System.err:     at com.google.vrtoolkit.cardboard.CardboardViewNativeImpl$RendererHelper.onDrawFrame(CardboardViewNativeImpl.java:741)
W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)


This is the wrong code.VRStreamingTexture.java has the same code with StreamingTexture.java,I just renamed it.
