### ISSUE TITLE
Texture file not loading properly

### ISSUE THREAD

**Issue by exttest1** [Rajawali/Rajawali#1669]
#### Rajawali Version or Branch
1.1

#### Device and Android Version
6.0.1

#### Summary
I am trying to load a large structure (3D object) of building in Android app using Rajawali framework. The .obj file alone is getting rendered but when I try to load texture from .jpg file, some of the parts of building are looking transparent (or not getting loaded from texture). Is there any way I can fix this? I have also  attached a screenshot below. The building is looking as a hollow structure.

#### Trace or Log Output
![image](https://cloud.githubusercontent.com/assets/18701685/14854931/481aa428-0caf-11e6-8008-34b499d808ed.png)

**Comment by contriteobserver** [comment]
The OBJ loader only handles triangles and quads.
Does this building mesh contain any faces with more than four sides?

**Comment by jwoolston** [comment]
Closing this issue as stale.
