### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by OthmaneNahyl** [Rajawali/Rajawali#1678]
Hi everyone.

We are developing a fighting game using Rajawali and we have perfomance issues.
Our game involves high speed movement, which is faster that the time the device takes to process frames.
Are there any tricks we could make use of to improve the situation ?

Thank you in advance.

**Comment by sunjinbo** [comment]
To enable hardware accelerate, I guess.

**Comment by jwoolston** [comment]
How many polygons are in your scene and what is the nature of the materials being used? Your question is very, very broad and the performance issues could easily be from any number of things.

**Comment by jwoolston** [comment]
Closing as stale.
