### ISSUE TITLE
 How to fix Error: "A renderer has already been set for this view."

### ISSUE THREAD

**Issue by hieubeta118** [Rajawali/Rajawali#1681]
I'm trying to create a new CustomizeSurfaceView class based on Rajawali's SurfaceView to attach into my recyclerView's Item layout. When I scroll up, then scroll down again it crashed and I saw this Error "A renderer has already been set for this view.". I guess my recyclerview is re-used the Renderer again. This is my code in RecyclerView's Adapter:

`

```
public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {

    FootBallModel footBallModel = footBallArrayList.get(position);

    if(holder.getItemViewType() == TYPE_FIELD){

        final FieldViewHolder fieldViewHolder = (FieldViewHolder) holder;

        RendererClass rendererClass = new RendererClass(context);

        fieldViewHolder.customizeSurfaceView.setSurfaceRenderer(rendererClass);

            } 

}`
```

`
 class FieldViewHolder extends RecyclerView.ViewHolder{

```
   CustomizeSurfaceView customizeSurfaceView;

    public FieldViewHolder(View itemView) {

        super(itemView);

        this.customizeSurfaceView = (CustomizeSurfaceView) itemView.findViewById(R.id.surfaceView);

    }
}`
```

**Comment by hieubeta118** [comment]
I'm so stupid, so sorry about that. I have to use `setSurfaceRenderer` in `ViewHolder `instead of `onBindViewHolder`. But I have a new problem. When I scroll up and scroll down again. The surfaceView is gone. 
This is the first time I launch my application. It's works fine
![13254167_1127613447259532_3067182115046782931_n](https://cloud.githubusercontent.com/assets/18164203/15491036/f332caec-2196-11e6-8f65-e9548e954e3d.jpg)
And this is when I scroll recyclerview up and down again. The objects in surfaceview is gone.
![13230086_1127613457259531_3349788298561510373_n](https://cloud.githubusercontent.com/assets/18164203/15491067/3898f0e8-2197-11e6-9be3-5c75e915c754.jpg)

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
