### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by zzg1122** [Rajawali/Rajawali#1682]
#### Rajawali Version or Branch

tree:6f85d47111
#### Device and Android Version

Nexus 6 Android 5.1.1 Api 22
#### Summary

After I synced gradle, show errors below:
Error:Execution failed for task ':vr:compileReleaseJavaWithJavac'.

> Compilation failed; see the compiler error output for details.
> #### Steps to Reproduce
#### Trace or Log Output

E:\Rajawali-6f85d471114d0ae7a729f8bda346538b3437b23f\vr\src\main\java\org\rajawali3d\vr\materials\HotspotMaterial.java
Error:(20, 22) 错误: 找不到符号
符号:   类 R
位置: 程序包 org.rajawali3d
Error:(33, 33) 错误: 程序包R不存在
E:\Rajawali-6f85d471114d0ae7a729f8bda346538b3437b23f\vr\src\main\java\org\rajawali3d\vr\surface\VRSurfaceView.java
Error:(62, 88) 错误: 程序包org.rajawali3d.R不存在
Error:(66, 41) 错误: 程序包org.rajawali3d.R不存在
Error:(68, 48) 错误: 程序包org.rajawali3d.R不存在
Error:(70, 48) 错误: 程序包org.rajawali3d.R不存在
Error:(73, 48) 错误: 程序包org.rajawali3d.R不存在
Error:(75, 48) 错误: 程序包org.rajawali3d.R不存在
Error:(77, 48) 错误: 程序包org.rajawali3d.R不存在
Error:(79, 48) 错误: 程序包org.rajawali3d.R不存在
Error:(81, 48) 错误: 程序包org.rajawali3d.R不存在
Error:(83, 48) 错误: 程序包org.rajawali3d.R不存在
Error:(85, 48) 错误: 程序包org.rajawali3d.R不存在
13 个错误
Error:Execution failed for task ':vr:compileReleaseJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

how to fix this,thanks in advance~

**Comment by jwoolston** [comment]
In order to help you with this we are going to need a trace log in English.

**Comment by jwoolston** [comment]
Closing this issue as resolved/stale.
