### ISSUE TITLE
Colors in Line3d is not working

### ISSUE THREAD

**Issue by 3DRaven** [Rajawali/Rajawali#1684]
#### Rajawali Version or Branch
1.1.337
#### Device and Android Version
AVD - Nexus 4 API 22 
#### Summary
In example code i set axis colors to red,green,blue. But color is wrong and only one for whole object. 
#### Steps to Reproduce
 
            int[] colors = new int[]{
                    Color.rgb(255, 0, 0), Color.rgb(255, 0, 0),
                    Color.rgb(0, 255, 0), Color.rgb(0, 255, 0),
                    Color.rgb(0, 0, 255), Color.rgb(0, 0, 255)
            };

            Stack<Vector3> points = new Stack<>();

            int length = 10;
            points.add(new Vector3(0, 0, 0));
            points.add(new Vector3(length, 0, 0));
            points.add(new Vector3(0, 0, 0));
            points.add(new Vector3(0, length, 0));
            points.add(new Vector3(0, 0, 0));
            points.add(new Vector3(0, 0, length));

            Line3D axis = new Line3D(points, 10,colors);
            axis.setMaterial(new Material());
            getCurrentScene().addChild(axis);

**Comment by contriteobserver** [comment]
Calling the useVertexColors(true) method in the material should help, as in:
```
            Material material = new Material();
            material.useVertexColors(true);
            Line3D axis = new Line3D(points, 10,colors);
            axis.setMaterial(material);
            getCurrentScene().addChild(axis);
```

**Comment by 3DRaven** [comment]
Yes its work fine. Thanks. But its strange code. "colors" send to Line3D constructor, and enable use colors to material.
