### ISSUE TITLE
Kronos Vulkan / DaydreamVR integration

### ISSUE THREAD

**Issue by dcerisano** [Rajawali/Rajawali#1687]

**Comment by jwoolston** [comment]
I have mulled this over in my head as well, especially in the context of my work needs using some of the more advanced 3.1 features and Rajawali's current state becoming increasingly behind the curve. I think the biggest hurdle at present is I have yet to see any indication of when or even if a Java API will be available on Android. With the current state of NDK development on Android in Android Studio being what it is (Frankly, Google should be ashamed with themselves in this regard, its basically useless unless you have a contrived example), I have ZERO desire to attempt this integration on the native side. 

That said, as you point out the biggest advantage of Vulkan is Async GL pipelines - something I have tried hard to make seemless with Rajawali, but at the end of the day, its just an abstraction to a single pipeline so its easy to queue up enough tasks in Rajawali to make frames stammer. For this reason alone, I would be open to exploring the possibilities.

**Comment by dcerisano** [comment]
I believe your current design is already future-proofed for Vulkan.
Please don't correct me too hard if I am wrong, but you seem to have a Java abstraction layer for shaders that transpiles java byte code to GLSL.

I think this could easily be extended to transpile Vulkan, SPIR-V and other shader languages?

**Comment by jwoolston** [comment]
Yes that is true. In fact I need to update it to allow for version 3/3.1.
My more immediate concern would be for pipeline calls via Java. Have you
seen or heard of Java bindings for Vulkan?

**Comment by dcerisano** [comment]
Sorry, I was updating my last comment while researching it.

The native Java bindings for Vulkan are here:
https://github.com/LWJGL/lwjgl3/tree/master/modules/core/src/main/java/org/lwjgl/vulkan

**Comment by jwoolston** [comment]
Once I get everything with my livestock situated, I'll make some time to take a look and make a preliminary assessment of it. Probably sometime next week. If there is a way to integrate Vulkan, I am definitely interested because it fixes my biggest issue with OpenGL which is the inherently single threaded nature.

**Comment by ToxicBakery** [comment]
Just teach the goats to code and grow your army. 🐐

**Comment by jwoolston** [comment]
There are only 4 goats....however around 500 quail and a bunch of rabbits. I wonder if the monkey shakespeare thing carries over to other animals and code?

**Comment by dcerisano** [comment]
Fail

**Comment by jwoolston** [comment]
Adding a comment which was deleted:

From @dcerisano 

> Sorry, I was updating my last comment while researching it.

The native Java bindings for Vulkan are here:
https://github.com/LWJGL/lwjgl3/tree/master/modules/core/src/main/java/org/lwjgl/vulkan
