### ISSUE TITLE
如何实现UToVr3.4.*版本 中暂停键效果

### ISSUE THREAD

**Issue by haohongxian77** [Rajawali/Rajawali#1691]
#### Rajawali Version or Branch
[describe the precise release version or branch and commit id, feature requests can simply specify master]

#### Device and Android Version
[list at least one device and the version number that produced a stace trace if applicable]

#### Summary
[describe the issue or feature]

#### Steps to Reproduce
[Describe reproducable steps and sample code]

#### Trace or Log Output
[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by jwoolston** [comment]
This does not appear to be a valid ticket.
