### ISSUE TITLE
Black background in SurfaceView when i set white background

### ISSUE THREAD

**Issue by 3DRaven** [Rajawali/Rajawali#1692]
#### Rajawali Version or Branch

1.1.337
#### Device and Android Version

AVD - Nexus 4 API 22 
#### Summary

When set Renderer to SurfaceView in initScene() set background to white. But when i create fragment in activity i see black backgound and then SurfaceView render white background.
#### Steps to Reproduce

//In fragment

@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        layout = (FrameLayout) inflater.inflate(R.layout.fragment_spline, container, false);
        renderSurface = (SurfaceView) layout.findViewById(R.id.rajwali_surface);
        renderSurface.setSurfaceRenderer(model.newRenderer(renderSurface));
        return layout;
    }

//In renderer
private final class SplineRenderer extends Renderer implements OnObjectPickedListener {
......
        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.rgb(255,255,255));
.....
}
}

**Comment by contriteobserver** [comment]
having trouble reproducing your issue, this is the code I am using, what is wrong with it?
```
public class RajawaliActivity extends Activity {
    RajawaliSurfaceView surface;
    RajawaliRenderer renderer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_rajawali);

        renderer = new ExampleRenderer(getApplicationContext());
        surface = (RajawaliSurfaceView) findViewById(R.id.glsl_content);

        surface.setFrameRate(30);
        surface.setRenderMode(IRajawaliSurface.RENDERMODE_WHEN_DIRTY);
        surface.setSurfaceRenderer(renderer);
    }

    class ExampleRenderer extends RajawaliRenderer {

        public ExampleRenderer(Context context) {
            super(context);
            setFrameRate(30);
        }

        protected void initScene() {
            Cube cube = new Cube(1);
            Material material = new Material();
            cube.setMaterial(material);
            getCurrentScene().addChild(cube);

            getCurrentScene().setBackgroundColor(Color.rgb(255,255,255));
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {
        }

        @Override
        public void onTouchEvent(MotionEvent event) {
        }
    }
}
```

**Comment by 3DRaven** [comment]
You use activity without fragments. In attach my example project with fragments for demonstrate bug.
[main.zip](https://github.com/Rajawali/Rajawali/files/286223/main.zip)

**Comment by contriteobserver** [comment]
Sorry, should have used fragments, however, still having trouble reproducing your issue, this is the revised code I am using, what is wrong with it?

MainActivity.java
```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Create a new fragment and specify the planet to show based on position
        Fragment fragment = new BlankFragment();

        // Insert the fragment by replacing any existing fragment
        FragmentManager fragmentManager = getSupportFragmentManager();
        fragmentManager.beginTransaction()
                .replace(R.id.content_fragment, fragment)
                .commit();
    }
}
```

BlankFragment.java
```
public class BlankFragment extends Fragment {

    SurfaceView surface;
    Renderer renderer;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        ViewGroup rootView = (ViewGroup) inflater.inflate(
                R.layout.fragment_blank, container, false);

        renderer = new ExampleRenderer(getContext());
        surface = (SurfaceView) rootView.findViewById(R.id.glsl_content);

        surface.setFrameRate(30);
        surface.setRenderMode(ISurface.RENDERMODE_WHEN_DIRTY);
        surface.setSurfaceRenderer(renderer);

        return rootView;
    }

    class ExampleRenderer extends Renderer {

        public ExampleRenderer(Context context) {
            super(context);
            setFrameRate(30);
        }

        protected void initScene() {
            Cube cube = new Cube(1);
            Material material = new Material();
            cube.setMaterial(material);
            getCurrentScene().addChild(cube);

            getCurrentScene().setBackgroundColor(Color.rgb(255,255,255));
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {
        }

        @Override
        public void onTouchEvent(MotionEvent event) {
        }
    }
}
```

**Comment by 3DRaven** [comment]
In your code, creating fragment happens before it is displayed. This is because the method called OnCreate activity before the activity is displayed. In my code fragment is created dynamically when pressing a button and is displayed immediately after the created. My code allows you to see the error. I sent a complete example.

**Comment by jwoolston** [comment]
@3DRaven can you send me a debuggable APK demonstrating this? Alternatively, a AS project I can import.

**Comment by 3DRaven** [comment]
in my comments have main.zip application in which there is a project with the sample code . Comment by 27 May.

**Comment by 3DRaven** [comment]
https://github.com/Rajawali/Rajawali/files/286223/main.zip

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
