### ISSUE TITLE
Fix to Rajawali surface and texture views in visual editor

### ISSUE THREAD

**Issue by adamantivm** [Rajawali/Rajawali#1696]
#### Rajawali Version or Branch
v1.0.325

#### Device and Android Version
Android Studio 2.1

#### Summary
I have a tiny fix to the Rajawali views that get them working on the Design view on Android Studio [here](https://github.com/Rajawali/Rajawali/compare/v1.0.325...ekumenlabs:fix-design-view)

I based off of 1.0.325 since I am using the release branch and I have some hope this can be rolled into a next release.

Would that be acceptable? If yes, how should I PR this? meaning, what should I use as a base branch?

#### Steps to Reproduce
Add RajawaliSurfaceView or RajawaliTextureView to a layout xml and try to open that layout xml in Android Studio in the Design tab.

#### Trace or Log Output
 Rendering Problems 

`java.lang.NullPointerException   at org.rajawali3d.surface.RajawaliTextureView.onResume(RajawaliTextureView.java:473)   at org.rajawali3d.surface.RajawaliTextureView.onVisibilityChanged(RajawaliTextureView.java:170)   at android.view.View.dispatchAttachedToWindow(View.java:14537)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)   at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)`

**Comment by ToxicBakery** [comment]
You can base it off of the latest develop and I can get it merged for you.

**Comment by adamantivm** [comment]
Thanks @ToxicBakery . Sorry for the dumb question but which is the develop corresponding to the v1.0 release?

**Comment by ToxicBakery** [comment]
Nope not a dumb question. Sorry most of what I work on is gitflow so I just assumed we had a develop. You can branch master. I believe @jwoolston and I talked in the past about switching to gitflow but I think we all got really busy and it didn't happen.

**Comment by adamantivm** [comment]
@ToxicBakery the problem is that master has changes which are backwards-incompatible with v1.0 release. Most normally there is a development branch off of each supported release where this kind of fixes go, which don't include API changes, etc. which are not going to be released in that version.
But I don't know how this is being handled in Rajawali. I took a quick look at the contribution guidelines and wasn't able to understand this.

**Comment by adamantivm** [comment]
There's 1436-development and 1615-development, perhaps it's one of those?
I'm unfortunately not familiar with gitflow, I've always done these things by hand.

**Comment by adamantivm** [comment]
I guess the real question is: are you guys going to support v1.0.x? Meaning, will you accept fixes to v1.0.x before the (admittedly small) API change and perform new v1.0.x+ releases? Or will you only do releases on top of master?
If the answer is (sadly) the latter then I will rebase off master and defer using this until the next release and until I have time to migrate my apps to the new API.
Sorry for the verbosity, I'd appreciate your advice.

**Comment by ToxicBakery** [comment]
I can't speak for @jwoolston but I believe the goal was features over compatibility. A lot of the original API even with all the breaking changes just was not forward thinking enough most notably with gles 3 features. More major changes are needed still so the best answer currently is to work off master. If you want to avoid rebasing you can try cherrypicking the changes in.

**Comment by adamantivm** [comment]
ok, thanks @ToxicBakery. I don't mind rebasing, I was hoping to get a fix into my current applications which use this so the real work is to adapt my applications to the new API. But if no new release is going to come out with the "old" API then I will have no choice on that front.
Out of time today, but I'll rebase to master and PR soon.

**Comment by adamantivm** [comment]
ok, I sent against master on #1697 

Still hoping for an answer about whether this can be released as an update to v1.0 - willing to help in any way necessary - or a negative confirmation on this so that I can schedule updating my code to v1.1.

**Comment by ToxicBakery** [comment]
The only releases we will be doing is from master ATM. In the future we will use gitflow so release branches will exist like you mentioned before but I do not believe we will be back porting anything currently.

**Comment by adamantivm** [comment]
@ToxicBakery thanks for the answer. I will schedule updating our code to the new release then.

Any advice on how to tune in for the next release out of master? Ideally I would update to that when that is available (as opposed to a master snapshot).
