### ISSUE TITLE
adding a child to the current scene result in error about: "Getting location of uniform returned -1"

### ISSUE THREAD

**Issue by gianmaria** [Rajawali/Rajawali#1699]
#### Rajawali Version or Branch
not sure since are the ones used in the  Project Tango examples, but the gradle file under dependencies say: **org.rajawali3d:rajawali:1.0.294-SNAPSHOT@aar**

#### Device and Android Version
Google Project Tango Android 4.4.2

#### Summary
each time i try to add a child to the current scene, like a Sphere, i get some error about the location of uniform that returned -1

#### Steps to Reproduce
``` java
Sphere s = new Sphere(0.50f, 50, 50);
s.setMaterial(new Material());
s.setColor(Color.RED);
s.setPosition(new Vector3());
getCurrentScene().addChild(s);

```
#### Trace or Log Output
``` log
06-06 16:42:39.842 E/Rajawali: Getting location of uniform: uNormalMatrix returned -1!
06-06 16:42:39.842 E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
06-06 16:42:39.842 E/Rajawali: Getting location of uniform: uModelViewMatrix returned -1!
06-06 16:42:39.842 E/Rajawali: Getting location of uniform: uTime returned -1!
```

**Comment by jwoolston** [comment]
These are not not errors (I realize they show as such). They are in fact debug output indicating the auto-shader system did not include those uniforms (because they aren't used by your material). They can safely be ignored and have been suppressed in later versions of the library.
