### ISSUE TITLE
Rajawali - Vuforia 5.5 Migration

### ISSUE THREAD

**Issue by rasystems** [Rajawali/Rajawali#1703]
Hey Rajawali Team!

Is there a way to migrate current Vuforia Build (5.5-9) for use with Rajawali? Vuforia 5.5 supports 3D Object Tracking. If you have time to do this pls release a standalone example.

**Comment by jwoolston** [comment]
We have discussed, but the future plans for Rajawali and VR libraries are unknown. The new licensing model of Vuforia (v4+) is not the greatest when it comes to allowing us to redistribute binaries or even test with examples. When a plan is formulated, we will post information about it.
