### ISSUE TITLE
in the cardboard vr ,Camera is not in 0 points, how to judge the object is looked at?

### ISSUE THREAD

**Issue by yiwuxue** [Rajawali/Rajawali#1706]
in the cardboard vr ,Current Camera is not in (0,0,0) points, how to judge the object is looked at?

How to modify this function ?

```
public boolean isLookingAtObject(Object3D target, float maxAngle) {
    mHeadViewQuaternion.fromMatrix(mHeadViewMatrix);
    mHeadViewQuaternion.inverse();
    mForwardVec.setAll(0, 0, 1);
    mForwardVec.transform(mHeadViewQuaternion);

    mHeadTranslation.setAll(mHeadViewMatrix.getTranslation());
    mHeadTranslation.subtract(target.getPosition());
    mHeadTranslation.normalize();

    return mHeadTranslation.angle(mForwardVec) < maxAngle;
}
```

I would like to do a project to achieve walking effect, but the camera is not zero how to select the object to see

**Comment by sunjinbo** [comment]
I think the better way is to using RayPicker class, but if that you need to modify some logic in it for optimal performance.

**Comment by yiwuxue** [comment]
Can you give me an example?
@sunjinbo

**Comment by sunjinbo** [comment]
You can reference the offical example [examples\interactive\ObjectPickingFragment], for cardboard, the xy-coords is the center of the left screen.

        public void getObjectAt(float x, float y) {
            mPicker.getObjectAt(x, y);
        }

**Comment by yiwuxue** [comment]
Thank you. I'll try.

**Comment by sgrumo** [comment]
@yiwuxue Is it possibile to know the solution of this problem? I'm facing the same.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
