### ISSUE TITLE
How can i draw the Texture of rtmp video to a Sphere ? 

### ISSUE THREAD

**Issue by KarvenMa** [Rajawali/Rajawali#1709]
Now i can play local video on a Sphere with the MediaPlayer.
But i don't know how to play a rtmp video to a Sphere. Can you give us the suggests? Thanks.
@dschuler @ChristofferGreen

**Comment by sunjinbo** [comment]
It's video player's problem, you can use ijkMediaPlayer or VitamioMediaPlayer instead of MediaPlayer, and then made a little bit change in the rajawali source codes.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
