### ISSUE TITLE
How to draw a solid word (with a thickness of the word)

### ISSUE THREAD

**Issue by yiwuxue** [Rajawali/Rajawali#1711]
How to draw a solid word (with a thickness of the word)?

Can you give me an example?

**Comment by contriteobserver** [comment]
Create a word mesh in a 3D modelling program like Blender, (in blender just add a text object,
convert it to a mesh, apply a solidify modifier, then apply a remesh [uncheck Remove Disconnected Pieces] modifier, then export the mesh in a (Wavefront) *.obj format. Place the *.obj and *.mtl files in the app/res/raw dir, and rename to *_obj and *_mtl

Code like this can then load the mesh:
```
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                LoaderOBJ loader = new LoaderOBJ(this, R.raw.word01_obj);
                loader.parse();
                Object3D word = loader.getParsedObject();
                getCurrentScene().addChild(word);

                arcball.setLookAt(word.getPosition());
                getCurrentScene().replaceAndSwitchCamera(getCurrentCamera(), arcball);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
```

**Comment by yiwuxue** [comment]
Thank you. I'll try.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
