### ISSUE TITLE
Jitter problems on gyro and acceloremeter with cardboard

### ISSUE THREAD

**Issue by F3RN4NDOJF3RN4ND3Z** [Rajawali/Rajawali#1712]
#### Rajawali Version or Branch
1.0
#### Rajawali Cardboard Version or Branch
1.0
#### Device and Android Version
Motoroal Moto X andorid 5.1

#### Summary
When I start my render activity wich is a 360 video player I have an issues in my scene
even when the phone is on a surface and not even moving, the camera begins to move to the left slowly some times, some times more faster and when I pick up the phone the camera starts jitterying. I have read a lot of blogs and the solution is implementing a low pass filter, I´m not an experienced opengl programmer not even in sensors, I found some code and this is what I have jet implemented but the camera movement is even worst. I need some help because this is very important for hetting a good vr expereince, the movement of the camera needs to be smooth. I have tested in several phones,Xiaomi Redmi 2 Pro and with a lenovo vibe k5 is really crazy, the camera moves in any direction and never stops.
#### Steps to Reproduce
Here is my render

package com.govideo.apps.video360;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Rect;
import android.graphics.SurfaceTexture;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.media.MediaPlayer;
import android.net.Uri;
import android.view.MotionEvent;
import android.view.Surface;
import android.view.SurfaceHolder;
import android.view.animation.LinearInterpolator;

import org.rajawali3d.animation.ColorAnimation3D;
import org.rajawali3d.cardboard.RajawaliCardboardRenderer;
import org.rajawali3d.materials.Material;
import org.rajawali3d.materials.textures.ATexture;
import org.rajawali3d.materials.textures.StreamingTexture;
import org.rajawali3d.materials.textures.Texture;
import org.rajawali3d.math.vector.Vector3;
import org.rajawali3d.primitives.Sphere;

import java.util.List;

import javax.microedition.khronos.egl.EGLConfig;

/**
 * Created by Fernandojavier on 16/09/2015.
 * Render loop Rajawaali3d implementa RajawaliCardboardRenderer y ex un surface holder para el menidaplayer
 */

public class Renderer extends RajawaliCardboardRenderer
        implements SurfaceHolder,SensorEventListener {
    Context mContext;

    public MediaPlayer mMediaPlayer;
    private StreamingTexture mVideoTexture;

    private Texture mSplashTexture;
    private Sphere mSphere;
    private int mOriginalWidth, mOriginalHeigth;
    private ColorAnimation3D gotoBlackScreenAnim;
    public int videoassetid;
    public int splashid;
    private boolean mOrigVrState;
    public boolean cargaSplash;
    public int videoassetname;
    public boolean mVREnabled = false;
    public boolean isRemoteVideo;
    public Uri videoUri;
    public boolean isMplayerInMatereial;
    private SensorManager mSensorManager;
    private Sensor mSensor;
    private float RTmp[] = new float[9];
    private float Rot[] = new float[9];
    private float I[] = new float[9];
    private float grav[] = new float[3];
    private float mag[] = new float[3];
    private float results[] = new float[3];
    public static float azimuth;
    public static float pitch;
    public static float roll;
    static final float ALPHA = 0.25f;
    protected float[] gravSensorVals;
    protected float[] magSensorVals;
    private List<Sensor> mSensors;
    private Sensor sensorGrav, sensorMag;

    public boolean isRemoteVideo() {
        return isRemoteVideo;
    }

    public void setIsRemoteVideo(boolean isRemoteVideo) {
        this.isRemoteVideo = isRemoteVideo;
    }

    public Uri getVideoUri() {
        return videoUri;
    }

    public void setVideoUri(Uri videoUri) {
        this.videoUri = videoUri;
    }

    public Texture getmSplashTexture() {
        return mSplashTexture;
    }

    public void setmSplashTexture(Texture mSplashTexture) {
        this.mSplashTexture = mSplashTexture;
    }

    public int getSplashid() {
        return splashid;
    }

    public void setSplashid(int splashid) {
        this.splashid = splashid;
    }

    public boolean isCargaSplash() {
        return cargaSplash;
    }

    public void setCargaSplash(boolean cargaSplash) {
        this.cargaSplash = cargaSplash;
    }

    public int getVideoassetname() {
        return videoassetname;
    }

    public void setVideoassetname(int videoassetname) {
        this.videoassetname = videoassetname;
    }

    public boolean ismVREnabled() {
        return mVREnabled;
    }

    public void setmVREnabled(boolean mVREnabled) {
        this.mVREnabled = mVREnabled;
    }

    public int getVideoassetid() {
        return videoassetid;
    }

    public void setVideoassetid(int videoassetid) {
        this.videoassetid = videoassetid;
    }

    public Renderer(Context context,MediaPlayer pMediaPlayer) {
        super(context);
        mContext = context;
        mMediaPlayer=new MediaPlayer();
        mMediaPlayer=pMediaPlayer;
        mSensorManager = (SensorManager) mContext.getSystemService(Context.SENSOR_SERVICE);
        mSensor = mSensorManager.getDefaultSensor(Sensor.TYPE_GYROSCOPE);

    }

    @Override
    protected void initScene() {
        isMplayerInMatereial=false;
        mVideoTexture = new StreamingTexture("Video360", mMediaPlayer);
        renderSphere();
        //Carga splahs de animacion antes del video
        if (isCargaSplash()) {

            mSplashTexture = new Texture("Video360" + "_splash", splashid);
            Material material = new Material();
            material.setColorInfluence(0);
            try {
                material.addTexture(mSplashTexture);
            } catch (ATexture.TextureException e) {
                e.printStackTrace();
            }
            setSphereMaterial(material);
            material.setColorInfluence(1f);

            gotoBlackScreenAnim = new ColorAnimation3D(Color.BLACK, Color.WHITE);

            gotoBlackScreenAnim.setTransformable3D(mSphere);
            gotoBlackScreenAnim.setDurationMilliseconds(5000);
            gotoBlackScreenAnim.setInterpolator(new LinearInterpolator());
            getCurrentScene().registerAnimation(gotoBlackScreenAnim);
            gotoBlackScreenAnim.play();

        } else {

            Material material = new Material();
            material.setColorInfluence(0);

            try {
                material.addTexture(mVideoTexture);
            } catch (ATexture.TextureException e) {
                e.printStackTrace();
            }
            setSphereMaterial(material);

        }

        mSensorManager = (SensorManager) mContext.getSystemService(mContext.SENSOR_SERVICE);

        mSensors = mSensorManager.getSensorList(Sensor.TYPE_ACCELEROMETER);
        if (mSensors.size() > 0) {
            sensorGrav = mSensors.get(0);
        }

        mSensors = mSensorManager.getSensorList(Sensor.TYPE_MAGNETIC_FIELD);
        if (mSensors.size() > 0) {
            sensorMag = mSensors.get(0);
        }

        mSensorManager.registerListener(this, sensorGrav, SensorManager.SENSOR_DELAY_NORMAL);
        mSensorManager.registerListener(this, sensorMag, SensorManager.SENSOR_DELAY_NORMAL);

    }

    public void play(){
        if(mMediaPlayer != null)
            mMediaPlayer.start();

    }

    private void setSphereMaterial(Material material) {
        mSphere.setMaterial(material);

    }

    private void renderSphere() {
        mSphere= new Sphere(50, 64, 32);
        mSphere.setScaleX(-1);

        getCurrentScene().addChild(mSphere);

        getCurrentCamera().setPosition(Vector3.ZERO);

        getCurrentCamera().setFieldOfView(75);
    }

    @Override
    protected void onRender(long ellapsedRealtime, double deltaTime) {
        super.onRender(ellapsedRealtime, deltaTime);
        //Reproducir animacion
        if (mMediaPlayer.isPlaying()) {
            mVideoTexture.update();
        }else if(isCargaSplash() && gotoBlackScreenAnim.isEnded() && mMediaPlayer.getCurrentPosition()==0 && !isMplayerInMatereial){
            Material material = new Material();
            material.setColorInfluence(0);

            try {
                material.addTexture(mVideoTexture);
            } catch (ATexture.TextureException e) {
                e.printStackTrace();
            }
            setSphereMaterial(material);
            isMplayerInMatereial=true;
            play();

        }

    }

    @Override
    public void onRenderSurfaceDestroyed(SurfaceTexture surfaceTexture) {
        mMediaPlayer.release();
        mMediaPlayer=null;
        getCurrentScene().destroyScene();
        //stopRendering();
        super.onRenderSurfaceDestroyed(surfaceTexture);

    }

    @Override
    public void onSurfaceChanged(int width, int height) {
        //Inicializa las dimensiones originales del dispositivo
        //Esta condicion se cumple cuando aun no existe la vista
        if(getDefaultViewportWidth()==0 && getDefaultViewportHeight()==0 ) {
            super.onSurfaceChanged(width, height);
            mOriginalWidth = getDefaultViewportWidth();
            mOriginalHeigth = getDefaultViewportHeight();
            mOrigVrState=ismVREnabled();
        }
        if(mOrigVrState){
            if(!ismVREnabled()){
                width = width * 2;
                mOrigVrState=false;
            }
        }else {
            if(ismVREnabled()){
                width = width / 2;
                mOrigVrState=ismVREnabled();
                mOrigVrState=true;
            }
        }

        super.onSurfaceChanged(width, height);

    }

    @Override
    public void onSurfaceCreated(EGLConfig config) {
        super.onSurfaceCreated(config);
    }

    @Override
    public void onTouchEvent(MotionEvent event) {
        super.onTouchEvent(event);
    }

    @Override
    public void addCallback(Callback callback) {

    }

    @Override
    public void removeCallback(Callback callback) {

    }

    @Override
    public boolean isCreating() {
        return false;
    }

    @Override
    public void setType(int type) {

    }

    @Override
    public void setFixedSize(int width, int height) {

    }

    @Override
    public void setSizeFromLayout() {

    }

    @Override
    public void setFormat(int format) {

    }

    @Override
    public void setKeepScreenOn(boolean screenOn) {

    }

    @Override
    public Canvas lockCanvas() {
        return null;
    }

    @Override
    public Canvas lockCanvas(Rect dirty) {
        return null;
    }

    @Override
    public void unlockCanvasAndPost(Canvas canvas) {

    }

    @Override
    public Rect getSurfaceFrame() {
        return null;
    }

    @Override
    public Surface getSurface() {
        return null;
    }

    @Override
    public void onSensorChanged(SensorEvent event) {

        /*if (event.sensor.getType() == Sensor.TYPE_ACCELEROMETER) {
            gravSensorVals = lowPass(event.values.clone(), gravSensorVals);
            grav[0] = event.values[0];
            grav[1] = event.values[1];
            grav[2] = event.values[2];

        } else if (event.sensor.getType() == Sensor.TYPE_MAGNETIC_FIELD) {
            magSensorVals = lowPass(event.values.clone(), magSensorVals);
            mag[0] = event.values[0];
            mag[1] = event.values[1];
            mag[2] = event.values[2];

        }

        if (gravSensorVals != null && magSensorVals != null) {
            SensorManager.getRotationMatrix(RTmp, I, gravSensorVals, magSensorVals);

            //int rotation =getCurrentCamera().getRotation();

            if (Math.round(getCurrentCamera().getRotX()) == 1) {
                SensorManager.remapCoordinateSystem(RTmp, SensorManager.AXIS_X, SensorManager.AXIS_MINUS_Z, Rot);
            } else {
                SensorManager.remapCoordinateSystem(RTmp, SensorManager.AXIS_Y, SensorManager.AXIS_MINUS_Z, Rot);
            }

            SensorManager.getOrientation(Rot, results);

            Renderer.azimuth = (float)(((results[0]*180)/Math.PI)+180);
            Renderer.pitch = (float)(((results[1]*180/Math.PI))+90);
            Renderer.roll = (float)(((results[2]*180/Math.PI)));
            getCurrentCamera().setCameraPitch(pitch);
            getCurrentCamera().setCameraRoll(roll);
            getCurrentCamera().setCameraYaw(azimuth);

            //Renderer.postInvalidate();
        }*/
    }

    protected float[] lowPass( float[] input, float[] output ) {
        if ( output == null ) return input;

        for ( int i=0; i<input.length; i++ ) {
            output[i] = output[i] + ALPHA * (input[i] - output[i]);
        }
        return output;
    }

    @Override
    public void onAccuracyChanged(Sensor sensor, int accuracy) {

    }
}

**Comment by jwoolston** [comment]
This question is better suited for the community or stack overlow. The implementation of a low pass filter for sensor data has nothing to do with OpenGL and therefore nothing to do with Rajawali.
