### ISSUE TITLE
Override mtl file when parsing OBJ file

### ISSUE THREAD

**Issue by power7714** [Rajawali/Rajawali#1713]
#### Rajawali Version or Branch
Rajawali v1.1.337

#### Device and Android Version
Android 4.4.2

#### Summary
Assign image/texture to OBJ from drawable folder. Override mtl file. I would like to use any image I want as the texture for the OBJ model. Possibly a bitmap. Any ideas? Transitioning from v0.9 to current versions.

#### Steps to Reproduce
`LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(),
                    mTextureManager, R.raw.label_obj);
            objParser.parse();

            Object3D mObjectGroup = objParser.getParsedObject();

            Material material = new Material();
            material.enableLighting(true);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.addTexture(new Texture("rajawaliTex", R.drawable.graf));
            material.setColorInfluence(0);
            mObjectGroup.setMaterial(material);
            getCurrentScene().addChild(mObjectGroup);`

#### Trace or Log Output
none/ no crash

@MasDennis @jwoolston

**Comment by contriteobserver** [comment]
To assign an image/texture to OBJ from drawable folder using the mtl file, just add the line `map_Kd graf.png`, as in 
```
# Blender MTL File: 'None'
# Material Count: 1

newmtl Material
Ns 96.078431
Ka 1.000000 1.000000 1.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2
map_Kd graf.png
```

However, to override the texture with a bitmap drawn on the fly, one should remove the old texture and add the newly painted one, like this:
```
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                LoaderOBJ loader = new LoaderOBJ(this, R.raw.model_obj);
                loader.parse();
                Object3D obj = loader.getParsedObject();
                ATexture texture = cube.getMaterial().getTextureList().get(0);
                obj.getMaterial().removeTexture(texture);

                Bitmap bitmap = Bitmap.createBitmap(128, 128, Bitmap.Config.ARGB_8888);
                Canvas canvas = new Canvas(bitmap);
                Paint paint = new Paint();
                paint.setColor(Color.YELLOW);
                paint.setStyle(Paint.Style.FILL);
                canvas.drawRect(0,0,128,128, paint);

                cube.getMaterial().addTexture(new Texture("canvas", bitmap));
                getCurrentScene().addChild(obj);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
```

**Comment by power7714** [comment]
I already know how to include a texture/image in the mtl file. I'll try
your code and see if that works. Thank you

**Comment by power7714** [comment]
@contriteobserver 
Your method for removing the texture from the mtl file programmatically works but adding one doesn't. It leaves the model black. Any suggestions?

**Comment by contriteobserver** [comment]
I did fix a couple of typos in the example, this example is specifically overriding an existing image/texture, if one is not already there it will `throwIndexOutOfBoundsException` attached efore and after screenshots
![beforeandafter](https://cloud.githubusercontent.com/assets/17471201/16690392/8c7d3512-44dc-11e6-9d4d-7608133c3cd6.png)

**Comment by power7714** [comment]
@contriteobserver I tried your code again. using exactly what you posted just replacing the model with my own and it still doesn't work. Doing this doesn't show the model at all.

**Your method(doesn't show model)**

`	              protected void initScene() {
				mLight = new PointLight();
				mLight.setPosition(0, 0, 4);
				mLight.setPower(3);

				getCurrentScene().addLight(mLight);
				getCurrentCamera().setZ(4);
				try {
					getCurrentScene().setBackgroundColor(Color.BLUE);

					LoaderOBJ loader = new LoaderOBJ(this, R.raw.label_obj);
					loader.parse();
					Object3D obj = loader.getParsedObject();
					ATexture texture = obj.getMaterial().getTextureList().get(0);
					obj.getMaterial().removeTexture(texture);
					obj.setScale(4f);

					Bitmap bitmap = Bitmap.createBitmap(128, 128, Bitmap.Config.ARGB_8888);
					Canvas canvas = new Canvas(bitmap);
					Paint paint = new Paint();
					paint.setColor(Color.YELLOW);
					paint.setStyle(Paint.Style.FILL);
					canvas.drawRect(0, 0, 128, 128, paint);

					obj.getMaterial().addTexture(new Texture("canvas", bitmap));
					getCurrentScene().addChild(obj);

				} catch (Exception e) {
					e.printStackTrace();
				}

			}`

here's my model: [Google Drive](https://drive.google.com/file/d/0B8qSjqZvA_2_NFZwQUVjQXVTaWM/view?usp=sharing)

**Comment by contriteobserver** [comment]
The model has two meshes that interfere with each other. 
Remove either mesh and the model is displayed as expected.
![cylinders](https://cloud.githubusercontent.com/assets/17471201/16711735/3be56044-4620-11e6-977d-6bcddc977524.png)

**Comment by power7714** [comment]
@contriteobserver  hmm interesting. It wasn't supposed to have two meshes so thank you for pointing that out. I'll remove one of the meshes and try to get the result you're getting. Just so you know, I am modifying the LoadModelFragment from the Rajawali Examples repository to try to get my model to show the way it's supposed to.

**Comment by power7714** [comment]
@contriteobserver  Thank you. That worked.
