### ISSUE TITLE
TODO Bug

### ISSUE THREAD

**Issue by 3DRaven** [Rajawali/Rajawali#1716]
#### Rajawali Version or Branch
compile 'org.rajawali3d:rajawali:1.1.337@aar'
#### Device and Android Version
4.0.1
#### Summary
/**
	* Adds a {@link Camera} to the scene.
	*
	* @param camera {@link Camera} object to add.
	* @return boolean True if the addition was successfully queued.
	*/
	public boolean addCamera(final Camera camera) {
		final AFrameTask task = new AFrameTask() {
            @Override
            protected void doTask() {
                mCameras.add(camera);
                if (mSceneGraph != null) {
                    //mSceneGraph.addObject(camera); //TODO: Uncomment
                }
            }
        };
        return internalOfferTask(task);
	}

This code in RajawaliScene.java

**Comment by jwoolston** [comment]
There is no indication of what the problem is here. That todo is left as a reminder and the code is in a valid state currently.
