### ISSUE TITLE
How to switch bitmap texture of Object by using rajawali?

### ISSUE THREAD

**Issue by sunjinbo** [Rajawali/Rajawali#1717]
#### Rajawali Version or Branch
all

#### Device and Android Version
LG Nexus

#### Summary
How to switch bitmap texture of Object by using rajawali?

#### Steps to Reproduce
I want to develop a function that there are has a object in my scene, and this object has a bitmap texture. Then if you touched the object, its texture will be switched to another one, how can I implement it?

#### Trace or Log Output
None

**Comment by helloamoswu** [comment]
You can replace the bitmap like this:        
        mTexture.setBitmap(bitmap);
        TextureManager.getInstance().replaceTexture(mTexture);
you should note that size between bitmaps should be the same.  Otherwise it will not work!
if your bitmaps have different size, you can try this one:
            Material material = yourObject.getMaterial();
            material.removeTexture(mTexture);
            mTexture = new Texture("name", bitmap);
            try {
                material.addTexture(mTexture);
            } catch (ATexture.TextureException e) {
                e.printStackTrace();
            }

i don't know whether i did the right thing, but is work for me. i hope this will help you.
