### ISSUE TITLE
Change texture in real-time?

### ISSUE THREAD

**Issue by power7714** [Rajawali/Rajawali#1719]
#### Rajawali Version or Branch

1.1.337
#### Device and Android Version

Asus PadFone 4.4.2
#### Summary

Realtime changes

In v0.9 you would make "realtime" changes in the onDrawFrame() method. What is the current method for updating the scene in "realtime"? 
I am using the Firebase library and when the user logs in they will have the ability to create their own texture and it will save to cloud storage. The image/texture can be retrieved in real-time immediately after submitting the custom image. What I need though is a way to update the texture in realtime as Firebase retrieves it in realtime. I currently have the bitmap referenced to the users Firebase created image but the model only updates if you close and re-open it.  Would the onRenderFrame() method work for this?

**Comment by contriteobserver** [comment]
`TextureManager.replaceTexture` called in `onRender`should get you there. Here is an example of a time driven texture update, just updating the bitmap color, but one should be able to `drawBitmp` as Firebase provides an image.
```
    private class ParametricTextureRenderer extends Renderer {
        static final double ONE_BILLION = 1000 * 1000 * 1000;
        Texture mMutableTexture;

        public ParametricTextureRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                // Create video texture and apply to material
                Material material = new Material();
                Bitmap bitmap = Bitmap.createBitmap(128, 128, Bitmap.Config.ARGB_8888);
                mMutableTexture = new Texture("mutable", bitmap);
                material.setColorInfluence(0);
                material.addTexture(mMutableTexture);
                
                // Create object
                Object3D object = new Cube(1);
                object.setMaterial(material);
                getCurrentScene().addChild(object);

                arcball.setTarget(object);
                getCurrentScene().replaceAndSwitchCamera(arcball, 0);
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }
        }

        int ParametricColor(double t) {
            long r = Math.round(255 * (Math.sin(t)/2 + 0.5));
            long g = 255;
            long b = Math.round(255 * (Math.cos(t)/2 + 0.5));
            return Color.rgb((int)r, (int)g, (int)b);
        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            double t = ellapsedRealtime/ONE_BILLION;
            Bitmap bitmap = mMutableTexture.getBitmap();
            Canvas canvas = new Canvas(bitmap);
            Paint paint = new Paint();
            paint.setColor(ParametricColor(t));
            paint.setStyle(Paint.Style.FILL);
            canvas.drawRect(0,0,bitmap.getWidth(), bitmap.getHeight(), paint);
            TextureManager.getInstance().replaceTexture(mMutableTexture);
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```

**Comment by power7714** [comment]
@contriteobserver  What if I am replacing the Bitmap in real-time associate with a specific material?

**Comment by contriteobserver** [comment]
Sorry, but I do not understand the intent behind "What if I am replacing the Bitmap in real-time associate with a specific material?", please be more specific.

**Comment by power7714** [comment]
@contriteobserver So, the Firebase library retrieves the bitmap from the cloud storage. Everytime there is a change to the bitmap, either through the app or through web, the change is instant across all platforms.
If I have:
`Bitmap customBitmap = FirebaseStorageReference;`

and my Material has:
`myMaterial.setTexture(new Texture("custom", customBitmap)):`

How can I be certain the material will update instantly with Firebase?

**Comment by contriteobserver** [comment]
If the new bitmap is the same size a the old, you can replace the bitmap with:
```
try {
    mTexture.setBitmap(bitmap);
    TextureManager.getInstance().replaceTexture(mTexture);
} catch (Exception e) {
    e.printStackTrace();
}
```

If your bitmaps have different size, this should gt you there:
```
try {
    Material material = yourObject.getMaterial();
    material.removeTexture(mTexture);
    mTexture = new Texture("name", bitmap);
    material.addTexture(mTexture);
} catch (Exception e) {
    e.printStackTrace();
}
```

**Comment by power7714** [comment]
@contriteobserver I tried your last post but I keep getting this error:
Texture could not be replaced because there is no Bitmap or ByteBuffer set.

I know from the logcat and debugging that there is in fact a bitmap present for the texture. It's not replacing though when I select a different bitmap. I am using [this](https://github.com/firebase/friendlypix/blob/master/android/app/src/main/java/com/google/firebase/samples/apps/friendlypix/NewPostActivity.java) class to create the custom bitmap. I save the result to my application class using a static String. I use that same static string reference in my MainActivity to convert it to a bitmap using the Glide library and pass it back to my application class using a static bitmap reference. I then access that static bitmap reference in my renderer class in the onRender method like you stated above. Yet it's not replacing the texture  or showing any texture for that matter. Just a red color on the model.

**Comment by jwoolston** [comment]
The error message you indicate will only occur if the material's internal bitmap and byte buffer references are both null. Since you aren't using byte buffers, I would expect that one to be null. If you are using the code posted by @contriteobserver above, then the logical conclusion is your bitmap reference you are passing to the material points to null.

**Comment by power7714** [comment]
@jwoolston @contriteobserver I am still having issues applying the image from the firebase url to the texture as a bitmap. Please see my question on [StackOverflow](http://stackoverflow.com/questions/38711316/how-to-convert-image-string-from-firebase-database-to-bitmap-in-android).

**Comment by power7714** [comment]
@jwoolston @contriteobserver  Ok. I managed to create my own texture class to load images from a url. Unfortunately, the texture doesn't update if the url is changed in real-time. Here's my texture class:

`	public class RemoteTexture extends ASingleTexture {

		private String bmpUrl;
		private Bitmap mUrlBitmap;
		private boolean shouldCache = true;
		private MemoryCache memoryCache=new MemoryCache();
		
		public RemoteTexture(String name, String url) {
			this(name, url, false);
			
		}

		/**
		 * Creates texture from a url source
		 *
		 * @param url	Url of the image
		 * @param cache Should we cache the image or not
		 */
		public RemoteTexture(String name, String url, boolean cache) {
			super(TextureType.DIFFUSE, name);
			
			bmpUrl = url;
			shouldCache = cache;

			loadFromUrl();

		}

		private RemoteTexture(RemoteTexture other) {
			super(other);
			//setGLTextureType(GLES11Ext.GL_TEXTURE_EXTERNAL_OES);
			setFrom(other);
		}

		public void setFrom(RemoteTexture other){
			super.setFrom(other);
			mBitmap = other.getBitmap();
			bmpUrl = other.getBmpUrl();
			shouldCache = other.getCacheBoolean();
		}

		private void loadFromUrl() {

			mUrlBitmap = null;
			try{
				// Creates the URL object to load up the data from the internet.
				URL url = new URL(bmpUrl);
				// This function gets the content of the URL. We typecast it to an InputStream Object as that is what will be returned. If the file is missing it will throw an exception which will be caught in the try catch block.
				InputStream is = (InputStream)url.getContent();
				// Decodes the bitmap stream to give us the final bitmap data. This function also takes care of the filetype for the resource
				mUrlBitmap = BitmapFactory.decodeStream(is);

				if(shouldCache){
					memoryCache.put(this.mTextureName, mUrlBitmap);
					mBitmap = mUrlBitmap;
				}else {
					mBitmap = memoryCache.get(this.mTextureName);
				}

				//mBitmap = mUrlBitmap;

			} catch(MalformedURLException mue) {
				mue.printStackTrace();
				Log.e("malformed url", "failed");
			} catch(IOException ioe){
				ioe.printStackTrace();
				Log.e("Bitmap streaming failed", "failed");
			} catch (Throwable ex){
				if(ex instanceof OutOfMemoryError)
					memoryCache.clear();
					mBitmap = null;
			}

			//mUrlBitmap.recycle();
		}

		public RemoteTexture clone() {
			return new RemoteTexture(this);
		}

		public void setRemoteUrl(String url){
			bmpUrl = url;
			loadFromUrl();
		}

		public String getBmpUrl(){
			return bmpUrl;
		}

		public Boolean getCacheBoolean(){
			return shouldCache;
		}

		public Bitmap getBitmap(){
			return mUrlBitmap;
		}

	}`

How can I get this texture to update itself when the url for the image is changed? I am saving and retrieving the url using SharedPreferences. If I update the texture in onRender or onRenderFrame, the model rotates extremely slowly and the memory heap increases dramatically because it is constantly pulling the url. Any ideas?

**Comment by contriteobserver** [comment]
Another approach would be to use a Headless Fragment to manage the remote URL, this fragment would send a message to the Rajawali Fragment that an update was available, the Rajawali Fragment would then set a flag in the renderer that indicates the texture should be updated in it's next onRender. onRender would reset the flag when the bitmap is updated.

**Comment by power7714** [comment]
Could you provide an example? I'm not understanding what you mean.

**Comment by contriteobserver** [comment]
It would be more appropriate for you to create a [Firebase](https://github.com/firebase) ticket, asking how to create a Headless Fragment to manage the remote URL and keep a local bitmap current.

**Comment by jwoolston** [comment]
Closing this issue as resolved/stale.
