### ISSUE TITLE
Custom GLSL issues

### ISSUE THREAD

**Issue by power7714** [Rajawali/Rajawali#1720]
#### Rajawali Version or Branch
1.1.337

#### Device and Android Version
Asus PadFone 4.4.2

#### Summary
Custom Shader not rendering

#### Steps to Reproduce
[Here's](http://goo.gl/z6oTYM) my shader. Even checking in a visualizer doesn't produce any errors but doesn't show anything either.

Anyone have any ideas as to what I might be doing wrong?

**Comment by power7714** [comment]
**Trace**

> 	07-16 15:25:56.267 9250-9279/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
	07-16 15:25:56.267 9250-9279/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uTime returned -1!
	07-16 15:29:28.154 9250-15596/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uMVPMatrix returned -1!
	07-16 15:29:28.155 9250-15596/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uNormalMatrix returned -1!
	07-16 15:29:28.155 9250-15596/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
	07-16 15:29:28.155 9250-15596/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uModelViewMatrix returned -1!
	07-16 15:29:28.155 9250-15596/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uColor returned -1!
	07-16 15:29:28.157 9250-15596/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uTime returned -1!
	07-16 15:29:28.157 9250-15596/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uColorInfluence returned -1!
	07-16 15:29:28.157 9250-15596/com.monyetmabuk.rajawali.tutorials E/Rajawali: Getting location of uniform: uInfluencemyTex returned -1!

**Comment by contriteobserver** [comment]
So close, the defines in your fragment shader are the issue, if you take them out, it works.
```
precision mediump float;

varying vec2 vTextureCoord;
varying vec4 vColor;
uniform sampler2D uDiffuseTexture;
uniform sampler2D uAlphaTexture;

void main() {
    gl_FragColor = texture2D(uDiffuseTexture, vTextureCoord);

    float alpha = texture2D(uAlphaTexture, vTextureCoord).r;
    gl_FragColor.a = alpha;
}
```
here is the rest of the code example
```
    private class glslRenderer extends Renderer {
        Material mMaterial = null;
        double mTime = 0;

        public glslRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);;

                mMaterial = new Material(new RawPointVertexShader(), new RawPointFragmentShader());
                mMaterial.addTexture(new Texture("diffuse", R.drawable.jigsaw));
                mMaterial.addTexture(new AlphaMapTexture("alpha", R.drawable.text));
                mMaterial.enableTime(true);
                mTime = 0;
                Cube cube = new Cube(1);
                cube.setMaterial(mMaterial);
                cube.setTransparent(true);
                getCurrentScene().addChild(cube);

                arcball.setTarget(cube);
                getCurrentScene().replaceAndSwitchCamera(arcball, 0);
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }
        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            mTime += deltaTime;
            mMaterial.setTime((float)mTime);
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }

        private class RawPointVertexShader extends VertexShader {
            public RawPointVertexShader()
            {
                super();
                mNeedsBuild = false;
                initialize();
            }

            @Override
            public void initialize()
            {
                mShaderString = RawShaderLoader.fetch(R.raw.power_vertex_shader);
                //Log.d(getLocalClassName(), mShaderString);
            }

        }

        private class RawPointFragmentShader extends FragmentShader {
            public RawPointFragmentShader()
            {
                super();
                mNeedsBuild = false;
                initialize();
            }

            @Override
            public void initialize()
            {
                mShaderString = RawShaderLoader.fetch(R.raw.power_fragment_shader);
                //Log.d(getLocalClassName(), mShaderString);
            }

        }
    }
```

**Comment by power7714** [comment]
@contriteobserver  are you using the same vertex shader from the link? I'm still getting an empty render both in rajawali and a shader visualizer. Here's the link to the vertex in case you missed it. [Vertex Shader](http://goo.gl/9MHJD0)

_BTW, I really appreciate your help. I should've kept up with the progression of the library. So much has changed since v0.9. Your assistance is helping me get up to speed with the current way of doing things. So thank you!!_

**Comment by power7714** [comment]
@contriteobserver nevermind, I figured out the vertex shader part. Thank you again for your help!
