### ISSUE TITLE
How to set a plane anti aliasing ?

### ISSUE THREAD

**Issue by yiwuxue** [Rajawali/Rajawali#1721]
How to set a plane anti aliasing ?

**Comment by sunjinbo** [comment]
I didn't find a good way to anti aliasing by coding, one work-around is use a bitmap of the edges of the transparent as texture for your plane, you can try it.

**Comment by contriteobserver** [comment]
The code for FXAA is up at http://www.geeks3d.com/20110405/fxaa-fast-approximate-anti-aliasing-demo-glsl-opengl-test-radeon-geforce/3 So it should be possible to put together an plugin. Please advise if there is interest in an FXAA plugin.

**Comment by jwoolston** [comment]
Closing as resolved per #1733
