### ISSUE TITLE
How to change rate of speed of 360° images in example?

### ISSUE THREAD

**Issue by power7714** [Rajawali/Rajawali#1725]
#### Rajawali Version or Branch
Examples Master

Using the 360° Images Example, if I change the images and number of textures to something different, it displays very fast. Only changing images and number images. Nothing else. I've tried to figure this out but how can I slow down the images or change the rate of speed at which they cycle through?

@contriteobserver

**Comment by jwoolston** [comment]
@power7714 Looking at the example code, the rate of switching is based on the modulus of the frame count and number of textures, which determines the index of the array to load. In this case, changing the texture on every frame. You could replace this math with some other math that results in an integer distribution across the range of valid indices.

**Comment by power7714** [comment]
@jwoolston I appreciate the help but I'm a bit confused. Math wasn't one of my strong suits :/ 
Could you elaborate a little on the example please? For example, could you explain or break down this equation for me:
`for (int i = 1; i <= NUM_TEXTURES; i++)`
I know that the first "int" is the number needed for the first index of the bitmap but what is the second and third statement for? Is the third statement there to cycle through to the next image in the sequence? I am basically wanting to control the rate of speed at which the images cycle through and have it stop on the last image. Sorry for sounding like such a noob but how would I do that? I've been trying to figure this out since v0.9. Thank you in advance.

**Comment by jwoolston** [comment]
````java
@Override
protected void onRender(long ellapsedRealtime, double deltaTime) {
    super.onRender(ellapsedRealtime, deltaTime);
    // -- get the texture info list and remove the previous TextureInfo object
   mMaterial.getTextureList().remove(
       mTextures[mFrameCount++ % NUM_TEXTURES]);
   // -- add a new TextureInfo object
   mMaterial.getTextureList().add(
       mTextures[mFrameCount % NUM_TEXTURES]);
}
````

On every frame, the image to display is chosen by the equation `mFrameCount % NUM_TEXTURES`. `mFrameCount` is incremented on every frame. By using the modulus of `mFrameCount` and `NUM_TEXTURES`, the index for the `mTextures` array will range from 0 to NUM_TEXTURES, incrementing by one on every frame and then rolling over from NUM_TEXTURES to 0, restarting the loop forever.

**Comment by power7714** [comment]
What if you want it to stop on the last frame?

**Comment by ToxicBakery** [comment]
It's an array, all this does is pick an index to use per frame. Stop changing the index and it will stop changing the texture.

**Comment by power7714** [comment]
Hey Ian, been awhile.  Forgive me here but which part is changing the index? "i++" or mFrameCount++
I'm about to pay someone to do this on Freelancer so if I can get this working before doing that, that would be fantastic.

**Comment by ToxicBakery** [comment]
As @jwoolston noted

This removes the current texture then increments the framecount by 1.
```java
mMaterial.getTextureList().remove(mTextures[mFrameCount++ % NUM_TEXTURES]);
```

This adds the next texture because the framecount was just increased on the previous line
```java
mMaterial.getTextureList().add(mTextures[mFrameCount % NUM_TEXTURES]);
```

**Comment by jwoolston** [comment]
Closing as resolved.
