### ISSUE TITLE
I stopped using rajawali in my project

### ISSUE THREAD

**Issue by 3DRaven** [Rajawali/Rajawali#1727]
#### Rajawali Version or Branch
337
#### Device and Android Version
API 15
#### Summary
1. Crash AVD witch API 15/16! 2. Reboot my phone witch API 15! 3. Black fragment when fragment creation (i make issue in github). 4. Memory leak. 5. Trash in log.

#### Steps to Reproduce
Update 3d object position in realtime or many other.

Thanks for the code that I could use as an example. I look at arcballcamera realization and remade it on opengles.

Bye!

**Comment by ToxicBakery** [comment]
no, bye to you sir
