### ISSUE TITLE
Broken link in wiki tutorial 17

### ISSUE THREAD

**Issue by mihaibujanca** [Rajawali/Rajawali#1729]
There is a broken link pointing to https://github.com/Rajawali/RajawaliExamples/blob/master/src/com/monyetmabuk/rajawali/tutorials/RajawaliLoadModelRenderer.java
in https://github.com/Rajawali/Rajawali/wiki/Tutorial-17-Importing-.Obj-Files, at the bottom of the page

**Comment by ToxicBakery** [comment]
Fixed
