### ISSUE TITLE
whether can Rajawali  load svg ?

### ISSUE THREAD

**Issue by liyihongcug** [Rajawali/Rajawali#1734]
I have 2 svg files (a.svg ,b.svg). They are 0 layer and 1 layer plane shape data of the same building each other .  I can load one svg to Rajawali in android.But I don't know how to deal with 2 svg files at the same activity.

svg files are 2,  So I am ready to stretch all data and thus we can get the 3d picture.
Please notice 1 leve svg file path's basic refer coordinate is the same as 0 leve svg file path data.
So 1 leve's 3d coordinate is different from 0 level' 3d coordinate. I don't know how to update codes below

``` java
    SVGPath svgPath = new SVGPath();
    List<CompoundCurve3D> paths = svgPath.parseResourceString(mContext, R.raw.lavatories_svg_path);
    paths.addAll(svgPath.parseString(path));
    Stack<Stack<Vector3>> pathPoints = new Stack<Stack<Vector3>>();

    for (int i = 0; i < paths.size(); i++) {
        ICurve3D subPath = paths.get(i);
        Stack<Vector3> points = new Stack<Vector3>();
        int subdiv = 1000;
        for (int j = 0; j <= subdiv; j++) {
            Vector3 point = new Vector3();
            subPath.calculatePoint(point, (float) j / (float) subdiv);
            points.add(point);
        }
        pathPoints.add(points);
        Line3D line = new Line3D(points, 1);
    }
```

Question:
1 where can I update path's height and stretch it to 5m?

**Comment by contriteobserver** [comment]
Working through a response, but a little more information is needed.

Rajawali SVGpath supports a subset of SVG path commands. [MmZzLlHhVvCcSs]
Are you attempting to parse Quadratic Bézier or Elliptical arc commands? [QqTtAa]

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
