### ISSUE TITLE
ParticleMaterial Missing

### ISSUE THREAD

**Issue by wolfbigbig** [Rajawali/Rajawali#1736]
#### Rajawali Version or Branch
Version:1.0.325 
#### Device and Android Version
android studio :2.1.2

#### Summary
I want use particles effect，When I Open ExampleParticlesSystem2，I found the class ParticleMaterial not existed. Waht should I do？I want achieve Particles in Rajawali 3D. What should I do? Thank you

**Comment by contriteobserver** [comment]
I am working on a particle material, this is what I have so far....

Renderer:
```
    private class ParticleRenderer extends Renderer {
        Object3D  obj = null;
        float[] initVerts = null;
        float[] vertices = null;
        int[] indices = null;
        static final int NUM_DIMENSIONS = 3;
        static final int NUM_PARTICLES = 256;
        static final double ONE_BILLION = 1000 * 1000 * 1000;

        public ParticleRenderer(Context context) {
            super(context);

        }

        @Override
        protected void initScene() {
            initVerts = genVertices(NUM_PARTICLES);
            vertices = new float[NUM_PARTICLES*NUM_DIMENSIONS];
            indices = genIndices(NUM_PARTICLES);
            getCurrentScene().setBackgroundColor(Color.BLUE);

            Material material = new Material(new RawPointVertexShader(), new RawPointFragmentShader());
            obj = new Object3D();
            obj.setTransparent(true);
            obj.setMaterial(material);
            obj.setDrawingMode(GLES20.GL_POINTS);
            getCurrentScene().addChild(obj);

            Animation3D anim = new RotateOnAxisAnimation(new Vector3(1,-1,1), 360);
            anim.setDurationMilliseconds(123456);
            anim.setRepeatMode(Animation.RepeatMode.INFINITE);
            anim.setTransformable3D(obj);
            getCurrentScene().registerAnimation(anim);
            anim.play();

            getCurrentCamera().setPosition(2,2,2);
            getCurrentCamera().setLookAt(obj.getPosition());
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }

        float[] genVertices(int size) {
            float[] vertices = new float[size*3];
            Random random = new Random();
            for(int i=0; i<size; i++) {
                vertices[i*NUM_DIMENSIONS+0] = random.nextFloat() * 2.0f - 1.0f;
                vertices[i*NUM_DIMENSIONS+1] = random.nextFloat() * 2.0f - 1.0f;
                vertices[i*NUM_DIMENSIONS+2] = random.nextFloat() * 2.0f - 1.0f;
            }
            return vertices;
        }

        int[] genIndices(int size) {
            int[] indices = new int[size*3];
            for(int i=0; i<size; i++) {
                indices[i*NUM_DIMENSIONS+0] = i;
                indices[i*NUM_DIMENSIONS+1] = i;
                indices[i*NUM_DIMENSIONS+2] = i;
            }
            return indices;
        }

        float[] updateParticles(float[] src, float[] dest, double t) {
            System.arraycopy(src, 0, dest, 0, dest.length);
            for(int i=0; i<dest.length/3; i++) {
                dest[i*NUM_DIMENSIONS+0] = (float)Math.sin(t * src[i*NUM_DIMENSIONS+0]) * 0.1f * src[i*NUM_DIMENSIONS+0];
                dest[i*NUM_DIMENSIONS+1] = (float)Math.sin(t * src[i*NUM_DIMENSIONS+1]) * 0.1f * src[i*NUM_DIMENSIONS+1];
                dest[i*NUM_DIMENSIONS+2] = (float)Math.sin(t * src[i*NUM_DIMENSIONS+2]) * 0.1f + src[i*NUM_DIMENSIONS+2];
            }
            return dest;
        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            float[] normals = null;
            float[] textureCoords = null;
            float[] colors = null;
            boolean createVBOs = true;

            double t = ellapsedRealtime / ONE_BILLION;
            super.onRender(ellapsedRealtime, deltaTime);
            updateParticles(initVerts, vertices, t);
            obj.setData(vertices, normals, textureCoords, colors, indices, createVBOs);
        }

        private class RawPointVertexShader extends VertexShader {
            private int muPointThicknessHandle;

            public RawPointVertexShader()
            {
                super();
                mNeedsBuild = false;
                initialize();
            }

            @Override
            public void initialize()
            {
                mShaderString = RawShaderLoader.fetch(R.raw.point_vertex_shader);
            }

            @Override
            public void main() {

            }

            @Override
            public void setLocations(final int programHandle)
            {
                super.setLocations(programHandle);
                muPointThicknessHandle = getUniformLocation(programHandle, "uThickness");
            }

            @Override
            public void applyParams()
            {
                super.applyParams();
                GLES20.glUniform1f(muPointThicknessHandle, 16f);
            }
        }

        private class RawPointFragmentShader extends FragmentShader {
            private int muThicknessHandle;

            public RawPointFragmentShader()
            {
                super();
                mNeedsBuild = false;
                initialize();
            }

            @Override
            public void initialize()
            {
                mShaderString = RawShaderLoader.fetch(R.raw.point_fragment_shader);
            }

            @Override
            public void main() {

            }

            @Override
            public void setLocations(final int programHandle)
            {
                super.setLocations(programHandle);
                muThicknessHandle = getUniformLocation(programHandle, "uThickness");
            }

            @Override
            public void applyParams()
            {
                super.applyParams();
                GLES20.glUniform1f(muThicknessHandle, 6f);
            }
        }
    }
```
Vertex Shader
```
uniform mat4 uMVPMatrix;
uniform float uThickness;

attribute vec4 aPosition;

void main() {
    gl_PointSize = uThickness;
    gl_Position = uMVPMatrix * aPosition;
}
```
Fragment Shader
```
precision mediump float;

varying vec4 vColor;

void main() {
    float x = (gl_PointCoord.x - 0.5) * 2.;
    float y = (gl_PointCoord.y - 0.5) * 2.;
    float d = x*x + y*y;
    gl_FragColor = vec4(1.,1.,1.,1.-d);
}
```

**Comment by wolfbigbig** [comment]
@contriteobserver Thx for your help. I don't know how to use the Render to achieve Particle effect. Can you give me a demo? Thx very much!

**Comment by contriteobserver** [comment]
To use the ParticleRenderer, try this...
```
public class LocalRajawaliActivity extends AppCompatActivity {
    SurfaceView surface;
    Renderer renderer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_local_rajawali);

        surface = (SurfaceView) findViewById(R.id.rajawali_content);
        renderer = new ParticleRenderer(this);
        surface.setSurfaceRenderer(renderer);
    }
}
```

**Comment by jwoolston** [comment]
The particle effect we previously include was intentionally broken a while back and we have not had the time to fix it yet.

**Comment by wolfbigbig** [comment]
@jwoolston Thank you  for your reply.

**Comment by wolfbigbig** [comment]
@contriteobserver Thx, I have achieve particle effect. But I also have a problem, If I want to achieve a particle effect with snoflake, petal etc not just with dot, what should I do? In other words, Can I load custom models? Thanks again.

**Comment by jwoolston** [comment]
@wolfbigbig What you want is essentially a combination of the 2000 Planes demo and particles. You can make each particle a point sprite with whatever texture you want.

**Comment by wolfbigbig** [comment]
@jwoolston Thx for your advice. I have achieve petal particle effect with 2000 Planes demo. I found the effect of each plane is deformed, when I map petal as texture to plans. (some petals became triangle). how to fix it? Thank you.

**Comment by wolfbigbig** [comment]
@jwoolston In Rajawali 3D demo, petals rotated as the rotation speed. But when use it to my project, the rotation speed invalid. Where is the problem? Thank you~

**Comment by jwoolston** [comment]
> I found the effect of each plane is deformed, when I map petal as texture to plans. (some petals became triangle). how to fix it? Thank you.

Did this occur when the planes were at oblique angles to the camera? If so this is a projection issue and it takes special textures to deal with that. 

As for the rotation speed being invalid, you will have to be more specific.

**Comment by wolfbigbig** [comment]
@jwoolston Thx, deformation has fixed. As for rotation speed. In Rajawali 3D demo, I can control plans'  rotation speed by setting "rotationSpeed" (PlanesGalore.class). But it dosen't work when do it in my project. Thank you!

**Comment by wolfbigbig** [comment]
@jwoolston Thx, deformation has fixed. As for rotation speed. In Rajawali 3D demo, I can control plans' rotation speed by setting "rotationSpeed" (PlanesGalore.class). But it dosen't work when do it in my project. And I want konw, Can I set acceleration gravity to planes? 
**PS: My project is based on Cardboard. I'm not sure this would affect it? I'm crazzy!**
This my code:

MyRenderer.class
`  protected void initScene() {
DirectionalLight light1 = new DirectionalLight(0, 0, 0);
        light1.setPower(1.0f);
        light1.setLookAt(new Vector3(0,0,1));
        light1.enableLookAt();
        getCurrentScene().addLight(light1);

getCurrentCamera().enableLookAt();
        getCurrentCamera().setPosition(0, 0, 0);
        getCurrentCamera().setFieldOfView(FOV);
        getCurrentCamera().setLookAt(new Vector3(0,0,0));

final PlanesGalore planes = new PlanesGalore();
        mMaterial = planes.getMaterial();
        mMaterial.setColorInfluence(0);
        try {
            mMaterial.addTexture(new Texture("petals", R.drawable.petals16));
        } catch (ATexture.TextureException e) {
            e.printStackTrace();
        }
        mMaterialPlugin = planes.getMaterialPlugin();

        planes.setDoubleSided(true);
        planes.setTransparent(true);
        planes.setUpAxis(Vector3.Axis.Y);
        planes.setRotation(Vector3.Axis.Y,80);
        planes.setBackSided(true);

        Object3D empty = new Object3D();
        getCurrentScene().addChild(empty);

        CatmullRomCurve3D path = new CatmullRomCurve3D();

 path.addPoint(new Vector3(6, 10, DISTANCE_Z));
        path.addPoint(new Vector3(DISTANCE_X, 8, DISTANCE_Z));
        path.addPoint(new Vector3(5, 6, DISTANCE_Z));
        path.addPoint(new Vector3(DISTANCE_X, 4, DISTANCE_Z));
        path.addPoint(new Vector3(5, 2, DISTANCE_Z));
        path.addPoint(new Vector3(DISTANCE_X, -2, DISTANCE_Z));
        path.addPoint(new Vector3(5, -4, DISTANCE_Z));
        path.addPoint(new Vector3(DISTANCE_X, -6, DISTANCE_Z));
        path.addPoint(new Vector3(5, -8, DISTANCE_Z));

        final SplineTranslateAnimation3D anim = new SplineTranslateAnimation3D(path);
        anim.setDurationMilliseconds(50000);
        anim.setRepeatMode(Animation.RepeatMode.INFINITE);
        anim.setTransformable3D(planes);
        anim.setInterpolator(new AccelerateDecelerateInterpolator());
        getCurrentScene().registerAnimation(anim);
        anim.play();
}

  public void onRenderSurfaceCreated(EGLConfig config, GL10 gl, int width, int height) {
        super.onRenderSurfaceCreated(config, gl, width, height);
        mStartTime = System.currentTimeMillis();
    }

 protected void onRender(long ellapsedRealtime, double deltaTime) {
        GLES20.glEnable(GLES20.GL_ALPHA_BITS);
        super.onRender(ellapsedRealtime, deltaTime);
        mMaterial.setTime((System.currentTimeMillis() - mStartTime) / 1000f);
        mMaterialPlugin.setCameraPosition(getCurrentCamera().getPosition());

        try {
            mCurtainObject.updateRender();
            mRayPicker.getObjectAt(mX, mY);
            checkPlayerTimeout();
            handleToastElapsedRealtime();
        } catch (RuntimeException e) {
            Log.e(TAG, e.getMessage());
        } catch (Exception e) {
            Log.e(TAG, e.getMessage());
        }

        GLES20.glDisable(GLES20.GL_ALPHA_BITS);
    }`

My PlanesGalore.class and PlanesGaloreMaterialPlugin.class are same as Optimized2000PlanesFragment.

I am so confoused. Thank you~

**Comment by wolfbigbig** [comment]
@jwoolston Thx, deformation has fixed. As for rotation speed. In Rajawali 3D demo, I can control plans' rotation speed by setting "rotationSpeed" (PlanesGalore.class). But it dosen't work when do it in my project. And I want konw, Can I set acceleration gravity to planes? 
**PS: My project is based on Cardboard. I'm not sure this would affect it? I'm crazzy!**
This my code:

**_MyRenderer.class_**
` protected void initScene() {
DirectionalLight light1 = new DirectionalLight(0, 0, 0);
light1.setPower(1.0f);
light1.setLookAt(new Vector3(0,0,1));
light1.enableLookAt();
getCurrentScene().addLight(light1);

getCurrentCamera().enableLookAt();
getCurrentCamera().setPosition(0, 0, 0);
getCurrentCamera().setFieldOfView(FOV);
getCurrentCamera().setLookAt(new Vector3(0,0,0));

final PlanesGalore planes = new PlanesGalore();
mMaterial = planes.getMaterial();
mMaterial.setColorInfluence(0);
try {
mMaterial.addTexture(new Texture("petals", R.drawable.petals16));
} catch (ATexture.TextureException e) {
e.printStackTrace();
}
mMaterialPlugin = planes.getMaterialPlugin();

    planes.setDoubleSided(true);
    planes.setTransparent(true);
    planes.setUpAxis(Vector3.Axis.Y);
    planes.setRotation(Vector3.Axis.Y,80);
    planes.setBackSided(true);

    Object3D empty = new Object3D();
    getCurrentScene().addChild(empty);

    CatmullRomCurve3D path = new CatmullRomCurve3D();
path.addPoint(new Vector3(6, 10, DISTANCE_Z));
path.addPoint(new Vector3(DISTANCE_X, 8, DISTANCE_Z));
path.addPoint(new Vector3(5, 6, DISTANCE_Z));
path.addPoint(new Vector3(DISTANCE_X, 4, DISTANCE_Z));
path.addPoint(new Vector3(5, 2, DISTANCE_Z));
path.addPoint(new Vector3(DISTANCE_X, -2, DISTANCE_Z));
path.addPoint(new Vector3(5, -4, DISTANCE_Z));
path.addPoint(new Vector3(DISTANCE_X, -6, DISTANCE_Z));
path.addPoint(new Vector3(5, -8, DISTANCE_Z));

    final SplineTranslateAnimation3D anim = new SplineTranslateAnimation3D(path);
    anim.setDurationMilliseconds(50000);
    anim.setRepeatMode(Animation.RepeatMode.INFINITE);
    anim.setTransformable3D(planes);
    anim.setInterpolator(new AccelerateDecelerateInterpolator());
    getCurrentScene().registerAnimation(anim);
    anim.play();
}

public void onRenderSurfaceCreated(EGLConfig config, GL10 gl, int width, int height) {
super.onRenderSurfaceCreated(config, gl, width, height);
mStartTime = System.currentTimeMillis();
}

protected void onRender(long ellapsedRealtime, double deltaTime) {
GLES20.glEnable(GLES20.GL_ALPHA_BITS);
super.onRender(ellapsedRealtime, deltaTime);
mMaterial.setTime((System.currentTimeMillis() - mStartTime) / 1000f);
mMaterialPlugin.setCameraPosition(getCurrentCamera().getPosition());

    try {
        mCurtainObject.updateRender();
        mRayPicker.getObjectAt(mX, mY);
        checkPlayerTimeout();
        handleToastElapsedRealtime();
    } catch (RuntimeException e) {
        Log.e(TAG, e.getMessage());
    } catch (Exception e) {
        Log.e(TAG, e.getMessage());
    }

    GLES20.glDisable(GLES20.GL_ALPHA_BITS);
}`

My **PlanesGalore.class** and **PlanesGaloreMaterialPlugin.class** are same as **Optimized2000PlanesFragment**.

I am so confoused. Thank you~

**Comment by wolfbigbig** [comment]
@jwoolston Thx, deformation has fixed. As for rotation speed. In Rajawali 3D demo, I can control plans' rotation speed by setting "rotationSpeed" (PlanesGalore.class). But it dosen't work when do it in my project. And I want konw, Can I set acceleration gravity to planes? 
PS: My project is based on Cardboard. I'm not sure this would affect it? I'm crazzy!
This my code:

**MyRenderer.class**
` protected void initScene() {
DirectionalLight light1 = new DirectionalLight(0, 0, 0);
light1.setPower(1.0f);
light1.setLookAt(new Vector3(0,0,1));
light1.enableLookAt();
getCurrentScene().addLight(light1);

getCurrentCamera().enableLookAt();
getCurrentCamera().setPosition(0, 0, 0);
getCurrentCamera().setFieldOfView(FOV);
getCurrentCamera().setLookAt(new Vector3(0,0,0));

final PlanesGalore planes = new PlanesGalore();
mMaterial = planes.getMaterial();
mMaterial.setColorInfluence(0);
try {
mMaterial.addTexture(new Texture("petals", R.drawable.petals16));
} catch (ATexture.TextureException e) {
e.printStackTrace();
}
mMaterialPlugin = planes.getMaterialPlugin();

planes.setDoubleSided(true);
planes.setTransparent(true);
planes.setUpAxis(Vector3.Axis.Y);
planes.setRotation(Vector3.Axis.Y,80);
planes.setBackSided(true);

Object3D empty = new Object3D();
getCurrentScene().addChild(empty);

CatmullRomCurve3D path = new CatmullRomCurve3D();

path.addPoint(new Vector3(6, 10, DISTANCE_Z));
path.addPoint(new Vector3(DISTANCE_X, 8, DISTANCE_Z));
path.addPoint(new Vector3(5, 6, DISTANCE_Z));
path.addPoint(new Vector3(DISTANCE_X, 4, DISTANCE_Z));
path.addPoint(new Vector3(5, 2, DISTANCE_Z));
path.addPoint(new Vector3(DISTANCE_X, -2, DISTANCE_Z));
path.addPoint(new Vector3(5, -4, DISTANCE_Z));
path.addPoint(new Vector3(DISTANCE_X, -6, DISTANCE_Z));
path.addPoint(new Vector3(5, -8, DISTANCE_Z));

final SplineTranslateAnimation3D anim = new SplineTranslateAnimation3D(path);
anim.setDurationMilliseconds(50000);
anim.setRepeatMode(Animation.RepeatMode.INFINITE);
anim.setTransformable3D(planes);
anim.setInterpolator(new AccelerateDecelerateInterpolator());
getCurrentScene().registerAnimation(anim);
anim.play();
}

 public void onRenderSurfaceCreated(EGLConfig config, GL10 gl, int width, int height) {
        super.onRenderSurfaceCreated(config, gl, width, height);
        mStartTime = System.currentTimeMillis();
    }

protected void onRender(long ellapsedRealtime, double deltaTime) {
        GLES20.glEnable(GLES20.GL_ALPHA_BITS);
        super.onRender(ellapsedRealtime, deltaTime);
        mMaterial.setTime((System.currentTimeMillis() - mStartTime) / 1000f);
        mMaterialPlugin.setCameraPosition(getCurrentCamera().getPosition());

        try {
            mCurtainObject.updateRender();
            mRayPicker.getObjectAt(mX, mY);
            checkPlayerTimeout();
            handleToastElapsedRealtime();
        } catch (RuntimeException e) {
            Log.e(TAG, e.getMessage());
        } catch (Exception e) {
            Log.e(TAG, e.getMessage());
        }

        GLES20.glDisable(GLES20.GL_ALPHA_BITS);
    }

`

My **PlanesGalore.class** and **PlanesGaloreMaterialPlugin.class** are same as **Optimized2000PlanesFragment**.

I am so confoused. Thank you~

**Comment by wolfbigbig** [comment]
@jwoolston Thx, deformation has fixed. As for rotation speed. In Rajawali 3D demo, I can control plans' rotation speed by setting "rotationSpeed" (PlanesGalore.class). But it dosen't work when do it in my project. And I want konw, Can I set acceleration gravity to planes? 
**PS: My project is a VR project based on Cardboard. I'm not sure this would affect it?** I'm crazzy!
This my code block:

**MyRenderer.class**

       `protected void initScene() {
        DirectionalLight light1 = new DirectionalLight(0, 0, 0);
        light1.setPower(1.0f);
        light1.setLookAt(new Vector3(0,0,1));
        light1.enableLookAt();
        getCurrentScene().addLight(light1);


        getCurrentCamera().enableLookAt();
        getCurrentCamera().setPosition(0, 0, 0);
        getCurrentCamera().setFieldOfView(FOV);
        getCurrentCamera().setLookAt(new Vector3(0,0,0));


        final PlanesGalore planes = new PlanesGalore();
        mMaterial = planes.getMaterial();
        mMaterial.setColorInfluence(0);
        try {
            mMaterial.addTexture(new Texture("petals", R.drawable.petals16));
        } catch (ATexture.TextureException e) {
            e.printStackTrace();
        }
        mMaterialPlugin = planes.getMaterialPlugin();

        planes.setDoubleSided(true);
        planes.setTransparent(true);
        planes.setUpAxis(Vector3.Axis.Y);
        planes.setRotation(Vector3.Axis.Y,80);
        planes.setBackSided(true);

        Object3D empty = new Object3D();
        getCurrentScene().addChild(empty);

        CatmullRomCurve3D path = new CatmullRomCurve3D();

        path.addPoint(new Vector3(6, 10, DISTANCE_Z));
        path.addPoint(new Vector3(DISTANCE_X, 8, DISTANCE_Z));
        path.addPoint(new Vector3(5, 6, DISTANCE_Z));
        path.addPoint(new Vector3(DISTANCE_X, 4, DISTANCE_Z));
        path.addPoint(new Vector3(5, 2, DISTANCE_Z));
        path.addPoint(new Vector3(DISTANCE_X, -2, DISTANCE_Z));
        path.addPoint(new Vector3(5, -4, DISTANCE_Z));
        path.addPoint(new Vector3(DISTANCE_X, -6, DISTANCE_Z));
        path.addPoint(new Vector3(5, -8, DISTANCE_Z));

        final SplineTranslateAnimation3D anim = new SplineTranslateAnimation3D(path);
        anim.setDurationMilliseconds(50000);
        anim.setRepeatMode(Animation.RepeatMode.INFINITE);
        anim.setTransformable3D(planes);
        anim.setInterpolator(new AccelerateDecelerateInterpolator());
        getCurrentScene().registerAnimation(anim);
        anim.play();
        }

      public void onRenderSurfaceCreated(EGLConfig config, GL10 gl, int width, int height) {
        super.onRenderSurfaceCreated(config, gl, width, height);
        mStartTime = System.currentTimeMillis();
      }

        protected void onRender(long ellapsedRealtime, double deltaTime) {
        GLES20.glEnable(GLES20.GL_ALPHA_BITS);
        super.onRender(ellapsedRealtime, deltaTime);
        mMaterial.setTime((System.currentTimeMillis() - mStartTime) / 1000f);
        mMaterialPlugin.setCameraPosition(getCurrentCamera().getPosition());

        try {
            mCurtainObject.updateRender();
            mRayPicker.getObjectAt(mX, mY);
            checkPlayerTimeout();
            handleToastElapsedRealtime();
        } catch (RuntimeException e) {
            Log.e(TAG, e.getMessage());
        } catch (Exception e) {
            Log.e(TAG, e.getMessage());
        }

        GLES20.glDisable(GLES20.GL_ALPHA_BITS);
    }
My **PlanesGalore.class** and **PlanesGaloreMaterialPlugin.class** are same as **Optimized2000PlanesFragment.**

I am so confoused. If you want see my other code blocks just tell me. Thank you very much!
