### ISSUE TITLE
Texture Could Not Be Updated

### ISSUE THREAD

**Issue by wolfbigbig** [Rajawali/Rajawali#1746]
Hi all:
when I run my project based on Optimized2000PlanesFragment, Logcat export an error as 

` E/Rajawali: Execution Failed: org.rajawali3d.materials.textures.ATexture$TextureException: Texture could not be updated because the texture size is different from the original.`

When I use the normal texture **'flickrpics'** also have the same error log.

**PS: My project is based on Cardboard.**

Somebody help me? Thank you~

**Comment by jwoolston** [comment]
The error is pretty clear...the original texture was created with some size, and you are trying to update it with an image of a different size. You cant do this. If you need to, then you need to change the texture not replace the image.

**Comment by wolfbigbig** [comment]
@jwoolston THX~
