### ISSUE TITLE
Problem loading OBJ from sdcard

### ISSUE THREAD

**Issue by li96968510** [Rajawali/Rajawali#1747]
the same of  #1141,when i load it from res/raw ,work fine.

load from sdcard code:
  LoaderOBJ objParser = new LoaderOBJ(this, "/briscAR/lowpoly_statue.obj");
  objParser.parse();
  mObjectGroup = objParser.getParsedObject();
  getCurrentScene().addChild(mObjectGroup);

error:
[org.rajawali3d.materials.Material] Could not compile fragment shader: Shader log: 0:7: L0001: Expected token ';', found '.'

How to solved it?

**Comment by power7714** [comment]
You have to use getExternalStorage(). You can't use strings to access the
sd card.

**Comment by power7714** [comment]
Read this article to get an idea of how to read any for from the sd card: http://code2care.org/2015/read-text-file-from-sd-card-android-programming/

**Comment by jwoolston** [comment]
The loader implementations handle this for you so his method of loading is correct. The error message reports an issue in the fragment shader compilation. Is this the only log message you see? Can you share the obj file which is causing the problem?

**Comment by li96968510** [comment]
@jwoolston  yes, this is the only log message of error. I send the model to the email of     "Rajawali/Rajawali"<Rajawali@noreply.github.com>;    And CC to "Author"<author@noreply.github.com>;
I'm not sure whether you have received it or not.

**Comment by li96968510** [comment]
@power7714  As jwoolston said.  I found the code in  Rajawali， the class is  ALoader : 
	public ILoader parse() throws ParsingException {
		if (mFile == null && mFileOnSDCard != null)
			mFile = new File(Environment.getExternalStorageDirectory(), mFileOnSDCard);

		if (mFile != null && RajLog.isDebugEnabled())
			RajLog.d("Parsing: " + mFile.getAbsolutePath());
		return this;
	}

**Comment by jwoolston** [comment]
Those email addresses don't go anywhere, thats why they have noreply in the name. Send it to the email address on my github profile page.

**Comment by li96968510** [comment]
@jwoolston  thanks, already send to you .

**Comment by jwoolston** [comment]
@li96968510 the issue is due to the name of the texture having a `.` in it which is ending up as the variable name in the fragment shader. The loader should sanitize this so I will fix it momentarily. I'm upgrading this to a bug.

**Comment by li96968510** [comment]
@jwoolston  ok， Current I export from 3DBuilder.  it also have the same problem. 
error message:
1、com.monyetmabuk.rajawali.tutorials E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
2、 [org.rajawali3d.materials.Material] Could not compile fragment shader: Shader log: 0:4: L0001: Expected token ';', found 'float-point literal'.

**Comment by jwoolston** [comment]
- Disregard the first issue, its just Rajawali trying to check things before Android is ready.
- The fix I'm pushing now will resolve number 2. I am emailing you a screen shot of the rendered model.

**Comment by jwoolston** [comment]
The new artifact is building, it will take about 20 minutes to complete. You can watch the progress here if you would like: https://travis-ci.org/Rajawali/Rajawali/builds/156114682 

The new artifact will be 1.1.566-SNAPSHOT

**Comment by li96968510** [comment]
@jwoolston  ok，already work. Thank you.
