### ISSUE TITLE
  How to switch between different models in the same scene?

### ISSUE THREAD

**Issue by Owen-Hw** [Rajawali/Rajawali#1748]
#### Rajawali Version or Branch

org.rajawali3d:rajawali:1.1.566-SNAPSHOT@aar

if I have three models.   How to switch between different models in the same scene?

**Comment by jwoolston** [comment]
Just change the visibility of the objects as you want them to show/hide.

**Comment by li96968510** [comment]
@jwoolston  ok ,thank you.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
