### ISSUE TITLE
too much rendering time

### ISSUE THREAD

**Issue by kubisingh** [Rajawali/Rajawali#1753]
#### Rajawali Version or Branch

'org.rajawali3d:rajawali:1.0.325@aar'
'org.rajawali3d:rajawali:1.1.xxx-snapsort@aar'
#### Device and Android Version

Lava iris(Kitkat) and Moto G 2gen(Aandroid lollipop) , 
#### Summary

i am working on 3D testing app, i am facing problem regarding rendering 3D obj file, it takes lot of time(around 2-3 min) to render an obj+mtl file even much more time for heavy obj files, from last one week i am searching for reducing rendering time, but didn't get anything, please help me, thank you

here my code:

[Renderer.txt](https://github.com/Rajawali/Rajawali/files/446503/Renderer.txt)

it may be problem with my 3D obj file, i has downloaded .3ds file and convert to .obj & .mtl file by blander as mention in https://github.com/Rajawali/Rajawali/wiki/Tutorial-17-Importing-.Obj-Files
change name with "_" and also inside obj file, rendering is proper but only  problem is that its take to much time,  

Sample Obj files : https://www.dropbox.com/sh/hmt5tz7jfop1tqh/AABaA2MANndihucz9--8HEIBa?dl=0

**Comment by jwoolston** [comment]
How many triangles do you have in this model? My guess is it is simply a massive detailed model.

**Comment by ToxicBakery** [comment]
That's not rendering time, it is parsing time. Convert your obj to awd format.

**Comment by kubisingh** [comment]
Thank you for replying, yes @jwoolston  it's massive detailed car model. I downloaded and imported/export fm blender according to rajawali standard so no idea about triangles, but sure there are lots of triangles,
Sorry @ToxicBakery , yes it's parsing problem not rendering problem. Thank you i will try awd format. 

But i was thinking saving 3D object (Object3D) in serialized file first time , than i can use that file for next time to skip parsing,  is this right approach and will this work?

**Comment by jwoolston** [comment]
Serialization has been removed from Rajawali in favor of AWD. It is a binary format and has all the benefits of serialized with none of the down sides.

**Comment by kubisingh** [comment]
Yes serialization will not going to help me, becoz it contain too many child objects, i try to convert obj+mtl file to awd by using online AWAY3D tool , but when i am parsing file, it taking to much time , it keep on parsing but didn't showing any object or any error, It may be Away3D AWD file is not correct format, can you give any reference or tools link to convert 3ds or obj(mtl) file to AWD. **(I have no idea about 3D modelling except importing-exporting in blender ).  Thank you in advance.

**Comment by jwoolston** [comment]
I think you would be well served by reducing the complexity of your model

**Comment by jwoolston** [comment]
Closing this issue as resolved/stale.
