### ISSUE TITLE
how to extrude one plane polygon to 3d object?

### ISSUE THREAD

**Issue by liyihongcug** [Rajawali/Rajawali#1754]
how to extrude one 2d plane polygon to 3d object?
For example , I have data
    float vertices[] = { -width, -height, -depth, // 0
                             width, -height, -depth, // 1
                             width,  height, -depth, // 2
                            -width,  height, -depth, // 3}
Now I extrude 2depth and then vertices have changed below:
float height  =(float)0.5;
float depth   =(float)0.5;
       float vertices[] = { -width, -height, -depth, // 0
                             width, -height, -depth, // 1
                             width,  height, -depth, // 2
                            -width,  height, -depth, // 3
                            -width, -height,  depth, // 4
                             width, -height,  depth, // 5
                             width,  height,  depth, // 6
                            -width,  height,  depth, // 7
       };

I want to know how to get   short[] indices = (indexBuffer).
Please notice it is not only data above and in fact polygon's edges  numbers can add.
（tips : Clockwise and counter clockwise）

**Comment by liyihongcug** [comment]
I don't know how to handle with concave polygon  (Clockwise and counter clockwise)
At first,  who can provide  EAR algorithm about concave polygon in android ES 2.0?

**Comment by jwoolston** [comment]
It really is not clear here what you are asking for.

**Comment by liyihongcug** [comment]
Thanks.  solved
