### ISSUE TITLE
What tool to create awd files?

### ISSUE THREAD

**Issue by yiwuxue** [Rajawali/Rajawali#1758]
What tool to create awd files?

**Comment by power7714** [comment]
I still use this to create awd versions of my models:
https://github.com/ToxicBakery/Rajawali-Serializer

**Comment by power7714** [comment]
I downloaded the app from the market. I believe it's still up.

**Comment by ToxicBakery** [comment]
I made the serializer and I would recommend against using it at this point for various reasons.

This is what I used to create all the AWD test files in the examples app and what I used to create test data to validate the AWD loader implementation modules worked as intended.
http://away3d.com/awaybuilder/

**Comment by power7714** [comment]
The serializer app isn't relevant anymore?

**Comment by jwoolston** [comment]
> The serializer app isn't relevant anymore?

No. It was taken off the play store years ago, the classes it uses have been deprecated for years, and as of last week, don't even exist anymore.

**Comment by power7714** [comment]
Gotcha.
