### ISSUE TITLE
How to achieve the effect of glass ？

### ISSUE THREAD

**Issue by yiwuxue** [Rajawali/Rajawali#1763]
How to achieve the effect of glass ? 

Can give me  an example?

**Comment by jwoolston** [comment]
This is an advanced topic in 3D graphics, and far beyond the scope of the Rajawali issues unless you are having trouble with specific details in the engine.

**Comment by power7714** [comment]
I'm working on a glass material for Rajawali users. Keep an eye out on the
G+ community. I'll share it there. 😉

**Comment by jwoolston** [comment]
@power7714 Why not submit a PR for it when you are done?

**Comment by yiwuxue** [comment]
@power7714 Can you give me an address ？

**Comment by power7714** [comment]
Address? What do you mean?

**Comment by yiwuxue** [comment]
“I'm working on a glass material for Rajawali users. Keep an eye out on the
G+ community. I'll share it there. ”

I can't find your share

**Comment by power7714** [comment]
I haven't shared it yet. I'm still working on it but will share it there
once I get it working to my satisfaction.

**Comment by yiwuxue** [comment]
@power7714  ok, thanks
