### ISSUE TITLE
Draw a 3D theta360 with 2 half sphere, screen is black(sometimes one half sphere)

### ISSUE THREAD

**Issue by gedeju** [Rajawali/Rajawali#1765]
#### Rajawali Version or Branch
[rajawali-1.0.325]

#### Device and Android Version
[nexus5/5x android6.0.1]

#### Summary
[draw a 3D theta 360 with 2 half sphere]

#### Steps to Reproduce
```java
private void initSceneForImage() {
            try {
                // one half 
                int\[\] textureIds1 = new int"[1"];
                GLES20.glGenTextures(1, textureIds1, 0);
                GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, textureIds1[0]);

                Bitmap northBitmap = BitmapUtil.loadBitmapScaled(mPathNorth);
                GLUtils.texImage2D(GL10.GL_TEXTURE_2D, 0, northBitmap, 0);
                northBitmap.recycle();

                GLES20.glTexParameterf(GLES20.GL_TEXTURE_2D,
                        GLES20.GL_TEXTURE_MIN_FILTER, GLES20.GL_NEAREST);
                GLES20.glTexParameterf(GLES20.GL_TEXTURE_2D,
                        GLES20.GL_TEXTURE_MAG_FILTER, GLES20.GL_NEAREST);

                mImageNorth = new Texture("jetTexture" + mTextureNameSuffix);
                mImageNorth.setTextureId(textureIds1[0]);
                mNorthSphere = initHalfPicture(mImageNorth);
                getCurrentScene().addChild(mNorthSphere);

                // the other half 
                int[] textureIds2 = new int[1];
                GLES20.glGenTextures(1, textureIds2, 0);
                GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, textureIds2[0]);
                
                Bitmap southBitmap;
                if (TextUtils.isEmpty(mPathSouth)) {
                    southBitmap = BitmapFactory.decodeResource(mContext.getResources(), R.drawable.texture_background);
                } else {
                    southBitmap = BitmapUtil.loadBitmapScaled(mPathSouth);
                }
                GLUtils.texImage2D(GL10.GL_TEXTURE_2D, 0, southBitmap, 0);
                southBitmap.recycle();
                
                GLES20.glTexParameterf(GLES20.GL_TEXTURE_2D,
                        GLES20.GL_TEXTURE_MIN_FILTER, GLES20.GL_NEAREST);
                GLES20.glTexParameterf(GLES20.GL_TEXTURE_2D,
                        GLES20.GL_TEXTURE_MAG_FILTER, GLES20.GL_NEAREST);

                mImageSouth = new Texture("southTexture" + mTextureNameSuffix);
                mImageSouth.setTextureId(textureIds2[0]);
                mSouthSphere = initHalfPicture(mImageSouth);
                setRotationAngle(mRotationAngle);
                getCurrentScene().addChild(mSouthSphere);
            } catch (Exception e) {
                Log.e(TAG, "Error:" + e.getMessage());
            }
        }
```

#### Trace or Log Output
```
java.lang.IllegalArgumentException: string == null
W/System.err:     at android.opengl.GLES20.glShaderSource(Native Method)
W/System.err:     at org.rajawali3d.materials.Material.loadShader(Material.java:732)
W/System.err:     at org.rajawali3d.materials.Material.createProgram(Material.java:757)
W/System.err:     at org.rajawali3d.materials.Material.createShaders(Material.java:680)
W/System.err:     at org.rajawali3d.materials.Material.reload(Material.java:488)
W/System.err:     at org.rajawali3d.materials.MaterialManager.taskReload(MaterialManager.java:72)
W/System.err:     at org.rajawali3d.renderer.RajawaliRenderer.onRenderSurfaceSizeChanged(RajawaliRenderer.java:363)
W/System.err:     at xxxxxxxx$xxxRenderer.onRenderSurfaceSizeChanged(xxxxViewer.java:)
W/System.err:     at org.rajawali3d.surface.RajawaliTextureView$GLThread.guardedRun(RajawaliTextureView.java:1266)
W/System.err:     at org.rajawali3d.surface.RajawaliTextureView$GLThread.run(RajawaliTextureView.java:997)
```

**Comment by gedeju** [comment]
<img width="348" alt="111" src="https://cloud.githubusercontent.com/assets/12440740/18302979/55599b8c-750d-11e6-8d64-e8bf9a742869.png">

**Comment by gedeju** [comment]
like the pic above.

**Comment by jwoolston** [comment]
Looks like the shader string was null when trying to recreate the context. When in the application life cycle does this happen? Some sort of Android event must have happened like returning from sleep.

**Comment by gedeju** [comment]
it happened the first time when I drew the screen.

**Comment by jwoolston** [comment]
How are you creating your material?

**Comment by gedeju** [comment]
here is the code of creating material. thank you.
----------------------------------------
       private HalfSphere initHalfPicture(Texture texture) {
            try {
                Material material = new Material();
                material.enableLighting(true);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.addTexture(texture);
                material.setColorInfluence(0);

                HalfSphere sphere = new HalfSphere(mRadius, mSphereW, mSphereH, true, false, false, true, true);
                sphere.setMaterial(material);
                sphere.setPosition(0, 0, 0); 
                sphere.setScaleX(-1.0f);   
                return sphere;
            } catch (ATexture.TextureException e) {
                Log.e(TAG, "Error:" + e.getMessage());
            }
            return null;
        }

**Comment by jwoolston** [comment]
The way you are creating your textures is taking Rajawali out of the loop. I strongly suspect that by managing them yourself, you have made it so Rajawali has some invalid value. Try replacing your texture generation code with the Rajawali method so that it is able to properly manage things.

**Comment by gedeju** [comment]
i found that o lots of custom Texture Classes in Rajawali.
can tell me which Rajawali method and how to use.
or which code i can reference.

**Comment by jwoolston** [comment]
Since they appear to be simple diffuse textures, you want the `Texture` class. The basic getting started example shows you how to use it. You can also see the tutorial [here](https://github.com/Rajawali/Rajawali/wiki/Materials) for more details.

**Comment by gedeju** [comment]
i cannot solve my problem but thank you for your support.
