### ISSUE TITLE
Plane object fit to text bitmap

### ISSUE THREAD

**Issue by Angie-Ie** [Rajawali/Rajawali#1775]
I am trying to create a plane object to which I am setting canvas text to it. 
how to draw a plane which would fit the text width and height? 

Thanks you :)

**Comment by jwoolston** [comment]
There is a fair bit of math involved here. What projection are you using? Is it 2D or 3D? Does the place stay at a fixed distance? Is it always orthogonal to the camera?

**Comment by Angie-Ie** [comment]
Hi, thanks for your response. So I have switch button to change projection into 2D or 3D. Plane can change position in x,y  when in 2D projection and change position in x,y,z when in 3D projection.

Thank you :)

**Comment by jwoolston** [comment]
In 3D, this really has no meaning as world is supposed to be free to have its own independent dimensions that get projected to screen space. If you wish to force this behavior, you need to use the inverse of the projection matrix to determine the dimensions given a desired position in space. You would "unproject" the four corners of the screen into a ray of whatever length you want (where the ray intersects the corresponding corner of your plane). In this case you would need to pick a ray length to calculate the x/y/z coordinates. You will end up with a system of equations you will need to solve. 

In the case of 2D, you can simply use a screen quad like the 2D renderer example or how the FBO effects work.

**Comment by bobm3** [comment]
Here's a class for creating a single line text object with a rounded rectangle background that fits the text.
The setWidth() and setHeight() methods maintain aspect ratio when resizing.

`public class Text  extends Object3D {
    
    @Nullable protected Surface mSurface;
    protected String mTextureName;
    protected StreamingTexture mTexture = null;
    protected final int mPixelWidth;
    protected final int mPixelHeight;
    private final float mWidth;
    private final float mHeight;
    protected int mBackgroundColor = 0x66000000;
    protected int mTextColor = Color.WHITE;
    protected float mPadding;
    protected CharSequence mText;
    protected TextPaint mTextPaint;
    private Paint mBackgroundPaint;
    private RectF mBackgroundRect;
    private volatile boolean mShouldReDraw = true;

    public Text(CharSequence text, float textSizePixels) {
        mText = text;
        mBackgroundPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
        mBackgroundRect = new RectF();
        mTextPaint = new TextPaint(Paint.ANTI_ALIAS_FLAG);
        mTextPaint.setTextSize(textSizePixels);
        mPadding = textSizePixels * 0.25f;
        mPixelWidth = (int) (mTextPaint.measureText(text.toString()) + mPadding * 2f);
        mPixelHeight = (int) (mTextPaint.descent() - mTextPaint.ascent() + mPadding * 2f);
        // width is dependent on the length of the text, scale uniformly to required size
        // there are get and set methods for plane size that maintain aspect ratio
        mHeight = 1f;
        mWidth = (float) mPixelWidth / mPixelHeight * mHeight;
        setupPlane();
        setUpMaterial();
    }

    //create plane 
    private void setupPlane() {
        int i, j;
        int segmentsW = 1;
        int segmentsH = 1;
        int numVertices = (segmentsW + 1) * (segmentsH + 1);
        float[] vertices = new float[numVertices * 3];
        float[] textureCoords = new float[numVertices * 2];
        float[] normals = new float[numVertices * 3];
        int[] indices = new int[6];
        int vertexCount = 0;
        int texCoordCount = 0;

        for (i = 0; i <= segmentsW; i++) {
            for (j = 0; j <= segmentsH; j++) {
                float v1 = ((float) i / (float) segmentsW - 0.5f) * mWidth;
                float v2 = ((float) j / (float) segmentsH - 0.5f) * mHeight;
                vertices[vertexCount] = v1;
                vertices[vertexCount + 1] = v2;
                vertices[vertexCount + 2] = 0;

                float u = (float) i / (float) segmentsW;
                textureCoords[texCoordCount++] = u;
                float v = (float) j / (float) segmentsH;
                textureCoords[texCoordCount++] = (1.0f - v);

                normals[vertexCount] = 0;
                normals[vertexCount + 1] = 0;
                normals[vertexCount + 2] = 1;

                vertexCount += 3;
            }
        }

        int colspan = segmentsH + 1;
        int indexCount = 0;

        for (int col = 0; col < segmentsW; col++) {
            for (int row = 0; row < segmentsH; row++) {
                int ul = col * colspan + row;
                int ll = ul + 1;
                int ur = (col + 1) * colspan + row;
                int lr = ur + 1;
                indices[indexCount++] = ur;
                indices[indexCount++] = lr;
                indices[indexCount++] = ul;

                indices[indexCount++] = lr;
                indices[indexCount++] = ll;
                indices[indexCount++] = ul;
            }
        }

        setData(vertices, normals, textureCoords, null, indices, true);

        vertices = null;
        normals = null;
        textureCoords = null;
        indices = null;
    }

    //create a surface texture to fit the text
    private void setUpMaterial() {
        mTextureName = "tex" + (int) (Math.random() * 10000);
        setTransparent(true);
        setDoubleSided(true);
        Material material = new Material();
        material.setColorInfluence(0);
        material.enableLighting(false);
        try {
            mTexture = new StreamingTexture(mTextureName, new StreamingTexture.ISurfaceListener() {
                @Override
                public void setSurface(Surface surface) {
                    mTexture.getSurfaceTexture().setDefaultBufferSize(mPixelWidth, mPixelHeight);
                    mSurface = surface;
                    invalidate();
                }
            });
            mTexture.setMipmap(false);
            mTexture.setFilterType(ATexture.FilterType.LINEAR);
            material.addTexture(mTexture);
        } catch (ATexture.TextureException e) {
            e.printStackTrace();
        }
        setMaterial(material);
    }

    public void invalidate() {
        mShouldReDraw = true;
    }

    @Override
    protected void preRender() {
        super.preRender();
        if (mShouldReDraw) {
            updateTexture();
            mShouldReDraw = false;
        }
    }

    public void draw(Canvas canvas){
        mTextPaint.setColor(mTextColor);
        mBackgroundPaint.setColor(mBackgroundColor);
        mBackgroundRect.set(0, 0, mPixelWidth, mPixelHeight);
        final float cornerRadius = mPadding;
        canvas.drawRoundRect(mBackgroundRect, cornerRadius, cornerRadius, mBackgroundPaint);
        canvas.drawText(mText.toString(), mPadding, mPadding - mTextPaint.ascent(), mTextPaint);
    }

    protected boolean updateTexture() {
        try {
            if (mSurface != null && mSurface.isValid()) {
                final Canvas canvas = mSurface.lockCanvas(null);
                canvas.drawColor(mBackgroundColor, PorterDuff.Mode.CLEAR);
                draw(canvas);
                mSurface.unlockCanvasAndPost(canvas);
                mTexture.update();
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    // release in onRenderSurfaceDestroyed()
    public void dispose() {
        if (mSurface != null) mSurface.release();
    }

    public void setHeight(float height) {
        setScale(height);
    }

    public void setWidth(float width) {
        setScale(mHeight / mWidth * width);
    }

    public float getWidth() {
        return (float) (mWidth * getScaleX());
    }

    public float getHeight() {
        return (float) (mHeight * getScaleY());
    }

    public int getBackgroundColor() {
        return mBackgroundColor;
    }

    public void setBackgroundColor(int backgroundColor) {
        mBackgroundColor = backgroundColor;
        invalidate();
    }

    public int getTextColor() {
        return mTextColor;
    }

    public void setTextColor(int textColor) {
        mTextColor = textColor;
    }
}`

**Comment by jwoolston** [comment]
Closing as resolved/stale. We can re-open if you still have questions.
