### ISSUE TITLE
Error when using vertex colors

### ISSUE THREAD

**Issue by bobamason** [Rajawali/Rajawali#1781]
#### Rajawali Version or Branch

current master branch
#### Device and Android Version

all devices
#### Summary

line 869 of Geometry3D.java

``` java
public void setColors(float[] colors) {
    setTextureCoords(colors, false);  // error
}
```

should be changed to ->`setColors(colors, false);`
#### Steps to Reproduce

[Describe reproducable steps and sample code]
#### Trace or Log Output

[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by contriteobserver** [comment]
This was fixed as part of #1810, for details see pull request #1811
