### ISSUE TITLE
Object Picking is not work on SKeletalAnimation? 

### ISSUE THREAD

**Issue by B-Rabbit** [Rajawali/Rajawali#1782]
ObjectPickingFragment is work . model is AWD. but I use MD5 model in SkeletalAnimationFragment,and add OnObjectPickedListener ,it don't work.
ObjectColorPicker is not support SkeletalAnimation?please help me .

**Comment by jwoolston** [comment]
This is due to the registered object being the parent container which does not render to screen. You will need to register the specific children you are interested in.
