### ISSUE TITLE
Render Text without Texture and Bitmap

### ISSUE THREAD

**Issue by wolfbigbig** [Rajawali/Rajawali#1783]
Hi, all.
I am trying to implement **rendering text**. I know that the usual method is converting the text to **Texture** and then through the  **Bitmap** to draw, but this will cause the project is **relatively huge**. I would like to do a **lightweight application**, I want ask if we can directly achieve text rendering rather than **Texture** and **Bitmap**? 
If so, what should I do? Do you have any suggestions?
Thank you!

**Comment by androidcx** [comment]
I want this function too!

**Comment by jwoolston** [comment]
There are libraries out there which use a set of glyphs in a texture atlas to render arbitrary text. Doing this requires handling of kerning and line wrapping, etc. We have always suggested using a Bitmap backed canvas in Android as all this is built in already.

**Comment by wolfbigbig** [comment]
@jwoolston Thanks for your reply. 
What are the appropriate libraries recommendations? Will Rajawali support friendly to these libraries?
Thank you!

**Comment by jwoolston** [comment]
I don't currently know of any that are android compatible. If you find one, let us know.

**Comment by wolfbigbig** [comment]
Of course!
Thank you again.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
