### ISSUE TITLE
Unable to import .obj file

### ISSUE THREAD

**Issue by ParagRKadam** [Rajawali/Rajawali#1788]
I am trying to import .obj file in my project and for that I am following [this](https://github.com/Rajawali/RajawaliExamples/blob/v0.9/src/com/monyetmabuk/rajawali/tutorials/RajawaliLoadModelRenderer.java) tutorial but many of the classes cannot be resolved like BaseObject3D,ObjParser etc as they are not present in the the library. I am adding compile 'org.rajawali3d:rajawali:1.0.325@aar' dependency in my gradle (is this the right dependency required?).
So my question is whether the tutorial available [here](https://github.com/Rajawali/Rajawali/wiki/Tutorial-17-Importing-.Obj-Files) is still relevent or not? If it is not relevant than what is the right way of importing .obj file ? Thanks.

**Comment by power7714** [comment]
LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(),
			mTextureManager, R.raw.multiobjects_obj);
	        try {
		        objParser.parse();
		        mObjectGroup = objParser.getParsedObject();
		        getCurrentScene().addChild(mObjectGroup);

	        } catch (ParsingException e) {
		        e.printStackTrace();
	        }

Taken from the RajawaliExample LoadModelFragment.class [here.](https://github.com/Rajawali/RajawaliExamples/blob/master/examples/src/main/java/com/monyetmabuk/rajawali/tutorials/examples/loaders/LoadModelFragment.java)

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
