### ISSUE TITLE
how to stop current model parsing, load another.

### ISSUE THREAD

**Issue by Owen-Hw** [Rajawali/Rajawali#1792]
1、the model is loading, then I click the back menu, how can i stop to loading it .

2、When switching multiple models, how to stop loading a model, there is a way to load all the first, and then through the control is visible to show, but this method is too long for the first time to load. I want to achieve click on the model to load which model, to stop the other models of the load.

**Comment by jwoolston** [comment]
Im not aware of any mechanism for this.
