### ISSUE TITLE
Load collada in Rajawali

### ISSUE THREAD

**Issue by Angie-Ie** [Rajawali/Rajawali#1803]
Hi, I would like to know what kind of 3d objects can load in Rajawali? Can Rajawali load DAE? I already use Rajawali to load obj using LoaderObj but I can't find LoaderDae in rajawali. 
Thank you

**Comment by jwoolston** [comment]
It is not currently supported, but I am hoping to add it one day.

**Comment by geosky** [comment]
Why close this issue? has the feature requested been added?
