### ISSUE TITLE
ObjectColorPicker unregistering problem

### ISSUE THREAD

**Issue by lkieliger** [Rajawali/Rajawali#1804]
#### Rajawali Version or Branch
1.1.610

#### Summary
Color picking fails to detect object after a call to the unregisterObject method.

#### Steps to Reproduce

1. Add a sphere to the scene
2. Register it with an ObjectColorPicker
3. Unregister it
4. Register it, picking doesn't work anymore

#### Example code

The following illustrates the bugg:

```
        Material m = new Material();
        Sphere testSphere = new Sphere(10,8,8);
        testSphere.setPosition(new Vector3(50,0,0));
        m.setColor(150);
        m.enableLighting(false);

        getCurrentScene().addChild(testSphere);
        testSphere.setMaterial(m);

        mPicker.registerObject(testSphere);
        mPicker.unregisterObject(testSphere);
        mPicker.registerObject(testSphere);
```

The sphere remains undetected in the above case. However, adding the line: `testSphere.setPickingColor(0);` after the second call to the register method solves the problem.

I've experienced the issue primarily when unregistering objects, then destroying them, then adding new ones. Even the new ones wouldn't be picked by the ObjectColorPicker so that might indicate a deeper problem.

What bothers me is that in the implementation of the ColorPicker the picking index is always incremented upon registration but never decremented. I've manually kept track of the picking index, decrementing it when needed and that solved the problem for me. But I can't explain actually why decrementing the index fixed the problem. Maybe some side effects ?

**Comment by jwoolston** [comment]
This would be a good one for @rpicolet

**Comment by rpicolet** [comment]
@lkieliger I modified the Rajawali `ObjectPicking` example to unregister/re-register the first monkey within `initScene()` and did not see the problem. Could you provide more information about the context of your `registerObject()` and `unregisterObject()` calls (which thread, relative timings, within a Rajawali initScene/callback, etc.) or - ideally - an executable test case that shows the problem?

FYI, `mColorIndex` is used both as the actual rendered color by the color-picking algorithm, as well as the index into the list of registered objects for mapping back from the selected pixel's color to the picked object; the field could also be named `mNextColorIndex`. Unregistering an object simply nulls out the corresponding location in the list of registered objects, which leaves a hole in the list as we don't currently attempt to re-use colors, and so never decrement mColorIndex. The "fixes" you see by manually changing the index/setting picking colors are purely coincidental, and should not be a normal part of your code, or in the test case.

**Comment by lkieliger** [comment]
I didn't manage to reproduce the problem using the example code, even by making the contents of `initScene()` and `onObjectPicked` virtually identical. (Using the simple example of a single sphere)

I'll try to investigate this on my side and keep you updated if I find anything. It might take a while since I'm a bit short of time

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
