### ISSUE TITLE
Cylinder does not shows set Color while rotating

### ISSUE THREAD

**Issue by protocol10** [Rajawali/Rajawali#1806]
I created Cylinder and tried to rotate using `RotateAnimation3D` it rotates well but it does not shows or I should say it becomes transparent when it comes to 90 degrees.

**Comment by kmare** [comment]
You should provide more info. Like Rajawali version, android version, device model, etc.

**Comment by protocol10** [comment]
I am using  following version 
compile 'org.rajawali3d:rajawali:1.0.325@aar'

Following is the code
`

 PointLight mLight = new PointLight();
                mLight.setPosition(-2, 1, -4);
                mLight.setPower(3.5f);
                getCurrentCamera().setPosition(0, 0, -14);
                getCurrentCamera().setLookAt(0, 0, 0);
                Object3D monkey = new Cylinder(0.3f, 2f, 10, 40);

                Material material = new Material();
                material.enableLighting(true);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                monkey.setMaterial(material);
                monkey.setColor(Color.RED);
            monkey.rotate(Vector3.Axis.Y, 180.0);
                getCurrentScene().setBackgroundColor(Color.WHITE);
                getCurrentScene().addLight(mLight);
                getCurrentScene().addChild(monkey);
`

**Comment by protocol10** [comment]
![screenshot_20161110-101351](https://cloud.githubusercontent.com/assets/6994466/20164916/d0d760b6-a72e-11e6-8843-af9e9596f705.png)

This is the above view how it looks I need a solid cylinder not a hollow. Please help

**Comment by jwoolston** [comment]
This is a bit of a shot in the dark but could you try adding `monkey.setDoubleSided(true)` and let me know what happens. Also, what device is this on?

**Comment by protocol10** [comment]
Yeah I have added `setDoubleSided(true)` but it doesn't work, doe setting vertex colors will work, I was not able to find any example how do we ideally set vertex colors for Cylinder, the above issue only appears for Cylinder  rest other shapes work fine

**Comment by jwoolston** [comment]
@protocol10 Can you please confirm the make and model of the device this is on?

**Comment by protocol10** [comment]
'Device - MOTOG(3rd Generation)'
OS - 6.0.1
Serial Number -  ZY2228MBC7

**Comment by jwoolston** [comment]
Please email me the APK you are producing. I want to check this on a few devices but I am neck deep in Rajawali 2.0 and would prefer not checkout a new repo (1.0.x was before unifying the examples and core library into one project)

**Comment by protocol10** [comment]
By the way I was able to reproduce it '1.35' and the latest i.e '1.1.668`

**Comment by jwoolston** [comment]
> By the way I was able to reproduce it '1.35' and the latest i.e '1.1.668`

That is useful information, and supports my theory. I take it you have 1.1.668 checked out? If so, go here: https://github.com/Rajawali/Rajawali/blob/v1.1.668/rajawali/src/main/java/org/rajawali3d/materials/shaders/VertexShader.java#L93 and change `Precision.MEDIUMP` to `Precision.HIGHP` and see what happens.

**Comment by protocol10** [comment]
APK 
https://cloudup.com/cFiu-FY2j5r

**Comment by protocol10** [comment]
@jwoolston  It doesn''t worked I just changed the `VertexShader` as you had suggested it does not have any effect

**Comment by jwoolston** [comment]
@protocol10 Ok, I am taking a look at the apk now and will let you know if I have any more revelations.

**Comment by jwoolston** [comment]
So looking at the Cylinder code closer, I am fairly certain it simply doesn't close the ends. @Ifrohman could confirm as he is the original author of that class, but I think the most straightforward fix would be to add triangles for the ends.

**Comment by protocol10** [comment]
@jwoolston How can we add traingles can you please provide the sample code

**Comment by jwoolston** [comment]
i will have to pick through the code to find the best position to insert those triangles after confirming it is necessary. Im going to spend the rest of the evening with my family tonight so I will take a look at it in the morning. If you wish to look in the meantime, it will be in the `init()` method of the `Cylinder` class.

**Comment by ToxicBakery** [comment]
Examples exist for this

http://cboard.cprogramming.com/game-programming/133658-opengl-draw-cylinder-yourself.html

**Comment by jwoolston** [comment]
Until I get around to fixing this, I recommend using the `NPrism` class. Simply specify the number of sides you want as if they were the number of circular segments in the `Cylinder` class.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.

**Comment by matheusbarcellos** [comment]
I solved this problem using the following:

`mCylinder[i].setDoubleSided(true);
 mCylinder[i].setDrawingMode(GLES20.GL_TRIANGLE_FAN);`
