### ISSUE TITLE
onRender() callback stop being called after a while

### ISSUE THREAD

**Issue by minhkhiem** [Rajawali/Rajawali#1807]
#### Rajawali Version or Branch
Latest master

#### Device and Android Version
Google Nexus 5

#### Summary
I used Rajawali to render a panoramic image. At the first time, the texture is loaded successfully. But if I close the activity and reopen it again, Rajawali will show black screen.

Here is the code:

```
// initScene()
protected void initScene() {
        // This is the temporary texture. Real texture will be loaded through texture 
        // update after Picasso finishes download task
        mTexture = new Texture(TEXTURE_NAME, R.drawable.white);
        //mTexture.shouldRecycle(true);

        mSphereObject = new Sphere(50, 64, 32);
        mSphereObject.setScaleX(-1);

        Material material = new Material();
        material.setColor(0);
        try {
            material.addTexture(mTexture);
        } catch (ATexture.TextureException e) {
            e.printStackTrace();
        }
        mSphereObject.setMaterial(material);
        mSphereObject.setPosition(0, 0, 1);
        getCurrentScene().addChild(mSphereObject);

        getCurrentCamera().setPosition(0, 0, .5);
        getCurrentCamera().setFieldOfView(100);

        mIsInitialized = true;

        if (mListener != null) {
            mListener.onInitialized();
        }
    }

// onRender()
protected void onRender(long ellapsedRealtime, double deltaTime) {
    super.onRender(ellapsedRealtime, deltaTime);

    // Update the view with orientation data from sensor
    Quaternion q = mSensor.getOrientation();
    getCurrentCamera().setOrientation(q);
    Log.d("", String.format("x: %.1f; y: %.1f; z: %.1f", q.x, q.y, q.z));
}
```

Having observed onRender() callback through above Log.d line, I noticed that this callback will not be called anymore after a period of time. Then the surface will ended up showing black screen if it's need to be redrawn like: activity pause/resume or new orientation data is coming from the sensor.

#### Trace or Log Output
Here I attach full rajawali log for 2 texture loading times:

**The first texture load:**

I/Rajawali: Rajawali | Bombshell | v1.1.610 Release 
I/Rajawali: This is a stable release.
I/RajawaliGLThread: noticed surfaceView surface lost tid=4987
I/RajawaliGLThread: noticed surfaceView surface acquired tid=4987
I/RajawaliGLThread: noticing that we want render notification tid=4987
W/RajawaliGLThread: egl createSurface
W/RajawaliGLThreadManager: checkGLESVersion mGLESVersion = 3 mMultipleGLESContextsAllowed = false
W/RajawaliGLThreadManager: checkGLDriver renderer = "Adreno (TM) 330" multipleContextsAllowed = true mLimitedGLESContexts = false
D/Rajawali: startRendering()
D/Rajawali: Material is being added.
D/Rajawali: -=-=-=- VERTEX SHADER -=-=-=-
D/Rajawali: precision mediump float;
            uniform mat4 uMVPMatrix;
            uniform vec4 uColor;
            uniform mat4 uModelMatrix;
            uniform mat3 uNormalMatrix;
            uniform mat4 uModelViewMatrix;
            attribute vec3 aNormal;
            attribute vec2 aTextureCoord;
            attribute vec4 aPosition;
            varying vec3 vNormal;
            varying vec4 vColor;
            varying vec2 vTextureCoord;
            varying vec3 vEyeDir;
            vec4 gColor;
            vec4 gPosition;
            vec3 gNormal;
            vec2 gTextureCoord;
            
            void main() {
            gPosition = aPosition;
            gNormal = aNormal;
            gTextureCoord = aTextureCoord;
            gColor = uColor;
            gl_Position = uMVPMatrix * gPosition;
            vNormal = normalize(uNormalMatrix * gNormal);
            vTextureCoord = gTextureCoord;
            vColor = gColor;
            vEyeDir = vec3(uModelViewMatrix * gPosition);
            }
D/Rajawali: -=-=-=- FRAGMENT SHADER -=-=-=-
D/Rajawali: precision mediump float;
            uniform vec2 uRepeat0;
            uniform sampler2D photo;
            uniform float uInfluencephoto;
            uniform float uColorInfluence;
            varying vec3 vNormal;
            varying vec4 vColor;
            varying vec2 vTextureCoord;
            varying vec3 vEyeDir;
            float gShadowValue;
            float gSpecularValue;
            vec4 gColor;
            vec3 gNormal;
            vec2 gTextureCoord;
            
            void main() {
            gNormal = normalize(vNormal);
            gTextureCoord = vTextureCoord;
            gColor = uColorInfluence * vColor;
            gShadowValue = 0.0;
            gSpecularValue = 1.0;
            gTextureCoord *= uRepeat0;
            vec4 texColor = texture2D(photo, gTextureCoord);
            texColor *= uInfluencephoto;
            gColor += texColor;
            gl_FragColor = gColor;
            }
E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
E/Rajawali: Getting location of uniform: uTime returned -1!
I/RajawaliGLThread: sending render notification tid=4987
D/Rajawali: -=-=-=- VERTEX SHADER -=-=-=-
D/Rajawali: precision mediump float;
            uniform mat4 uMVPMatrix;
            uniform vec4 uColor;
            uniform mat4 uModelMatrix;
            uniform mat3 uNormalMatrix;
            uniform mat4 uModelViewMatrix;
            attribute vec3 aNormal;
            attribute vec2 aTextureCoord;
            attribute vec4 aPosition;
            varying vec3 vNormal;
            varying vec4 vColor;
            varying vec2 vTextureCoord;
            varying vec3 vEyeDir;
            vec4 gColor;
            vec4 gPosition;
            vec3 gNormal;
            vec2 gTextureCoord;
            
            void main() {
            gPosition = aPosition;
            gNormal = aNormal;
            gTextureCoord = aTextureCoord;
            gColor = uColor;
            gl_Position = uMVPMatrix * gPosition;
            vNormal = normalize(uNormalMatrix * gNormal);
            vTextureCoord = gTextureCoord;
            vColor = gColor;
            vEyeDir = vec3(uModelViewMatrix * gPosition);
            }
D/Rajawali: -=-=-=- FRAGMENT SHADER -=-=-=-
D/Rajawali: precision mediump float;
            uniform vec2 uRepeat0;
            uniform sampler2D photo;
            uniform float uInfluencephoto;
            uniform float uColorInfluence;
            varying vec3 vNormal;
            varying vec4 vColor;
            varying vec2 vTextureCoord;
            varying vec3 vEyeDir;
            float gShadowValue;
            float gSpecularValue;
            vec4 gColor;
            vec3 gNormal;
            vec2 gTextureCoord;
            
            void main() {
            gNormal = normalize(vNormal);
            gTextureCoord = vTextureCoord;
            gColor = uColorInfluence * vColor;
            gShadowValue = 0.0;
            gSpecularValue = 1.0;
            gTextureCoord *= uRepeat0;
            vec4 texColor = texture2D(photo, gTextureCoord);
            texColor *= uInfluencephoto;
            gColor += texColor;
            gl_FragColor = gColor;
            }
E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
E/Rajawali: Getting location of uniform: uTime returned -1!

**The second texture load:**

I/Rajawali: Rajawali | Bombshell | v1.1.610 Release 
I/Rajawali: This is a stable release.
I/RajawaliGLThread: noticed surfaceView surface lost tid=4991
I/RajawaliGLThread: noticed surfaceView surface acquired tid=4991
I/RajawaliGLThread: noticing that we want render notification tid=4991
W/RajawaliGLThread: egl createSurface
D/Rajawali: Open GL ES Version String: OpenGL ES 3.0 V@127.0 AU@  (GIT@I96aee987eb)
D/Rajawali: Derived GL ES Version: 3.0
D/Rajawali: startRendering()
D/Rajawali: Material is being added.
D/Rajawali: -=-=-=- VERTEX SHADER -=-=-=-
D/Rajawali: precision mediump float;
            uniform mat4 uMVPMatrix;
            uniform vec4 uColor;
            uniform mat4 uModelMatrix;
            uniform mat3 uNormalMatrix;
            uniform mat4 uModelViewMatrix;
            attribute vec3 aNormal;
            attribute vec2 aTextureCoord;
            attribute vec4 aPosition;
            varying vec3 vNormal;
            varying vec4 vColor;
            varying vec2 vTextureCoord;
            varying vec3 vEyeDir;
            vec4 gColor;
            vec4 gPosition;
            vec3 gNormal;
            vec2 gTextureCoord;
            
            void main() {
            gPosition = aPosition;
            gNormal = aNormal;
            gTextureCoord = aTextureCoord;
            gColor = uColor;
            gl_Position = uMVPMatrix * gPosition;
            vNormal = normalize(uNormalMatrix * gNormal);
            vTextureCoord = gTextureCoord;
            vColor = gColor;
            vEyeDir = vec3(uModelViewMatrix * gPosition);
            }
D/Rajawali: -=-=-=- FRAGMENT SHADER -=-=-=-
D/Rajawali: precision mediump float;
            uniform vec2 uRepeat0;
            uniform sampler2D photo;
            uniform float uInfluencephoto;
            uniform float uColorInfluence;
            varying vec3 vNormal;
            varying vec4 vColor;
            varying vec2 vTextureCoord;
            varying vec3 vEyeDir;
            float gShadowValue;
            float gSpecularValue;
            vec4 gColor;
            vec3 gNormal;
            vec2 gTextureCoord;
            
            void main() {
            gNormal = normalize(vNormal);
            gTextureCoord = vTextureCoord;
            gColor = uColorInfluence * vColor;
            gShadowValue = 0.0;
            gSpecularValue = 1.0;
            gTextureCoord *= uRepeat0;
            vec4 texColor = texture2D(photo, gTextureCoord);
            texColor *= uInfluencephoto;
            gColor += texColor;
            gl_FragColor = gColor;
            }
E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
E/Rajawali: Getting location of uniform: uTime returned -1!
I/RajawaliGLThread: sending render notification tid=4991
D/Rajawali: -=-=-=- VERTEX SHADER -=-=-=-
D/Rajawali: precision mediump float;
            uniform mat4 uMVPMatrix;
            uniform vec4 uColor;
            uniform mat4 uModelMatrix;
            uniform mat3 uNormalMatrix;
            uniform mat4 uModelViewMatrix;
            attribute vec3 aNormal;
            attribute vec2 aTextureCoord;
            attribute vec4 aPosition;
            varying vec3 vNormal;
            varying vec4 vColor;
            varying vec2 vTextureCoord;
            varying vec3 vEyeDir;
            vec4 gColor;
            vec4 gPosition;
            vec3 gNormal;
            vec2 gTextureCoord;
            
            void main() {
            gPosition = aPosition;
            gNormal = aNormal;
            gTextureCoord = aTextureCoord;
            gColor = uColor;
            gl_Position = uMVPMatrix * gPosition;
            vNormal = normalize(uNormalMatrix * gNormal);
            vTextureCoord = gTextureCoord;
            vColor = gColor;
            vEyeDir = vec3(uModelViewMatrix * gPosition);
            }
D/Rajawali: -=-=-=- FRAGMENT SHADER -=-=-=-
D/Rajawali: precision mediump float;
            uniform vec2 uRepeat0;
            uniform sampler2D photo;
            uniform float uInfluencephoto;
            uniform float uColorInfluence;
            varying vec3 vNormal;
            varying vec4 vColor;
            varying vec2 vTextureCoord;
            varying vec3 vEyeDir;
            float gShadowValue;
            float gSpecularValue;
            vec4 gColor;
            vec3 gNormal;
            vec2 gTextureCoord;
            
            void main() {
            gNormal = normalize(vNormal);
            gTextureCoord = vTextureCoord;
            gColor = uColorInfluence * vColor;
            gShadowValue = 0.0;
            gSpecularValue = 1.0;
            gTextureCoord *= uRepeat0;
            vec4 texColor = texture2D(photo, gTextureCoord);
            texColor *= uInfluencephoto;
            gColor += texColor;
            gl_FragColor = gColor;
            }
E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
E/Rajawali: Getting location of uniform: uTime returned -1!

**Comment by minhkhiem** [comment]
False alarm. The renderer has been messed up because of the google vrtoolkit which is the one reported invalid head track data. However, I still getting confused with the onRender() callback. Why does it stop being called somehow?

**Comment by jwoolston** [comment]
One possibility is the view lifecycle events are not being properly passed through, resulting in the renderer failing to resume when it comes back into focus.
