### ISSUE TITLE
TextureView's onPause() doesn't get called when press power button to lock phone screen

### ISSUE THREAD

**Issue by minhkhiem** [Rajawali/Rajawali#1808]
#### Rajawali Version or Branch
Latest master

#### Device and Android Version
Android 4.4.2

#### Summary
TextureView's onPause() method never get called when user press power button to lock the phone. Hence, after the phone is being unlocked, rajawali renderer surface seems to be locked, no further rendering is able to be observed anymore.

In contrast, pressing home button to send the app to background doesn't affected.

#### Log

The following log is observed if send app to background by Home button & wake it up from recent list:
```
I/RajawaliGLThread: releasing EGL surface because paused tid=2383
I/RajawaliGLThread: releasing EGL context because paused tid=2383
D/dalvikvm: GC_CONCURRENT freed 15395K, 53% free 42870K/89763K, paused 20ms+25ms, total 206ms
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
W/RajawaliGLThread: egl createSurface
```

But if I press the power button, nothing is getting printed to the log console.

**Comment by jwoolston** [comment]
Take a look at how the view life cycle works in the examples as they operate correctly under this situation.

**Comment by minhkhiem** [comment]
Ok. Then is there any way in Rajawali framework which allows to recreate the whole renderer & render surface? I tried to call onRenderSurfaceDestroyed, then create Renderer again. But it seems this is not the correct approach, since the initScene is called once in onCreate only.

**Comment by jwoolston** [comment]
Rajawali in its current incarnation is not meant to let you have that kind of control. Specifically, as it is setup right now you can set a renderer on the surface once and that's it. You would need to have android create a new surface (either in XML or programmatically) if you wish to use a different renderer. The version currently under development seeks to address this issue.

**Comment by minhkhiem** [comment]
Make sense. Thank you very much for your support.
