### ISSUE TITLE
Re-add support for short buffers.

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#1816]
#### Rajawali Version or Branch
v2.0 Camden Hells

#### Device and Android Version
Samsung SGH-T869 Mali-400MP GPU Android 4.0.4

#### Summary
This device does not contain the `GL_OES_element_index_uint` extension and therefore cannot use UINT buffers. I removed these previously thinking it was ubiquitous but I have found a reasonably recent device that does not support it.

**Comment by jjv360** [comment]
I'm experiencing this as well on a Vodafone VF695...

**Comment by jwoolston** [comment]
This was resolved via 04a03a811c03fda2c7a0d33bf4a738304115b708
