### ISSUE TITLE
Increse distance between two objects

### ISSUE THREAD

**Issue by lorenzo-gangemi** [Rajawali/Rajawali#1820]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.777@aar

Hello to everybody!

I'd like to figure out how to increse the distance between a two objects or between one object and a point in the scene. 

It would help me resolving a lot of animation issuses caused by the use of traslateAnimation3D while all the objects in the scene are rotating around the center.

**Comment by rpicolet** [comment]
If I get the gist of the issue, you should be aware that animations operate on local coordinates, i.e. relative to their containing object. To animate an increase in distance while rotating, try introducing a container object for the translating object(s), rotate that container (or its container), then the translation itself will also rotate. Hope this helps.

**Comment by lorenzo-gangemi** [comment]
Thanks a lot, i've just tryed and it works fine.
My other solution would be to rotate the camera instead of rotating all the objets, but it was difficult to implement and it was so laggy.
