### ISSUE TITLE
Implement particles effect

### ISSUE THREAD

**Issue by lorenzo-gangemi** [Rajawali/Rajawali#1821]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.777@aar

This is not really an issue, but the wiky seems a bit dated and i can't figure out how to implent a simple particle affect to use for example to rapresent small sparks or some smoke.
I've tryed to read the wiki article and to embedd the code in my app but there are a lot of methods which cannot be resolved.
I've also tryed to look if there was a Object3D_Particles.

**Comment by jwoolston** [comment]
Particles have been broken for some time now and are not currently considered part of the library.

**Comment by ValkA** [comment]
How big the gap is from taking it old material implementation and updating to current implementation?

Would you point a few hints to implement that? 
I might just send a pull request with this feature in the future.
