### ISSUE TITLE
How to set fov for the Camera?

### ISSUE THREAD

**Issue by JaneLMF** [Rajawali/Rajawali#1828]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.346-SNAPSHOT@aar

#### Device and Android Version
sdkVersion 17

#### Summary
I load a .obj model and i want to update fov to match design.

#### Steps to Reproduce
i try to use "getCurrentCamera().setFieldOfView(40);" , but not match my design.

#### Trace or Log Output
[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by contriteobserver** [comment]
Not sure I understand what is not working for you, here is an FOV test example:
```
        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.CYAN);
                DirectionalLight key = new DirectionalLight(-2, 2, 2);
                key.setPosition(new Vector3(2,2,2));
                key.setPower(2);
                getCurrentScene().addLight(key);

                Material material = new Material();
                material.setColor(Color.MAGENTA);
                material.enableLighting(true);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.setAmbientColor(Color.GRAY);
                Object3D obj = new Cube(2);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                getCurrentCamera().setPosition(2,2,2);
                getCurrentCamera().setLookAt(obj.getPosition());
                getCurrentCamera().setFieldOfView(20);
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }
        }
```

Here are the results for FOV=80, 40, 20
![fov](https://cloud.githubusercontent.com/assets/17471201/21465799/a4386154-c966-11e6-867c-bde84a45b487.png)

Please clarify what about this is unexpected.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
