### ISSUE TITLE
How to setAntiAlias when i load a .obj file.

### ISSUE THREAD

**Issue by JaneLMF** [Rajawali/Rajawali#1830]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.346-SNAPSHOT@aar

#### Device and Android Version
sdkVersion 17

#### Summary
[describe the issue or feature]
![device-2016-12-26-154506](https://cloud.githubusercontent.com/assets/16095111/21478008/526576a0-cb82-11e6-9448-649be8324f72.png)

#### Steps to Reproduce
[Describe reproducable steps and sample code]

#### Trace or Log Output
[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by contriteobserver** [comment]
FXAAPass was not in 'org.rajawali3d:rajawali:1.1.346-SNAPSHOT@aar', suggest you migrate to 'org.rajawali3d:rajawali:1.1.668@aar'

Then you can use FXAAPass like this:
```
    private class EffectsRenderer extends Renderer {
        private PostProcessingManager mEffects;

        public EffectsRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.CYAN);
                DirectionalLight key = new DirectionalLight(-2,-2,-2);
                key.setPosition(new Vector3(2,2,2));
                key.setPower(2);
                getCurrentScene().addLight(key);

                Material material = new Material();
                material.setColor(Color.MAGENTA);
                material.enableLighting(true);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.setAmbientColor(Color.GRAY);
                Object3D obj = new Cube(1);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                Animation3D anim = new RotateOnAxisAnimation(new Vector3(1,1,1), 360);
                anim.setTransformable3D(obj);
                anim.setDurationMilliseconds(5678);
                anim.setRepeatMode(Animation.RepeatMode.INFINITE);
                anim.play();

                getCurrentScene().registerAnimation(anim);
                getCurrentScene().addAndSwitchCamera(arcball);

                mEffects = new PostProcessingManager(this);

                RenderPass renderPass = new RenderPass(getCurrentScene(), arcball, 0);
                mEffects.addPass(renderPass);

                EffectPass antialiasPass = new FXAAPass();
                antialiasPass.setRenderToScreen(true);
                mEffects.addPass(antialiasPass);


            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }
        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            mEffects.render(ellapsedRealtime, deltaTime);
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```

**Comment by JaneLMF** [comment]
Hi, Thanks for your answer, But i have a problem, i installed the app to my android phone, i can not see my cube in my phone when i from 'org.rajawali3d:rajawali:1.1.346-SNAPSHOT@aar' migrate to 'org.rajawali3d:rajawali:1.1.668@aar' . 

my code like this:
`public LoadModelRenderer(Context context) {
            super(context);
        }

        private PostProcessingManager mEffects;
        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.CYAN);
                DirectionalLight key = new DirectionalLight(-2,-2,-2);
                key.setPosition(new Vector3(2,2,2));
                key.setPower(2);
                getCurrentScene().addLight(key);

                Material material = new Material();
                material.setColor(Color.MAGENTA);
                material.enableLighting(true);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.setAmbientColor(Color.GRAY);
                Object3D obj = new Cube(1);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                Animation3D anim = new RotateOnAxisAnimation(new Vector3(1,1,1), 360);
                anim.setTransformable3D(obj);
                anim.setDurationMilliseconds(5678);
                anim.setRepeatMode(Animation.RepeatMode.INFINITE);
                anim.play();

                getCurrentScene().registerAnimation(anim);
//                getCurrentScene().addAndSwitchCamera(arcball);

                mEffects = new PostProcessingManager(this);

//                RenderPass renderPass = new RenderPass(getCurrentScene(), arcball, 0);
//                mEffects.addPass(renderPass);

                EffectPass antialiasPass = new FXAAPass();
                antialiasPass.setRenderToScreen(true);
                mEffects.addPass(antialiasPass);


            } catch (Exception e) {
                Log.d("Jane", e.toString());
            }
        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            mEffects.render(ellapsedRealtime, deltaTime);
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }`


and then , i catch a log for this situation. 
[log.txt](https://github.com/Rajawali/Rajawali/files/672791/log.txt)

**Comment by JaneLMF** [comment]
Hi, i catch a new log after add this code:
`RajLog.setDebugEnabled(true);`

[log.txt](https://github.com/Rajawali/Rajawali/files/672818/log.txt)

**Comment by contriteobserver** [comment]
One has to have the RenderPass, that gathers the processing source, to postprocess the current camera, just use:
```
                RenderPass renderPass = new RenderPass(getCurrentScene(), getCurrentCamera(), 0);
                mEffects.addPass(renderPass);
```

**Comment by JaneLMF** [comment]
Hi, That great, i added your code , i can see the cube in my android phone,  but i still can not see it in my android box.

android box:
ro.build.version.sdk=19

android phone:
ro.build.version.sdk=21


i catch a log when it runing in android box:
[log.txt](https://github.com/Rajawali/Rajawali/files/672843/log.txt)

**Comment by contriteobserver** [comment]
what is the make and model of the android box?

**Comment by JaneLMF** [comment]
Hi, the android box model is pivos.

i export file /system/build.prop of the box.
[build.txt](https://github.com/Rajawali/Rajawali/files/673518/build.txt)

i can see the cube in my android box when i rollback to 'org.rajawali3d:rajawali:1.1.346-SNAPSHOT@aar'

**Comment by contriteobserver** [comment]
the /system/build.prop contains the line: `ro.opengles.version=131072` which indicates openGLES v2.0.

Unfortunately, [FXAAPass.java](../blob/master/rajawali/src/main/java/org/rajawali3d/postprocessing/passes/FXAAPass.java) says it requires openGLES v3.0 or better

**Comment by jwoolston** [comment]
Closing issue as resolved/stale. Please inform if issues persist.
