### ISSUE TITLE
load obj file with large size jpg

### ISSUE THREAD

**Issue by thelordvampire** [Rajawali/Rajawali#1832]
i downloaded an obj model includes 1 file obj, 1 file mtl, and 3 files jpg, this source from here http://tf3dm.com/3d-model/rose-31675.html

3 files jpg used in file mtl. But there is one large file jpg (6 MB). And its not working with that large file jpg. I mean it just show a random color for object. Another files work fine. If i change the name of large file jpg by name of other file jpg in file mtl, it works. So i think the problem is the large file jpg.
Ah i put all files in a folder in sdcard and load obj file from sdcard

Can anyone help me? Thank you

Here is my code:
File sdcard = Environment.getExternalStorageDirectory();
 File file = new File(sdcard, "KLTN/example1/rose_obj");
 LoaderOBJ objLoader = new LoaderOBJ(this, file);
            objLoader = objLoader.parse();
            hinh3D = objLoader.getParsedObject();
            getCurrentScene().clearChildren();
            getCurrentScene().addChild(hinh3D);

The log:

01-13 23:03:49.224 17200-17215/com.example.bao.myapplication I/art: Background partial concurrent mark sweep GC freed 548(35KB) AllocSpace objects, 0(0B) LOS objects, 7% free, 193MB/209MB, paused 42.227ms total 407.794ms
01-13 23:03:50.804 17200-17303/com.example.bao.myapplication W/Adreno-ES20: <core_glTexImage2D:501>: GL_INVALID_VALUE
01-13 23:03:50.914 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
01-13 23:03:50.914 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uTime returned -1!
01-13 23:03:50.934 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
01-13 23:03:50.934 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uTime returned -1!
01-13 23:03:50.944 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
01-13 23:03:50.944 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uTime returned -1!
01-13 23:03:51.034 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
01-13 23:03:51.034 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uTime returned -1!
01-13 23:03:51.164 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uModelMatrix returned -1!
01-13 23:03:51.164 17200-17303/com.example.bao.myapplication E/Rajawali: Getting location of uniform: uTime returned -1!

**Comment by contriteobserver** [comment]
Attempted to recreate your issue, in the linked `rose.rar`, the `grass_texture225.jpg` file was corrupted, so downloaded it from `http://bgfons.com/upload/grass_texture225.jpg`, then renamed:
* `rose.obj` -> `rose_obj.obj`
* `rose.mtl` -> `rose_mtl.mtl`
* `texture-green-paper-pattern-scratch-background-photo-hd-wallpaper.jpg` -> `texture_green_paper_pattern.jpg`
* `wildtextures-leather-Campo-rose.jpg` -> `wildtextures_leather_campo_rose.jpg`

then loaded the result with:
```
    private class RoseRenderer extends Renderer {

        public RoseRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.CYAN);
                DirectionalLight key = new DirectionalLight(-32, -32, -32);
                key.setPosition(new Vector3(32,32,32));
                key.setPower(2);
                getCurrentScene().addLight(key);

                LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(),
                        mTextureManager, R.raw.rose_obj);
                objParser.parse();
                Object3D objGroup = objParser.getParsedObject();
                getCurrentScene().addChild(objGroup);

                getCurrentScene().addAndSwitchCamera(arcball);
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }
        }
```

but it turned out that the files are too big for my device:
```
01-13 09:01:01.464 7668-7718/com.example.rosespike E/AndroidRuntime: FATAL EXCEPTION: GLThread 419
                                                                               Process: com.example.rosespike, PID: 7668
                                                                               java.lang.OutOfMemoryError
                                                                                   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                   at java.nio.MemoryBlock.allocate(MemoryBlock.java:125)
                                                                                   at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:72)
                                                                                   at org.rajawali3d.Geometry3D.setTextureCoords(Geometry3D.java:843)
                                                                                   at org.rajawali3d.Geometry3D.setTextureCoords(Geometry3D.java:833)
                                                                                   at org.rajawali3d.Geometry3D.setData(Geometry3D.java:458)
                                                                                   at org.rajawali3d.Object3D.setData(Object3D.java:160)
                                                                                   at org.rajawali3d.Object3D.setData(Object3D.java:153)
                                                                                   at org.rajawali3d.loader.LoaderOBJ.parse(LoaderOBJ.java:355)
                                                                                   at com.tveon.komixstream.rosespike.RoseActivity$RoseRenderer.initScene(RoseActivity.java:60)
                                                                                   at org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(Renderer.java:351)
                                                                                   at org.rajawali3d.view.SurfaceView$RendererDelegate.onSurfaceChanged(SurfaceView.java:232)
                                                                                   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
                                                                                   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

So I scaled down the textures to 50% in GIMP, and decimated the model in blender,  finally the rose would load. While the leaves and stem look right, but something has gone wrong with the petals, will look in
![device-2017-01-13-102425](https://cloud.githubusercontent.com/assets/17471201/21940765/ab8680de-d97a-11e6-8c4f-6c52a117ddc5.png)
ro that next.

**Comment by contriteobserver** [comment]
the problem appears to be in the code that splits quads into triangles, if one triangulates faces in blender, everything comes up roses...
![device-2017-01-13-104818](https://cloud.githubusercontent.com/assets/17471201/21941528/fe5a91b2-d97d-11e6-8292-bb28c702aa36.png)

**Comment by thelordvampire** [comment]
Thanks contriteobserver, but my idea is different. i want to create a folder in sdcard and user can copy paste manually obj file into sdcard so i cant use this code :
LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(), mTextureManager, R.raw.rose_obj);
 instead of, i use:
LoaderOBJ objLoader = new LoaderOBJ(this, file); (is it ok?)

Next, i replaced the dot "." in all file names like that:
rose.obj => rose_obj (not rose_obj.obj)
rose.mtl => rose_mtl
grass_texture225.jpg => grass_texture225_jpg

i also changed the file name into the content of file like that:
mtllib rose.mtl => mtllib rose_mtl (in file rose_obj)
(same with other files)
 because if i used dot ".", these errors will happen:
01-14 02:01:48.729 5380-5406/com.example.bao.myapplication W/Adreno-ES20: <core_glTexImage2D:501>: GL_INVALID_VALUE
01-14 02:01:48.749 5380-5406/com.example.bao.myapplication E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
01-14 02:01:48.749 5380-5406/com.example.bao.myapplication E/Rajawali: Shader log: Fragment shader compilation failed.
                                                                       ERROR: 0:3: '.' : Syntax error:  syntax error
                                                                       ERROR: 1 compilation errors.  No code generated.
01-14 02:01:48.759 5380-5406/com.example.bao.myapplication E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
01-14 02:01:48.759 5380-5406/com.example.bao.myapplication E/Rajawali: Shader log: Fragment shader compilation failed.
                                                                       ERROR: 0:3: '.' : Syntax error:  syntax error
                                                                       ERROR: 1 compilation errors.  No code generated.

Maybe, if i use files like resource files, i can change the file names like you did.
Can you try load this obj file into sdcard. Thanks so much.

This is my app screen image now:
![screenshot_2017-01-14-02-29-03](https://cloud.githubusercontent.com/assets/9023308/21943143/7ffdecee-da02-11e6-95b1-460f4f123dd2.png)

**Comment by contriteobserver** [comment]
You might want to consider another approach, `LoaderOBJ` parses only a subset of the [Wavefront OBJ geometry definition format](https://en.wikipedia.org/wiki/Wavefront_.obj_file), and it is not very robust, allowing arbitrary input would be unwise.

**Comment by thelordvampire** [comment]
I think the problem is the size of file wildtextures-leather-Campo-rose.jpg . So i open it in Paint, cut a small part of this image and paste in a new paint. Now the new file is about 60 KB. I run again and it works.
I still load file in sdcard.
![screenshot_2017-01-14-17-11-24](https://cloud.githubusercontent.com/assets/9023308/21954242/24693f6a-da7e-11e6-8093-cce403366736.png)
![screenshot_2017-01-14-17-11-32](https://cloud.githubusercontent.com/assets/9023308/21954243/246c3e7c-da7e-11e6-8445-0aca043e3587.png)
![screenshot_2017-01-14-17-11-36](https://cloud.githubusercontent.com/assets/9023308/21954244/246c4232-da7e-11e6-8002-444f5d56ce4e.png)

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
