### ISSUE TITLE
Documentation link in README.md is dead

### ISSUE THREAD

**Issue by magillus** [Rajawali/Rajawali#1836]
#### Rajawali Version or Branch
latest from master 

#### Summary
Documentation link in README.md to 'Introducing Plugin Architecture for Rajawali' is dead end.
Did the tutorial moved or has been removed?

#### Steps to Reproduce
goto: https://github.com/Rajawali/Rajawali/blob/master/README.md
in Tutorials by Other section see the link 'Introducing Plugin Architecture for Rajawali'
url: http://www.andrewjo.com/blog/mobile-development/introducing-plugin-architecture-for-rajawali

**Comment by jwoolston** [comment]
Closing as resolved.
