### ISSUE TITLE
Why can't I see the object I'm trying to render?

### ISSUE THREAD

**Issue by julianonunes** [Rajawali/Rajawali#1841]
#### Rajawali Version or Branch
1.1.777

#### Device and Android Version
Lenovo C2 - Android 6.0.1

#### Summary
I need to render a car model (converted from FBX to OBJ using Autodesk FBX Converter, as LoaderFBX is not suggested) and allow touch interaction to move the camera.

#### Steps to Reproduce
```
public class CarRenderer extends Renderer {
    public Context mContext;
    private Animation3D mCameraAnim, mLightAnim;
    private PointLight mLight;

    public CarRenderer(Context context) {
        super(context);
        mContext = context;
    }

    @Override
    protected void initScene() {
        mLight = new PointLight();
        mLight.setPosition(0, 0, 4);
        mLight.setPower(3);

        getCurrentScene().addLight(mLight);
        getCurrentCamera().setZ(16);

        try {
            LoaderOBJ parser = new LoaderOBJ(mContext.getResources(), TextureManager.getInstance(), R.raw.f458_mtl);
            parser.parse();

            Object3D o = parser.getParsedObject();
            getCurrentScene().addChild(o);

            mCameraAnim = new RotateOnAxisAnimation(Vector3.Axis.Y, 360);
            mCameraAnim.setDurationMilliseconds(8000);
            mCameraAnim.setRepeatMode(Animation.RepeatMode.INFINITE);
            mCameraAnim.setTransformable3D(o);
        } catch (ParsingException e) {
            e.printStackTrace();
        }

        mLightAnim = new EllipticalOrbitAnimation3D(new Vector3(),
                new Vector3(0, 10, 0), Vector3.getAxisVector(Vector3.Axis.Z), 0,
                360, EllipticalOrbitAnimation3D.OrbitDirection.CLOCKWISE);

        mLightAnim.setDurationMilliseconds(3000);
        mLightAnim.setRepeatMode(Animation.RepeatMode.INFINITE);
        mLightAnim.setTransformable3D(mLight);

        getCurrentScene().registerAnimation(mCameraAnim);
        getCurrentScene().registerAnimation(mLightAnim);

        mCameraAnim.play();
        mLightAnim.play();
    }

    @Override
    public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

    }

    @Override
    public void onTouchEvent(MotionEvent event) {

    }
}
```

#### Trace or Log Output
02-15 14:28:16.876 5124-5124/? I/art: Late-enabling -Xcheck:jni
02-15 14:28:16.954 5124-5124/com.myapp.threedpoc W/System: ClassLoader referenced unknown path: /data/app/com.myapp.threedpoc-1/lib/arm
02-15 14:28:16.970 5124-5124/com.myapp.threedpoc I/InstantRun: Instant Run Runtime started. Android package is com.myapp.threedpoc, real application class is null.
02-15 14:28:17.105 5124-5124/com.myapp.threedpoc D/OpenSSLLib: OpensslErr:Module:12(116:176); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:186;Function:ASN1_get_object
02-15 14:28:18.200 5124-5124/com.myapp.threedpoc W/System: ClassLoader referenced unknown path: /data/app/com.myapp.threedpoc-1/lib/arm
02-15 14:28:18.222 5124-5124/com.myapp.threedpoc D/ActivityThread: BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{cc71773 com.myapp.threedpoc}}
02-15 14:28:18.223 5124-5124/com.myapp.threedpoc V/ActivityThread: Handling launch of ActivityRecord{fdc3630 token=android.os.BinderProxy@265e2a9 {com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}} startsNotResumed=false
02-15 14:28:18.332 5124-5139/com.myapp.threedpoc I/System: FinalizerDaemon: finalize objects = 1
02-15 14:28:18.437 5124-5124/com.myapp.threedpoc V/ActivityThread: ActivityRecord{fdc3630 token=android.os.BinderProxy@265e2a9 {com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}}: app=android.app.Application@af1b7cf, appName=com.myapp.threedpoc, pkg=com.myapp.threedpoc, comp={com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}, dir=/data/app/com.myapp.threedpoc-1/base.apk
02-15 14:28:18.572 5124-5124/com.myapp.threedpoc W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-15 14:28:18.834 5124-5124/com.myapp.threedpoc E/MultiWindowProxy: getServiceInstance failed!
02-15 14:28:19.193 5124-5124/com.myapp.threedpoc D/SurfaceView: checkSurfaceViewlLogProperty get invalid command
02-15 14:28:19.194 5124-5124/com.myapp.threedpoc D/GLSurfaceView: checkGLSurfaceViewlLogProperty get invalid command
02-15 14:28:19.232 5124-5124/com.myapp.threedpoc I/Rajawali: Rajawali | Bombshell | v1.1.777 Release 
02-15 14:28:19.233 5124-5124/com.myapp.threedpoc I/Rajawali: This is a stable release.
02-15 14:28:19.321 5124-5124/com.myapp.threedpoc I/GLSurfaceView: setRenderer(), this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......I. 0,0-0,0}
02-15 14:28:19.326 5124-5124/com.myapp.threedpoc I/GLSurfaceView: setRenderMode = 0, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......I. 0,0-0,0}
02-15 14:28:19.329 5124-5124/com.myapp.threedpoc V/ActivityThread: Performing resume of ActivityRecord{fdc3630 token=android.os.BinderProxy@265e2a9 {com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}}
02-15 14:28:19.352 5124-5124/com.myapp.threedpoc D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{fdc3630 token=android.os.BinderProxy@265e2a9 {com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}}
02-15 14:28:19.352 5124-5124/com.myapp.threedpoc V/ActivityThread: Resume ActivityRecord{fdc3630 token=android.os.BinderProxy@265e2a9 {com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}} started activity: false, hideForNow: false, finished: false
02-15 14:28:19.352 5124-5124/com.myapp.threedpoc V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.PhoneWindow$DecorView{6fa213a I.E...... R.....ID 0,0-0,0}
02-15 14:28:19.375 5124-5124/com.myapp.threedpoc D/WindowClient: Add to mViews: com.android.internal.policy.PhoneWindow$DecorView{6fa213a I.E...... R.....ID 0,0-0,0}, this = android.view.WindowManagerGlobal@68749af
02-15 14:28:19.388 5124-5124/com.myapp.threedpoc D/OpenGLRenderer: Dumper init 2 threads <0xa8f930a0>
02-15 14:28:19.388 5124-5124/com.myapp.threedpoc D/OpenGLRenderer: <com.myapp.threedpoc> is running.
02-15 14:28:19.391 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-15 14:28:19.391 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: CanvasContext() 0xaf751000
02-15 14:28:19.446 5124-5124/com.myapp.threedpoc I/[MALI][Gralloc]: [+]r_hnd(0xa8f791e0), client(32), share_fd(31)
02-15 14:28:19.446 5124-5124/com.myapp.threedpoc D/GraphicBuffer: register, handle(0xa8f791e0) (w:1216 h:2048 s:1216 f:0x1 u:0x000100)
02-15 14:28:19.448 5124-5124/com.myapp.threedpoc D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{c67e1bc com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity,ident = 0}
02-15 14:28:19.459 5124-5124/com.myapp.threedpoc V/ActivityThread: Resuming ActivityRecord{fdc3630 token=android.os.BinderProxy@265e2a9 {com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}} with isForward=true
02-15 14:28:19.459 5124-5124/com.myapp.threedpoc V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{c67e1bc com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity,ident = 0}, this =com.android.internal.policy.PhoneWindow$DecorView{6fa213a V.E...... R.....ID 0,0-0,0}
02-15 14:28:19.459 5124-5124/com.myapp.threedpoc V/ActivityThread: Scheduling idle handler for ActivityRecord{fdc3630 token=android.os.BinderProxy@265e2a9 {com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}}
02-15 14:28:19.461 5124-5124/com.myapp.threedpoc D/ActivityThread: ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{fdc3630 token=android.os.BinderProxy@265e2a9 {com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity}}
02-15 14:28:19.463 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- onWindowVisibilityChanged, visibility = 0, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......I. 0,0-0,0}
02-15 14:28:19.617 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: CanvasContext() 0xaf751000 initialize window=0xaf3d2608, title=com.myapp.threedpoc/com.myapp.threedpoc.RajawaliSampleActivity
02-15 14:28:19.619 5124-5323/com.myapp.threedpoc I/OpenGLRenderer: Initialized EGL, version 1.4
02-15 14:28:19.619 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- setFrame, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.630 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.632 5124-5124/com.myapp.threedpoc I/SurfaceView: Changes: creating=true format=true size=true visible=true left=true top=true mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=true mVisible=false mRequestedVisible=true, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.638 5124-5124/com.myapp.threedpoc I/SurfaceView: Cur surface: Surface(name=null)/@0x93ac49a, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.640 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: Created EGL context (0xa8ec6280)
02-15 14:28:19.644 5124-5143/com.myapp.threedpoc V/SurfaceView: this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120} got resized: w=720 h=1120, cur w=-1 h=-1
02-15 14:28:19.647 5124-5124/com.myapp.threedpoc I/SurfaceView: New surface: Surface(name=null)/@0xf08d1cb, vis=true, frame=Rect(0, 160 - 720, 1280), this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.647 5124-5124/com.myapp.threedpoc I/SurfaceView: Callback --> surfaceCreated, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.648 5124-5124/com.myapp.threedpoc I/SurfaceView: surfaceCreated callback +, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.648 5124-5323/com.myapp.threedpoc I/OpenGLRenderer: Get enable program binary service property (1)
02-15 14:28:19.648 5124-5323/com.myapp.threedpoc I/OpenGLRenderer: Initializing program atlas...
02-15 14:28:19.648 5124-5124/com.myapp.threedpoc I/SurfaceView: surfaceCreated callback -, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.648 5124-5124/com.myapp.threedpoc I/SurfaceView: surfaceChanged -- format=1 w=720 h=1120, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.649 5124-5124/com.myapp.threedpoc I/SurfaceView: surfaceChanged callback +, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.649 5124-5323/com.myapp.threedpoc D/ProgramBinary/Service: BpProgramBinaryService.getFileDescriptor
02-15 14:28:19.649 5124-5124/com.myapp.threedpoc I/SurfaceView: surfaceChanged callback -, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.649 5124-5321/com.myapp.threedpoc I/EglHelper: eglInitialize = 327903, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.649 5124-5124/com.myapp.threedpoc I/SurfaceView: surfaceRedrawNeeded, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.649 5124-5124/com.myapp.threedpoc I/SurfaceView: finishedDrawing, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.649 5124-5321/com.myapp.threedpoc I/EglHelper: chooseConfig = 327903, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.650 5124-5321/com.myapp.threedpoc I/DefaultContextFactory: createContext = 327903, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.652 5124-5321/com.myapp.threedpoc D/Surface: Surface::connect(this=0xaf3d2d00,api=1)
02-15 14:28:19.653 5124-5323/com.myapp.threedpoc D/ProgramBinary/Service: BpProgramBinaryService.getProgramMapLen
02-15 14:28:19.654 5124-5321/com.myapp.threedpoc W/libEGL: [ANDROID_RECORDABLE] format: 4
02-15 14:28:19.654 5124-5124/com.myapp.threedpoc V/SurfaceView: Layout: x=0 y=160 w=720 h=1120, frame=Rect(0, 0 - 720, 1120), this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.654 5124-5323/com.myapp.threedpoc D/ProgramBinary/Service: BpProgramBinaryService.getProgramMapArray
02-15 14:28:19.656 5124-5323/com.myapp.threedpoc D/ProgramBinary/Service: BpProgramBinaryService.getProgramBinaryLen
02-15 14:28:19.656 5124-5321/com.myapp.threedpoc D/mali_winsys: new_window_surface returns 0x3000
02-15 14:28:19.657 5124-5323/com.myapp.threedpoc I/OpenGLRenderer: Program binary detail: Binary length is 171416, program map length is 152.
02-15 14:28:19.657 5124-5323/com.myapp.threedpoc I/OpenGLRenderer: Succeeded to mmap program binaries. File descriptor is 39, and path is /dev/ashmem�LG̠aҩ.
02-15 14:28:19.657 5124-5323/com.myapp.threedpoc I/OpenGLRenderer: No need to use file discriptor anymore, close fd(39).
02-15 14:28:19.658 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: Initializing program cache from 0xb6cc4eac, size = 3
02-15 14:28:19.663 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: -- init (key = 0x0000000000000000)
02-15 14:28:19.665 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: -- init (key = 0x0000000800000003)
02-15 14:28:19.667 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: -- init (key = 0x0000003800000000)
02-15 14:28:19.670 5124-5323/com.myapp.threedpoc D/Surface: Surface::connect(this=0xaf3d2600,api=1)
02-15 14:28:19.670 5124-5323/com.myapp.threedpoc W/libEGL: [ANDROID_RECORDABLE] format: 1
02-15 14:28:19.671 5124-5323/com.myapp.threedpoc D/mali_winsys: new_window_surface returns 0x3000
02-15 14:28:19.676 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.676 5124-5124/com.myapp.threedpoc I/SurfaceView: Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=true mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.676 5124-5124/com.myapp.threedpoc I/SurfaceView: Cur surface: Surface(name=null)/@0x93ac49a, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.682 5124-5124/com.myapp.threedpoc I/SurfaceView: New surface: Surface(name=null)/@0xf08d1cb, vis=true, frame=Rect(0, 160 - 720, 1280), this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.682 5124-5124/com.myapp.threedpoc I/SurfaceView: surfaceRedrawNeeded, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.682 5124-5124/com.myapp.threedpoc I/SurfaceView: finishedDrawing, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.683 5124-5124/com.myapp.threedpoc V/SurfaceView: Layout: x=0 y=160 w=720 h=1120, frame=Rect(0, 0 - 720, 1120), this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......ID 0,0-720,1120}
02-15 14:28:19.709 5124-5124/com.myapp.threedpoc I/SurfaceView: Punch a hole(dispatchDraw), w = 720, h = 1120, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ........ 0,0-720,1120}
02-15 14:28:19.717 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: CacheTexture 2 upload: x, y, width height = 0, 0, 89, 116
02-15 14:28:19.721 5124-5323/com.myapp.threedpoc I/[MALI][Gralloc]: [+]r_hnd(0xa0b87320), client(32), share_fd(41)
02-15 14:28:19.721 5124-5323/com.myapp.threedpoc D/GraphicBuffer: register, handle(0xa0b87320) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
02-15 14:28:19.735 5124-5323/com.myapp.threedpoc D/OpenGLRenderer: ProgramCache save to disk, size = 3
02-15 14:28:19.749 5124-5323/com.myapp.threedpoc I/[MALI][Gralloc]: [+]r_hnd(0xa0b87460), client(32), share_fd(44)
02-15 14:28:19.749 5124-5323/com.myapp.threedpoc D/GraphicBuffer: register, handle(0xa0b87460) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
02-15 14:28:19.862 5124-5141/com.myapp.threedpoc I/art: Background partial concurrent mark sweep GC freed 6253(1164KB) AllocSpace objects, 1(20KB) LOS objects, 28% free, 10MB/14MB, paused 2.857ms total 120.534ms
02-15 14:28:19.894 5124-5321/com.myapp.threedpoc I/[MALI][Gralloc]: [+]r_hnd(0xa8f79500), client(32), share_fd(42)
02-15 14:28:19.894 5124-5321/com.myapp.threedpoc D/GraphicBuffer: register, handle(0xa8f79500) (w:720 h:1120 s:736 f:0x4 u:0x000b00)
02-15 14:28:19.921 5124-5321/com.myapp.threedpoc I/[MALI][Gralloc]: [+]r_hnd(0xa8f79640), client(32), share_fd(43)
02-15 14:28:19.921 5124-5321/com.myapp.threedpoc D/GraphicBuffer: register, handle(0xa8f79640) (w:720 h:1120 s:736 f:0x4 u:0x000b00)
02-15 14:28:19.937 5124-5321/com.myapp.threedpoc I/[MALI][Gralloc]: [+]r_hnd(0xa8f79b40), client(32), share_fd(46)
02-15 14:28:19.937 5124-5321/com.myapp.threedpoc D/GraphicBuffer: register, handle(0xa8f79b40) (w:720 h:1120 s:736 f:0x4 u:0x000b00)
02-15 14:28:19.969 5124-5321/com.myapp.threedpoc I/[MALI][Gralloc]: [+]r_hnd(0xa8f79c80), client(32), share_fd(49)
02-15 14:28:19.969 5124-5321/com.myapp.threedpoc D/GraphicBuffer: register, handle(0xa8f79c80) (w:720 h:1120 s:736 f:0x4 u:0x000b00)
02-15 14:28:19.992 5124-5124/com.myapp.threedpoc V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#81810100
02-15 14:28:19.993 5124-5124/com.myapp.threedpoc V/InputMethodManager: START INPUT: com.android.internal.policy.PhoneWindow$DecorView{6fa213a V.E...... R.....ID 0,0-720,1280} ic=null tba=android.view.inputmethod.EditorInfo@c5639c0 controlFlags=#104
02-15 14:28:20.161 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- UPDATE_WINDOW_MSG, this = Handler (android.view.SurfaceView$1) {cf46f9}
02-15 14:28:20.162 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- setFrame, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......I. 0,0-720,1120}
02-15 14:28:20.166 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......I. 0,0-720,1120}
02-15 14:28:20.167 5124-5124/com.myapp.threedpoc I/SurfaceView: Punch a hole(dispatchDraw), w = 720, h = 1120, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ........ 0,0-720,1120}
02-15 14:28:20.186 5124-5323/com.myapp.threedpoc I/[MALI][Gralloc]: [+]r_hnd(0xa0b875a0), client(32), share_fd(47)
02-15 14:28:20.186 5124-5323/com.myapp.threedpoc D/GraphicBuffer: register, handle(0xa0b875a0) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
02-15 14:28:20.357 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- setFrame, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......I. 0,0-720,1120}
02-15 14:28:20.358 5124-5124/com.myapp.threedpoc I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ......I. 0,0-720,1120}
02-15 14:28:20.358 5124-5124/com.myapp.threedpoc I/SurfaceView: Punch a hole(dispatchDraw), w = 720, h = 1120, this = org.rajawali3d.view.SurfaceView{1f25d8e V.E...... ........ 0,0-720,1120}

I've added the OBJ and FBX to my Dropbox: https://www.dropbox.com/sh/j0ec2bdulmajs4y/AABk8rI0gAdvc-UzUrzknoXoa?dl=0

**Comment by contriteobserver** [comment]
There appears to be an issue with the OBJ file, it will not import into Blender either. Blender Errors list:
```
(  0.0000 sec |   0.0000 sec) Importing OBJ '/tmp/Downloads/f458.obj'...
  (  0.0005 sec |   0.0000 sec) Parsing OBJ file...
    (  1.8266 sec |   1.8244 sec) Done, loading materials and images...
ProgressMaterial not found MTL: '/tmp/Downloads/458.mtl'
    (  1.8568 sec |   1.8546 sec) Done, building geometries (verts:98364 faces:179907 materials: 50 smoothgroups:0) ...
Progress:  66.67%

Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/io_scene_obj/__init__.py", line 147, in execute
    return import_obj.load(context, **keywords)
  File "/usr/share/blender/scripts/addons/io_scene_obj/import_obj.py", line 1200, in load
    dataname,
  File "/usr/share/blender/scripts/addons/io_scene_obj/import_obj.py", line 709, in create_mesh
    blen_uvs.data[lidx].uv = verts_tex[0 if (face_uvidx is ...) else face_uvidx]
IndexError: list index out of range


```

**Comment by julianonunes** [comment]
That's strange. I tried with a file exported using Blender and Autodesk FBX Converter.

The file exported using Blender is here too https://www.dropbox.com/sh/j0ec2bdulmajs4y/AABk8rI0gAdvc-UzUrzknoXoa?dl=0, it's called ferrari.obj

**Comment by contriteobserver** [comment]
Keep in mind that LoaderOBJ only parses a subset of the OBJ format.

Took ferrari.obj, loaded into Blender, removed the materials, exported it and got a visible result.

Here is the Renderer code:
```
    private class ObjRenderer extends Renderer {
        Object3D obj;

        public ObjRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);
                DirectionalLight key = new DirectionalLight(-8, 8, 8);
                key.setPosition(new Vector3(8,8,8));
                key.setPower(8);
                getCurrentScene().addLight(key);

                Camera currentCamera = getCurrentCamera();
                currentCamera.setPosition(8, 8, 8);
                currentCamera.setLookAt(Vector3.ZERO);

                try {
                    LoaderOBJ loader = new LoaderOBJ(this,R.raw.ferrari02_obj);
                    loader.parse();
                    Object3D obj = loader.getParsedObject();
                    getCurrentScene().addChild(obj);

                } catch (ParsingException e) {
                    e.printStackTrace();
                }
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }

        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```
![device-2017-02-15-185703](https://cloud.githubusercontent.com/assets/17471201/23005504/88f4dcea-f3b1-11e6-8df6-4049e50abab9.png)

**Comment by julianonunes** [comment]
But do I have any other option (maybe another format) if I want to display the colors?

And one more question, does Rajawali allow me to define "clickable" areas in a model? I mean, can I define in my code an action when the user touches the car's door?

Thank you.
