### ISSUE TITLE
How to make a Object3D revolves around the Y-axis of the current scene?

### ISSUE THREAD

**Issue by sunjinbo** [Rajawali/Rajawali#1846]
# Rajawali Version or Branch
All versions.

#### Device and Android Version
Google Pixel Android 7.1.1

#### Summary
I can get a Quaternion-object from Camera.getOrientation() API, How can use it to make a Object3D revolves around the Y-axis of the current scene?

#### Steps to Reproduce
None.

#### Trace or Log Output
None.

**Comment by contriteobserver** [comment]
combining `Quaternion.getYAxis()` with `RotateOnAxisAnimation` should get you there, as in:
```
            Quaternion orientation = getCurrentCamera().getOrientation();
            Animation3D animation3D = new RotateOnAxisAnimation(orientation.getYAxis(), 360);
```
