### ISSUE TITLE
onObjectPicked never gets called

### ISSUE THREAD

**Issue by julianonunes** [Rajawali/Rajawali#1847]
#### Rajawali Version or Branch
1.1.777

#### Device and Android Version
Lenovo C2 - Android 6.0.1

#### Summary
I need to detect touch on my model and if possible on specific parts (like touching the car's door).

#### Steps to Reproduce

```
import android.content.Context;
import android.graphics.Color;
import android.support.annotation.NonNull;
import android.util.Log;
import android.view.MotionEvent;

import org.rajawali3d.Object3D;
import org.rajawali3d.cameras.Camera;
import org.rajawali3d.lights.DirectionalLight;
import org.rajawali3d.loader.LoaderOBJ;
import org.rajawali3d.loader.ParsingException;
import org.rajawali3d.materials.textures.TextureManager;
import org.rajawali3d.math.Matrix4;
import org.rajawali3d.math.vector.Vector3;
import org.rajawali3d.renderer.Renderer;
import org.rajawali3d.util.GLU;
import org.rajawali3d.util.ObjectColorPicker;
import org.rajawali3d.util.OnObjectPickedListener;

import javax.microedition.khronos.opengles.GL10;

/**
 * Created by juliano on 2/15/2017.
 */

public class CarRenderer extends Renderer implements OnObjectPickedListener {
    public Context mContext;

    private Camera mCamera;
    private Object3D mSelectedObject;
    private ObjectColorPicker mPicker;
    private Matrix4 mViewMatrix;
    private Matrix4 mProjectionMatrix;
    private int[] mViewport;
    private double[] mNearPos4;
    private double[] mFarPos4;
    private Vector3 mNearPos;
    private Vector3 mFarPos;
    private Vector3 mNewObjPos;


    public CarRenderer(Context context) {
        super(context);
        mContext = context;
    }

    @Override
    protected void initScene() {
        getCurrentScene().setBackgroundColor(Color.WHITE);

        DirectionalLight key = new DirectionalLight(-8, 8, 8);
        key.setPosition(new Vector3(8,8,8));
        key.setPower(8);
        getCurrentScene().addLight(key);

        mCamera = getCurrentCamera();
        mCamera.setPosition(12, 12, 12);
        mCamera.setLookAt(Vector3.ZERO);

        mViewport = new int[] { 0, 0, getViewportWidth(), getViewportHeight() };
        mViewMatrix = getCurrentCamera().getViewMatrix();
        mProjectionMatrix = getCurrentCamera().getProjectionMatrix();
        mNearPos4 = new double[4];
        mFarPos4 = new double[4];
        mNearPos = new Vector3();
        mFarPos = new Vector3();
        mNewObjPos = new Vector3();

        try {
            mPicker = new ObjectColorPicker(this);
            mPicker.setOnObjectPickedListener(this);

            Object3D container = new Object3D();
            getCurrentScene().addChild(container);

            LoaderOBJ parser = new LoaderOBJ(mContext.getResources(), TextureManager.getInstance(), R.raw.ferrari_obj);
            parser.parse();

            Object3D o = parser.getParsedObject();
            container.addChild(o);
            mPicker.registerObject(o);

        } catch (ParsingException e) {
            e.printStackTrace();
        }

    }

    @Override
    public void onRenderSurfaceSizeChanged(GL10 gl, int width, int height) {
        super.onRenderSurfaceSizeChanged(gl, width, height);
        mViewport[2] = getViewportWidth();
        mViewport[3] = getViewportHeight();
        mViewMatrix = getCurrentCamera().getViewMatrix();
        mProjectionMatrix = getCurrentCamera().getProjectionMatrix();
    }

    @Override
    public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

    }

    @Override //This method moves the camera using direct touch events. Tracking a flick and turning it into a procedural animation for smoothing
    public void onTouchEvent(MotionEvent event) {
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                Log.i("TOUCH", "ACTION_DOWN");
                getObjectAt(event.getX(), event.getY());
                break;
            case MotionEvent.ACTION_MOVE:
                Log.i("TOUCH", "ACTION_MOVE");
                moveSelectedObject(event.getX(), event.getY());
                break;
            case MotionEvent.ACTION_UP:
                Log.i("TOUCH", "ACTION_UP");
                stopMovingSelectedObject();
                break;
        }
    }

    @Override
    public void onObjectPicked(@NonNull Object3D object) {
        mSelectedObject = object;
    }

    @Override
    public void onNoObjectPicked() {
        Log.d("CarRenderer", "No object picked");
    }

    public void getObjectAt(float x, float y) {
        mPicker.getObjectAt(x, y);
    }

    public void moveSelectedObject(float x, float y) {
        if (mSelectedObject == null)
            return;

        //
        // -- unproject the screen coordinate (2D) to the camera's near plane
        //

        GLU.gluUnProject(x, getViewportHeight() - y, 0, mViewMatrix.getDoubleValues(), 0,
                mProjectionMatrix.getDoubleValues(), 0, mViewport, 0, mNearPos4, 0);

        //
        // -- unproject the screen coordinate (2D) to the camera's far plane
        //

        GLU.gluUnProject(x, getViewportHeight() - y, 1.f, mViewMatrix.getDoubleValues(), 0,
                mProjectionMatrix.getDoubleValues(), 0, mViewport, 0, mFarPos4, 0);

        //
        // -- transform 4D coordinates (x, y, z, w) to 3D (x, y, z) by dividing
        // each coordinate (x, y, z) by w.
        //

        mNearPos.setAll(mNearPos4[0] / mNearPos4[3], mNearPos4[1]
                / mNearPos4[3], mNearPos4[2] / mNearPos4[3]);
        mFarPos.setAll(mFarPos4[0] / mFarPos4[3],
                mFarPos4[1] / mFarPos4[3], mFarPos4[2] / mFarPos4[3]);

        //
        // -- now get the coordinates for the selected object
        //

        double factor = (Math.abs(mSelectedObject.getZ()) + mNearPos.z)
                / (getCurrentCamera().getFarPlane() - getCurrentCamera()
                .getNearPlane());

        mNewObjPos.setAll(mFarPos);
        mNewObjPos.subtract(mNearPos);
        mNewObjPos.multiply(factor);
        mNewObjPos.add(mNearPos);

        mSelectedObject.setX(mNewObjPos.x);
        mSelectedObject.setY(mNewObjPos.y);
    }

    public void stopMovingSelectedObject() {
        mSelectedObject = null;
    }
}

```

#### Trace or Log Output
The app is not crashing. It simply doesn't execute the onObjectPicked method.

**Comment by rpicolet** [comment]
One thing to check is whether the object(s) that you register has(have) any visible geometry; pure containers have no geometry and cannot use color picking.  Also, registering a containing object that does have some geometry still does not register its children, only the container's geometry.  If you want to differentiate between doors, trunks, hoods, tires, or whatever, each needs to have the relevant geometry separated into registerable objects.  If it is difficult/cumbersome to get all the desired existing parts of e.g. a door (handle, panel, window, etc) as a single object, you can try adding transparent "bounding boxes" as siblings or containers, and register those instead.  Hope this helps...

**Comment by julianonunes** [comment]
Thank you for your answer. By geometry you mean any Object3D? The model file is being parsed and added to the scene correctly (I've added it to a container just as a test, but I was adding it directly to the scene).
I have created separate objects on Blender for each part that must be clickable. Do I have to export each one of them as a separate OBJ file? Or can Rajawali understand this division inside a main OBJ file?

About the transparent bounding boxes, how can I position them correctly without having to rerun the app and try a different value each time? Because as my model currently has 17MB, it takes almost a minute to load.

**Comment by rpicolet** [comment]
Not any Object3D, no.  It has to have some vertices/triangle faces of its own (or some that are shared e.g. via cloning of a parsed model object), and not just be a pure container of other Ojbect3Ds; when you register an object, it is only that object-local geometry that gets colored (off-screen) and therefore picked. That you have your clickable objects in Blender is good, assuming again they have the desired clickable geometry.

You do not have to export each such object in its own file, but you do need to be able to find them, e.g. using the name of the object (you can devise your own mapping if there are numerous such items using some kind of systematic naming/id scheme), so that you can register them and know which one is being clicked.  Rajawali will not (and could not) do this for you, as it is app-specific.

Re transparent touch objects, if you use them they should be part of the same model/framework as the non-transparent objects, so that they are subject to the same transformations.  Just add them to the same containers holding the visible elements.  Again, you only need to do this is if it is simpler than naming/registering/tracking all the visible objects, (or if the objects are small and hard to touch in the first place, then the transparent objects can work as hot-spots).

17MB seems like a large model.  If I were going to break it up, I'd look for opportunities to load some parts (internals? underside? hidden backsides facing away from initial camera position?) after the initial startup gets something acceptable showing (via background tasks or on demand).  Or maybe load a low-res version to get started and then gradually load higher-res parts in the background, kinda like jpegs load over the web. Or some combination of such approaches...   Also, are there parts with easily re-used geometry (e.g. perhaps left-right pairs could use a simple -1 scale transformation, tires could be clones of a single object in the OBJ file, etc.).  It all takes work, but there ya go...

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.

**Comment by SolitaryWolf** [comment]
This post helps me a lot. I successfully handled touching each part of model.
Use "getChildByName" to get each Object3D(parts of model) and register all of them "registerObject"
=>onObjectPicked will be invoked.
