### ISSUE TITLE
Tilted camera images on the ScreenQuad

### ISSUE THREAD

**Issue by entkler** [Rajawali/Rajawali#1850]
#### Rajawali Version or Branch
1.1.777 (even later builds like 1.1.863)

#### Device and Android Version
Project Tango tablet (Android 4.4)

#### Summary
I tried to stream camera images on a "ScreenQuad" Object this worked but just that the images are tilted upside down. This happend using Rajawali 1.1.777 (or even the later master builds like 1.1.863). Any idea how i can fix this ? thanks for the help

**Comment by contriteobserver** [comment]
Submitted path to adress UV coordinate issue.

**Comment by jwoolston** [comment]
Resolved via #1854
