### ISSUE TITLE
move object with Arcball Camera

### ISSUE THREAD

**Issue by thelordvampire** [Rajawali/Rajawali#1852]
Rajawali Version 1.1.777

how to pick and move object with arcball camera? if i use normal camera, i can easily pick and move an object but i can't  take camera flying around with z axis(world coordinate system, not camera coordinate system) and always see the point(0,0,0). The solution arcball camera is so great,it is simple to do that, but i can't pick and move an object? What should i do now? Thanks for your help

**Comment by thelordvampire** [comment]
I found enableLookAt() in Camera so i could take camera always see one point. But  why i can't pick and move object with arcball camera?

**Comment by jwoolston** [comment]
Arcball camera does not enforce usage of much of the base API. This will be resolved in the future.
