### ISSUE TITLE
MD5 and AWD Animation

### ISSUE THREAD

**Issue by SmileSFL** [Rajawali/Rajawali#1857]
A few days ago, I am here to submit a question, is about the skeletal animation, MD5 format of skeletal animation, after completion of loading, play, the entire model of skeletal animation is twisted, its action also is wrong, and AWD skeletal animation is better, is the two arms of the animation is wrong, the problem can be solved? This is the second time I submit this problem, hope to be able to catch your eye, to modify this mistake.

**Comment by ToxicBakery** [comment]
Do not open duplicate tickets

**Comment by SmileSFL** [comment]
A few days before I submit the problem, but saw no one give me any reply, or modify rajawali, so will only copy, hope you can understand, I really hope you can solve this problem, so rajawali3D the graphics engine can more powerful.
