### ISSUE TITLE
Basic help needed: NullPointer and ArrayIndexOOB exceptions when rendering

### ISSUE THREAD

**Issue by jshwdmnn** [Rajawali/Rajawali#1859]
Basic help is needed:

Every now and then, I tend to get NullPointer- and ArrayIndexOutOfBounds exceptions in the rendering and preRendering process of my Object3D objects. I do heavily add and remove children from Object3D objects for grouping purposes and I suspected that these exceptions happen when a rendering process is running and in the middle of it I remove a child from the grouping object / from the scene. So I started to, whenever I modify anything in the scene, stop the renderer, do the modifications and start the renderer again.
It feels like this made the occasions of those exceptions rarer but not absent. Maybe the renderer doesn't stop immediately when I call stopRendering?

Do I miss some basics? Whats the correct approach?

Thanks a ton

#### Rajawali Version or Branch
'org.rajawali3d:rajawali:1.1.777@aar'

**Comment by jwoolston** [comment]
Please show code of how you are adding/removing objects.

**Comment by jshwdmnn** [comment]
For example, I extended Object3D class. The initializer of it creates a few planes and adds them using `super.addChild(plane)`, like so:

```
this.plane = new Plane(UIConstants.PLANE_WIDTH, UIConstants.PLANE_HEIGHT, 1, 1);
this.plane.setColor(0x803d3d3d);
this.plane.setTransparent(true);
super.addChild(this.plane);
```

Removing planes:

```
Plane plane = super.getChildAt(0);
super.removeChild(plane);
plane.destroy();
```
_(Is the destroy even necessary? Won't it all be garbage collected anyway?)_


(Of course to have it all rendered in the end, the 'Object3D' object is added to the scene using `this.renderer.getCurrentScene().addChild(this.myObject)`)

**Comment by jwoolston** [comment]
The call to `destroy()` frees the memory on the GPU used by the object, which the GC wont cover. You do have to be careful using it though as if the geometry is being shared with another object, it will cause that object to have problems. Object cloning would be the only way in the engine for this to happen, but user code can add many more situations. I suspect that most likely what is happening is a thread safety bug. I addressed it for the scene add/remove child functions, but not Object3D. The solution would be to either stop removing them and manage things some other way such as thorugh show/hide or promoting to scene objects, or register a scene frame callback and do the delete there, that way it is on the GL thread.

**Comment by jshwdmnn** [comment]
Oh! So cloning objects and calling `destroy()` on them can actually lead to geometry NullPointers. I had those a few times! I need to check my code for this.
For the thread safety part: Can you please elaborate on the scene frame callback? Where can I hook into it?

**Comment by jwoolston** [comment]
You register them with the scene. See here: https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/main/java/org/rajawali3d/scene/Scene.java#L763

**Comment by jshwdmnn** [comment]
Works like charme now!

Thank you so much
