### ISSUE TITLE
apply multiple texture into 1 single object in separate coordinate

### ISSUE THREAD

**Issue by cuxxie** [Rajawali/Rajawali#1865]
#### Rajawali Version or Branch
Master 1.1.777

Is there any way to apply multiple texture into 1 single object (for example sphere). for this side i will apply texture A while for another side apply texture B. I've tried by adding texture in material but it seems it just over-layering texture B on top of texture A.

**Comment by jwoolston** [comment]
doing this will require you either create a single texture with both textures properly mapped to the correct coordinate space, or create a special material that will choose which texture to apply based on the texture coordinates.

**Comment by cuxxie** [comment]
@jwoolston can i use the AMultiTexture ?

**Comment by jwoolston** [comment]
You could use `CubeMapTexture` (currently the only concrete implementation of `AMultiTexture`) but its mapping will be distorted on a sphere. If you are doing this on a cube, it will work, but you will be bound by the restrictions of cube maps in open gl, namely that each face texture be identical in size and that all 6 faces must be provided.

**Comment by rpicolet** [comment]
Why not split the sphere into two half spheres, and put them in a shared container for transformations?

**Comment by cuxxie** [comment]
@jwoolston alright.. Thanks for the info.. Ill try to implement the custom texture and material

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
