### ISSUE TITLE
Rotating 3D object onSwiping left and right or up and down

### ISSUE THREAD

**Issue by SAGARSURI** [Rajawali/Rajawali#1866]
#### Rajawali Version or Branch
[1.1.777]

#### Device and Android Version
[Asus ZenPad 8.0 and Android Marshmallow]

#### Summary
[there is no proper documentation on how to rotate a 3D model on swiping. I am able to achieve scaling but I am not able to rotate it.
`public class MainActivity extends AppCompatActivity {

    private ScaleGestureDetector mScaleDetector;
    private GestureDetector gestureDetector;
    MyRenderer renderer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final SurfaceView surface = new SurfaceView(this);
        surface.setFrameRate(60.0);
        surface.setRenderMode(ISurface.RENDERMODE_WHEN_DIRTY);

        // Add mSurface to your root view
        addContentView(surface, new ActionBar.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT));

        renderer = new MyRenderer(this);
        mScaleDetector = new ScaleGestureDetector(this, renderer.scaleListener);
        gestureDetector = new GestureDetector(this, renderer.gestureListener);
        surface.setSurfaceRenderer(renderer);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        mScaleDetector.onTouchEvent(event);
        gestureDetector.onTouchEvent(event);
        if (event.getAction() == MotionEvent.ACTION_UP) {
            Log.e("MotionEvent", "up");
        } else if (event.getAction() == MotionEvent.ACTION_DOWN) {
            Log.e("MotionEvent", "down");
        }
        //Log.e("TouchEvent", event.getAction() + "");

        // Assume all touch events are consumed
        return true;
    }

    class MyRenderer extends Renderer implements OnFPSUpdateListener {

        Context context;
        private Sphere mEarthSphere;
        private DirectionalLight mDirectionalLight;
        public final ScaleListener scaleListener;
        public final GestureListener gestureListener;
        public boolean left, right;
        public boolean up, down;

        private final DecimalFormat mDFormat;

        public MyRenderer(Context context) {
            super(context);
            this.context = context;
            mDFormat = new DecimalFormat("#.##");

            scaleListener = new ScaleListener();
            gestureListener = new GestureListener();
            setFrameRate(60);
            setFPSUpdateListener(this);
        }

        @Override
        protected void initScene() {
            mDirectionalLight = new DirectionalLight(1f, .2f, -1.0f);
            mDirectionalLight.setColor(1.0f, 1.0f, 1.0f);
            mDirectionalLight.setPower(2);
            getCurrentScene().addLight(mDirectionalLight);

            Material material = new Material();
            material.enableLighting(true);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setColorInfluence(0);
            Texture earthTexture = new Texture("Earth", R.drawable.earthtruecolor_nasa_big);
            try {
                material.addTexture(earthTexture);

            } catch (ATexture.TextureException error) {
                Log.d("DEBUG", "TEXTURE ERROR");
            }

            mEarthSphere = new Sphere(1, 24, 24);
            mEarthSphere.setMaterial(material);
            getCurrentScene().addChild(mEarthSphere);
            getCurrentCamera().setZ(4.2f);
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
           // mEarthSphere.rotate(Vector3.Axis.Y, 1.0);
        }

        public class ScaleListener extends
                ScaleGestureDetector.SimpleOnScaleGestureListener {
            @Override
            public boolean onScale(ScaleGestureDetector detector) {
                float scale = (float) (mEarthSphere.getScaleX() * detector
                        .getScaleFactor());
                scale = Math.max(0.1f, Math.min(scale, 5.0f));
                mEarthSphere.setScale(scale);
                return true;
            }

        }

        private class GestureListener implements GestureDetector.OnGestureListener {
            @Override
            public boolean onDown(MotionEvent motionEvent) {
                return false;
            }

            @Override
            public void onShowPress(MotionEvent motionEvent) {

            }

            @Override
            public boolean onSingleTapUp(MotionEvent motionEvent) {
                return false;
            }

            @Override
            public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
                //Method to rotate the 3D model
                Log.d("Gesture ", " onScroll");
                if (e1.getY() < e2.getY()){
                    mEarthSphere.rotate(Vector3.Axis.Y ,1.0);
                    Log.d("Gesture ", " Scroll Down");
                }
                if(e1.getY() > e2.getY()){
                    mEarthSphere.rotate(Vector3.Axis.X,4.0);
                    Log.d("Gesture ", " Scroll Up");
                }
                return true;
            }

            @Override
            public void onLongPress(MotionEvent motionEvent) {

            }

            @Override
            public boolean onFling(MotionEvent e1, MotionEvent e2, float velocityX, float velocityY) {
                if (e1.getX() < e2.getX()) {
                    Log.d("Gesture ", "Left to Right swipe: "+ e1.getX() + " - " + e2.getX());
                    Log.d("Speed ", String.valueOf(velocityX) + " pixels/second");
                }
                if (e1.getX() > e2.getX()) {
                    Log.d("Gesture ", "Right to Left swipe: "+ e1.getX() + " - " + e2.getX());
                    Log.d("Speed ", String.valueOf(velocityX) + " pixels/second");
                }
                if (e1.getY() < e2.getY()) {
                    Log.d("Gesture ", "Up to Down swipe: " + e1.getX() + " - " + e2.getX());
                    Log.d("Speed ", String.valueOf(velocityY) + " pixels/second");
                }
                if (e1.getY() > e2.getY()) {
                    Log.d("Gesture ", "Down to Up swipe: " + e1.getX() + " - " + e2.getX());
                    Log.d("Speed ", String.valueOf(velocityY) + " pixels/second");
                }
                return true;

            }
        }

        @Override
        public void onFPSUpdate(double fps) {
            System.out.println("~fps: " + mDFormat.format(fps));
        }
    }
}

check my code here.

**Comment by contriteobserver** [comment]
Here is an implementation of flinging, does this meet your needs?
```
public class ObjManipActivity extends AppCompatActivity {
    Renderer renderer;
    SurfaceView surface;
    Cube cube;
    GestureDetector scrollDetector;
    float xVelocity;
    float yVelocity;
    Point screenSize;
    static float DAMPING = 6f;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_obj_manip);

        renderer = new ManipRenderer(getApplicationContext());
        surface = (SurfaceView) findViewById(R.id.rajawali_content);
        surface.setSurfaceRenderer(renderer);

        Display display = getWindowManager().getDefaultDisplay();
        screenSize = new Point();
        display.getSize(screenSize);
        Log.d(getLocalClassName(), "ScreenSize" + " x=" + screenSize.x + " y=" + screenSize.y);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        scrollDetector.onTouchEvent(event);
        return true; // Assume all touch events are consumed
    }

    class ManipRenderer extends Renderer {

        public ManipRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.CYAN);

            Material material = new Material();
            material.setColor(Color.MAGENTA);
            material.enableLighting(true);
            cube = new Cube(1);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setSpecularMethod(new SpecularMethod.Phong());
            cube.setMaterial(material);
            getCurrentScene().addChild(cube);

            DirectionalLight key = new DirectionalLight(-2,-2, 2);
            key.setLookAt(cube.getPosition());
            key.setPower(9);
            getCurrentScene().addLight(key);

            getCurrentCamera().setPosition(3,3,3);
            getCurrentCamera().setLookAt(cube.getPosition());
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            if(xVelocity > screenSize.x/DAMPING) {
                xVelocity -= screenSize.x/DAMPING;
            }
            if(yVelocity > screenSize.y/DAMPING) {
                yVelocity -= screenSize.y/DAMPING;
                if(yVelocity < (screenSize.y/DAMPING)) yVelocity = 0;
            }
            if(xVelocity < -screenSize.x/DAMPING) {
                xVelocity += screenSize.x/DAMPING;
            }
            if(yVelocity < -screenSize.y/DAMPING) {
                yVelocity += screenSize.y/DAMPING;
            }
            if(xVelocity > -screenSize.x/DAMPING && xVelocity < screenSize.x/DAMPING) xVelocity = 0;
            if(yVelocity > -screenSize.y/DAMPING && yVelocity < screenSize.y/DAMPING) yVelocity = 0;

            if(!(xVelocity==0) && !(yVelocity==0)){
                Vector3 xAxis = renderer.getCurrentCamera().getOrientation().getXAxis();

                Vector3 yAxis = renderer.getCurrentCamera().getOrientation().getYAxis();
                Vector3 zAxis = renderer.getCurrentCamera().getOrientation().getZAxis();

                //Method to rotate the 3D model
                Quaternion x = new Quaternion(xAxis, 8 * xVelocity / screenSize.x);
                Quaternion y = new Quaternion(zAxis, 8 * yVelocity / screenSize.y);
                cube.rotate(x.multiply(y));
            }

            super.onRender(ellapsedRealtime, deltaTime);
        }
    }

    public class ScrollListener extends
            GestureDetector.SimpleOnGestureListener {

        @Override
        public boolean onFling(MotionEvent e1, MotionEvent e2, float velocityX, float velocityY) {
            Log.d(getLocalClassName(), " velocityX=" + velocityX + " velocityY=" + velocityY);
            xVelocity += velocityX;
            yVelocity += velocityY;
            return super.onFling(e1, e2, velocityX, velocityY);
        }
    }
}
```

**Comment by rpicolet** [comment]
You may want to consider making writing of xVelocity and yVelocity on the UI thread mutually exclusive with reading those values on the GL thread (perhaps using synchronized blocks/methods), and making both values volatile.

I'm not really sure what the desired behavior is here, but it seems more natural to me that swiping left/right should rotate the object around its y-axis, and up/down should rotate it around its x-axis, and in general the object should rotate around an axis that is perpendicular to the swipe/fling motion.

Finally, I'm no quat expert, so maybe multiplying the two quats is what you want, but it might not be equivalent to one rotation around a single axis; if the result looks like a screwball and that's not desired, then maybe just one quat around a single computed axis would be better.

**Comment by contriteobserver** [comment]
[xy]Velocities don't need to be volatile in this case, as the changes are all within the same module. Didn't bother with synchronisation, as this is just a fling, if the two values are off by one update, no one will notice.

The intent is to rotate the object about the perpendicular axes of the camera, rather than global axes.

We use multiplication of two quaternions to represent a composition of the two rotations: equivalent to performing one rotation and then performing the other one, but without that nasty gimbal lock. However, keep in mind that this composition of rotations (like any other approach to composing 3D rotations) is not commutative, so the order of composition matters.

**Comment by rpicolet** [comment]
Sorry for the delayed response, life and all.

Re volatile; not sure what modularity has to do with it. My understanding is the volatile keyword makes sure the (CPU-)cached versions of a variable are forced to stay in sync; if the UI and GL threads are running on the same CPU, yeah it shouldn't matter, but if not, then GL reads may not get sync'd reliably with UI writes which could make scrolls appear glitchy.  Maybe I'm missing something that makes this a non-issue.

Re "just a fling"; unlike scroll events (which , I believe there is only one fling event (after the touch leaves the screen) per gesture. There is thus the possibility of a race condition between the x and y component updates, which means that (without a synchronized block/method around the two component updates) every once in a while, the fling will only see one of the components and go off in some unexpected direction. Maybe this is just a typo, and your meant onSroll()?  Anyway, flings probably need some kind of updates as well to spin forever or decelerate after the original fling event.

Re rotation axes, I was unclear.  I should have said "swiping left/right should rotate the object around _an axis parallel to the world y-axis/camera up-axis" and similar for the up/down swipe. My point was not really which set of axes to use in code, but that many users' intuitions/expectations would be that swiping left-right should cause a rotation around a (user-view) vertical axis and up/down around a (user-view) horizontal axis, and in general around an axis perpendicular to the swipe. The code provided seems to interpret left-right swipes to rotate the cube around a (user-view) horizontal axis, and up-down swipes around the screen z-axis, and I'm not sure what happens in between e.g. a 45-degree swipe. Maybe you are going for an arcball-style control or something instead...

Re composition of quaternions, my point was really about how to handle those 45-degree swipes, i.e. rather than composing two rotations (and trying to figure out which order to use), just compute an axis that is perpendicular to the swipe, and rotate once around that. If that's not what you are trying for, then ignore this.

Maybe I'm still missing some points, but no need to correct my thinking unless I've misstated some facts. Hope this helps your efforts, and thanks for helping the OP!

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
