### ISSUE TITLE
3D model not rotating on swipe

### ISSUE THREAD

**Issue by SAGARSURI** [Rajawali/Rajawali#1867]
I am trying to rotate a 3D model using RotateAnimation3D which is only working once if i swipe up on android screen. I am using a gesturelistener to rotate the model. If I swipe twice or thrice the model is vanished. My question is whats the best way to rotate the model. I have provided my code below.

   ` public class MainActivity extends AppCompatActivity {

    private ScaleGestureDetector mScaleDetector;
    private GestureDetector gestureDetector;
    RotateAnimation3D xAnim, negxAnim;
    MyRenderer renderer;
    int x = 200, neg_x = -200;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final SurfaceView surface = new SurfaceView(this);
        surface.setFrameRate(60.0);
        surface.setRenderMode(ISurface.RENDERMODE_WHEN_DIRTY);

        // Add mSurface to your root view
        addContentView(surface, new ActionBar.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT));

        renderer = new MyRenderer(this);
        mScaleDetector = new ScaleGestureDetector(this, renderer.scaleListener);
        gestureDetector = new GestureDetector(this, renderer.gestureListener);
        surface.setSurfaceRenderer(renderer);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        mScaleDetector.onTouchEvent(event);
        gestureDetector.onTouchEvent(event);
        if (event.getAction() == MotionEvent.ACTION_UP) {
            Log.e("MotionEvent", "up");
        } else if (event.getAction() == MotionEvent.ACTION_DOWN) {
            Log.e("MotionEvent", "down");
        }
        //Log.e("TouchEvent", event.getAction() + "");

        // Assume all touch events are consumed
        return true;
    }

    public class MyRenderer extends Renderer implements OnFPSUpdateListener {

        Context context;
        public Sphere mEarthSphere;
        private DirectionalLight mDirectionalLight;
        public final ScaleListener scaleListener;
        public final GestureListener gestureListener;

        private final DecimalFormat mDFormat;

        public MyRenderer(Context context) {
            super(context);
            this.context = context;
            mDFormat = new DecimalFormat("#.##");

            scaleListener = new ScaleListener();
            gestureListener = new GestureListener();
            setFrameRate(60);
            setFPSUpdateListener(this);
        }

        @Override
        protected void initScene() {
            mDirectionalLight = new DirectionalLight(1f, .2f, -1.0f);
            mDirectionalLight.setColor(1.0f, 1.0f, 1.0f);
            mDirectionalLight.setPower(2);
            getCurrentScene().addLight(mDirectionalLight);

            Material material = new Material();
            material.enableLighting(true);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setColorInfluence(0);
            Texture earthTexture = new Texture("Earth", R.drawable.earthtruecolor_nasa_big);

            try {
                material.addTexture(earthTexture);

            } catch (ATexture.TextureException error) {
                Log.d("DEBUG", "TEXTURE ERROR");
            }

            mEarthSphere = new Sphere(1, 24, 24);
            mEarthSphere.setMaterial(material);
            getCurrentScene().addChild(mEarthSphere);
            getCurrentCamera().setZ(4.2f);

        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            // mEarthSphere.rotate(Vector3.Axis.Y, 1.0);
        }

        public class ScaleListener extends
                ScaleGestureDetector.SimpleOnScaleGestureListener {
            @Override
            public boolean onScale(ScaleGestureDetector detector) {
                float scale = (float) (mEarthSphere.getScaleX() * detector
                        .getScaleFactor());
                scale = Math.max(0.1f, Math.min(scale, 5.0f));
                mEarthSphere.setScale(scale);
                return true;
            }

        }

        public class GestureListener extends GestureDetector.SimpleOnGestureListener {

            private static final int SWIPE_THRESHOLD = 100;
            private static final int SWIPE_VELOCITY_THRESHOLD = 100;

            @Override
            public boolean onDown(MotionEvent e) {
                return true;
            }

            @Override
            public boolean onFling(MotionEvent e1, MotionEvent e2, float velocityX, float velocityY) {
                boolean result = false;
                try {
                    float diffY = e2.getY() - e1.getY();
                    float diffX = e2.getX() - e1.getX();
                    if (Math.abs(diffX) > Math.abs(diffY)) {
                        if (Math.abs(diffX) > SWIPE_THRESHOLD && Math.abs(velocityX) > SWIPE_VELOCITY_THRESHOLD) {
                            if (diffX > 0) {
                                onSwipeRight();
                            } else {
                                onSwipeLeft();
                            }
                            result = true;
                        }
                    } else if (Math.abs(diffY) > SWIPE_THRESHOLD && Math.abs(velocityY) > SWIPE_VELOCITY_THRESHOLD) {
                        if (diffY > 0) {
                            onSwipeBottom();
                            Log.e("Down", "True");
                            negxAnim = new RotateAnimation3D(neg_x, 0, 0);
                            negxAnim.setDurationMilliseconds(1000);
                            negxAnim.setRepeatMode(Animation.RepeatMode.RESTART);
                            getCurrentScene().registerAnimation(negxAnim);
                            negxAnim.setTransformable3D(mEarthSphere);
                            negxAnim.play();
                            neg_x -= 200;
                           // x = neg_x+200;
                        } else {
                            Log.e("Up", "True");
                            onSwipeTop();
                            xAnim = new RotateAnimation3D(x, 0, 0);
                            xAnim.setDurationMilliseconds(1000);
                            xAnim.setRepeatMode(Animation.RepeatMode.RESTART);
                            getCurrentScene().registerAnimation(xAnim);
                            xAnim.setTransformable3D(mEarthSphere);
                            xAnim.play();
                            //x += 200;
                           // neg_x = x-200;
                        }
                        result = true;
                    }
                } catch (Exception exception) {
                    exception.printStackTrace();
                }
                return result;
            }
        }

        public void onSwipeRight() {
        }

        public void onSwipeLeft() {
        }

        public void onSwipeTop() {
        }

        public void onSwipeBottom() {
        }

        @Override
        public void onFPSUpdate(double fps) {
            System.out.println("~fps: " + mDFormat.format(fps));
        }
    }
}`

**Comment by contriteobserver** [comment]
Is this what you had in mind?
```
public class ObjManipActivity extends AppCompatActivity {
    SurfaceView surface;
    Cube cube;
    ScrollListener scrollListener;
    GestureDetector scrollDetector;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_obj_manip);

        Renderer renderer = new ManipRenderer(getApplicationContext());
        surface = (SurfaceView) findViewById(R.id.rajawali_content);
        surface.setSurfaceRenderer(renderer);

        scrollListener = new ScrollListener();
        scrollDetector = new GestureDetector(this, scrollListener);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        scrollDetector.onTouchEvent(event);
        return true; // Assume all touch events are consumed
    }

    class ManipRenderer extends Renderer {

        public ManipRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.CYAN);

            Material material = new Material();
            material.setColor(Color.MAGENTA);
            material.enableLighting(true);
            cube = new Cube(1);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setSpecularMethod(new SpecularMethod.Phong());
            cube.setMaterial(material);
            getCurrentScene().addChild(cube);

            DirectionalLight key = new DirectionalLight(-2,-2, 2);
            key.setLookAt(cube.getPosition());
            key.setPower(9);
            getCurrentScene().addLight(key);

            getCurrentCamera().setPosition(0,0,3);
            getCurrentCamera().setLookAt(cube.getPosition());
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }

    public class ScrollListener extends
            GestureDetector.SimpleOnGestureListener {

        @Override
        public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
            //Method to rotate the 3D model
            Quaternion x = new Quaternion(Vector3.X, distanceY/9);
            Quaternion y = new Quaternion(Vector3.Y, distanceX/9);
            cube.rotate(x.multiply(y));
            return super.onScroll(e1, e2, distanceX, distanceY);
        }
    }
}
```

**Comment by rpicolet** [comment]
Not sure what other issues there might be, but neither of the above solutions are thread-safe.  The UI touch/gesture event callbacks run on the UI thread, and the Object3D transformations (e.g. scale and rotate) performed there could easily interrupt/corrupt a render mid-operation on the GL thread, with undefined results...

**Comment by contriteobserver** [comment]
Good point, I updated the example to separate the two threads.

**Comment by jwoolston** [comment]
Closing this issue as resolved based on the information provided and lack of response. Thankyou @contriteobserver for the example and @rpicolet for the thread safety catch.

**Comment by oksett** [comment]
@contriteobserver  How to initialize the xDistance and the yDistance variables? Also the Quaternion quat variable is never used
