### ISSUE TITLE
loading obj file from sd card

### ISSUE THREAD

**Issue by lchivan916** [Rajawali/Rajawali#1871]
#### Rajawali Version or Branch
compile 'org.rajawali3d:rajawali:1.0.186-SNAPSHOT@aar'

#### Summary
i would like to load the 3D model from the sd card storage. However, the LoaderOBJ parser keep changing the mtl path from cat.mtl to cat_mtl when i use it to parse the obj file.

**Comment by contriteobserver** [comment]
More info needed: Please set RajLog debugging and post the log output

`RajLog.setDebugEnabled(true)`

**Comment by jwoolston** [comment]
Closing issue as stale since the requested information has not been provided.
