### ISSUE TITLE
keep vertex position when load .obj

### ISSUE THREAD

**Issue by JonathanOzsvath** [Rajawali/Rajawali#1874]
#### Rajawali Version or Branch
[org.rajawali3d:rajawali:1.1.346-SNAPSHOT@aar]

#### Device and Android Version
[andoid 5.1]

Hi,

I use the LoaderOBJ and it is work, but when i try to get back vertices it is different then the .obj file.
It seems delete or add some vertices from the list, because when i want the 50th vertex i get back the 44
th vertex and the difference is bigger later. Are there any solution to keep every vertices on the position or i did something wrong?
![rv](https://cloud.githubusercontent.com/assets/10198815/24827728/e5d28130-1c4f-11e7-8733-9c06f07d1e88.PNG)
![rv2](https://cloud.githubusercontent.com/assets/10198815/24827701/741c4828-1c4f-11e7-9a76-336f8552eaf7.PNG)
The first two lines are comments and 3rd is mtl files name.

**Comment by jwoolston** [comment]
The vertex order from your file and the vertex order in the VBO won't necessarily match, due to parsing logic needs.
