### ISSUE TITLE
Add mtl to Obj model 

### ISSUE THREAD

**Issue by TheOska** [Rajawali/Rajawali#1875]
#### Rajawali Version or Branch
v1.1.777

#### Device and Android Version
Motorola Droid Turbo / Android 6.0.1

#### Summary

Hi, does Rajawali currently support adding mtl to obj model ? If yes, could you teach me how to add, because I tried different ways but fail to add mtl to obj model. 

Thanks a lot!

**Comment by ToxicBakery** [comment]
https://github.com/Rajawali/Rajawali/wiki/Tutorial-17-Importing-.Obj-Files
