### ISSUE TITLE
Object Render Not Showing 

### ISSUE THREAD

**Issue by hasanesfahan** [Rajawali/Rajawali#1876]
i use rajawali in my app. 

work when load 3dobject on my phone (sumsung s5).

but never show in tablet .

i test this link
https://play.google.com/store/apps/details?id=com.monyetmabuk.rajawali.tutorials
showing loader object in my phone and tablet . 

but my app never show object in tablet  .

**Comment by contriteobserver** [comment]
More detail is needed:

- What model is your tablet?
- Can you post your object, or provide a link to it?

**Comment by hasanesfahan** [comment]
first time never show object . 

i search in google 
change file Object3D.java 

from 

GLES20.glDrawElements(GLES20.GL_TRIANGLES,  mGeometry.getNumIndices(),   bufferType , 0);

to 

GLES20.glDrawElements(GLES20.GL_TRIANGLES,  mGeometry.getNumIndices(),   GLES20.GL_UNSIGNED_SHORT  , 0);


now show item 
but incorrect item 

test in multiple tablet . Not known . for example tonb . 
test in remix  .incorrect show item .



![image](https://cloud.githubusercontent.com/assets/8850437/24998866/ce3f3dba-2050-11e7-9ce1-e0f5c9449d46.png)

**Comment by hasanesfahan** [comment]
Can you post your object, or provide a link to it?
my project copy of Rajawali 
with fragment load obj  .

**Comment by hasanesfahan** [comment]
add simple cube 

![image](https://cloud.githubusercontent.com/assets/8850437/25020866/4e1dd1fa-20a5-11e7-8c6f-5d80848d95bf.png)

**Comment by jwoolston** [comment]
Closing issue as stale and/or resolved. @contriteobserver provided a very clear demonstration.
