### ISSUE TITLE
onWindowResize takes up way too much CPU time

### ISSUE THREAD

**Issue by jshwdmnn** [Rajawali/Rajawali#1879]
Hello again,
switching back to my rajawali SurfaceView activity takes very very long until it actually shows an image again and handles user input. When I method trace this issue it tells me the reason is the onWindowResize method (see attached screenshot). How can this be and is it my fault?

Thanks very much for any help

![methodtracer_onwindowresize](https://cloud.githubusercontent.com/assets/2640276/25484856/e4d81590-2b5b-11e7-9015-b328ac2770dc.png)

#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.777@aar

**Comment by contriteobserver** [comment]
Have you tried loading your geometry and textures in a fragment, and then merely adding them to the Renderer in your SurfaceViewActivity?

**Comment by jwoolston** [comment]
As @contriteobserver alludes to, the issue is not with Rajawali, but rather whatever work you are performing in `initScene`. If you wish it to take less time, offload some or all of this work to be asynchronous.
