### ISSUE TITLE
RectangularPrism depth parameter affects perceived width?

### ISSUE THREAD

**Issue by odin-** [Rajawali/Rajawali#1883]
I have created one RectangularPrism with default camera in Rajawali 1.1.777:

`RectangularPrism p = new RectangularPrism(2f, 2f, xf);`

Depending on x (depth) the perceived width on the Android screen varies.

* If the depth is 2f the width of the prism fills the screen.
* If the depth is 0.5f & 1f the width of the prism does not fill the screen.

So from a Rajawali/OpenGL perspective how and why does the depth parameter affect the perceived width of the object on the screen? Since the width (2f) is kept static shouldn't the prism always fill the screen in the same way? 

0.1f:
![spbvh](https://cloud.githubusercontent.com/assets/7396319/25594017/5b2a53aa-2ebf-11e7-8d2b-6f3028fb9339.png)

1f:
![iemce](https://cloud.githubusercontent.com/assets/7396319/25594068/7a806fdc-2ebf-11e7-905a-3c8d04e81b0a.png)

2f:
![humem](https://cloud.githubusercontent.com/assets/7396319/25594093/896f38de-2ebf-11e7-81eb-b3047d9894ea.png)

**Comment by contriteobserver** [comment]
The default camera is a [Perspective Camera](https://en.wikipedia.org/wiki/3D_projection#Perspective_projection), faces in the distance appear smaller than faces close by. The default camera is located at 0,0,4 and looks at 0,0,0. If one places a `RectangularPrism` of size 2,2,0.5 at 0,0,0, the distance between the camera and the closest face is 3.75.  If one places a `RectangularPrism` of size 2,2,2 at 0,0,0, the distance between the camera and the closest face is only 3, and so the closest face appears bigger.

If perspective is not desired, one may instantiate an [Orthographic Camera](https://en.wikipedia.org/wiki/3D_projection#Orthographic_projection) and `getCurrentScene().addAndSwitchCamera(orthographicCamera)`.

**Comment by odin-** [comment]
That sounds very logical. I'm a newbie :-). Thanks for the explanation.
