### ISSUE TITLE
Improving initialisation speed of Renderer

### ISSUE THREAD

**Issue by odin-** [Rajawali/Rajawali#1889]
I am using Rajawali 1.1.777

In my current application the user switches between activities. Each activity has as SurfaceView. There are about 225-300 objects (mostly RectangularPrism) being created each time. This takes a few seconds which is noticeable for the user.

Is there any smart way to try to optimize this using Rajawali. Precreating objects or similair?

**Comment by contriteobserver** [comment]
One approach is to have fragments instead of activities, fragments can be created before they are displayed, and can persist while the user switches to another fragment, so the scene does not need to be created each time it is made visible to the user.

**Comment by odin-** [comment]
I did some tests and it does seem that what takes time is creating the 3d objects, like RectangularPrism with texture. Adding them to the scene is lightning fast.

So I'll try to move the creation of objects in the background when my app starts up.

**Comment by odin-** [comment]
Did as you suggested and used Fragments, thanks!

Although I managed to get another problem :-)

https://github.com/Rajawali/Rajawali/issues/1893

I think we can close this one though.
