### ISSUE TITLE
Removing children from objects

### ISSUE THREAD

**Issue by odin-** [Rajawali/Rajawali#1890]
I am using Rajawali 1.1.777

I got a Plane where I added multiple RectangularPrism using addChild:

```
Plane plane = new Plane(...);
getCurrentScene().addChild(plane);

for (n = 0; n < 10; n++) {
   RectangularPrism p = new RectangularPrism(...)
   plane.addChild(p);
   objects.add(p);
}
```

Now I want to remove the children and thus have done a function such as:

```
public void removeAllChildren() {
   for (RectangularPrism p : objects) {
      plane.removeChild(p);
   }
}
```

The remove of the children is done from the activity on the renderer:

`mRenderer.removeAllChildren();`

When I try to remove the children I get an exception:

java.lang.ArrayIndexOutOfBoundsException: length=215; index=215
at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:121)
at java.util.Collections$SynchronizedList.get(Collections.java:2147)
at org.rajawali3d.Object3D.render(Object3D.java:338)
at org.rajawali3d.Object3D.render(Object3D.java:184)
at org.rajawali3d.scene.Scene.render(Scene.java:1135)
at org.rajawali3d.scene.Scene.render(Scene.java:1002)
at org.rajawali3d.renderer.Renderer.render(Renderer.java:426)
at org.rajawali3d.renderer.Renderer.onRender(Renderer.java:416)
at com.my.app.MyRenderer.onRender(MyRenderer.java:91)
at org.rajawali3d.renderer.Renderer.onRenderFrame(Renderer.java:391)
at org.rajawali3d.view.SurfaceView$RendererDelegate.onDrawFrame(SurfaceView.java:237)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

Do I need to do something special when removing children?

**Comment by contriteobserver** [comment]
Are you removing the children in the render thread? The following works for me
```
    private class BatchRenderer extends Renderer {
        private Object3D root;
        private boolean removeChildren = false;

        public BatchRenderer(Context context) {
            super(context);
        }

        private Material createMaterial(int color){
            Material material = new Material();
            material.setColor(color);
            return material;
        }

        @Override
        protected void initScene() {
            try {
                Random r = new Random();
                getCurrentScene().setBackgroundColor(Color.BLUE);

                root = new Cube(1);
                root.setMaterial(createMaterial(Color.CYAN));

                Cube base_object = new Cube(1);
                for(int i=0; i<=300;i++) {
                    Object3D child = base_object.clone();
                    child.setMaterial(createMaterial(Color.rgb(255, i*5, 255)));
                    child.setPosition(r.nextDouble(), r.nextDouble(), r.nextDouble());
                    root.addChild(child);
                }
                root.setRenderChildrenAsBatch(true);
                renderer.getCurrentScene().addChild(root);

            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }

        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            if(removeChildren) {
                while (root.getNumChildren() > 0) {
                    root.removeChild(root.getChildAt(0));
                }
                removeChildren = false;
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {
            switch (event.getAction()) {
                case MotionEvent.ACTION_UP:
                    removeChildren = true;
            }
        }
    }
```

**Comment by odin-** [comment]
Nope didn't think of that. I'll try it out. Thanks.
