### ISSUE TITLE
SurfaceView shows up black in Fragment

### ISSUE THREAD

**Issue by odin-** [Rajawali/Rajawali#1893]
I am using Rajawali 1.1.777

I have implemented a `ViewPager` containing two `Fragments`. The second `Fragment` contains a `SurfaceView`  statically declared in the fragment xml file:

```
<org.rajawali3d.view.SurfaceView
android:id="@+id/surface_view"
android:layout_width="match_parent"
android:layout_height="match_parent" />
```

The first `Fragment` is displayed at startup and the second `Fragment` is displayed by user action. When the second `Fragment` is displayed containing the `SurfaceView` and a few objects I just see a black screen. 

However if I leave the app and resume it I can see the objects for a very short while until the `SurfaceView` goes black again. This would indicate that the objects are there and it is rendering.

If I change the `SurfaceView` for a `TextureView` everything works fine and I see the objects as expected.

Any ideas why this might be so?

Thanks.

**Comment by contriteobserver** [comment]
I cannot be sure without more details, but it sounds like you have more than one Surface with the same Z-ordering. If this is the case, the results are undefined, but generally speaking you will see one Surface but not the other. Use `setZOrderMediaOverlay()` to set one in front of the other. Note that this must be set before the surface view's containing window is attached to the window manager.

**Comment by odin-** [comment]
If I got more than one surface it is implicit. I.e. I did not add more than one intentionally in my xml or java files. 

I'll continue debugging to see if I can find anything.

**Comment by odin-** [comment]
If I set the `SurfaceView `to transparent using `setTransparent `the 3d object shows up both in both `ViewPager `pages.

**Comment by odin-** [comment]
Checked with layout inspector and the `SurfaceView` is greyed out which probably means invisible. Although it has not been set invisible as visibility is `VISIBLE` according to layout inspector. The `FrameLayout` and `ProgressBar` is shown as visible in the inspector.

```
    <FrameLayout
        android:id="@+id/frame_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        android:orientation="vertical">

        <org.rajawali3d.view.SurfaceView
            android:id="@+id/surface_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:visibility="visible" />

        <ProgressBar
            android:id="@+id/board_progress_bar"
            android:layout_width="60dp"
            android:layout_height="60dp"
            android:layout_gravity="center"
            android:background="@android:color/transparent"
            android:gravity="center" />

    </FrameLayout>
```

**Comment by odin-** [comment]
Something going on with the `ViewPager`, if I put the Fragment with the `SurfaceView` to be displayed at startup it works just fine. If I put it as the second page which I switch to later by user interaction it does not work.

**Comment by odin-** [comment]
Just did two very clean Fragment layouts in xml for the `ViewPager`:

* One with the `SurfaceView`
* One with an AppCompatButton switching to the `SurfaceView` page. 

Same thing.

**Comment by odin-** [comment]
Gave up on `ViewPager` and just used `Fragments` with transactions. Works like a charm. Never again `ViewPager` :-)

Worked with TextureView though but I didn't want to degrade(?) performance.
