### ISSUE TITLE
failed RotateAnimation3D

### ISSUE THREAD

**Issue by lfrohman** [Rajawali/Rajawali#1901]
#### Rajawali Version or Branch
1.1.899-SNAPSHOT

#### Device and Android Version
Google Pixel - Android 7.1.2, API25

#### Summary
if I call
   new org.rajawali3d.animation.RotateAnimation3D(0.0,0.0,180.0);
this returns a RotateAnimation3D with
w: 6.1 E-17
x:0.0
y:0.0
z:1.0

then when applyTransformation() is called on the animation, it creates an orientation of
w:NaN
x:NaN
y:NaN
z:NaN

tracing through the code, it is dividing by zero

#### Steps to Reproduce
RotateAnimation3D a = new org.rajawali3d.animation.RotateAnimation3D(0.0,0.0,180.0);
a.applyTransformation();

#### Trace or Log Output
-

**Comment by contriteobserver** [comment]
Having trouble understanding your issue, `RotateAnimation3D.applyTransformation()` is a protected function, one does not call it directly. One the other hand, the following example works as expected, what is wrong with this approach?
```
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                Camera currentCamera = getCurrentCamera();
                currentCamera.setPosition(3, 3, 3);
                currentCamera.setLookAt(Vector3.ZERO);

                Material material = new Material();
                material.setColor(Color.GREEN);
                obj = new Cube(1);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                RotateAnimation3D a = new org.rajawali3d.animation.RotateAnimation3D(0.0,0.0,180.0);
                a.setTransformable3D(obj);
                a.setDurationMilliseconds(10 * 1000);
                a.setRepeatMode(Animation.RepeatMode.INFINITE);
                getCurrentScene().registerAnimation(a);
                a.play();
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }

        }
```

**Comment by lfrohman** [comment]
Sorry for the poor description. The code below will cause the Quaternion.slerp() method to create 
theta = 0
invSinTheta = Infinite
w,x,y,z all are NaN

=====

    protected void initScene() {
        try {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            Camera currentCamera = getCurrentCamera();
            currentCamera.setPosition(3, 3, 3);
            currentCamera.setLookAt(Vector3.ZERO);

            Material material = new Material();
            material.setColor(Color.GREEN);
            Cube obj = new Cube(1);
            obj.setMaterial(material);
            getCurrentScene().addChild(obj);

            AnimationGroup ag = new AnimationGroup();
            RotateAnimation3D a = new org.rajawali3d.animation.RotateAnimation3D(0.0,0.0,180.0);
            a.setTransformable3D(obj);
            a.setDurationMilliseconds(10 * 1000);
            ag.addAnimation(a);
            RotateAnimation3D b = new org.rajawali3d.animation.RotateAnimation3D(0.0,0.0,180.0);
            b.setTransformable3D(obj);
            b.setDelayMilliseconds(10 * 1000);
            b.setDurationMilliseconds(10 * 1000);
            ag.addAnimation(b);
            getCurrentScene().registerAnimation(ag);
            ag.play();
        } catch (Exception e) {
            Log.d("MainRenderer", e.toString());
        }
}

**Comment by contriteobserver** [comment]
The problem with the `AnimationGroup` in the example is there are two `RotateAnimation3D` operating on the same object. (a says go while b says wait) Sequential Animations are better performed with `AnimationQueue`, as per the following example (however, that too is not working as expected in 1.1.899-SNAPSHOT, suggest we close this issue and open a new one for unexpected `AnimationQueue` behavior) :
```
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                Camera currentCamera = getCurrentCamera();
                currentCamera.setPosition(3, 3, 3);
                currentCamera.setLookAt(Vector3.ZERO);

                Material material = new Material();
                material.setColor(Color.GREEN);
                Cube obj = new Cube(1);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                AnimationQueue aq = new AnimationQueue();
                RotateAnimation3D a = new org.rajawali3d.animation.RotateAnimation3D(0.0, 0.0, 180.0);
                a.setTransformable3D(obj);
                a.setDurationMilliseconds(10 * 1000);
                aq.addAnimation(a);
                RotateAnimation3D b = new org.rajawali3d.animation.RotateAnimation3D(0.0, 0.0, 180.0);
                b.setTransformable3D(obj);
                b.setDurationMilliseconds(10 * 1000);
                aq.addAnimation(b);
                getCurrentScene().registerAnimation(aq);
                aq.play();
            } catch (Exception e) {
                Log.d("MainRenderer", e.toString());
            }
        }
```

**Comment by jwoolston** [comment]
@contriteobserver I agree, but I am not sure what the bug you are referring to is.

**Comment by lfrohman** [comment]
"suggest we close this issue" - OK, see above:

I will let you "open a new one for unexpected AnimationQueue behavior)"
