### ISSUE TITLE
Skybox size is hard coded

### ISSUE THREAD

**Issue by alex199568** [Rajawali/Rajawali#1904]
#### Rajawali Version or Branch
Apparently it is hard coded in all versions and is equal to 700

#### Summary
As my camera moves too far from the objects in the scene (when the distance between the camera and objects is greater than 350, because hard coded value is 700) the objects get obscured by too small skybox, which I cannot change, because the size is hard coded

```
public void setSkybox(int posx, int negx, int posy, int negy, int posz, int negz) throws TextureException {
		synchronized (mCameras) {
			for (int i = 0, j = mCameras.size(); i < j; ++i)
				mCameras.get(i).setFarPlane(1000); // why 1000? Why setSkybox changes far plane of all cameras?
		}
		synchronized (mNextSkyboxLock) {
			mNextSkybox = new Cube(700, true); // Why 700? What if I need it to be 800? or 600?
			int[] resourceIds = new int[] { posx, negx, posy, negy, posz, negz };
			
			mSkyboxTexture = new CubeMapTexture("skybox", resourceIds);
			((CubeMapTexture)mSkyboxTexture).isSkyTexture(true);
			Material mat = new Material();
			mat.setColorInfluence(0);
			mat.addTexture(mSkyboxTexture);
			mNextSkybox.setMaterial(mat);
		}
	}
```

**Comment by contriteobserver** [comment]
submitted a patch to set skybox geometry

**Comment by rami-dabain** [comment]
causing problems on large worlds, can view more than 350 units, need to view up to 18000

**Comment by TBog** [comment]
The skybox should be a box of size 1, be drawn last so that we don't redraw pixels, centred on camera position. I can provide a patch with this but it involves material plugin and I'm not sure if it's user friendly enough

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
