### ISSUE TITLE
Hints on how to create a RectangularPrism with multiple textures

### ISSUE THREAD

**Issue by odin-** [Rajawali/Rajawali#1906]
(I am using Rajawali 1.1.777)

I want to have a `RectangularPrism` with 6 unique textures. As far as I understand there's already 6 texture coordinates for the object in a `RectangularPrism`. So what I need to do is to add 6 textures. Is this possible by adding multiple `Texture` objects to the `Material` and set it on the `RectangularPrism`? I cannot use `CubeMapTexture`since the texture display are distorted if it's not a cube.

I am a bit uncertain where to start to understand how to do this. 

Any hints appreciated.

/ Newbie

(Preferably I do not want to create my 6 Plane objects with unique textures. I tried this approach and my feeling was it slowed down the rotation of the objects because I had a lot of Plane objects on the screen at the same time).

**Comment by rpicolet** [comment]
Did you try putting all of the Planes in a container object and just rotating that?  Six animations is _not_ a lot anyway (if you rotate them individually), so its _much_ more likely just the texture rendering itself that is slowing things down, and that you don't notice it until you move the prism.  Maybe check your frame rate, see if you are keeping up or missing frames or something...

**Comment by odin-** [comment]
Yep I tried that. Well I had approx. 1350 planes because I wanted to draw 225 rectangles.

**Comment by jwoolston** [comment]
In those 225 prisms, how many are different in appearance?

**Comment by rpicolet** [comment]
Oh.  Well you should have mentioned that little detail.  Its definitely not an animation problem.  You are just pushing the hardware limits, and need to figure out how to reduce the load - fewer/smaller objects, simpler textures , etc.  I’m no texture expert, but maybe there are different formats that render more efficiently?


BTW, I’m pretty sure RectangularPrism can only use one texture for all six faces.

**Comment by odin-** [comment]
jwoolston: out of 225 prisms I have 6 different types: 15, 11, 13, 11, 176 and 1 of each type. So most of them have the same appearance.

**Comment by jwoolston** [comment]
At a minimum, material batching will help here. Do they all need to move independently of each other? Do they keep relative positions the same? If so, the geometry could be combined as well, resulting in far fewer draw calls (this is whats slowing you down).

**Comment by odin-** [comment]
What do you mean by material batching? Using the `MarterialManager`?

**Comment by jwoolston** [comment]
See https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/main/java/org/rajawali3d/Object3D.java#L826

Essentially, you add all the objects of the same material to a container object, set it to render all children as part of a batch. It will bind the material properties once and then issue all the draw calls. This will save you 3 + nUniforms GL calls per object per frame.

**Comment by jwoolston** [comment]
You can also do it without the parent object if you desire by setting the flag on the objects themselves, but you will have to make sure the first object is not marked as a batch so the material is properly applied.

**Comment by odin-** [comment]
By the "first object" you mean the first one added to the scene?

**Comment by odin-** [comment]
The first one created of course...

**Comment by odin-** [comment]
Thanks for the help. I'll implement the material batching.

**Comment by jwoolston** [comment]
First one to render, which will be based on order added to scene, not order created.

**Comment by odin-** [comment]
OK can I simply set that flag just before adding objects to a scene? 

Because I precreate alot of objects and I don't know which one of them that will be the first to be added in the moment I start adding them to the scene.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
