### ISSUE TITLE
Transparent TextureView

### ISSUE THREAD

**Issue by emjei** [Rajawali/Rajawali#1908]
Hi,

I need to make a transparent TextureView to display a camera preview below it and UI buttons on top of it (in other words, I need to "sandwich" a TextureView). The problem is that I am unable to make the TextureView transparent since calling `setOpaque(false)` and `getCurrentScene().setBackgroundColor(color_with_alpha)` doesn't do anything. The alpha is ignored and the views behind the TextureView are not visible.

I used SurfaceView at first with `setTransparent(true)` and it worked but then I couldn't add UI buttons on top of the SurfaceView because the SurfaceView has `setZOrderOnTop(true)`.

So, my question is how can I make a transparent TextureView?

Let's say, that I'm using v1.1.177 and LG Nexus 5X with Android 7.1.2.

Thanks!

**Comment by contriteobserver** [comment]
`SurfaceView.setZOrderMediaOverlay(true)` allows one to place UI buttons on top of the SurfaceView.

**Comment by emjei** [comment]
I tried this but it didn't work:

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    setContentView(R.layout.activity_main);

    mCameraView = (CameraView) findViewById(R.id.camera);
    mCameraView.addCallback(mCallback);

    SurfaceView surface = (SurfaceView) findViewById(R.id.surface_view);
    surface.setTransparent(true);
    surface.setRenderMode(ISurface.RENDERMODE_WHEN_DIRTY);
    surface.setFrameRate(60);

    mRenderer = new OpengGLRenderer(this);

    surface.setSurfaceRenderer(mRenderer);
    surface.setZOrderMediaOverlay(true); // i'm setting it here because only after setSurfaceRenderer call setZOrderOnTop(true) is called
}
```

XML looks something like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/root_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/background">

    <FrameLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:padding="1dp"
        android:background="@drawable/border">

        <com.google.android.cameraview.CameraView
            android:id="@+id/camera"
            android:layout_width="@dimen/camera_view_width"
            android:layout_height="@dimen/camera_view_height"
            android:keepScreenOn="true" />
    </FrameLayout>

    <org.rajawali3d.surface.SurfaceView
        android:id="@+id/surface_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <View
        android:id="@+id/ring"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:layout_gravity="center"
        android:background="@drawable/ring" />
</FrameLayout>
```

I get a black background with no camera preview. But the ring view is on top of GLSurfaceView, which is good:

![screenshot_20170608-113555](https://user-images.githubusercontent.com/8386565/26919876-d213c26a-4c3f-11e7-915e-deefa43d8379.png)

When I remove the `setZOrderMediaOverlay(true)`, the background is no longer black and the camera preview is visible:

![screenshot_20170608-113424](https://user-images.githubusercontent.com/8386565/26919942-147602d0-4c40-11e7-89e3-294a267b15c2.png)

But then the ring view is also behind `GLSurfaceView` (which would be the same if I used a button).

Well, I thought that this was not possible according to this [post](https://stackoverflow.com/questions/25983784/add-view-on-top-of-transparent-surfaceview). So I thought the solution might be to use a `TextureView`. But I don't know how to make it transparent because the alpha is ignored and the camera preview is not visible.

**Comment by jwoolston** [comment]
It is not possible to have a transparent texture view

**Comment by emjei** [comment]
Ok. Got it. Thank you for your help. I'm closing the issue.

**Comment by inder243** [comment]
You Can try this solution:

 Paint mpaintTexture = new Paint();
 mpaintTexture.setAlpha(0.5f);
 textureView.setLayerType(View.LAYER_TYPE_HARDWARE,mpaintTexture);
 textureView.setLayerPaint(mpaintTexture);

**Comment by Asad-noor** [comment]
> You Can try this solution:
> 
> Paint mpaintTexture = new Paint();
> mpaintTexture.setAlpha(0.5f);
> textureView.setLayerType(View.LAYER_TYPE_HARDWARE,mpaintTexture);
> textureView.setLayerPaint(mpaintTexture);

Thanks a lot..... it really works
