### ISSUE TITLE
Unexpected DiffuseMethod.Toon() behavior

### ISSUE THREAD

**Issue by contriteobserver** [Rajawali/Rajawali#1913]
#### Rajawali Version or Branch
master

#### Summary
DuffuseMethod.Toon(int color0, int color1, int color2, int color3) does not setup shader colors as expected.

#### Steps to Reproduce
This material:
```
                Material toon = new Material();
                toon.setDiffuseMethod(new DiffuseMethod.Toon());
                toon.enableLighting(true);
                toon.setColorInfluence(0);
```
should look very similar to this material:
```
                Material toon = new Material();
                toon.setDiffuseMethod(new DiffuseMethod.Toon(0xffff7f7f, 0xff8f4f4f, 0xff6f3f3f, 0xff3f1818));
                toon.enableLighting(true);
                toon.setColorInfluence(0);
```
but they do not.
![diffusemethodtoonissue](https://user-images.githubusercontent.com/17471201/27083003-e4b3d63e-4ffb-11e7-9da4-0887a92a02db.png)

**Comment by jwoolston** [comment]
Resolved via #1914. Thanks @contriteobserver
