### ISSUE TITLE
Unexpected Spherical Environment Mapping 

### ISSUE THREAD

**Issue by contriteobserver** [Rajawali/Rajawali#1916]
#### Rajawali Version or Branch
master

#### Summary
given a polar image like this:
![polar1](https://user-images.githubusercontent.com/17471201/27191498-c7f76a1c-51ac-11e7-91b2-892e4859284c.png)
one would expect a spherical mapping to look like this:
![device-2017-06-15-091608](https://user-images.githubusercontent.com/17471201/27191525-dce26544-51ac-11e7-8b58-35e59c1c982d.png)
unexpectedly, the spherical mapping looks like this:
![device-2017-06-15-090435](https://user-images.githubusercontent.com/17471201/27191602-1f8bcc46-51ad-11e7-834e-68509b032ae3.png)

#### Steps to Reproduce
```
        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                SphereMapTexture texture = new SphereMapTexture("env", R.drawable.polar1);
                texture.isEnvironmentTexture(true);
                Material material = new Material();
                material.addTexture(texture);
                material.setColorInfluence(0);

                obj = new Sphere(1, 24, 24);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                getCurrentCamera().setPosition(-3,-3,3);
                getCurrentCamera().setLookAt(obj.getPosition());
            }catch (Exception e) {
                Log.d(getLocalClassName() + ".initScene", e.toString());
            }
        }
```

**Comment by contriteobserver** [comment]
will leave open so until the camera Z axis rotation is addressed

**Comment by jwoolston** [comment]
> will leave open until the camera Z axis rotation is addressed

Good idea

**Comment by contriteobserver** [comment]
all done here, the camera Z axis rotation was only a cube map issue.
