### ISSUE TITLE
Test if a specific point is located in a Plane

### ISSUE THREAD

**Issue by odin-** [Rajawali/Rajawali#1925]
Rajawali 1.1.777

Is it possible to test if a specific OpenGL coordinate point is located in a `Plane` in a easy manner?

The coordinate point and plane is both located at same z position.

**Comment by contriteobserver** [comment]
You will need to specify if the "OpenGL coordinate point" is defined using screen coordinates, world coordinates, or object coordinates. Better yet, please write a small example with a empty boolean function `isLocatedInPlane(Vector3 pt, Plane plane) { return false; } ` so we can see the question in context.

**Comment by odin-** [comment]
It's normalized (?) world coordinates in the form of (-1.0, -0.1) for example.

The `Plane` is an global class object and has been added to the scene. The coordinates comes from the user touching the screen (which I've converted from screen coordinates (for example [200,1000]) to world coordinates (for example [-1.0, -0.1]).

```
private void startTouch(Vector2 vector) {
   if (mPlane.contains(vector)) {
      /* Do something */
   }
}
```

(I know it might be possible to use the (color?) object picker but I would prefer this solution for other reasons).

**Comment by contriteobserver** [comment]
which kind of camera are you using?

**Comment by odin-** [comment]
I am using `OrthographicCamera`.

**Comment by contriteobserver** [comment]
This should get you there:
```
    private class IntersectorRenderer extends Renderer {

        public IntersectorRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);
            Material yellow = new Material();
            Material cyan = new Material();
            Material magenta = new Material();
            yellow.setColor(Color.YELLOW);
            cyan.setColor(Color.CYAN);
            magenta.setColor(Color.MAGENTA);

            Cube alpha = new Cube(1);
            alpha.setName("alpha");
            alpha.setPosition(0,0,0);
            alpha.setMaterial(yellow);
            getCurrentScene().addChild(alpha);

            Cube beta = new Cube(1);
            beta.setName("beta");
            beta.setPosition(3,3,0);
            beta.setMaterial(cyan);
            getCurrentScene().addChild(beta);

            Cube gamma = new Cube(1);
            gamma.setName("gamma");
            gamma.setPosition(-3,-3,0);
            gamma.setMaterial(magenta);
            getCurrentScene().addChild(gamma);

            orthographicCamera.setZoom(6);
            getCurrentScene().addAndSwitchCamera(orthographicCamera);
        }

        @Override
        public void onOffsetsChanged(float v, float v1, float v2, float v3, int i, int i1) {

        }

        @Override
        public void onTouchEvent(MotionEvent motionEvent) {
            double x = motionEvent.getX()/getViewportWidth();
            double y = motionEvent.getY()/getViewportHeight();
            double aspect_ratio = (double)getViewportWidth()/(double)getViewportHeight();
            x -= 0.5f;
            y -= 0.5f;
            x *= 2;
            y *= -2;
            x *= orthographicCamera.getZoom()*aspect_ratio;
            y *= orthographicCamera.getZoom();

            Vector3 rayStart = new Vector3(x,y,orthographicCamera.getNearPlane()-orthographicCamera.getPosition().z);
            Vector3 rayEnd = new Vector3(x,y,orthographicCamera.getFarPlane()-orthographicCamera.getPosition().z);
            for(Object3D child : getCurrentScene().getChildrenCopy()) {

                BoundingSphere boundingSphere = child.getGeometry().getBoundingSphere();
                boundingSphere.transform(child.getModelMatrix());
                Vector3 position = boundingSphere.getPosition();
                double radius = boundingSphere.getRadius();

                Boolean found = Intersector.intersectRaySphere(rayStart, rayEnd,  position, radius, new Vector3());
                if(found) {
                    Log.d(getLocalClassName(), "found " + child.getName());
                }
            }
        }
    }
```

**Comment by odin-** [comment]
Thanks. A question: 

Why use `getBoundingSphere` instead of `getBoundingBox`?

**Comment by contriteobserver** [comment]
`Intersector.intersectRayPlane` may not be what you think, it uses `org.rajawali3d.math.Plane` (infinite extent) not `org.rajawali3d.primitives.Plane` (constrained extent).

**Comment by odin-** [comment]
OK so I guess there's no built in easy function to use?

Since I know the X, Y, height and width of each rectangle (6 `Planes` each) I could probably just iterate and find the correct one myself.

**Comment by contriteobserver** [comment]
`Intersector.intersectRaySphere` does provide the point of intersection, which allows for mechanisms to further refine behaviour after the top level search.

**Comment by odin-** [comment]
When I tried `Intersector.intersectRaySphere` my problem was that I could not detect click of the full rectangle (actually the front `Plane` of the rectangle). I.e. the corners of the `Plane` wasn't clickable. My believe was that this is because `Intersector.intersectRaySphere` uses a radius?

Although I tried this in the emulator with a pointer so I was of course able to click exactly on a specific point anywhere on the `Plane`.

**Comment by contriteobserver** [comment]
I am confused, one should be able to click on the corners, `Geometry.getBoundingSphere()` returns the [circumscribed sphere](https://en.wikipedia.org/wiki/Circumscribed_sphere):
- `Plane(3,4,1,1)` the radius is `5/2`
- `Plane(12,5,1,1)` the radius is `13/2`
- `Plane(8,15,1,1)` the radius is `17/2`

Please explain how the corners of the `Plane` are not clickable.

**Comment by odin-** [comment]
My tiles which consists of 6 Planes and has a `Object3D` as root. The root object in turn is placed in another holder (holding multiple tiles). So all the positions on the tile planes are relative to the root which is in turn relative to the holder. Could this be the problem? I am iterating through each `Plane` of each tile:

```
        for (int x = 0; x < object.getNumChildren(); x++) {
            Object3D tile = object.getChildAt(x);

            for (int y = 0; y < tile.getNumChildren(); y++) {
                Plane face = (Plane)tile.getChildAt(y);

                BoundingSphere boundingSphere = face.getGeometry().getBoundingSphere();
                boundingSphere.transform(face.getModelMatrix());
                Vector3 position = boundingSphere.getPosition();
                double radius = boundingSphere.getRadius();
                boolean found = Intersector.intersectRaySphere(
                        rayStart, rayEnd, position, radius, new Vector3());

                if (found) {
                    Log.d(TAG, "found " + tile.getName());
                    return tile;
                }
            }
        }
```
![capture](https://user-images.githubusercontent.com/7396319/27882237-2c907192-61cc-11e7-9989-d0727e75cbc2.PNG)

**Comment by contriteobserver** [comment]
Have the planes been scaled? If so, use `BoundingSphere.getScaledRadius()` to get the radius.

**Comment by odin-** [comment]
Sorry for a stupid question but wouldn't the bounding sphere overlap on the next tile to be able to incapsulate the corners of the rectangle?

When I click 'T' to the left edge for example I get a hit on the 'I' rectangle.

**Comment by contriteobserver** [comment]
Yes, it will, bot `T` and `I` will get a hit, that is why we have the fifth parameter. The fifth parameter is used to return the `hitPosition`, which allows for mechanisms to further refine behaviour after the top level search. However, you will need a recent build, as there was a bug in this which was only recently patched with #1933

**Comment by odin-** [comment]
Took me a while to understand but you mean since it's a sphere. That's smart :-). 

One downside to the approach however is that the user could actually press outside the tile and still "touch" it, but I guess I could have a mechanism to disallow that by "throwing away" touches on a specific Z-point behind the tile.

What do you think about porting the `intersectRayBounds` from `libgdx`? Would that be easier for me?

**Comment by contriteobserver** [comment]
The addition of `intersectRayBounds` should be a separate feature request.

**Comment by odin-** [comment]
I've opened a new "feature request". Thanks for your help. It's really appriciated.
