### ISSUE TITLE
Vuforia does not work on Android 6.0+

### ISSUE THREAD

**Issue by fgnm** [Rajawali/Rajawali#1939]
#### Rajawali Version or Branch
Any Rajawali Version (v0.9 included).

#### Device and Android Version
Tested with errors on OnePlus 3 (Android 7.1.1) and OnePlus One (Android 6.0). Instead works fine on Redmi Note 3 running Android 5.0

#### Summary
Vuforia libs does not works with Android 6.0+ due to some android changes, since 2015 Vuforia libs are not being updated. As you can see in log output "libVuforia.so: has text relocations", this error is ignored and considered a warning prior 6.0. This error could be fixed upgrading Vuforia libs from old 3.0.9 to 6.2.10.

#### Steps to Reproduce
Run Vuforia example on a device running Android 6.0+

#### Trace or Log Output
```
07-03 17:52:18.659 7394-7394/org.rajawali3d.examples E/linker: /data/app/org.rajawali3d.examples-1/lib/arm/libVuforia.so: has text relocations
07-03 17:52:18.660 7394-7394/org.rajawali3d.examples E/Rajawali: The library libVuforia.so could not be loaded
07-03 17:52:18.662 7394-7394/org.rajawali3d.examples E/linker: /data/app/org.rajawali3d.examples-1/lib/arm/libVuforia.so: has text relocations
07-03 17:52:18.663 7394-7394/org.rajawali3d.examples E/Rajawali: The library libRajawaliVuforia.so could not be loaded
```

**Comment by jwoolston** [comment]
This is actually an issue with Android 5 too. There is little we can do about it because the licensing terms of the updated libraries changed are not compatible with how we distribute Vuforia currently. Fixing this has not been of particularly high priority right now but eventually we will incorporate two options - a distribution process that is compatible with the new Vuforia and an implementation of a wrapper for VRToolkit.

**Comment by fgnm** [comment]
Well not all 5.0, with some MIUI Vuforia works :)
Anyway a proper Java/C wrapper for new Vuforia even without linking latest libs would be very appreciated, thank you!

**Comment by ShaishavJogani** [comment]
Did anyone find the solution to this or any workaround? Without solving this, Rajawali's vuforia AR feature is completely useless.
