### ISSUE TITLE
Bad appearance 3D model into SurfaceView or CRASH

### ISSUE THREAD

**Issue by kovac777** [Rajawali/Rajawali#1954]
#### Device and Android Version
Android Emulator Nexus 10 SDK25

#### Summary
Bad appearance 3D model when xml layout contains two SurfaceViews (RajawaliSurfaceView) or CRASH app. But when I use one SurfaceView in my layout than all worked perfectly

#### Steps to Reproduce
My xml layout file
`    
<?xml version="1.0" encoding="utf-8"?>
    <android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.user.test3d.MainActivity">

    <org.rajawali3d.view.SurfaceView
        android:id="@+id/svFront"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginBottom="8dp"
        android:layout_marginLeft="8dp"
        android:layout_marginTop="8dp"
        app:frameRate="60"
        app:layout_constraintBottom_toTopOf="@+id/guideline"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:renderMode="RENDER_WHEN_DIRTY"
        app:layout_constraintVertical_bias="0.0"
        app:layout_constraintRight_toLeftOf="@+id/guideline2"
        android:layout_marginRight="8dp"/>

    <org.rajawali3d.view.SurfaceView
        android:id="@+id/svTop"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginBottom="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginTop="8dp"
        app:frameRate="60"
        app:layout_constraintBottom_toTopOf="@+id/guideline"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:renderMode="RENDER_WHEN_DIRTY"
        android:layout_marginLeft="8dp"
        app:layout_constraintLeft_toLeftOf="@+id/guideline2"/>

    <android.support.constraint.Guideline
        android:id="@+id/guideline"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:layout_constraintGuide_percent="0.7"/>

    <android.support.constraint.Guideline
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/guideline2"
        app:layout_constraintGuide_percent="0.5"
        android:orientation="vertical"/>

    </android.support.constraint.ConstraintLayout>
`

My Java file
`    
    public class MainActivity extends AppCompatActivity {

    private SurfaceView svFront, svTop;
    private RendererFront rendererFront, rendererTop;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        svFront = (SurfaceView) findViewById(R.id.svFront);
        svTop = (SurfaceView) findViewById(R.id.svTop);

        rendererFront = new RendererFront(this);
        rendererTop = new RendererFront(this);
    }
    }
`

#### Trace or Log Output
**SOMETIMES GENERATING IN LOGCAT -** `E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glUseProgram:1556 GL error 0x501` 
**SOMETIMES CRASH WITH**
    `E/AndroidRuntime: FATAL EXCEPTION: GLThread 280
                                                                         Process: com.example.user.test3d, PID: 24589
                                                                         java.lang.IllegalArgumentException: string == null
                                                                             at android.opengl.GLES20.glShaderSource(Native Method)
                                                                             at org.rajawali3d.materials.Material.loadShader(Material.java:758)
                                                                             at org.rajawali3d.materials.Material.createProgram(Material.java:783)
                                                                             at org.rajawali3d.materials.Material.createShaders(Material.java:703)
                                                                             at org.rajawali3d.materials.Material.reload(Material.java:491)
                                                                             at org.rajawali3d.materials.MaterialManager.taskReload(MaterialManager.java:72)
                                                                             at org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(Renderer.java:367)
                                                                             at org.rajawali3d.view.SurfaceView$RendererDelegate.onSurfaceChanged(SurfaceView.java:232)
                                                                             at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
                                                                             at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)`

**Comment by contriteobserver** [comment]
You need to call `SurfaceView.setSurfaceRenderer()`, this should get you there:
```
public class GuidelineActivity extends AppCompatActivity {
    private SurfaceView svFront, svTop;
    private RendererFront rendererFront, rendererTop;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_guideline);

        svFront = (SurfaceView) findViewById(R.id.svFront);
        svTop = (SurfaceView) findViewById(R.id.svTop);

        rendererFront = new RendererFront(this);
        rendererTop = new RendererFront(this);

        svFront.setSurfaceRenderer(rendererFront);
        svTop.setSurfaceRenderer(rendererTop);
    }

    class RendererFront extends Renderer {
        public RendererFront(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            Object3D cube = new Cube(1);
            cube.setMaterial(new Material());
            getCurrentScene().addChild(cube);

            Animation3D anim = new RotateOnAxisAnimation(Vector3.Axis.Y, 360);
            anim.setTransformable3D(cube);
            anim.setRepeatMode(Animation.RepeatMode.INFINITE);
            anim.setDurationMilliseconds(12345);
            anim.play();
            getCurrentScene().registerAnimation(anim);
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
}
```
