### ISSUE TITLE
Pick Object3D

### ISSUE THREAD

**Issue by kovac777** [Rajawali/Rajawali#1956]
#### Rajawali Version or Branch
1.1.777

#### Summary
I`m trying pick Object3D and i followed this tutorial https://github.com/Rajawali/Rajawali/wiki/v0.9-Tutorial-12-Object-Picking , but method onObjectPicked(@NonNull Object3D object ) of OnObjectPickedListener is never called.

**This worked perfectly** when I use primitive Object3D (test with Cube), **but not** with parsed 3D model. 

    public class MainActivity extends AppCompatActivity {

    private TextureView textureView;
    private MyRenderer myRenderer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        textureView = (TextureView) findViewById(R.id.tvFront);
        textureView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                if (motionEvent.getAction() == MotionEvent.ACTION_DOWN) {
                    myRenderer.getObjectAt(motionEvent.getX(), motionEvent.getY());
                }
                return MainActivity.super.onTouchEvent(motionEvent);
            }
        });

        myRenderer = new MyRenderer(this);
        textureView.setSurfaceRenderer(myRenderer);

    }
}

    public class MyRenderer extends Renderer implements OnObjectPickedListener {

    private Context context;
    private DirectionalLight directionalLight;
    private Object3D object3D;

    private ObjectColorPicker picker;
    
    public MyRenderer(Context context) {
        super(context);
        this.context = context;
    }

    public MyRenderer(Context context, boolean registerForResources) {
        super(context, registerForResources);
        this.context = context;
    }

    @Override
    protected void initScene() {
        directionalLight = new DirectionalLight(1.0, 0.2, -1.0);
        directionalLight.setColor(1.0f, 1.0f, 1.0f);
        directionalLight.setPower(2.0f);
        getCurrentScene().addLight(directionalLight);

        LoaderOBJ loaderTable = new LoaderOBJ(this, R.raw.trees_obj);
        try {
            loaderTable.parse();
        } catch (ParsingException e) {
            e.printStackTrace();
        }

        object3D = loaderTable.getParsedObject();
        getCurrentScene().addChild(object3D);

        getCurrentCamera().setZ(4.2f);

        picker = new ObjectColorPicker(this);
        picker.setOnObjectPickedListener(this);
        picker.registerObject(object3D);
    }

    @Override
    public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

    }

    @Override
    public void onTouchEvent(MotionEvent event) {

    }

    @Override
    public void onObjectPicked(@NonNull Object3D object) {
        //never called when load .obj files
        Log.d("logi", "MyRenderer -> onObjectPicked : ");
    }

    @Override
    public void onNoObjectPicked() {
    }

    public void getObjectAt(float x, float y) {
        picker.getObjectAt(x, y);
    }
}

model --- [3dmodel.zip](https://github.com/Rajawali/Rajawali/files/1162493/3dmodel.zip)

Can you help me?

**Comment by jwoolston** [comment]
We are going to need far more information than you have provided. What you state indicates there is a high probability with your code handling the parsed object, so you will need to post it for us to make any sense of what the problem might be.

**Comment by kovac777** [comment]
I just added code above

**Comment by contriteobserver** [comment]
`LoaderOBJ` only loads a subset of [Wavefront .obj](https://en.wikipedia.org/wiki/Wavefront_.obj_file) features. In specific, `LoaderObj` only parses quads and triangles, `trees_obj` contains faces with more than four sides. We can proceed further once you have updated `3dmodel.zip` accordingly.
