### ISSUE TITLE
Question: Why not assign CubeMapTexture to mSkyboxTexture in Scene.java's setSkybox(Bitmap[] bitmaps) method?

### ISSUE THREAD

**Issue by dzbx** [Rajawali/Rajawali#1959]
#### Rajawali Version or Branch
1.1.970

#### Summary
In Scene.java, the method setSkybox(int resourceId) and setSkybox(int posx, int negx, int posy, int negy, int posz, int negz) both have 
`mSkyboxTexture = new Texture(xxxx) `
but the setSkybox(Bitmap[] bitmaps) method only do 
`final CubeMapTexture texture = new CubeMapTexture("bitmap_skybox", bitmaps);`
not assign the CubeMapTexture to mSkyboxTexture.
Because of this, I can't use updateSkybox(Bitmap[] bitmaps) method if I use setSkybox(Bitmap[] bitmaps) firstly. It throws Nullpointer Exception beceuse mSkyboxTexture is null.

**Comment by contriteobserver** [comment]
does pull request #1909 address your issue?

**Comment by dzbx** [comment]
Oh, yes
