### ISSUE TITLE
Question : synchronize video in 2 devices 

### ISSUE THREAD

**Issue by riadhnet** [Rajawali/Rajawali#1963]
Hello guys , I'm playing the same video on 2 devices (using rajawali cardboard) , in the device number 1 is using the sensors to orient the camera, in the device number 2 i try to show the same as device 1 (disabling sensors in device 2 ) 

this is my code in device 1 
` Override
    public void onDrawEye(Eye eye) {
        super.onDrawEye(eye);
               Matrix4 eyeMatrix = new Matrix4();
            Quaternion eyeQuaternion = new Quaternion();
            eyeMatrix.setAll(eye.getEyeView());
            eyeQuaternion = eyeQuaternion.fromMatrix(eyeMatrix);

            eyeQuaternion.x = eyeQuaternion.x * -1 ;
            eyeQuaternion.y = eyeQuaternion.y * -1 ;
            eyeQuaternion.w = eyeQuaternion.w * -1 ;
            eyeQuaternion.z = eyeQuaternion.z * -1 ;

            BtMessage btMessage = new BtMessage();
            btMessage.setType(Constants.MESSAGE_TYPE.move_camera);
            btMessage.setContent(new Gson().toJson(eyeQuaternion));

            app.sendMessage(mContext, (new Gson().toJson(btMessage)));
        
    }`

and in device 2 
`   public void moveCamera(Quaternion eyeQuaternion){
        getCurrentCamera().setOrientation(eyeQuaternion);
    }`

in the beginning , device 2 was looking wrong , then after multiplying by -1 the Quaternion values , it started to look good except of right / left, it's inverted , when device 1 looks to the right, device 2 looks to the left , 
(top / bottom are fine )
Any suggestions ? 

Thanks

**Comment by rami-dabain** [comment]
try conjugate

**Comment by riadhnet** [comment]
didn't work , view was worst with only conjugate

**Comment by rami-dabain** [comment]
did you try getOrientation on device1 and setOrientation on device 2 ?

Kind regards ,
Rami Dabain

**Comment by riadhnet** [comment]
device 1 send "getCurrentCamera().getOrientation()"

device 2 :  getCurrentCamera().setOrientation(receivedOrientation)

didn't work too

**Comment by rami-dabain** [comment]
If that didn't work, it is possible that the problem is in another palce
int he code not related to that, check you up axis and positions. can't
help more sorry man

**Comment by riadhnet** [comment]
thanks you for your help , hope to find a solutions soon

**Comment by riadhnet** [comment]
Could the problem of left/right do to my 360 video sphere ? 
Sphere sphere = new Sphere(1, 24, 24);
        sphere.setPosition(0, 0, 0);
        sphere.setScaleX(100);
        sphere.setScaleY(100);
        sphere.setScaleZ(100);

**Comment by riadhnet** [comment]
For anyone wondering : i made it working after setting a rotation in the device 2 

getCurrentCamera().setOrientation(eyeQuaternion);
getCurrentCamera().rotate(Vector3.Y,180);

and keeping the -1 in the first device 
 eyeQuaternion.x = eyeQuaternion.x * -1 ;
 eyeQuaternion.y = eyeQuaternion.y * -1 ;
 eyeQuaternion.z = eyeQuaternion.z * -1 ;
eyeQuaternion.w = eyeQuaternion.w * -1 ;
