### ISSUE TITLE
Add StreamingTexture and normal Texture to an Plane?

### ISSUE THREAD

**Issue by yeyezizhi** [Rajawali/Rajawali#1966]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.777@aar

#### Device and Android Version
huawei honor 6, android 6.0

#### Summary
I want to add an audio to a plane and add another image texture at the same time. I have successfully added the StreamingTexture to the plane, but the app cashes after i added another image texture. So i want to know whether i can add two texture to the same object.  Any advice would be appreciated!

**Comment by contriteobserver** [comment]
In 1.1.777 it is possible to add two video or two image textures to a material.
However, there is an issue when adding an image and video texture to a material.
/pull request #1967 addresses the mapping of mixed (image and video) textures.

**Comment by yeyezizhi** [comment]
Thanks for your reply! I'll try it.
