### ISSUE TITLE
Screen shot of 3D model

### ISSUE THREAD

**Issue by galazkapatryk** [Rajawali/Rajawali#1972]
#### Rajawali Version or Branch
Last one

#### Device and Android Version
All

#### Summary
Hi,
I want to take screenshot from my camera when model is showing. But I can't catch 3D model at my activity screenshot. Is there any possibility to catch bitmap from current model state ?

**Comment by jwoolston** [comment]
Take a look at the `ScreenGrab` class. Note that whether you use this class or some other implementation, at some point to get the 3D render it will need to use `GLES20.glReadPixels()` which means it must be called from the GL thread.

**Comment by galazkapatryk** [comment]
@jwoolston Do you have any other ideas ? Because catching it with ScreenGrab return black blank screen, caching SurfaceView did the same

**Comment by jwoolston** [comment]
@galazkapatryk  are you certain you called it from the GL thread?

**Comment by sumitsahoo** [comment]
How do we make sure it runs on GL thread ? I am also trying this and placed a method inside CustomRenderer class.

**Comment by jwoolston** [comment]
There are several ways, the easiest is to put it in `onRender()` _BEFORE_ your call to `super.onRender()`. Note that this will grab the previous frame, not the one you are about to render.

**Comment by sumitsahoo** [comment]
@jwoolston Yep if placed inside `onRender()` it works but any idea how to implement the same if we need to take the screen grab on demand ? For example on tap of a button from Activity ?

**Comment by jwoolston** [comment]
What you are asking about there is Java inter thread communication and the options are too numerous to list here. At the simplest end you  have a method which sets a volatile boolean flag, to more complex task queues. The right choice depends on the demand and what you expect your other threads to do in the meantime.

**Comment by sumitsahoo** [comment]
Well I found a simple solution. Instead of SurfaceView I used TextureView and it has a method to get a Bitmap. Here is the code that I wrote to get and save the screenshot to SD card.

Use TextureView : 

```
textureView = new TextureView(this);
textureView.setRenderMode(ISurface.RENDERMODE_CONTINUOUSLY);
((LinearLayout) renderView).addView(textureView);
customObjRenderer = new CustomObjRenderer(this, objResourceId, renderView);
textureView.setSurfaceRenderer(customObjRenderer);
```
Get the screenshot : 

```
String path = Util.getStorageDirectoryPath();
Bitmap bitmap = textureView.getBitmap();

boolean isSuccess = Util.saveBitmapToSdCard(bitmap, path, Bitmap.CompressFormat.PNG, 100);

String bitmapPath = MediaStore.Images.Media.insertImage(getContentResolver(), bitmap,"title", null);
Uri bitmapUri = Uri.parse(bitmapPath);
Intent intent = new Intent(Intent.ACTION_SEND);
intent.setType("image/png");
intent.putExtra(Intent.EXTRA_STREAM, bitmapUri );
startActivity(intent);
```

And here is the code that I added to my `Utils` class which saves the Bitmap to SD card in PNG format : 

```
public static boolean saveBitmapToSdCard(Bitmap bitmap, String path, Bitmap.CompressFormat compressFormat, int quality) {

        File file = new File(path);

        try {
            file.createNewFile();
            FileOutputStream fos = new FileOutputStream(file);
            bitmap.compress(compressFormat, quality, fos);

            fos.flush();
            fos.close();
            return true;
        } catch (IOException e) {
            e.printStackTrace();
        }

        return false;
    }
```

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
