### ISSUE TITLE
[Support] - Fill color inside a shape

### ISSUE THREAD

**Issue by mrkey1996** [Rajawali/Rajawali#1975]
I used a list of points, i can use line3d to draw them to a shape, how can i fill color inside the shape.

![screenshot_2017-09-09-16-18-42-987_org rajawali3d examples 1](https://user-images.githubusercontent.com/14037475/30238906-f29516ea-957a-11e7-8477-baa0346990c6.png)

**Comment by TBog** [comment]
Generate triangles from the points in order then draw the triangles

**Comment by contriteobserver** [comment]
you may find [jdelaunay](https://github.com/orbisgis/jdelaunay) to be of help.

**Comment by mrkey1996** [comment]
thanks @TBog, i already have solution for this by generating triangles,
