### ISSUE TITLE
Transparent material/texture

### ISSUE THREAD

**Issue by aresares** [Rajawali/Rajawali#1979]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.970

#### Device and Android Version
API 25

Im trying to create a transparent material with no success

```
AlphaMapTexture alphaMap = new AlphaMapTexture("alphaMap", R.drawable.trans);
Material m = new Material();
m.addTexture(alphaMap);
```
where trans.png is BLACK. When I apply this to the object3D it become RED.

```
Object3D points3D=new Object3D();
points3D.setTransparent(true);
points3D.setDoubleSided(true);
points3D.setMaterial(m);
```

I also tried `points3D.setMaterial(new Material(AMaterial.ALPHA_MASKING))` but it cant resolve AMaterial

**Comment by contriteobserver** [comment]
Having trouble reproducing your behaviour, what is wrong with this code?
```

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                DirectionalLight key = new DirectionalLight(-3,-4,-5);
                key.setPower(2);
                getCurrentScene().addLight(key);

                AlphaMapTexture alphaMap = new AlphaMapTexture("alphaMap", R.drawable.checkerboard);
                Material m = new Material();
                m.addTexture(alphaMap);

                obj = new Plane(2,2,2,2);
                obj.setTransparent(true);
                obj.setDoubleSided(true);
                obj.setMaterial(m);
                getCurrentScene().addChild(obj);

                getCurrentCamera().setPosition(3,3,3);
                getCurrentCamera().setLookAt(obj.getPosition());
            } catch (Exception e) {
                Log.d(getLocalClassName() + ".initScene", e.toString());
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```
![device-2017-09-15-102104](https://user-images.githubusercontent.com/17471201/30495341-828ec384-9a00-11e7-85a7-59ac72ce90c7.png)

**Comment by jwoolston** [comment]
I think the issue you are having is this is an alpha map texture, which means the pixel is either on or off. The  "white" areas from the alpha map are red because that is the default in rajawali and you have not specified anything different.

**Comment by jwoolston** [comment]
If you want the white areas to be white, the simplest way would be to add:

```java
material.setColor(Color.WHITE);
material.setColorInfluence(1.0f);
```

**Comment by jwoolston** [comment]
Alternatively, you can use the same image in a diffuse texture. In order to not duplicate the memory of the bitmap, i suggest loading it manually first then creating the two textures from the one bitmap rather than creating the textures from the resource id.

**Comment by aresares** [comment]
Thanks all, I solved using a Fragment shader
