### ISSUE TITLE
Why scene turns upside down when apply EffectsPass

### ISSUE THREAD

**Issue by peterrichardc** [Rajawali/Rajawali#1980]
Why my scene turns upside down when apply FXAAPass[Anti-Aliasing]? 

Im setting FXAAPass in my scene, but after apply my scene turns upside down...

    @Override
    protected void initScene() {
        sceneRoom = new Scene(this);

        DirectionalLight mDirectionalLight = new DirectionalLight(1f, .2f, -1.0f);
        mDirectionalLight.setColor(1.0f, 1.0f, 1.0f);
        mDirectionalLight.setPower(2);
        sceneRoom.addLight(mDirectionalLight);

        //Add Objects.
        addRoomObj();
        addBedObj();

        //Set Camera Pos.
        sceneRoom.getCamera().setPosition(0, 8, 30);
        replaceAndSwitchScene(getCurrentScene(), sceneRoom);

        //Anti analising <<<<<<<<<<<<<<<<<<<<<<<<<<<<< HERE \/
        postProcessingManager = new PostProcessingManager(this);
        RenderPass renderPass = new RenderPass(sceneRoom, sceneRoom.getCamera(), 0);
        postProcessingManager.addPass(renderPass);

        EffectPass antialiasPass = new FXAAPass();
        antialiasPass.setRenderToScreen(true);
        postProcessingManager.addPass(antialiasPass);

    }

    @Override
    protected void onRender(long ellapsedRealtime, double deltaTime) {
        //super.onRender(ellapsedRealtime, deltaTime);

        postProcessingManager.render(ellapsedRealtime, deltaTime);
    }

#### Rajawali Version or Branch
1.1.970.

#### Device and Android Version
6.0

**Comment by contriteobserver** [comment]
Cannot seem to reproduce this issue. What is wrong with this test code:
```
        @Override
        protected void initScene() {
            Scene scene = new Scene(this);

            scene.setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-3,-4,-5);
            key.setPower(2);
            scene.addLight(key);

            LoaderOBJ loader = new LoaderOBJ(getResources(), getTextureManager(), R.raw.up01_obj);
            try {
                loader.parse();
                obj = loader.getParsedObject();
                obj.setScale(0.3f);
                scene.addChild(obj);
            } catch (ParsingException e) {
                e.printStackTrace();
            }

            scene.getCamera().setPosition(3,3,3);
            scene.getCamera().setLookAt(obj.getPosition());
            replaceAndSwitchScene(getCurrentScene(), scene);

            boolean useFXAA = true;
            //Anti analising <<<<<<<<<<<<<<<<<<<<<<<<<<<<< HERE \/
            if(useFXAA) {
                PostProcessingManager postProcessingManager = new PostProcessingManager(this);
                RenderPass renderPass = new RenderPass(scene, getCurrentCamera(), 0);
                postProcessingManager.addPass(renderPass);

                EffectPass antialiasPass = new FXAAPass();
                antialiasPass.setRenderToScreen(true);
                postProcessingManager.addPass(antialiasPass);
            }
        }
```
![device-2017-09-24](https://user-images.githubusercontent.com/17471201/30781086-b468ff2c-a0cd-11e7-939f-3d08f0227cbc.png)

**Comment by peterrichardc** [comment]
You need override:

    @Override
    protected void onRender(long ellapsedRealtime, double deltaTime) {
        //super.onRender(ellapsedRealtime, deltaTime);
        postProcessingManager.render(ellapsedRealtime, deltaTime);
    }

**Comment by contriteobserver** [comment]
Thanks, forgot about the `onRender` override, updated example code accordingly.

Found that this issue is not limited to `FXAAPass` all `EffectPass` variants exhibit vertical transformation. Which gives us a possible interim workaround, adding 
```
BlurPass(BlurPass.Direction.VERTICAL, 0, getViewportWidth(), getViewportHeight());
```
 should restore the vertical alignment.

**Comment by jwoolston** [comment]
This is caused by the texture coordinates of screen quad and its use both in a FBO and not. Essentially it keeps getting messed with without proper testing.
