### ISSUE TITLE
OBJ Loader texture not getting applied

### ISSUE THREAD

**Issue by sumitsahoo** [Rajawali/Rajawali#1983]
#### Rajawali Version or Branch
Android N and O
Library Version : 1.1.970

#### Device and Android Version
Nexus 6, Pixel
#### Summary
I am using OBJ Loader to load an obj file with mtl and texture images. Texture images are present inside drawable-nodpi and obj and mtl present inside raw folder. In the source the texture image is getting loaded but not displayed. I have attached the 3d obj model along with mtl and texture files.

Code to load obj : 
```  
LoaderOBJ loader = new LoaderOBJ(context.getResources(), getTextureManager(), R.raw.alienware_18_obj);
        try {
            loader.parse();
        } catch (ParsingException e) {
            e.printStackTrace();
        }
        object3D = loader.getParsedObject();
        object3D.setScale(0.3f);
        getCurrentScene().addChild(object3D);
```
Source where image is loaded (line 605 LoaderOBJ.java) : 
```
if(hasTexture) {
				if(mFile == null) {
					final String fileNameWithoutExtension = getFileNameWithoutExtension(matDef.diffuseTexture);
					int id = mResources.getIdentifier(fileNameWithoutExtension, "drawable", mResourcePackage);
					int etc1Id = mResources.getIdentifier(fileNameWithoutExtension, "raw", mResourcePackage);
...
...
```
#### Steps to Reproduce
Load the obj using LoaderOBJ 

#### Trace or Log Output

[Alienware.zip](https://github.com/Rajawali/Rajawali/files/1314216/Alienware.zip)

**Comment by contriteobserver** [comment]
First step, the third line of `alienware_18_obj.obj` contained the line:
```
mtllib alienware_18_mtl.mtl
```
it should be
```
mtllib alienware_18.mtl
```
this gets us closer:
![device-2017-09-19](https://user-images.githubusercontent.com/17471201/30619538-d173bbec-9d54-11e7-86df-e16f85d71742.png)

With this change, another problem arises, log errors like:
```
09-19 16:00:32.052 28243-28262/org.tveon.komixstream.bombshellspike E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
09-19 16:00:32.052 28243-28262/org.rajawali.spike.bombshellspike E/Rajawali: Shader log: ERROR: 0:3: '.007' : Syntax error:  syntax error
                                                                                INTERNAL ERROR: no main() function!
                                                                                ERROR: 1 compilation errors.  No code generated.
09-19 16:00:32.082 28243-28262/org.rajawali.spike.bombshellspike I/Adreno: ERROR: 0:8: '.016' : Syntax error:  syntax error
                                                                              INTERNAL ERROR: no main() function!
                                                                              ERROR: 1 compilation errors.  No code generated.
09-19 16:00:32.082 28243-28262/org.rajawali.spike.bombshellspike E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
09-19 16:00:32.082 28243-28262/org.tveon.komixstream.bombshellspike E/Rajawali: Shader log: ERROR: 0:8: '.016' : Syntax error:  syntax error
                                                                                INTERNAL ERROR: no main() function!
                                                                                ERROR: 1 compilation errors.  No code generated.
09-19 16:00:32.192 28243-28262/org.rajawali.spike.bombshellspike I/Adreno: ERROR: 0:2: '.011' : Syntax error:  syntax error
                                                                              INTERNAL ERROR: no main() function!
                                                                              ERROR: 1 compilation errors.  No code generated.
09-19 16:00:32.192 28243-28262/org.rajawali.spike.bombshellspike E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
09-19 16:00:32.192 28243-28262/org.rajawali.spike.bombshellspike E/Rajawali: Shader log: ERROR: 0:2: '.011' : Syntax error:  syntax error
                                                                                INTERNAL ERROR: no main() function!
                                                                                ERROR: 1 compilation errors.  No code generated.
```
Are you seeing this issue at your end, or it is just this device?

**Comment by jwoolston** [comment]
The compilation errors are due to some of the material names - I'm guessing the periods. I thought the parser removed them but apparently not. Try removing them from the file

**Comment by contriteobserver** [comment]
After one replaces the periods on the material and object names. One finds that there are six sided polygons in `Plane.002_Plane.008`, `LoaderOBJ.parse()` only handles triangles and quads. Fix those as well, and one get what looks like the desired result:
![device-2017-09-20](https://user-images.githubusercontent.com/17471201/30626359-1b1dfa68-9d7e-11e7-9b8b-0ecacae5d2db.png)

**Comment by sumitsahoo** [comment]
@contriteobserver Yep that log I also got those error log. So can you please tell me what to replace to get the desired output ?

**Comment by contriteobserver** [comment]
Replaced 
- `Material.` with `Material_`, 
- `Plane.` with `Plane_`
- `Untitled.` with `Untitled_`
and then triangulated the six sided polygons in `Plane.002_Plane.008`

**Comment by sumitsahoo** [comment]
Material, Plane and Untitled are in OBJ right ? And how do I triangulate the polygon ? Is it something that needs to be done in Blender ? Sorry I am kinda new to 3D so confused a little.

**Comment by contriteobserver** [comment]
One needs to replace the labels with periods in bot the OBJ and MTL files.
Another way is to load it up in Blender and change the mesh and material names.

To triangulate the polygons with Blender, import the model,, select `Plane.002_Plane.008`,
go into edit mode, deselect all the faces, select faces by trait, select faces by sides, set the number of sides to 6, note that a few polygons will be selected, then mesh operations, face operations, triangulate faces. Then save the result.

**Comment by jwoolston** [comment]
> To triangulate the polygons with Blender, import the model, select Plane.002_Plane.008,
> go into edit mode, deselect all the faces, select faces by trait, select faces by sides, set the number of sides to 6, note that a few polygons have been selected, then mesh operations, face operations, triangulate faces. Then save the result.

Or you can just import and export, and in the export settings check "Triangulate Faces"

**Comment by sumitsahoo** [comment]
@contriteobserver @jwoolston Thanks for the help. As suggested I have opened the blender project and exported using triangulate faces option but still error log comes and texture not visible. I guess I am doing something wrong :(

```
09-22 00:30:46.044 23913-23963/com.dell.rajawalilibexperiment I/Adreno: ERROR: 0:3: '.010' : Syntax error:  syntax error
                                                                        INTERNAL ERROR: no main() function!
                                                                        ERROR: 1 compilation errors.  No code generated.
09-22 00:30:46.044 23913-23963/com.dell.rajawalilibexperiment E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
09-22 00:30:46.044 23913-23963/com.dell.rajawalilibexperiment E/Rajawali: Shader log: ERROR: 0:3: '.010' : Syntax error:  syntax error
                                                                          INTERNAL ERROR: no main() function!
                                                                          ERROR: 1 compilation errors.  No code generated.
09-22 00:30:46.055 23913-23963/com.dell.rajawalilibexperiment I/Adreno: ERROR: 0:3: '.007' : Syntax error:  syntax error
                                                                        INTERNAL ERROR: no main() function!
                                                                        ERROR: 1 compilation errors.  No code generated.
09-22 00:30:46.055 23913-23963/com.dell.rajawalilibexperiment E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
09-22 00:30:46.055 23913-23963/com.dell.rajawalilibexperiment E/Rajawali: Shader log: ERROR: 0:3: '.007' : Syntax error:  syntax error
                                                                          INTERNAL ERROR: no main() function!
                                                                          ERROR: 1 compilation errors.  No code generated.
09-22 00:30:46.060 23913-23934/com.dell.rajawalilibexperiment I/zygote64: Waiting for a blocking GC ObjectsAllocated
09-22 00:30:46.138 23913-23963/com.dell.rajawalilibexperiment I/Adreno: ERROR: 0:2: '.011' : Syntax error:  syntax error
                                                                        INTERNAL ERROR: no main() function!
                                                                        ERROR: 1 compilation errors.  No code generated.
09-22 00:30:46.138 23913-23963/com.dell.rajawalilibexperiment E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
09-22 00:30:46.138 23913-23963/com.dell.rajawalilibexperiment E/Rajawali: Shader log: ERROR: 0:2: '.011' : Syntax error:  syntax error
                                                                          INTERNAL ERROR: no main() function!
                                                                          ERROR: 1 compilation errors.  No code generated.
09-22 00:30:46.240 23913-23963/com.dell.rajawalilibexperiment I/Adreno: ERROR: 0:8: '.016' : Syntax error:  syntax error
                                                                        INTERNAL ERROR: no main() function!
                                                                        ERROR: 1 compilation errors.  No code generated.
09-22 00:30:46.240 23913-23963/com.dell.rajawalilibexperiment E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
09-22 00:30:46.240 23913-23963/com.dell.rajawalilibexperiment E/Rajawali: Shader log: ERROR: 0:8: '.016' : Syntax error:  syntax error
                                                                          INTERNAL ERROR: no main() function!
                                                                          ERROR: 1 compilation errors.  No code generated.
```

[New Alienware.zip](https://github.com/Rajawali/Rajawali/files/1322434/New.Alienware.zip)

**Comment by jwoolston** [comment]
You did not adjust the names in Blender as @contriteobserver suggested, so you are now manifesting the original problem again where the `.` character is causing problems.

**Comment by sumitsahoo** [comment]
@jwoolston Replace label with period, does that mean `o Plane.002_Plane.008` with `o Plane.002.Plane.008` ? I am a little bit confused with the wording here. Sorry if it sounds odd but this obj and mtl is a completely new file type for me.

**Comment by jwoolston** [comment]
In the OBJ file, make sure that any entries `o`, `g`, `matlib` or `usemtl` do not include the `.` character. The one exception being in the case of the file name extension. 

In the MTL file, make sure all the material names do not include the `.` character.

**Comment by sumitsahoo** [comment]
Wow you guys rock @contriteobserver @jwoolston, Now I can see the texture. Well I surely learned a lot from you guys !! cheers :)

![device-2017-09-22-010743](https://user-images.githubusercontent.com/6181114/30715001-7e9f2908-9f32-11e7-9139-691d48dab2b7.png)
