### ISSUE TITLE
Show progress dialog while loading/parsing OBJ 

### ISSUE THREAD

**Issue by sumitsahoo** [Rajawali/Rajawali#1985]
#### Rajawali Version or Branch
v1.1.970

#### Device and Android Version
Pixel
#### Summary
I want to show a progress dialog or a loading text while the OBJ parsing happens in background but UI is not showing up somehow (until render is complete). Once I remove the surface view UI is immediately visible. 

#### Steps to Reproduce

```
SurfaceView surface = new SurfaceView(this);
surface.setRenderMode(ISurface.RENDERMODE_WHEN_DIRTY);
surface.setTransparent(true);
surface.setBackgroundColor(getResources().getColor(R.color.white));
layoutSurface.addView(surface);

customObjRenderer = new CustomObjRenderer(this, R.raw.alienware_obj);
surface.setSurfaceRenderer(customObjRenderer);

```

#### Trace or Log Output
No UI until OBJ parsing is complete.

**Comment by jwoolston** [comment]
The examples include several samples showing how to have a progress indicator while loading in the background. Additionally, there is an example showing Asynchronous loading which allows your render to continue as the loading happens.

**Comment by sumitsahoo** [comment]
Thanks for the suggestion. I got the loader to work by implementing `IAsyncLoaderCallback` in the `Renderer` class. I created a public interface inside `Renderer` class and implemented the same in `MainActivity`. After that notified the UI from `onModelLoadComplete` method from `Renderer` class.
