### ISSUE TITLE
Rajawali couldn't draw by load obj from .obj

### ISSUE THREAD

**Issue by ly20050516** [Rajawali/Rajawali#1997]
#### Rajawali Version or Branch
latest.

#### Device and Android Version
any device and android version
#### Summary
I tried to load obj from .obj,using LoaderOBJ.but there is nothing to show and no error.
and I guess it is too large (include 53215 vertex) to sharder for open gl es?

#### Steps to Reproduce
just load the .obj as LoadModelFragment

#### Trace or Log Output

[current_merged1.obj.zip](https://github.com/Rajawali/Rajawali/files/1370692/current_merged1.obj.zip)

**Comment by contriteobserver** [comment]
The model file does not provide normals. If one imports the file into blender, and then exports as an OBJ file, blender will construct a set of normals. Then the model can be rendered with:
```
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-3,-4,-5);
            key.setPower(2);
            getCurrentScene().addLight(key);

            try {
                LoaderOBJ loader = new LoaderOBJ(this, R.raw.current_merged2_obj);
                loader.parse();
                obj = loader.getParsedObject();
                obj.setScale(0.0001);
                Log.d(getLocalClassName(), "vertices=" + obj.getGeometry().getNumVertices());
                getCurrentScene().addChild(obj);
            } catch (Exception e) {
                Log.e(getLocalClassName(), e.getLocalizedMessage());
            }
            getCurrentCamera().setPosition(-40,-40,20);
            getCurrentCamera().setLookAt(obj.getPosition());
        }
```
![2017-10-10](https://user-images.githubusercontent.com/17471201/31389233-459a02e8-ad85-11e7-882c-2b797e301b00.png)

**Comment by ly20050516** [comment]
But my other file has no normal vector, and the difference is that it's not the same size。I will add normal and try it. thanks.

and is it no limit to vertex number or vertex indices for opengl ?

**Comment by jwoolston** [comment]
There is a limit, it depends on the data type of the element indecies. In rajawali it is int so the limit is the maximum int value

**Comment by ly20050516** [comment]
It can render by gldrawarray() method instead of gldrawelements()

**Comment by ly20050516** [comment]
maximum int value as follow,is it?

    @Native public static final int   MAX_VALUE = 0x7fffffff;

**Comment by jwoolston** [comment]
More specifically, `Integer.MAX_VALUE` which in Android is essentially always `2,147,483,647` or `0x7fffffff` as you say.

**Comment by ly20050516** [comment]
@contriteobserver what do you modified for current_merged1.obj 。and I try open it by blender,it can not work,nothing to render.

could you upload the current_merged2.obj you modified to me?
I still understand my other file without normal,but it can render by Rajawali and blender,as follow

[current_merged.obj.zip](https://github.com/Rajawali/Rajawali/files/1373918/current_merged.obj.zip)

**Comment by contriteobserver** [comment]
here it is, literally all I did was import current_merged1 into blender and then exported it as current_merged2.

[current_merged2.tar.gz](https://github.com/Rajawali/Rajawali/files/1374202/current_merged2.tar.gz)

**Comment by ly20050516** [comment]
Thanks @contriteobserver @jwoolston 
I have rendered the obj just by obj.setScale(0.0001),

But there is a doubt in Rajawali when LoadObj.parse() as follow. Why we need do a convert instead of putting vertex and indices array which reading from .obj into openGL.what 's target you expect.  It took much memory and time for converting it.It will be rendered if I don't do convert?

the convert as follow ：

for(int j=0; j<numObjects; ++j) {
			ObjIndexData oid = objIndices.get(j);

			int i;
			float[] aVertices 	= new float[oid.vertexIndices.size() * 3];
			float[] aTexCoords 	= new float[oid.texCoordIndices.size() * 2];
			float[] aNormals 	= new float[oid.normalIndices.size() * 3];
			float[] aColors		= new float[oid.colorIndices.size() * 4];
			int[] aIndices 		= new int[oid.vertexIndices.size()];

			for(i=0; i<oid.vertexIndices.size(); ++i) {
				int faceIndex = oid.vertexIndices.get(i) * 3;
				int vertexIndex = i * 3;
				try {
					aVertices[vertexIndex] = vertices.get(faceIndex);
					aVertices[vertexIndex+1] = vertices.get(faceIndex + 1);
					aVertices[vertexIndex+2] = vertices.get(faceIndex + 2);
					aIndices[i] = i;
				} catch(ArrayIndexOutOfBoundsException e) {
					RajLog.d("Obj array index out of bounds: " + vertexIndex + ", " + faceIndex);
				}
			}
			if(texCoords != null && texCoords.size() > 0) {
				for(i=0; i<oid.texCoordIndices.size(); ++i) {
					int texCoordIndex = oid.texCoordIndices.get(i) * 2;
					int ti = i * 2;
					aTexCoords[ti] = texCoords.get(texCoordIndex);
					aTexCoords[ti + 1] = texCoords.get(texCoordIndex + 1);
				}
			}
			for(i=0; i<oid.colorIndices.size(); ++i) {
				int colorIndex = oid.colorIndices.get(i) * 4;
				int ti = i * 4;
				aTexCoords[ti] = texCoords.get(colorIndex);
				aTexCoords[ti + 1] = texCoords.get(colorIndex + 1);
				aTexCoords[ti + 2] = texCoords.get(colorIndex + 2);
				aTexCoords[ti + 3] = texCoords.get(colorIndex + 3);
			}
			for(i=0; i<oid.normalIndices.size(); ++i){
				int normalIndex = oid.normalIndices.get(i) * 3;
				int ni = i * 3;
				if(normals.size() == 0) {
					RajLog.e("["+getClass().getName()+"] There are no normals specified for this model. Please re-export with normals.");
					throw new ParsingException("["+getClass().getName()+"] There are no normals specified for this model. Please re-export with normals.");
				}
				aNormals[ni] = normals.get(normalIndex);
				aNormals[ni+1] = normals.get(normalIndex + 1);
				aNormals[ni+2] = normals.get(normalIndex + 2);
			}

			oid.targetObj.setData(aVertices, aNormals, aTexCoords, aColors, aIndices, false);

**Comment by jwoolston** [comment]
@ly20050516 I don't understand anything in your last comment.

**Comment by ly20050516** [comment]
LoadObj.parse() took memory and time very much. I found there is a convert about vertex,indceis,normals for constructing the Geometry3D,as the code I give,they are converted aVertices,aNormal,aTexCoords,aColors,aIndices.
but Why not use the origin vertex,indceis and normal that from .obj

**Comment by jwoolston** [comment]
You need to take the time to form coherent sentences. If English is not your first language, please use Google translate to obtain a meaningful translation.

**Comment by ly20050516** [comment]
haha, I will have a try. Thank you very much

**Comment by contriteobserver** [comment]
The geometry needed for a rendering system is different from that needed by a modelling system. For example, in a rendering system, every triangle has exactly three vertices, whereas in a modelling system, vertices are shared between adjoining triangles. Thus in a modelling system, a cube has 8 vertices, in a rendering system a cube has 36 vertices.

Unfortunately, the parse time and memory usage are an inevitable part of the process.

**Comment by ly20050516** [comment]
Thank you,@contriteobserver
