### ISSUE TITLE
ndk-build.cmd finished with non-zero exit value 1

### ISSUE THREAD

**Issue by mistrydarshan99** [Rajawali/Rajawali#2000]
Hello,

When I run rajawali sample with vuforial sdk I got ndk error like **"ndk-build.cmd finished with non-zero exit value 1"**.

**Comment by jwoolston** [comment]
The version of vuforia integrated with the library is not compatible with recent Android versions and we have not updated to a more recent version of the library due to license restrictions.

**Comment by ToxicBakery** [comment]
The project can now be compiled with docker which should resolve any issues like this one going forward.
