### ISSUE TITLE
setRenderMode seems not working on RENDER_WHEN_DIRTY.

### ISSUE THREAD

**Issue by maxouille** [Rajawali/Rajawali#2006]
#### Rajawali Version or Branch
I'm using this version : 1.0.186-SNAPSHOT
    compile 'org.rajawali3d:rajawali:1.0.186-SNAPSHOT@aar'

#### Device and Android Version
Samsung Galaxy Tab S Android 6.0.1

#### Summary
setRenderMode seems not working on RENDER_WHEN_DIRTY.
When I receive data, I call requestRenderUpdate but there is a rendering continuously. Even if I comment the setFrameRate(int). 

#### Steps to Reproduce
Call requestRenderUpdate every 2 seconds and see that onRender() in Renderer is called continuously.

Thx for he help !

**Comment by contriteobserver** [comment]
Rajawali updates periodically, by default it does so at `Display.getRefreshRate()`, however, this behaviour can be overridden by calling `setFrameRate()`, which can be set to small values. When calling `RajawaliSurfaceView.setRenderMode(GLSurfaceView.RENDERMODE_WHEN_DIRTY)` the surface will update at the Rajawali rate, not the display update rate.
```
    class AnimationRenderer extends RajawaliRenderer {

        public AnimationRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            setFrameRate(1e-4);
            getCurrentScene().setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-3,-4,-5);
            key.setPower(2);
            getCurrentScene().addLight(key);

            Material material = new Material();
            material.setColor(Color.YELLOW);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.enableLighting(true);

            obj = new Cube(2);
            obj.setMaterial(material);
            getCurrentScene().addChild(obj);

            Animation3D anim = new RotateOnAxisAnimation(Vector3.Axis.Y, 360);
            anim.setDurationMilliseconds(12345);
            anim.setRepeatMode(Animation.RepeatMode.INFINITE);
            anim.setTransformable3D(obj);
            getCurrentScene().registerAnimation(anim);

            getCurrentCamera().setPosition(5,4,3);
            getCurrentCamera().setLookAt(obj.getPosition());


            anim.play();
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```

**Comment by maxouille** [comment]
Thx I'm gonna try it !!

**Comment by maxouille** [comment]
It's working fine ! Thx a lot :)
