### ISSUE TITLE
collictiondetection like the method hittest in ios

### ISSUE THREAD

**Issue by lliuzhiyongg** [Rajawali/Rajawali#2008]
#### Rajawali Version or Branch
[describe the _precise_ release version or branch and commit id, feature requests can simply specify master]. Responses such as "last one" or "latest" will not be treated seriously until it is an issue that impacts our developers.

#### Device and Android Version
[list at least one device and the version number that produced a stace trace if applicable]

#### Summary
[describe the issue or feature]

#### Steps to Reproduce
[Describe reproducable steps and sample code]

#### Trace or Log Output
[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by contriteobserver** [comment]
Rajawali can be integrated with physics packages that provide collision detection, we have a tutorial on [integration with JBox2D](https://github.com/Rajawali/Rajawali/wiki/Bombshell-02-Dynamics) which might meet your needs.

**Comment by lliuzhiyongg** [comment]
thank you very much ,is this for 3d?is there an example?

**Comment by contriteobserver** [comment]
The example is contained in the tutorial, [JBox2D](http://www.jbox2d.org/) is a 2D physics engine, which can be mapped to any plane in the Rajawali. If you need a 3D physics engine, let me know and I can prepare another tutorial using [ode4](https://github.com/tzaeschke/ode4j)j.

**Comment by lliuzhiyongg** [comment]
yeah, i need a 3d engine which is open  and matural ,if there  are matural demos it will be good.i get some problems in my programes several days. please help me and send me a email(my email:lliuzhiyongg@163.com) .waitting for you

**Comment by lliuzhiyongg** [comment]
yeah, i need a 3d engine which is open and matural ,if there are matural demos it will be good.i get some problems in my programes several days. please help me and send me an email(my email:lliuzhiyongg@163.com) .waitting for you

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
