### ISSUE TITLE
NPE on onResume()

### ISSUE THREAD

**Issue by maxouille** [Rajawali/Rajawali#2009]
#### Rajawali Version or Branch
1.0.186

#### Device and Android Version
One plus 2, 6.0.1

#### Summary
Including SurfaceView into an XML Fragment fail to inflate. The inflate in the 'onCreateView' fails.

Actually, it works when I call the fragment in the mainActivity like this : 

Fragment myFragment = new MyFragment();
FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
transaction.replace(R.id.fragment_container, myFragment);
transaction.addToBackStack(null);
transaction.commit();

However, it's not working when I call this in an OnClickListener or in the Drawer. It's weird, I don't know why this error appear right here ! 

#### Trace or Log Output
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.onResume()' on a null object reference
                                                                                   at android.opengl.GLSurfaceView.onResume(GLSurfaceView.java:562)
                                                                                   at org.rajawali3d.surface.RajawaliSurfaceView.onResume(RajawaliSurfaceView.java:89)
                                                                                   at org.rajawali3d.surface.RajawaliSurfaceView.onAttachedToWindow(RajawaliSurfaceView.java:106)

**Comment by contriteobserver** [comment]
Having trouble reproducing this issue, what is wrong with my example code?
```
public class TransactionActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_transaction);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        Fragment rajawaliFragment = new RajawaliFragment();
        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
        transaction.replace(R.id.fragment_container, rajawaliFragment);
        transaction.addToBackStack(null);
        transaction.commit();
        return super.onTouchEvent(event);
    }

    @Override
    protected void onResume() {
        Log.d(getClass().getSimpleName(), "onResume");
        super.onResume();
    }

    public static class RajawaliFragment extends Fragment {
        RajawaliSurfaceView surface;
        RajawaliRenderer renderer;

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                 Bundle savedInstanceState) {
            // Inflate the layout for this fragment
            ViewGroup rootView = (ViewGroup) inflater.inflate(
                    R.layout.fragment_transaction, container, false);
            renderer = new BasicRenderer(getContext());
            surface = rootView.findViewById(R.id.glsl_content);
            surface.setSurfaceRenderer(renderer);
            return rootView;
        }

        class BasicRenderer extends RajawaliRenderer {

            public BasicRenderer(Context context) {
                super(context);
            }

            @Override
            protected void initScene() {
                try {
                    getCurrentScene().setBackgroundColor(Color.BLUE);

                    DirectionalLight key = new DirectionalLight(-3,-4,-5);
                    key.setPower(2);
                    getCurrentScene().addLight(key);

                    Material material = new Material();
                    material.setColor(Color.YELLOW);
                    material.setDiffuseMethod(new DiffuseMethod.Lambert());
                    material.enableLighting(true);

                    Object3D obj = new Sphere(1, 24, 24);
                    obj.setMaterial(material);
                    getCurrentScene().addChild(obj);

                    getCurrentCamera().setPosition(3,3,3);
                    getCurrentCamera().setLookAt(obj.getPosition());
                }catch (Exception e) {
                    Log.d(getClass().getSimpleName() + ".initScene", e.toString());
                }

            }

            @Override
            public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

            }

            @Override
            public void onTouchEvent(MotionEvent event) {

            }
        }
    }
}
```
from the logs (filtered for onResume):
```
11-02 21:34:42.007/com.example.rajawai.transactionspike D/TransactionActivity: onResume
11-02 21:35:43.867/com.example.rajawai.transactionspike D/TransactionActivity: onResume
11-02 21:35:52.937/com.example.rajawai.transactionspike D/TransactionActivity: onResume
```

**Comment by maxouille** [comment]
Okay, I think I manage to find my mistake thanks to your working example ! 

I tried to create a renderer and setSurface Renderer in the 'onViewCreated'. I moved this code into the onCreateView and it's working fine for the moment !! :)

However, if you can explain why this return a NPE it would be awesome because I don't get it !

Thank for all !

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
