### ISSUE TITLE
why do my obj files not display as expected?

### ISSUE THREAD

**Issue by oksett** [Rajawali/Rajawali#2012]
#### Rajawali Version or Branch
I am using this dependency in my gradle, android studio 3.0
` implementation 'org.rajawali3d:rajawali:1.1.337@aar'`

#### Device and Android Version
I am using Samsung S6 Edge+ Nougat 7.0 version device

#### Summary
I try to attach jpg texture material on my custom .obj file the same as in the https://github.com/Rajawali/Rajawali/wiki/Anchor-01-Basic-Scene-Android-Studio.
My texture is not attach to my cylinder (custom .obj). I add my texture as .jpg to drawable-nodpi folder package.
Also i want to improve my touch/swipe experience - here is a good example what i want to achive
https://github.com/dbrant/ModelViewer3D
This is really good library, but not support adding textures to objects i guess.
Is it possible to achive the same experience of swipe/touch with this Rajawali library?
I want to be able to attach some texture to my cyllinder like logo, which will not be entirely cover my object - only part of it. 
#### Steps to Reproduce
Here is my code:

    public class ObjManipActivity extends AppCompatActivity {
        Renderer renderer;
        SurfaceView surface;
        ScrollListener scrollListener;
        GestureDetector scrollDetector;
        Quaternion quat;
        Boolean scroll = false;
        private float xDistance = 0;
        private float yDistance = 0;
        private DirectionalLight mDirectionalLight;
        private Object3D parsedObject;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_obj_manip);

        renderer = new ManipRenderer(getApplicationContext());
        surface = (SurfaceView) findViewById(R.id.rajawali_content);
        surface.setSurfaceRenderer(renderer);

        scrollListener = new ScrollListener();
        scrollDetector = new GestureDetector(this, scrollListener);

    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        scrollDetector.onTouchEvent(event);
        return true; 
    }

    class ManipRenderer extends Renderer {

        public ManipRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(), mTextureManager, R.raw.cylinder);
            try {
                objParser.parse();
            } catch (ParsingException e) {
                e.printStackTrace();
            }
            parsedObject = objParser.getParsedObject();
           
            mDirectionalLight = new DirectionalLight(1f, .2f, -1.0f);
            mDirectionalLight.setPower(2);
            getCurrentScene().addLight(mDirectionalLight);

            Material material = new Material();
            material.enableLighting(true);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setColorInfluence(0);
            Texture earthTexture = new Texture("Earth", R.drawable.earth_texture);
            try{
                material.addTexture(earthTexture);

            } catch (ATexture.TextureException error){
                Log.d("BasicRenderer" + ".initScene", error.toString());
            }

            parsedObject.setMaterial(material);
            getCurrentScene().addChild(parsedObject);
            getCurrentCamera().setZ(15.2f);
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            if(scroll) {
                Vector3 xAxis = renderer.getCurrentCamera().getOrientation().getXAxis();
                Vector3 yAxis = renderer.getCurrentCamera().getOrientation().getYAxis();
                Vector3 zAxis = renderer.getCurrentCamera().getOrientation().getZAxis();

                //Method to rotate the 3D model
                Quaternion x = new Quaternion(xAxis, -xDistance / 2);
                Quaternion y = new Quaternion(zAxis, -yDistance / 2);
                parsedObject.rotate(x.multiply(y));
                scroll = false;
            }
            super.onRender(ellapsedRealtime, deltaTime);
        }
    }

    public class ScrollListener extends
            GestureDetector.SimpleOnGestureListener {

        @Override
        public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
            xDistance = distanceX;
            yDistance = distanceY;
            scroll = true;
            return super.onScroll(e1, e2, distanceX, distanceY);
        
             }
        }
     }
I have also included some .obj files in raw.zip but for now only very simple 'cylinder' works somehow well - i also want to improve it with better object, e.g mugc.obj in my raw.zip attached folder. I want to have some kind of mug/cup object. Is it possible?
[raw.zip](https://github.com/Rajawali/Rajawali/files/1455662/raw.zip)

**Comment by contriteobserver** [comment]
Please, one question per issue. Suggest you rename this one, "why do my obj files not display as expected?", and then create new issues:
- how to change textures on models loaded from OBJ
- how to add decal to object
- how to improve touch/swipe experience

Notes on your mug.obj and mugc,obj
Easiest way to define textures for an OBJ file is to with the MTL file mechanism, added those to the cooked files.
[cooked.zip](https://github.com/Rajawali/Rajawali/files/1460522/cooked.zip)
The mug.obj had serious topology problems, Rajawali does not handle loose topology, which is why it did not display well, mug02 is an example of better topology.
![mug02-20171109](https://user-images.githubusercontent.com/17471201/32648316-1f7498b6-c5aa-11e7-9aa9-ad9cf9f8a248.png)
The mugc.obj was a very large model, it looks fine when scaled down, see mug03 attached.
![mug03-20171109](https://user-images.githubusercontent.com/17471201/32648332-2dbd77e4-c5aa-11e7-89f4-c0d2ef13e788.png)

**Comment by oksett** [comment]
Thanks for your response, i will start new issues in the way that you suggested.
But lastly here, i have imported the mug03.obj and with the code i have provide above it appears like this:
![mug_screenshot](https://user-images.githubusercontent.com/9077038/32649087-04dbe2ee-c5f9-11e7-84d2-3d2617fd8e03.png)

How to resolve it, to look like yours?(that actually have black coffee inside, not red :)
I've tried this without setting the material in my code above.

Thanks

**Comment by contriteobserver** [comment]
make sure that you also put the *.mtl files into the raw directory, otherwise materials get set to random values.

**Comment by oksett** [comment]
@contriteobserver when i add the mug03.mtl also, i get this error:

> Error:Execution failed for task ':app:mergeDebugResources'.
> [raw/mug03] C:\Users\user\AndroidStudioProjects\emf-android-tech-demo-3d\app\src\main\res\raw\mug03.obj	[raw/mug03] C:\Users\userk\AndroidStudioProjects\emf-android-tech-demo-3d\app\src\main\res\raw\mug03.mtl: Error: Duplicate resources

**Comment by contriteobserver** [comment]
One must rename the `*.mtl` file to `*_mtl.mtl`, it is also common to rename the `*.obj` to `*_obj.obj`, this is a workaround for android duplicate resources issues.
