### ISSUE TITLE
How to improve touch/swipe experience

### ISSUE THREAD

**Issue by oksett** [Rajawali/Rajawali#2014]
#### Rajawali Version or Branch
I am using this dependency in my gradle, android studio 3.0
implementation 'org.rajawali3d:rajawali:1.1.337@aar'

#### Device and Android Version
I am using Samsung S6 Edge+ Nougat 7.0 version device

#### Summary
I have problem with my touch/swipe experience - when i swipe right, my model shold just rotate right, same swiping left, should rotate left. Also it can rotate up on swipe up, down as swipe down, i guess nothing special.

Im looking for experience like here, for e.g swiping left: 
https://github.com/Rajawali/Rajawali/wiki/Anchor-01-Basic-Scene-Android-Studio
Here, earth is just rotating  like i want to achive it with only swiping

I also notice very good library, which also have swipe/touch experience that i am looking for:
https://github.com/dbrant/ModelViewer3D

#### Steps to Reproduce
My custom .obj model is here: 
[mug03_obj.zip](https://github.com/Rajawali/Rajawali/files/1460676/mug03_obj.zip)

My current code is here:

    public class ObjManipActivity extends AppCompatActivity {
       Renderer renderer;
       SurfaceView surface;
       ScrollListener scrollListener;
       GestureDetector scrollDetector;
       Quaternion quat;
       Boolean scroll = false;
       private float xDistance = 0;
       private float yDistance = 0;
       private DirectionalLight mDirectionalLight;
       private Object3D parsedObject;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_obj_manip);

    renderer = new ManipRenderer(getApplicationContext());
    surface = (SurfaceView) findViewById(R.id.rajawali_content);
    surface.setSurfaceRenderer(renderer);

    scrollListener = new ScrollListener();
    scrollDetector = new GestureDetector(this, scrollListener);

    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
    scrollDetector.onTouchEvent(event);
    return true; 
    }

    class ManipRenderer extends Renderer {

    public ManipRenderer(Context context) {
        super(context);
    }

    @Override
    protected void initScene() {
        LoaderOBJ objParser = new LoaderOBJ(mContext.getResources(), mTextureManager, R.raw.mug03.obj);
        try {
            objParser.parse();
        } catch (ParsingException e) {
            e.printStackTrace();
        }
        parsedObject = objParser.getParsedObject();
       
        mDirectionalLight = new DirectionalLight(1f, .2f, -1.0f);
        mDirectionalLight.setPower(2);
        getCurrentScene().addLight(mDirectionalLight);

        Material material = new Material();
        material.enableLighting(true);
        material.setDiffuseMethod(new DiffuseMethod.Lambert());
        material.setColorInfluence(0);
        Texture earthTexture = new Texture("Earth", R.drawable.earth_texture);
        try{
            material.addTexture(earthTexture);

        } catch (ATexture.TextureException error){
            Log.d("BasicRenderer" + ".initScene", error.toString());
        }

        parsedObject.setMaterial(material);
        getCurrentScene().addChild(parsedObject);
        getCurrentCamera().setZ(15.2f);
    }

    @Override
    public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

    }

    @Override
    public void onTouchEvent(MotionEvent event) {

    }

    @Override
    protected void onRender(long ellapsedRealtime, double deltaTime) {
        if(scroll) {
            Vector3 xAxis = renderer.getCurrentCamera().getOrientation().getXAxis();
            Vector3 yAxis = renderer.getCurrentCamera().getOrientation().getYAxis();
            Vector3 zAxis = renderer.getCurrentCamera().getOrientation().getZAxis();

            //Method to rotate the 3D model
            Quaternion x = new Quaternion(xAxis, -xDistance / 2);
            Quaternion y = new Quaternion(zAxis, -yDistance / 2);
            parsedObject.rotate(x.multiply(y));
            scroll = false;
        }
        super.onRender(ellapsedRealtime, deltaTime);
      }
    }

    public class ScrollListener extends
        GestureDetector.SimpleOnGestureListener {

    @Override
    public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
        xDistance = distanceX;
        yDistance = distanceY;
        scroll = true;
        return super.onScroll(e1, e2, distanceX, distanceY);
    
         }
      }
    }

#### Trace or Log Output
My current experience is like this for now:
[current_experience.zip](https://github.com/Rajawali/Rajawali/files/1460657/current_experience.zip)

Again, i want to achive something like in the https://github.com/Rajawali/Rajawali/wiki/Anchor-01-Basic-Scene-Android-Studio, but only on swipe event on my mug.

And also here is a good example:
[wanted_experience.zip](https://github.com/Rajawali/Rajawali/files/1460665/wanted_experience.zip)
In this wanted experience i've used this library:
https://github.com/dbrant/ModelViewer3D

**Comment by contriteobserver** [comment]
related to #1829
