### ISSUE TITLE
Scale Objects dynamically

### ISSUE THREAD

**Issue by GeorgePractics23** [Rajawali/Rajawali#2024]
Hello everyone,

my issue isn't really an issue, is a doubt that i have been investigating for some time.
I'm working in an android studio project that is used for charge dynamically 3d models from a remote server and these models are showed in a SurfaceView using your library. 

My problem is the following:
- All the 3D models received in the APP have a different size and if I applied an static scale to the objects, they aren't showed correctly. I'm searching some system for detect the size of every object and scale it considering this, so that all the objects have the same size and look the same. 
Another option would be to scale the object to the size of the screen... 

I would appreciate any contribution, thanks!

**Comment by contriteobserver** [comment]
One can set an objects scale to unity with:
```
                try {
                    double radius = obj.getGeometry().getBoundingSphere().getRadius();
                    obj.setScale(1/radius);
                } catch (Exception e) {
                    Log.d(getLocalClassName(), "failed to set scale");
                }
```

**Comment by GeorgePractics23** [comment]
@contriteobserver some of the models that I receive from the server, have a null BoundingSphere, so the first line throws a NullPointerException.

And the models that work, don't appear in the screen when they are scaled if I don't modify their position. These models are centered in the (0,0) axis, I have opened them with a 3D editor for check it.

**Comment by contriteobserver** [comment]
If your `Object3D` is a Container object, test `Object3D.isContainer()`, then you have to iterate through its children to get bounds:
```
            double radius = 0;
            for(int i=0;i<obj.getNumChildren();i++) {
                Object3D child = obj.getChildAt(i);
                BoundingSphere bounds = child.getGeometry().getBoundingSphere();
                if(bounds.getRadius() > radius) radius = bounds.getRadius();
            }
```

**Comment by GeorgePractics23** [comment]
okey, fine! With this, I solve the first problem! Not all the objects are shown with the same size, but their sizes are similar...

But I keep having the second problem, if I don't modify the position of the camera, or the position of the object, the objects don't appear in the screen.

**Comment by contriteobserver** [comment]
A second issue is by definition, another issue, please create one. Sorry to be pedantic about it, but having one issue per issue really does make it easier for others to search for solutions. It saves a lot of time on the support end. Also, please upload an example object, as the standard test subject `Utah Teapot`, `Stanford Bunny`, `Cornell Box` and `Suzanne` do not seem to exhibit this issue.

**Comment by GeorgePractics23** [comment]
Okey, no problem, is logical.

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
