### ISSUE TITLE
Execution failed for task ':examples:transformNativeLibsWithMergeJniLibsForWithVuforiaDebug'

### ISSUE THREAD

**Issue by jfelrod1960** [Rajawali/Rajawali#2027]
#### Rajawali Version or Branch
1.1.970
#### Device and Android Version
Android Studio 3.0 (Not compiling so APK is not being installed)

#### Summary
I'm get the following error when trying to load the examples

Error:Execution failed for task ':examples:transformNativeLibsWithMergeJniLibsForWithVuforiaDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libvraudio_engine.so'

#### Steps to Reproduce
Load the project into Android Studio 3.0.1 and run the examples project with your android phone or tablet selected.

#### Trace or Log Output
Information:Gradle tasks [:examples:assembleWithVuforiaDebug]
Error:Execution failed for task ':examples:transformNativeLibsWithMergeJniLibsForWithVuforiaDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libvraudio_engine.so'
Information:BUILD FAILED in 4s
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by trikko** [comment]
Same here.

**Comment by jfelrod1960** [comment]
@trikko Add the following within the android{} block

    packagingOptions {
        exclude 'lib/armeabi-v7a/libvraudio_engine.so'
        exclude 'lib/armeabi-v7a/libvrtoolkit.so'
    }

I added them to all the build.gradle files.

Jeff

**Comment by heng201** [comment]
same here，how to do
