### ISSUE TITLE
Could not compile fragment shader

### ISSUE THREAD

**Issue by ln206** [Rajawali/Rajawali#2034]
#### Rajawali Version or Branch
1.1.970

#### Device and Android Version
Note8 - Android 7.1.1

#### Summary
When I try to parse an obj file (with mtl and texture images). I get the errors below. Please let me know if you know how to solve this problem. Thanks.

#### Trace or Log Output
`02-16 10:12:26.490 301-463/com.tecace.testsphere E/Rajawali: [org.rajawali3d.materials.Material] Could not compile fragment shader:
02-16 10:12:26.490 301-463/com.tecace.testsphere E/Rajawali: Shader log: ERROR: 0:4: 'dotmarker' : redefinition 
                                                             ERROR: 0:32: 'texture2D' : no matching overloaded function found 
                                                             ERROR: 0:32: '=' :  cannot convert from 'const float' to '4-component vector of float'
                                                             ERROR: 3 compilation errors.  No code generated.`

**Comment by contriteobserver** [comment]
Having trouble reproducing this issue, could you provide more details.
The following works as expected:
![device-2018-02-16](https://user-images.githubusercontent.com/17471201/36335429-c9660bac-1334-11e8-9898-cb4e536b7812.png)

```
    class ObjRenderer extends Renderer {

        public ObjRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-5,-5,-5);
            key.setPower(2);
            getCurrentScene().addLight(key);

            try {
                LoaderOBJ loader = new LoaderOBJ(getResources(), getTextureManager(), R.raw.tetra01_obj);
                loader.parse();
                obj = loader.getParsedObject();
                getCurrentScene().addChild(obj);
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.getMessage());
            }

            getCurrentCamera().setPosition(-3,4,5);
            getCurrentCamera().setLookAt(obj.getPosition());
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```
Model file:
```
# OBJ File: 'tetra01_obj.obj'
mtllib tetra01.mtl
o Cube
v  1 -1  1
v -1 -1 -1
v  1  1 -1
v -1  1  1
vt 0 0
vt 1 0
vt 1 1
vt 0 0
vt 1 0
vt 1 1
vt 0 0
vt 1 0
vt 1 1
vt 0 0
vt 1 0
vt 1 1
vn  0.5774  0.5774  0.5774
vn  0.5774 -0.5774 -0.5774
vn -0.5774 -0.5774  0.5774
vn -0.5773  0.5774 -0.5774
usemtl Material
s off
f 1/1/1 3/2/1 4/3/1
f 3/4/2 1/5/2 2/6/2
f 4/7/3 2/8/3 1/9/3
f 2/10/4 4/11/4 3/12/4
```
Material file:
```
# MTL File: 'tetra01_mtl.mtl'
newmtl Material
Ns 99
Kd 1 1 1
Ks 1 1 1
Ni 1
d  1
illum 2
map_Kd tiles.png
```
texture file:
![tiles](https://user-images.githubusercontent.com/17471201/36335382-5d551b56-1334-11e8-9b2c-241223ed58ea.png)

**Comment by ln206** [comment]
There was incorrect naming of objects inside the obj file. I corrected those and it's working fine. Thanks.
