### ISSUE TITLE
Textures disappear when rotate to the front of camera view.

### ISSUE THREAD

**Issue by ln206** [Rajawali/Rajawali#2035]
#### Rajawali Version or Branch
1.1.970

#### Device and Android Version
Note 8 - 7.1.1

#### Summary
I tried to load an obj file exported from Blender. It seems like all the texts around the earth display correctly when I try to rotate the earth in Blender.  But when I loaded them from my app, the texts won't show in front of the camera (Please look at the images inside the attached zip file). I don't know if this is the library problem or there are some configurations in Blender that I need to change. Also, looks like some of the textures that visible in Blender is not loaded in my app as well. Has anyone else experienced this issue? Please let me know, thanks.

#### Steps to Reproduce
Load obj file exported from Blender to my android app.

#### Trace or Log Output
No trace/log

[images.zip](https://github.com/Rajawali/Rajawali/files/1761110/images.zip)

**Comment by contriteobserver** [comment]
A few issues here:
 - Blender's material capabilities extend well beyond Wavefront's Advanced Visualizer format, so one has to be very careful how the material is defined. Usually I end up tweeking the MTL file to get what I want.
- Rajawali (1.1.970) currently has issues with getting the Z order right when overlaying multiple objects with transparency, we are hoping to improve with Camden Hells.
- LoaderOBJ sets a material as transparent if `d` is less than 1, sometimes blender sets `d` to `0.999999`

However, one can get everything aligned right to get the effect you want.
![device-2018-02-27](https://user-images.githubusercontent.com/17471201/36735206-78a6c608-1b8a-11e8-9477-cee7e844a531.png)

Below is a simple example and blender file to get you started along the right path:
```
    class ObjRenderer extends Renderer {

        public ObjRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-5,-5,-5);
            key.setPower(1.5f);
            getCurrentScene().addLight(key);

            try {
                LoaderOBJ loader = new LoaderOBJ(getResources(), getTextureManager(), R.raw.labelled01_obj);
                loader.parse();
                obj = loader.getParsedObject();
                getCurrentScene().addChild(obj);

                Animation3D anim = new RotateOnAxisAnimation(Vector3.Axis.Y, -360);
                anim.setDurationMilliseconds(9876);
                anim.setRepeatMode(Animation.RepeatMode.INFINITE);
                anim.setTransformable3D(obj);
                getCurrentScene().registerAnimation(anim);
                anim.play();
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.getMessage());
            }

            getCurrentCamera().setPosition(-7,6,5);
            getCurrentCamera().setLookAt(obj.getPosition());
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```
[labelled.zip](https://github.com/Rajawali/Rajawali/files/1763303/labelled.zip)

**Comment by ln206** [comment]
Thank you. I was able to get the text to display correctly no matter where I rotate, I changed the 'd' value inside the mtl file for the texts to 1. But I have another problem, the faces that hold the texts are not transparent anymore, it is black now. Do you know how to fix this?

**Comment by contriteobserver** [comment]
For now, the easiest way to proceed is to use a simple texture 
and define the text using **geometry** rather than **transparency**.

In Blender to define text geometry:
- Add Text
- Convert Text to Mesh (Alt-C)
- Apply a Solidify Modifier
- Triangulate Faces (Ctrl-T)

**Comment by ln206** [comment]
Thanks, I solved the problem by following your instructions.
