### ISSUE TITLE
Memory keeps going up.

### ISSUE THREAD

**Issue by ln206** [Rajawali/Rajawali#2038]
#### Rajawali Version or Branch
1.1.970

#### Device and Android Version
Note8 - Android 7.1.1

#### Summary
So I have my renderer inside a fragment. If I keep going to this fragment with the renderer, and go back to the previous fragment, then go back to the fragment with the renderer again (keep doing this for a bunch of times). I could see that the memory keeps on going up without going down again, even when I go back to the previous fragment without the renderer, and stay on that fragment for a while. I have included my test renderer. Could anyone please tell me what I need to do to release memory?

#### Steps to Reproduce
Repeat this step: enter fragment with renderer, going back to the previous fragment, then go back to the fragment with renderer, repeat....

#### Trace or Log Output
No trace/log.

[renderer.zip](https://github.com/Rajawali/Rajawali/files/1773395/renderer.zip)

**Comment by contriteobserver** [comment]
Materials can be shared amongst many objects, so destroying an object does not release material resources, so one must add that step:
```
    @Override
    public void onRenderSurfaceDestroyed(SurfaceTexture surface) {
        MaterialManager mm = MaterialManager.getInstance();
//        Log.d(TAG, "onRenderSurfaceDestroyed");
        if(context != null) context = null;

        if(object3D != null) {
            mm.taskRemove(object3D.getMaterial());
            for(int i = 0; i < object3D.getNumChildren(); i++) {
                Object3D child = object3D.getChildAt(i);
                mm.taskRemove(child.getMaterial());
            }
            object3D.destroy();
            object3D = null;
        }
        if(plane != null) {
            mm.taskRemove(plane.getMaterial());
            plane.destroy();
            plane = null;
        }
        super.onRenderSurfaceDestroyed(surface);
    }
```

**Comment by ln206** [comment]
Thank you!
