### ISSUE TITLE
"Could not create frame buffer: [1282]: invalid operation"

### ISSUE THREAD

**Issue by ln206** [Rajawali/Rajawali#2039]
#### Rajawali Version or Branch
1.1.970

#### Summary
This crash seems to be really rare in debug version. But happens a lot with a release apk. It seems to be happen a lot when I try to rotate the device in a fragment with Rajawali SurfaceView.

#### Steps to Reproduce
Enter the fragment with Rajawali, rotate the device, crash... (This doesn't happen 100%)

#### Trace or Log Output
`java.lang.RuntimeException: Could not create framebuffer: [1282]: invalid operation
                                                                              ********** STACK TRACE **********
                                                                                  org.rajawali3d.renderer.RenderTarget.checkGLError(SourceFile:333)
                                                                                  org.rajawali3d.renderer.RenderTarget.create(SourceFile:253)
                                                                                  org.rajawali3d.renderer.RenderTarget.reload(SourceFile:324)
                                                                                  org.rajawali3d.renderer.Renderer.reloadRenderTargets(SourceFile:1005)
                                                                                  org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(SourceFile:369)
                                                                                  org.rajawali3d.view.SurfaceView$a.onSurfaceChanged(SourceFile:232)
                                                                                  android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1555)
                                                                                  android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
                                                                              ************* CAUSE ************
                                                                              *********************************`

**Comment by ln206** [comment]
I solved the problem by locking the orientation of that fragment. The problem still happens sometimes when I go back to the previous fragment.

**Comment by contriteobserver** [comment]
Having trouble reproducing this issue, what is wrong with my code?

```
public class ChangingOrientationActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Create a new fragment
        Fragment fragment = new RenderingFragment();

        // Insert the fragment by replacing any existing fragment
        FragmentManager fragmentManager = getSupportFragmentManager();
        fragmentManager.beginTransaction()
                .replace(R.id.content_fragment, fragment)
                .commit();

        final Handler handler = new Handler();
        // Define the code block to be executed
        final Runnable runnableCode = new Runnable() {
            @Override
            public void run() {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        switch (getResources().getConfiguration().orientation) {
                            case 1:
                                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
                                break;
                            case 2:
                                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
                                break;
                        }
                    }
                });

                // Repeat this the same runnable code block again
                // 'this' is referencing the Runnable object
                handler.postDelayed(this, 3456);
            }
        };
        // Start the initial runnable task by posting through the handler
        handler.post(runnableCode);
    }
}
```

```
public class RenderingFragment extends Fragment {

    SurfaceView surface;
    Renderer renderer;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        ViewGroup rootView = (ViewGroup) inflater.inflate(
                R.layout.fragment_blank, container, false);

        renderer = new BasicRenderer(getContext());
        surface = (SurfaceView) rootView.findViewById(R.id.glsl_content);

        surface.setFrameRate(30);
        surface.setRenderMode(ISurface.RENDERMODE_WHEN_DIRTY);
        surface.setSurfaceRenderer(renderer);

        return rootView;
    }

    class BasicRenderer extends Renderer {
        public BasicRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);
                Material material = new Material();
                material.setColor(Color.CYAN);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.enableLighting(true);
                Cube cube = new Cube(1);
                cube.setMaterial(material);
                getCurrentScene().addChild(cube);

                ALight key = new DirectionalLight();
                key.setPosition(3,-4,5);
                key.setPower(2);
                getCurrentScene().addLight(key);
                key.setLookAt(cube.getPosition());

                getCurrentCamera().setPosition(3,3,3);
                getCurrentCamera().setLookAt(cube.getPosition());

            } catch (Exception e) {
                Log.d(getClass().getSimpleName(), e.getMessage());
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
}
```

**Comment by ln206** [comment]
I still have no idea what is going on. Could you please tell me more detail about the crash? It seems like my app crashes when the SurfaceView is trying to resize. Thanks.

**Comment by contriteobserver** [comment]
It's likely that the Fragment is not being completely released after use, and it is needlessly holding resources, likely there is a circular dependency, possibly due to a specific callback implementation, but until we can reproduce it, it is difficult to be certain. Please augment with the the above testbench with the features you are using until it starts to fail.

**Comment by ToxicBakery** [comment]
This issue is missing the required information to provide proper support. Please reopen the issue with more detail if you still need help.

**Comment by milja94** [comment]
I am have this problem too only on Xiaomi device
