### ISSUE TITLE
Collision issues Camera and Object3D

### ISSUE THREAD

**Issue by vaillant1000hy** [Rajawali/Rajawali#2041]
#### Rajawali Version or Branch
master

#### Device and Android Version
All supported versions

#### Summary
Hello,
Tell me, i want to test collision bewteen the main camera and a cube. We created a first-person camera in which we can navigate into our scene. To test the collision bewteen those two things we used:

boundingBox  `  private IBoundingVolume boundingBoxPanneau` for the cube and
`private IBoundingVolume boundingCamera` for the camera 

we init the scene like this 
```
protected void initScene(){
        createPanneau();
        boundingBoxPanneau = panneau.getGeometry().getBoundingBox();
```
and inside the onRender we put : 

```
  public void onRender(final long elapsedTime, final double deltaTime) {
        super.onRender(elapsedTime, deltaTime);

        boundingBoxCamera = getCurrentCamera().getTransformedBoundingVolume();

        boundingBoxPanneau.transform(panneau.getModelMatrix());

        boolean intersects =  boundingBoxCamera.intersectsWith(boundingBoxPanneau);

            if (intersects){
                getCurrentScene().setBackgroundColor(Color.RED);
            }
        }
```
But when we test it ( we go through the cube with the camera), it doesn't work the collision is not detected.
Thanks in advance.

#### Steps to Reproduce
[Describe reproducable steps and sample code]

#### Trace or Log Output
[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by contriteobserver** [comment]
This works here, am I misunderstanding the issue?
```
        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            BoundingBox boundingBox = obj.getBoundingBox();
            boundingBox.transform(obj.getModelMatrix());
            Log.d(getLocalClassName(), "obj bounds=" + boundingBox);

            IBoundingVolume bounds = getCurrentCamera().getTransformedBoundingVolume();
            bounds.transform(getCurrentCamera().getModelMatrix());
            Log.d(getLocalClassName(), "camera bounds=" + bounds);
            Log.d(getLocalClassName(), "intercection:" + (boundingBox.intersectsWith(bounds) ? "true" : "false"));
            Log.d(getLocalClassName(), "intercection:" + (bounds.intersectsWith(boundingBox) ? "true" : "false"));
        }
```

**Comment by vaillant1000hy** [comment]
It works ! Thank you. It was because in the tutorial about collision it was said that you need to use 

`myObject.getGeometry().getBoundingBox();`

I think it was the getGeometry() which was blocking it i think.

Best Regards.

PS: i would like to know if there is a solution to not go through an object when the collision is detected. I was thinking about keeping the previous frame position and reset the Camera position on this last position, what do you think ?
PS PS : I apologize for my bad english ...

**Comment by contriteobserver** [comment]
one could hook into a physics engine, an example in the wiki at [Bombshell-02-Dynamics](https://github.com/Rajawali/Rajawali/wiki/Bombshell-02-Dynamics)

**Comment by vaillant1000hy** [comment]
Hm, 
Maybe i did not get it at all, but here is my problem, i want to have a .obj file loaded (lets say a room)  and a main camera. The camera is able to move in the space. And i need the camera to not go out of the room. I mean like real walls.

**Comment by contriteobserver** [comment]
Physical barriers (kinematics) and moving objects that collide (dynamics) are a big part of what physics engines are all about. If this camera moves about on a 2D plane (like a fixed height above the floor) then [Jbox2D](https://github.com/jbox2d/jbox2d) is a good choice, if the camera needs to move up and down and also be constrained by the floor and ceiling then a 3D engine like [ode4j](https://github.com/tzaeschke/ode4j) is more appropriate.
