### ISSUE TITLE
How to reuse object saved

### ISSUE THREAD

**Issue by truongnv1292** [Rajawali/Rajawali#2049]
I have saved object3d as a global variable for the app, so when I started back into the app instead of creating a new object, I always took the object to save for use, but strangely the saved object did not function as the new object created. can you help me this?

**Comment by contriteobserver** [comment]
Before beginning to help you with this, the following clarifications are required:

- which version of Rajawali exhibits this behavior?
- how is the object created?
- does the object contain children?
- what materials are associated with this object and any children?
- how are the materials created for this object and any children?
- are animations associated with this object or any children?
- are any material plugins used?
- how do you start back into the application?

**Comment by ToxicBakery** [comment]
This issue is missing the required information to provide proper support. Please reopen the issue with more detail if you still need help.
