### ISSUE TITLE
how can run gif using mtl and object .

### ISSUE THREAD

**Issue by testCanopus** [Rajawali/Rajawali#2053]
#### Rajawali Version or Branch
[describe the _precise_ release version or branch and commit id, feature requests can simply specify master]. Responses such as "last one" or "latest" will not be treated seriously until it is an issue that impacts our developers.

#### Device and Android Version
[list at least one device and the version number that produced a stace trace if applicable]

#### Summary
When i open my mouth some animation will be perform like insert some object.
For example when i open my mouth a cricket pitch should came from my mouth and a ball should be inside in my mouth  through this pitch and then saying bold.  

#### Steps to Reproduce
[Describe reproducable steps and sample code]

#### Trace or Log Output
[include stacktrace(s) if relevant to the issue. Engine crashes can not be debugged without a stacktrace or at minimum reproduction code.]

**Comment by contriteobserver** [comment]
There is an easier way to meet the described objective. As Rajawali is capable of rendering 3D objects, one can simple create a model of a cricket pitch, a ball, and lettering. These elements can then be animated using our `org.rajawali3d.animation.*` features.

**Comment by contriteobserver** [comment]
To load an animated GIF texture on a cube, see the following:
```
    class GIFrenderer extends Renderer {
        AnimatedGIFTexture texture;

        public GIFrenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-5,-5,-5);
            key.setPower(2);
            getCurrentScene().addLight(key);

            Material material = new Material();
            material.setColor(Color.GREEN);
            try {
                texture = new AnimatedGIFTexture("wikipedia", R.drawable.wikipedia);
                material.addTexture(texture);
                material.setColorInfluence(0);
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.getMessage());
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.enableLighting(true);
            }

            obj = new Cube(2);
            obj.setMaterial(material);
            getCurrentScene().addChild(obj);

            getCurrentCamera().setPosition(3,4,5);
            getCurrentCamera().setLookAt(obj.getPosition());
        }

        @Override
        public void onRenderFrame(GL10 gl) {
            super.onRenderFrame(gl);
            try {
                texture.update();
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.getMessage());
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {
        }
    }

``` 
GIF file from [wikimedia commons](https://commons.wikimedia.org/wiki/File:Wikipedia_logo_puzzle_globe_spins_horizontally_and_vertically,_revealing_the_contents_of_all_of_its_puzzle_pieces.gif)
![device-2018-05-16](https://user-images.githubusercontent.com/17471201/40134358-051da8a0-58f7-11e8-9558-1d064212af95.png)

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
