### ISSUE TITLE
As the application increases memory leading to crash when changing operations, my temporary solution is to reuse the renderer

### ISSUE THREAD

**Issue by truongnv1292** [Rajawali/Rajawali#2056]
#### Rajawali Version or Branch
I am using a module library (zip file) loaded directly from GitHub

#### Device and Android Version
Currently, I only care about memory usage, on the device and version of normal operation when not out of memory.

#### Summary
The wallpaper installer application I'm developing uses the Rajawali library as a module.
Because of my application every time I get into the app, memory goes up and so after a few interactions, the app crashes out of memory, I've used many ways to optimize the memory used by the app, But not to bring satisfaction
This is the solution I find most appropriate.
Once in the app, it initializes the renderer, I wanted to save it for use without having to re-create it
This is the code I saved the renderer when it was initialized and reused:
```
 @Override
    public AExampleRenderer createRenderer() {
        if (AppControler.getRenderer()==null){
            mRenderer = new ChaseSurfaceCameraFragment.ChaseCameraRenderer(getContext(), null);
            ((ChaseCameraRenderer)mRenderer).setViewLayoutListener(getActivity(), mLayout);
            AppControler.setRenderer(mRenderer);
        } else {
            mRenderer = AppControler.getRenderer();
            ((ChaseCameraRenderer)mRenderer).setViewLayoutListener(getActivity(), mLayout);
        }
        return ((AExampleRenderer) mRenderer);
    }
```

Unfortunately, when I initialized WallpaperService and took the renderer out of use, it did not work as well as I wanted it to but instead was a black screen.
This is the code in the class WallpaperService that I used to save the renderer:
```
 @Override
    public Engine onCreateEngine() {
        ISurfaceRenderer renderer = AppControler.getRenderer();
        WallpaperEngine wallpaperEngine =  new WallpaperEngine(AppWallpaperService.this, renderer, ISurface.ANTI_ALIASING_CONFIG.MULTISAMPLING);
        return wallpaperEngine;
    }
```

I do not understand why the renderer saved does not work the same as when it was born.
It's great when someone tells me where the problem lies.
Thank many.

**Comment by ToxicBakery** [comment]
Renderers are context-bound and thus cannot be retained. The memory leak is something that has been brought up in the past. We ask for sample code demonstrating the issue and to my knowledge, it's rarely been provided and I'm unsure of the status on that. If you have code you can share that demonstrates the issue we could look into it further.

If you can share a sample, please create a new issue describing the memory problem with the attached code.
