### ISSUE TITLE
Make abstract methods in ATexture protected

### ISSUE THREAD

**Issue by defrost256** [Rajawali/Rajawali#2057]
#### Rajawali Version or Branch
master

#### Summary
Abstract methods in `ATexture` like `add()` should be protected, so that users can implement their own textures.

#### Description
As of now the following abstract methods in `org.rajawali3d.materials.textures.ATexture` are only accessible from the same package, which means users can't create their own implementations of it. 

```
public abstract class ATexture {

...

	abstract void add() throws TextureException;
	abstract void remove() throws TextureException;
	abstract void replace() throws TextureException;
	abstract void reset() throws TextureException;

...

}
```

While I really like the Textures coming with Rajawali, some applications might require custom solutions. There might be some workaround for what I'm trying to accomplish, but this seems like the most straightforward way, with minimal impact on the current Rajawali code.

This might also be relevant to #2010 since that's what I'm trying to accomplish.

**Comment by contriteobserver** [comment]
Submitted pull request
