### ISSUE TITLE
About Rajawali Engine

### ISSUE THREAD

**Issue by cllanjim** [Rajawali/Rajawali#2061]
how to use rajawali engine for record video and Add a filter for the color lookup table ？

**Comment by contriteobserver** [comment]
Rajawali does not capture video from camera applications, see  [Android Video Basics](https://developer.android.com/training/camera/videobasics) for details on the Recording API.

Rajawali uses a plugin interface to add filters, there are two APIs, one that is specific to a material, and one that is applied across a scene.
* material level interface is invoked with the `Material.addPlugin()` interface
* scene level interface is managed by the `PostProcessingManager`

Please clarify which type of filters are of interest.

**Comment by cllanjim** [comment]
Thank you for your reply ！I created a LUTPass extends APass ，below is the java class code：
`public class LUTPass extends APass {

    protected final String PARAM_INTENSITY = "intensity";
    protected final String PARAM_TEXTURE = "uTexture";

    protected VertexShader mVertexShader;
    protected FragmentShader mFragmentShader;
    protected RenderTarget mReadTarget;
    protected RenderTarget mWriteTarget;

    public LUTPass(int width, int height) {
        this.mWidth = width;
        this.mHeight = height;
        mPassType = PassType.EFFECT;
        mNeedsSwap = true;
        mClear = false;
        mEnabled = true;
        mRenderToScreen = false;
        setSize(width, height);
        createMaterial(R.raw.minimal_vertex_shader, R.raw.lut_fragment);
    }

    protected void createMaterial(@NonNull VertexShader vertexShader, @NonNull FragmentShader fragmentShader) {
        mVertexShader = vertexShader;
        mFragmentShader = fragmentShader;
        mVertexShader.setNeedsBuild(false);
        mFragmentShader.setNeedsBuild(false);
        setMaterial(new Material(mVertexShader, mFragmentShader));
    }

    protected void createMaterial(@RawRes int vertexShaderResourceId, @RawRes int fragmentShaderResourceId) {
        createMaterial(new VertexShader(vertexShaderResourceId), new FragmentShader(fragmentShaderResourceId));
    }

    public void setShaderParams() {
        mFragmentShader.setUniform1f(PARAM_INTENSITY, 1.0f);

        try {
            Bitmap bmp = BitmapFactory.decodeResource(BaseApplication.getInstance().getResources(), R.drawable.lookup_amatorka);

            ATexture lutTexture = new LUTTexture(
                    ATexture.TextureType.LOOKUP,
                    "inputImageTexture", bmp);
            lutTexture.setFilterType(ATexture.FilterType.LINEAR);
            mMaterial.addTexture(lutTexture);
            mMaterial.bindTextureByName("inputImageTexture", 1, lutTexture);


        } catch (ATexture.TextureException e) {
            e.printStackTrace();
        }
        mMaterial.bindTextureByName(PARAM_TEXTURE, 0, mReadTarget.getTexture());
    }

    @Override
    public void render(Scene scene, Renderer renderer, ScreenQuad screenQuad, RenderTarget writeTarget, RenderTarget readTarget, long ellapsedTime, double deltaTime) {
        mReadTarget = readTarget;
        mWriteTarget = writeTarget;
        screenQuad.setMaterial(mMaterial);
        screenQuad.setAPass(this);

        if (mRenderToScreen) {
            scene.render(ellapsedTime, deltaTime, null);
        } else {
            scene.render(ellapsedTime, deltaTime, writeTarget);
        }
    }

}
`
Below is the lut_fragment glsl code：
`varying highp vec2 vTextureCoord; 

uniform sampler2D uTexture; 
uniform sampler2D inputImageTexture; 

uniform lowp float intensity;

void main()
{
    highp vec4 textureColor = texture2D(uTexture, vTextureCoord);

    highp float blueColor = textureColor.b * 63.0;

    highp vec2 quad1;
    quad1.y = floor(floor(blueColor) / 8.0);
    quad1.x = floor(blueColor) - (quad1.y * 8.0);

    highp vec2 quad2;
    quad2.y = floor(ceil(blueColor) / 8.0);
    quad2.x = ceil(blueColor) - (quad2.y * 8.0);

    highp vec2 texPos1;
    texPos1.x = (quad1.x * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.r);
    texPos1.y = (quad1.y * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.g);

    highp vec2 texPos2;
    texPos2.x = (quad2.x * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.r);
    texPos2.y = (quad2.y * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.g);

    lowp vec4 newColor1 = texture2D(inputImageTexture, texPos1);
    lowp vec4 newColor2 = texture2D(inputImageTexture, texPos2);

    lowp vec4 newColor = mix(newColor1, newColor2, fract(blueColor));
    gl_FragColor = mix(textureColor, vec4(newColor.rgb, textureColor.w), intensity);

}`
But OpenGL engine rendering display like this :
[](url)
![c57a17378528ddbcae2b1fe8a4c7d52d](https://user-images.githubusercontent.com/5005704/42856554-4c594000-8a78-11e8-914a-fae3598e3b34.jpg)

**Comment by cllanjim** [comment]
I will try the Material.addPlugin() interface to solve this problem. Thank you for your help !

**Comment by contriteobserver** [comment]
`EffectsPass` should get you there, add something like this in `initScene()`:
```
            RenderPass renderPass = new RenderPass(getCurrentScene(), getCurrentCamera(), 0);
            effects.addPass(renderPass);

            Texture lutTexture = new Texture("LookupTexture", R.drawable.contrast_enhance);
            LUTPass lutPass = new LUTPass(lutTexture);
            lutPass.setRenderToScreen(true);
            effects.addPass(lutPass);
```
override `onRender()`
```
        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            effects.render(ellapsedRealtime, deltaTime);
        }
```
and create a lookup table effects pass:
```
public class LUTPass extends EffectPass {
    protected final String PARAM_INTENSITY = "intensity";
    protected final String PARAM_LUT = "uTexture";
    ATexture lutTexture;

    public LUTPass(ATexture lutTexture) {
        super();
        TextureManager.getInstance().addTexture(lutTexture);
        this.lutTexture = lutTexture;

        mVertexShader = new VertexShader();
        mVertexShader.initialize();
        mVertexShader.buildShader();
        Log.d(getClass().getSimpleName(), "=== vertex shader ===\n" + mVertexShader.getShaderString());

        mFragmentShader = new LookupFragmentShader(R.raw.lut_fragment);
        mFragmentShader.initialize();
        Log.d(getClass().getSimpleName(), "=== fragment shader ===\n" + mFragmentShader.getShaderString());
        createMaterial(mVertexShader, mFragmentShader);
    }

    @Override
    public void setShaderParams() {
        super.setShaderParams();
        mMaterial.bindTextureByName(PARAM_LUT, 1, lutTexture);
        mVertexShader.applyParams();
        mFragmentShader.applyParams();
    }

    private class LookupFragmentShader extends FragmentShader
    {
        float intensity = 0.5f;
        RFloat uIntensity;
        int muIntensityHandle;

        public LookupFragmentShader(int resourceId) {
            super(resourceId);
        }

        @Override
        public void initialize() {
            super.initialize();
            uIntensity = (RFloat) addUniform(PARAM_INTENSITY, DataType.FLOAT);
        }

        @Override
        public void setLocations(int programHandle) {
            super.setLocations(programHandle);
            muIntensityHandle = getUniformLocation(programHandle, PARAM_INTENSITY);
        }

        @Override
        public void applyParams() {
            super.applyParams();
            GLES20.glUniform1f(muIntensityHandle, intensity);
        }
    }
}
```

**Comment by cllanjim** [comment]
Thank you，I will try this code，and reply you later.

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.

**Comment by sourabhgupta811** [comment]
Hi @cllanjim @contriteobserver @ToxicBakery i am trying to achieve something same and i am trying to record a video of all the 3d objects rendered onto the camera preview. Can you guys help me how can i record the video. What i have done till now is that i created an external texture and draw camera preview on it and applied it as a material to rajawali plane to show it on screen. But what i want now is to record the finalframebuffer that is being displayed on screen.
