### ISSUE TITLE
Transparent Textures

### ISSUE THREAD

**Issue by sebdomdev** [Rajawali/Rajawali#2062]
#### Rajawali Version or Branch
Rajawali 1.1.970

#### Device and Android Version
All devices

#### Summary
I have textures (png files) that have an alpha channel. I would like parts of the image that have an alpha of 0 to actually show up as transparent. According to the documentation (https://github.com/Rajawali/Rajawali/wiki/v0.9-Tutorial-28-Transparent-Textures) `Object3D.setTransparent(true)` has that effect. However, as the documentation states it has the drawback of setting glDepthMask to false rendering objects in the wrong order. As a possible solution, the documentation suggests to use `new Material(AMaterial.ALPHA_MASKING)`. However, that seems to be outdated because the current implementation (master-branch) doesn't even have a class AMaterial anymore. And the class [Material](https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/main/java/org/rajawali3d/materials/Material.java) neither has such a flag, nor a constructor that would accept it. So my question is, is there a replacement for `new Material(AMaterial.ALPHA_MASKING)` and if not, what is the best way of using (partially) transparent textures without using depth masking functionality (and without using alpha maps)?

**Comment by contriteobserver** [comment]
An `AlphaMaskMaterialPlugin` should get you there:
```
    class TransTextureRenderer extends Renderer {

        public TransTextureRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);

                DirectionalLight key = new DirectionalLight(-5,-5,-5);
                key.setPower(2);
                getCurrentScene().addLight(key);

                AlphaMaskMaterialPlugin plugin = new AlphaMaskMaterialPlugin(0.125f);
                Texture pattern = new Texture("rajawali", R.drawable.rajawali_icon);
                Material material = new Material();
                material.setColorInfluence(0);
                material.addTexture(pattern);
                material.addPlugin(plugin);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.enableLighting(true);

                obj = new Cube(2);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                getCurrentCamera().setPosition(3,4,5);
                getCurrentCamera().setLookAt(obj.getPosition());
            } catch (Exception e) {
                Log.d(getLocalClassName() + ".initScene", e.getMessage());
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {
        }
    }
```

**Comment by sebdomdev** [comment]
Perfect, that works. Thank you very much!

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
