### ISSUE TITLE
Can the dae format be supported?

### ISSUE THREAD

**Issue by ZhangGuangXin** [Rajawali/Rajawali#2071]
I want to load dae file, Is this engine supported？ if I must use AWD file, how can I get this format file?

In fact, I have noticed that someone raised the problem of DAE a long time ago, but it has not been solved until now.  why?  Is it because the engine won't be maintained?

**Comment by ZhangGuangXin** [comment]
I want to get the answer as soon as possible, please, because the work schedule is very busy

**Comment by jwoolston** [comment]
Then best to use Unity.

**Comment by ZhangGuangXin** [comment]
Is this engine really not going to be maintained? If so, I have to give up the engine.

**Comment by jwoolston** [comment]
The engine is and has always been a hobby project of the various developers. We will not respond to unpaid solicitations to work on someone else's schedule.

**Comment by ZhangGuangXin** [comment]
I hope this engine will get better in the future
