### ISSUE TITLE
signArchives failed

### ISSUE THREAD

**Issue by hannesa2** [Rajawali/Rajawali#2082]
During Travis build https://github.com/Rajawali/Rajawali/pull/2081, I run here
https://github.com/Rajawali/Rajawali/blob/01793facd8080af54b91add297675d89d0c0c785/.travis.yml#L50

into 
> Cannot perform signing task ':wear:signArchives' because it has no configured signatory

To be honest, I'm not sure what's wrong here. Does it mean `SONATYPE_USERNAME` and `SONATYPE_PASSWORD` isn't specified in Travis ?

### Plan B

We could go the way https://jitpack.io/#Rajawali/Rajawali as an alternative and remove this signing complete.
What do you think ?

**Comment by ToxicBakery** [comment]
I actually just rewrote the build process for circle and converted to maven-publish. The issue was the removal of the AES decryption steps in one of your other PRs. I'm trying to wrap this up today so builds work again (completely)

**Comment by hannesa2** [comment]
Nice, now CircleCI builds with latest stable NDK version (r18b) ! 
Only a minor thing is missing: the Slack notification
