### ISSUE TITLE
Emulator crash in example with ANTI_ALIASING_CONFIG.MULTISAMPLING

### ISSUE THREAD

**Issue by hannesa2** [Rajawali/Rajawali#2091]
with current master I run in emulator in `Lines Example` into

>  Process: org.rajawali3d.examples, PID: 12294
>  java.lang.IllegalStateException: This device does not support the requested EGL Configuration!
>      at org.rajawali3d.util.egl.RajawaliEGLConfigChooser.chooseConfig(RajawaliEGLConfigChooser.java:88)
>      at org.rajawali3d.view.TextureView$EglHelper.start(TextureView.java:736)

**Comment by hannesa2** [comment]
Any idea why `ISurface.ANTI_ALIASING_CONFIG.MULTISAMPLING` has issues on emulator ?

**Comment by ToxicBakery** [comment]
Seems the emulator does not support the feature. We can add an emulator check though and just not use multisampling or use blend functions as noted here for emulator runs

https://stackoverflow.com/a/5306157/1286667
