### ISSUE TITLE
Acceleration example has no influence from sensor

### ISSUE THREAD

**Issue by hannesa2** [Rajawali/Rajawali#2101]
During using the acceleration example, I expected an interaction from acceleration sensor, but object spins without any influence from device position/movement.
Should it ?
As the first view I see 

```
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
```

.. so it should

**Comment by ToxicBakery** [comment]
It's likely during some part of reworking in the engine that the sensor wiring was removed. If you try to follow that class back in history you may find out how it used to be implemented but I honestly do not remember if it ever worked or how.

**Comment by hannesa2** [comment]
https://github.com/Rajawali/Rajawali/pull/2104
