### ISSUE TITLE
VR example uses very old VR lib

### ISSUE THREAD

**Issue by hannesa2** [Rajawali/Rajawali#2115]
Current master uses a very old GoogleVR lib, it's copied and not used by dependencies.
This is a one way usage, so I tried to use most recent one, but I failed.
This is my last try https://github.com/Rajawali/Rajawali/pull/2114

**Comment by zhuohengfeng** [comment]
@hannesa2 Any updates for this ??

**Comment by hannesa2** [comment]
sorry no, but maybe @ToxicBakery knows more https://github.com/Rajawali/Rajawali/pull/2114#issuecomment-457577107
