### ISSUE TITLE
Multiple Rajawali textureview in a single activity not resuming correctly after onPause() and onresume() calls.

### ISSUE THREAD

**Issue by sourabhgupta811** [Rajawali/Rajawali#2124]
#### Rajawali Version: v1.1.970
version  v1.1.970
branch master

#### Device and Android Version
Redmi note 4
Android version 7

#### Summary
When adding multiple rajawali textureviews in a single activity, some textureviews are not drawn. And when onPause and onResume is called, only a single textureview continue drawing on the screen. All other textureviews stops.

#### Steps to Reproduce
 Add multiple textureviews in a single activity.
Set renderer to these textureviews.
Launch the app and switch between onPause and onresume state.

**Comment by contriteobserver** [comment]
Rajawali is not currently treadafe, and so does not support more than one `Renderer` an activity. Instead, launch a `Fragment` pair with one `Renderer` in each. This should get you there:
```
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

}

class BasicRenderer extends Renderer {
    public BasicRenderer(Context context) {
        super(context);
    }

    @Override
    protected void initScene() {
        try {
            DirectionalLight key = new DirectionalLight(-3,4,5);
            getCurrentScene().setBackgroundColor(Color.BLUE);
            key.setPower(5.0f);
            getCurrentScene().addLight(key);

            Material material = new Material();
            material.setColor(Color.GREEN);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setAmbientColor(Color.LTGRAY);
            material.enableLighting(true);

            Object3D obj = new Cube(2);
            obj.setMaterial(material);
            getCurrentScene().addChild(obj);

            Vector3 axis = new Vector3(-1,-1,-1);
            Animation anim = new RotateOnAxisAnimation(axis, 360);
            anim.setRepeatMode(Animation.RepeatMode.INFINITE);
            anim.setDurationMilliseconds(4321);
            ((RotateOnAxisAnimation) anim).setTransformable3D(obj);
            getCurrentScene().registerAnimation(anim);
            anim.play();

            getCurrentCamera().setPosition(3,4,5);
            getCurrentCamera().setLookAt(obj.getPosition());
        } catch (Exception e) {
            Log.d(getClass().getSimpleName(), e.getMessage());
        }
    }

    @Override
    public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

    }

    @Override
    public void onTouchEvent(MotionEvent event) {

    }
}

```
and the renderers:
```
public class AlphaRenderer extends Fragment {
    final static String TAG = "Alpha";
    SurfaceView view;
    Renderer renderer;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        ViewGroup rootView = (ViewGroup) inflater.inflate(
                R.layout.renderer_fragment, container, false);
        super.onCreate(savedInstanceState);

        view = rootView.findViewById(R.id.glsl_content);
        renderer = new BasicRenderer(getContext());

        view.setSurfaceRenderer(renderer);
        view.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                renderer.onTouchEvent(motionEvent);
                return false;
            }
        });

        return rootView;
    }

}
```
```
public class BetaRenderer extends Fragment {
    final static String TAG = "Beta";
    SurfaceView view;
    Renderer renderer;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        ViewGroup rootView = (ViewGroup) inflater.inflate(
                R.layout.renderer_fragment, container, false);
        super.onCreate(savedInstanceState);

        view = rootView.findViewById(R.id.glsl_content);
        renderer = new BasicRenderer(getContext());

        view.setSurfaceRenderer(renderer);
        view.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                renderer.onTouchEvent(motionEvent);
                return false;
            }
        });
        return rootView;

    }
}
```
the activity layout:
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"

    android:id="@+id/children_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:keepScreenOn="true"
    tools:context=".MainActivity">

    <fragment
        android:name="com.example.rajawalitextureviewspike.AlphaRenderer"
        android:id="@+id/alpha"
        android:layout_width="match_parent"
        android:layout_height="0dp"

        app:layout_constraintBottom_toTopOf="@id/beta"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <fragment
        android:name="com.example.rajawalitextureviewspike.BetaRenderer"
        android:id="@+id/beta"
        android:layout_width="match_parent"
        android:layout_height="0dp"

        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/alpha" />
```
fragment layout:
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent"
    android:layout_height="match_parent">

    <org.rajawali3d.view.SurfaceView
        android:id="@+id/glsl_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</android.support.constraint.ConstraintLayout>
```
results look like:
![2019-05-11](https://user-images.githubusercontent.com/17471201/57575043-e0f85c00-73f7-11e9-81c6-f21e762498c4.png)

**Comment by sourabhgupta811** [comment]
Hi
Thanks for the reply.
I did as you told. Although, It did solve the lifecycle problem but still not all textureViews are visible on every app launch. I am adding 9 fragments on the screen. Is there any limit of such sort?

**Comment by contriteobserver** [comment]
Updated the example to show a nine fragment case, surprised it runs at all.

One can often get by with one or two renderers in an application, but nine is just too many for our current implementation.

**Comment by sourabhgupta811** [comment]
Hi
The example you did is working good. But when i am using textures in my renderer. it does not work correctly. Here is my initScene method-

`        @Override
        protected void initScene() {
            DirectionalLight directionalLight = new DirectionalLight(0,0,-1f);
            directionalLight.setPower(1);
            getCurrentScene().addLight(directionalLight);
            getCurrentCamera().setPosition(0, 0, 16);

            try {
                Object3D monkey = new Cube(2.0f);
                Material material = new Material();
                material.setColorInfluence(0);
                material.addTexture(new Texture(name,R.drawable.animation_image));
                monkey.setMaterial(material);
                monkey.setScale(2);
                getCurrentScene().addChild(monkey);
                TranslateAnimation3D anim = new TranslateAnimation3D(new Vector3(0,0,0),new Vector3(3,3,3));
                anim.setDurationMilliseconds(1000);
                anim.setRepeatMode(Animation.RepeatMode.REVERSE_INFINITE);
                anim.setInterpolator(new OvershootInterpolator());
                anim.setTransformable3D(monkey);
                getCurrentScene().registerAnimation(anim);
                anim.play();
                RotateOnAxisAnimation animation = new RotateOnAxisAnimation(Vector3.Axis.Y,360);
                animation.setDurationMilliseconds(1000);
                animation.setRepeatMode(Animation.RepeatMode.REVERSE_INFINITE);
                animation.setInterpolator(new OvershootInterpolator());
                animation.setTransformable3D(monkey);
                getCurrentScene().registerAnimation(animation);
                animation.play();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }`
