### ISSUE TITLE
Plans to add Kotlin?

### ISSUE THREAD

**Issue by creativedrewy** [Rajawali/Rajawali#2143]
This is more of a question than an issue, but are there any plans to introduce Kotlin to the codebase? I've got some cool additions I'd love to submit back but they're in Kotlin and I'd hate to have to de-factor them.

In other news, this library is incredible! Just about the perfect OGL abstraction one could hope for. Definitely a hidden gem!

**Comment by creativedrewy** [comment]
Oh, I just saw this: https://github.com/Rajawali/Rajawali/pull/2092. Safe to make PRs with Kotlin?

**Comment by ToxicBakery** [comment]
Yeah kotlin is fine to use imo as it still meets the 'pure java' goal more or less.
