### ISSUE TITLE
Record surface while rendering using camera texture

### ISSUE THREAD

**Issue by sourabhgupta811** [Rajawali/Rajawali#2154]
#### Summary
I am trying to add recording functionality into Rajawali such that i would be able to record surfaceview with cameratexture and other 3d objects.  I have successfully linked camera2 with it and i have rendered the materials on top of camera stream. I am using MediaCodec and external SurfaceTexture to record video but i am not able to record 3d objects and all i get in the recorded video is the unfiltered version. The preview is working fine but now i am stuck with the recording part. Please help me with how can i achieve this?

**Comment by contriteobserver** [comment]
There are many parts to this issue, to make sure we are all on the same page, please post up simple example of what you have now, so we can all start from the same place.

**Comment by sourabhgupta811** [comment]
Hie
I figured out that this is a problem of eglContext. Till now i was using SurfaceView from rajawali that extends GlSurfaceView and manages its own eglContext but for recording the same surface without re rendering to the external encoder surface. I will have to use the same eglContext for both screen and encoder rendering. 
See https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/RecordFBOActivity.java
For camera rendering, I have created a CameraTexture that is very similar to StreamingTexture. I will try to post a sample as soon as possible after clearing up some code of my own. I hope you can start with the given info. I was using the camerarecording pipeline similar to this project
https://github.com/MasayukiSuda/CameraRecorder-android.

**Comment by sourabhgupta811** [comment]
issue has been resolved!

**Comment by contriteobserver** [comment]
Thank-you, pull requests are always welcome.
