### ISSUE TITLE
Add/Support SepiaMaterialPlugin

### ISSUE THREAD

**Issue by sourabhgupta811** [Rajawali/Rajawali#2168]
I am trying to build a SepiaMaterialPlugin. I am trying to create plugin using SepiaEffectPass in Rajawali but i am facing issues with it. I am getting undeclared variable exception when defining variables in plugin's main method. 
For eg- 
`RVec3 gray = new RVec3("gray")`
gives an undeclared variable gray exception.
Can you provide sample code for the same or guide me to some learning resource for the same.

This is the code that i am using in main method-

```       
RVec3 fragColor = new RVec3("fragColor");
fragColor.assign("texture2D(uTexture, vTextureCoord).rgb");
RFloat gray = new RFloat("gray");
gray.assign(dot(fragColor, castVec3(0.299f, 0.587f, 0.114f)));
RVec4 color = (RVec4) getGlobal(DefaultShaderVar.G_COLOR);
color.assign("uOPACITY * vec4(gray * vec3(1.2, 1.0, 0.8), 1.0)");
```

**Comment by contriteobserver** [comment]
First off, a material plugin is different from an `EffectsPass`, a material plugin alters only one material shader, whereas a postprocessing effect alters everything.  Second we have an existing SepiaPass effect. 

One problem appears to be an unexpected interaction between `dot` and `castVec3`, this should get you there:
```
RVec3 sepia = new RVec3("sepia");
sepia.assign(castVec3(0.299f, 0.587f, 0.114f));
gray.assign(dot(fragColor, sepia));
```

**Comment by sourabhgupta811** [comment]
Hie thanks for the reply. 
Yeah, I know there is a SepiaPass and i am trying to build a material plugin to apply on a specific material only.
I used the above code but it still gives me the exception. The shader is not getting compiled. These are the shader logs-
[org.rajawali3d.materials.Material] Could not compile fragment shader:
0:29: L0002: Undeclared variable 'uTexture'
0:31: L0002: Undeclared variable 'fragColor'
0:32: L0002: Undeclared variable 'gray'

**Comment by contriteobserver** [comment]
`uTexture` is not present in material plugins, it is only found in context of postprocessing plugins. 

Material textures are given the label used in the `new Texture(String, int)` call. To access a specific texture in a material plugin, one has to pass the name into the material plugin constructor. See the `GreenScreenMaterialPlugin` for details.

**Comment by sourabhgupta811** [comment]
Thanks for the help. Issue has been resolved!
