### ISSUE TITLE
Rendering to texture crashes renderer when backgrounding/returning to app

### ISSUE THREAD

**Issue by creativedrewy** [Rajawali/Rajawali#2179]
#### Rajawali Version or Branch
This issue has been observed on both the publicly released version of Rajawali - 1.1.970 as well as the code on master. Relevant code is in `RenderToTextureFragment.java`, but I have been able to reproduce when trying to replicate the same type of code elsewhere.

#### Device and Android Version
Tested on multiple devices/OS versions as well as the Emulator. Observed on all tested environments.

#### Summary
Utilizing the code infrastructure as it exists in RenderToTextureFragment.java reacts weirdly to the Android lifecycle. You might want to go and read the steps to reproduce now to see how I have reproduced the bug. I've debugged this fairly extensively and I have some theories about what is going on, but what I can say for sure is that the way the renderer re-initializes things after resuming from lifecycle backgrounding/returning causes the crash. My running theories of what the cause is:

- When you have multiple scenes present in a renderer, they are not getting re-initialized correctly. If you comment out line 146 of `RenderToTextureFragment` (the general "render" call), you do not get the crash. But of course,  other things don't run (i.e., the animations) either
- Something with recreating/updating the geometry related to the FBO/vbo material. In playing  with various permutations of this code, I got other low-level exceptions relating to fbo/vbo memory.
- Perhaps the FBO textures are not cleaned up/re-set up properly when returning to the app

One other thing I was able to see is that generally the app would crash/error out when it hit line 1225 of TextureView.kt, when it was trying to swap buffers and the eglSurface had changed due to the lifecycle event.

In general though, having multiple scenes in the renderer is the best way to see the crash. The other post-processing examples don't have this crash because in the `onRender()` call they only render the `PostProcessingManager` class instance, and not the `general super.onRender()` call

#### Steps to Reproduce
- Open the sample app and go to the "Render To Texture" example
- Hit the home button to background the app
- Bring the app back to the foreground.

Resulting behavior: On actual devices (Galaxy S9, for example), the render surface just blanks out such that nothing is showing at all. On the emulator the app actually crashes and restarts.

#### Trace or Log Output
Unfortunately on an actual device there is not a stack trace to see. The best I've gotten is on the emulator, getting a SIGSEGV which includes `Fatal signal 11 (SIGSEGV),  fault addr 0x20`.

**Comment by contriteobserver** [comment]
Having trouble reproducing a SIGSEGV, given the example below, I am seeing only the following warning when bringing the app to the foreground:
```
com.example.rajawali.bombshellspike W/Adreno-ES20: <gl_draw_error_checks:624>: GL_INVALID_OPERATION
```
please clarify what is wrong with this test code:
```
    class SceneSwitchingRenderer extends Renderer {
        boolean sceneChangeWhenReady = false;
        Scene sceneCube;
        Scene sceneSphere;

        public SceneSwitchingRenderer(Context context) {
            super(context);
        }

        void configCubeScene(Scene scene) {
            DirectionalLight key = new DirectionalLight(-3,4,5);
            scene.setBackgroundColor(Color.BLUE);
            key.setPower(5.0f);
            scene.addLight(key);

            Material material = new Material();
            material.setColor(Color.GREEN);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setAmbientColor(Color.LTGRAY);
            material.enableLighting(true);

            Object3D obj = new Cube(2);
            obj.setMaterial(material);
            scene.addChild(obj);

            Animation3D animation = new ColorAnimation3D(Color.GREEN, Color.MAGENTA);
            animation.setDurationMilliseconds(4321);
            animation.setRepeatMode(Animation.RepeatMode.NONE);
            animation.setTransformable3D(obj);
            animation.play();
            scene.registerAnimation(animation);

            Camera camera = new Camera();
            camera.setPosition(3,4,5);
            camera.setLookAt(obj.getPosition());

            scene.addAndSwitchCamera(camera);
        }

        void configSphereScene(Scene scene) {
            DirectionalLight key = new DirectionalLight(-3,4,5);
            scene.setBackgroundColor(Color.CYAN);
            key.setPower(5.0f);
            scene.addLight(key);

            Material material = new Material();
            material.setColor(Color.RED);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setAmbientColor(Color.LTGRAY);
            material.enableLighting(true);

            Object3D obj = new Sphere(1.5f,8,4);
            obj.setMaterial(material);
            scene.addChild(obj);

            Animation3D animation = new ColorAnimation3D(Color.RED, Color.YELLOW);
            animation.setDurationMilliseconds(4321);
            animation.setRepeatMode(Animation.RepeatMode.NONE);
            animation.setTransformable3D(obj);
            animation.play();
            scene.registerAnimation(animation);

            Camera camera = new Camera();
            camera.setPosition(3,4,5);
            camera.setLookAt(obj.getPosition());

            scene.addAndSwitchCamera(camera);
        }

        @Override
        protected void initScene() {
            try {
                sceneSphere = new Scene(this);
                configSphereScene(sceneSphere);
                addScene(sceneSphere);

                sceneCube = new Scene(this);
                configCubeScene(sceneCube);
                addAndSwitchScene(sceneCube);

            } catch (Exception e) {
                Log.d(getLocalClassName(), e.getMessage());
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {
            sceneChangeWhenReady = true;
        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            if(sceneChangeWhenReady) {
                sceneChangeWhenReady = false;
                if(getCurrentScene() == sceneCube) {
                    switchScene(sceneSphere);
                    sceneCube.destroyScene();
                    configCubeScene(sceneCube);
                }
                if(getCurrentScene() == sceneSphere) {
                    switchScene(sceneCube);
                    sceneSphere.destroyScene();
                    configSphereScene(sceneSphere);
                }
            }
        }
    }
```

**Comment by creativedrewy** [comment]
Thanks for the fast response! I realize I perhaps didn't make some things clear in my original description. I'll give your sample code a try for sure, but I'm not completely sure comparing my issue and your code is apples to apples.

The issue I'm seeing appears to be specifically related to there being **_multiple scenes with one of them being rendered in an FBO/PostProcessingManager._** I'll demonstrate with these two gifs:

This first gif is the `RenderToTextureFragment.java` as it is in the repo now - no changed code at all - demonstrating the crash on an emulator:

![crash_optimized](https://user-images.githubusercontent.com/2018851/82746939-ddf1b480-9d49-11ea-81d6-e0942f264d44.gif)

This second gif shows `RenderToTextureFragment.java` without the crash. The only difference between this and the previous gif is that line 146, or the general `super.onRender(elapsedTime, deltaTime);` render call has been commented out:

![no_crash_optimized](https://user-images.githubusercontent.com/2018851/82746999-2a3cf480-9d4a-11ea-88e2-c464609e4de8.gif)

As I mentioned above, none of the animations play because the "general" `super.onRender()` call is what runs the animations and such. But this is what made me think that the issue is with the combination of the PostProcessingManager/FBOs, multiple scenes, and the lifecycle. If you comment out the "general" `super.onRender()` call, it doesn't crash on leaving the app and coming back as shown in this gif.

More evidence along these lines is that none of the other PostProcessingManager examples call both the `PostProcessingManager.render` and general `super.onRender()` call in the example renderer's `onRender` method override. Looking at GaussianBlurFilterFragment.java, in the onRender() call, _only_ the PostProcessingManager instance, or `mEffects`, has `render` called on it (line 117).

You mention in your sample code above that a workaround is to reinitialize the scene(s). I'm thinking that is the nature of the fix, but perhaps just with a PostProcessingManager twist - something I'm not quite sure how to do. The renderer base class already tries to do some resetting/re-initializing in the `onRenderSurfaceSizeChanged` method. I think the particularly relevant lines are 367-370, or this block:

```java
mTextureManager.taskReload();
mMaterialManager.taskReload();
reloadScenes();
reloadRenderTargets();
```

I have tried rearranging those lines, commenting some out, etc. Some permutations result in a different crash, some of them don't crash but also result in a renderer that looks like my second gif above (not animating/moving). But I can't quite figure out how to make OpenGL happy.

I hope this info clears things up and can aid in figuring out what is going on!

**Comment by contriteobserver** [comment]
issue #2182 may be related to this issue, please try out the patch and let us know.

**Comment by creativedrewy** [comment]
I got the fix!

The PR you mentioned didn't directly fix my issue, but trying it out helped me to start following some other lines of inquiry that led to the resolution. I've submitted a PR with the fix to the crash mentioned here as well as a memory consumption issue that the sample code had as well! It's here:

https://github.com/Rajawali/Rajawali/pull/2183

Thanks for all the help!
