### ISSUE TITLE
Add RotateOnAxisAnimation while rendering

### ISSUE THREAD

**Issue by devdivr** [Rajawali/Rajawali#2190]
Hello,
There are some examples to use animation in `initScene() but I'm trying to use RotateOnAxisAnimation while rendering so that let the object rotate with a different angle whenever onRender call. 

My implementation is below. The angle is changed by another calculation.
```
override fun onRender(ellapsedRealtime: Long, deltaTime: Double) {
        super.onRender(ellapsedRealtime, deltaTime)
      animation = RotateOnAxisAnimation(Vector3.Axis.Y, object.rotY, angle).apply {
                durationMilliseconds = 100
                transformable3D = it
                currentScene.registerAnimation(this)
                this.play()
            }
}
```
My assume is object.rotY would be changed to angle first then changed the angle to another next angle... However, object.rotY doesn't result what I expected.

Logcat is like below. First rotY is normal but it's strange from second rotY value. I rotated the object from 0.692828 to 34.160980 so the second rotY should be 34.160980 + 0.692828, right?

```
2020-06-11 18:19:32.638 E: Rotation: rotY 0.692828 -> degreesToRotate 34.160980
2020-06-11 18:19:32.655 E: Rotation: rotY 8.196591 -> degreesToRotate 26.813892
2020-06-11 18:19:32.669 E: Rotation: rotY 27.470951 -> degreesToRotate 7.586278
2020-06-11 18:19:32.688 E: Rotation: rotY 59.510819 -> degreesToRotate -24.453590
2020-06-11 18:19:32.702 E: Rotation: rotY 115.949653 -> degreesToRotate -80.892423
2020-06-11 18:19:32.720 E: Rotation: rotY -142.596856 -> degreesToRotate 177.733945
2020-06-11 18:19:32.737 E: Rotation: rotY 92.363507 -> degreesToRotate -57.169933
2020-06-11 18:19:32.753 E: Rotation: rotY -154.396134 -> degreesToRotate 189.611134
2020-06-11 18:19:32.770 E: Rotation: rotY 72.335487 -> degreesToRotate -37.120487
```

How can I animate the object every render call? I was trying to use AnimationGroup but failed.
Do I need to changed to AnimationGroup or AnimationQueue?
Thanks in advance.

**Comment by contriteobserver** [comment]
If the objective is to set the orientation ever render, then an animator is not needed, just set the orientation every render, this should get you there:
```
    class OrientationRenderer extends Renderer {
        Object3D obj;

        public OrientationRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-3, 4, 5);
            key.setPower(5.0f);
            getCurrentScene().addLight(key);

            Material material = new Material();
            material.setColor(Color.CYAN & 0xffcccccc);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setAmbientColor(Color.DKGRAY);
            material.enableLighting(true);
            material.enableTime(true);
            material.addPlugin(new FresnelMaterialPlugin(material.getAmbientColor()));

            obj = new Cube(1);
            obj.setMaterial(material);
            getCurrentScene().addChild(obj);

            getCurrentCamera().setPosition(3, 4, 5);
            getCurrentCamera().setLookAt(obj.getPosition());
        }

        @Override
        protected void onRender(long elapsedRealtime, double deltaTime) {
            super.onRender(elapsedRealtime, deltaTime);
            if(obj != null) {
                double t = elapsedRealtime/1e9f;
                double angle = Math.toDegrees(Math.sin(t));
                Quaternion q = new Quaternion(Vector3.Y, angle);
                obj.setOrientation(q);
            }
        }

        @Override
        public void onOffsetsChanged(float v, float v1, float v2, float v3, int i, int i1) {

        }

        @Override
        public void onTouchEvent(MotionEvent motionEvent) {

        }
    }
```
![2020-06-11](https://user-images.githubusercontent.com/17471201/84444121-d8271a80-abf5-11ea-8add-b7c3e08e563b.gif)

**Comment by devdivr** [comment]
> If the objective is to set the orientation ever render, then an animator is not needed, just set the orientation every render, this should get you there:
> 
> ```
>     class OrientationRenderer extends Renderer {
>         Object3D obj;
> 
>         public OrientationRenderer(Context context) {
>             super(context);
>         }
> 
>         @Override
>         protected void initScene() {
>             getCurrentScene().setBackgroundColor(Color.BLUE);
> 
>             DirectionalLight key = new DirectionalLight(-3, 4, 5);
>             key.setPower(5.0f);
>             getCurrentScene().addLight(key);
> 
>             Material material = new Material();
>             material.setColor(Color.CYAN & 0xffcccccc);
>             material.setDiffuseMethod(new DiffuseMethod.Lambert());
>             material.setAmbientColor(Color.DKGRAY);
>             material.enableLighting(true);
>             material.enableTime(true);
>             material.addPlugin(new FresnelMaterialPlugin(material.getAmbientColor()));
> 
>             obj = new Cube(1);
>             obj.setMaterial(material);
>             getCurrentScene().addChild(obj);
> 
>             getCurrentCamera().setPosition(3, 4, 5);
>             getCurrentCamera().setLookAt(obj.getPosition());
>         }
> 
>         @Override
>         protected void onRender(long elapsedRealtime, double deltaTime) {
>             super.onRender(elapsedRealtime, deltaTime);
>             if(obj != null) {
>                 double t = elapsedRealtime/1e9f;
>                 double angle = Math.toDegrees(Math.sin(t));
>                 Quaternion q = new Quaternion(Vector3.Y, angle);
>                 obj.setOrientation(q);
>             }
>         }
> 
>         @Override
>         public void onOffsetsChanged(float v, float v1, float v2, float v3, int i, int i1) {
> 
>         }
> 
>         @Override
>         public void onTouchEvent(MotionEvent motionEvent) {
> 
>         }
>     }
> ```
> 
> ![2020-06-11](https://user-images.githubusercontent.com/17471201/84444121-d8271a80-abf5-11ea-8add-b7c3e08e563b.gif)

Thanks for your answer but I want to rotate the object smoothly. If there's a huge difference in angle for very short time in 20ms, it moves like a robot.
Actually, I play a video on Sphere and rotate Sphere every single render. However, your way of letting me know didn't look like animation. Of course my way did. I rotated the object using Object.setRotY().

Sorry for my short English but I hope you can understand my intend.

**Comment by contriteobserver** [comment]
One approach to smooth changes in orientation to arbitrary angles is to use a constant theta animation, this should get you there:
```
    class ConstantThetaRenderer extends Renderer {
        Object3D obj;
        double current = 0;
        double target = 0;

        public ConstantThetaRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-3, 4, 5);
            key.setPower(5.0f);
            getCurrentScene().addLight(key);

            Material material = new Material();
            material.setColor(Color.CYAN & 0xffcccccc);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.setAmbientColor(Color.DKGRAY);
            material.enableLighting(true);
            material.enableTime(true);
            material.addPlugin(new FresnelMaterialPlugin(material.getAmbientColor()));

            obj = new Cube(1);
            obj.setMaterial(material);
            getCurrentScene().addChild(obj);

            getCurrentCamera().setPosition(3, 4, 5);
            getCurrentCamera().setLookAt(obj.getPosition());
        }

        @Override
        protected void onRender(long elapsedRealtime, double deltaTime) {
            super.onRender(elapsedRealtime, deltaTime);
            if(target-current>1) current+=(deltaTime*getFrameRate());
            if(target-current<-1) current-=(deltaTime*getFrameRate());
            obj.setOrientation(new Quaternion(Vector3.Y, -current));
            Log.i(getLocalClassName(), "deltaTime=" + deltaTime);
        }

        @Override
        public void onOffsetsChanged(float v, float v1, float v2, float v3, int i, int i1) {

        }

        @Override
        public void onTouchEvent(MotionEvent motionEvent) {
            switch (motionEvent.getAction()) {
                case MotionEvent.ACTION_DOWN:
                    target = 180 * motionEvent.getX()/(double)getViewportWidth() - 90;
                    break;
            }
        }
    }
```

**Comment by devdivr** [comment]
> One approach to smooth changes in orientation to arbitrary angles is to use a constant theta animation, this should get you there:
> 
> ```
>     class ConstantThetaRenderer extends Renderer {
>         Object3D obj;
>         double current = 0;
>         double target = 0;
> 
>         public ConstantThetaRenderer(Context context) {
>             super(context);
>         }
> 
>         @Override
>         protected void initScene() {
>             getCurrentScene().setBackgroundColor(Color.BLUE);
> 
>             DirectionalLight key = new DirectionalLight(-3, 4, 5);
>             key.setPower(5.0f);
>             getCurrentScene().addLight(key);
> 
>             Material material = new Material();
>             material.setColor(Color.CYAN & 0xffcccccc);
>             material.setDiffuseMethod(new DiffuseMethod.Lambert());
>             material.setAmbientColor(Color.DKGRAY);
>             material.enableLighting(true);
>             material.enableTime(true);
>             material.addPlugin(new FresnelMaterialPlugin(material.getAmbientColor()));
> 
>             obj = new Cube(1);
>             obj.setMaterial(material);
>             getCurrentScene().addChild(obj);
> 
>             getCurrentCamera().setPosition(3, 4, 5);
>             getCurrentCamera().setLookAt(obj.getPosition());
>         }
> 
>         @Override
>         protected void onRender(long elapsedRealtime, double deltaTime) {
>             super.onRender(elapsedRealtime, deltaTime);
>             if(target-current>1) current+=(deltaTime*getFrameRate());
>             if(target-current<-1) current-=(deltaTime*getFrameRate());
>             obj.setOrientation(new Quaternion(Vector3.Y, -current));
>         }
> 
>         @Override
>         public void onOffsetsChanged(float v, float v1, float v2, float v3, int i, int i1) {
> 
>         }
> 
>         @Override
>         public void onTouchEvent(MotionEvent motionEvent) {
>             switch (motionEvent.getAction()) {
>                 case MotionEvent.ACTION_DOWN:
>                     target = 180 * motionEvent.getX()/(double)getViewportWidth() - 90;
>                     break;
>             }
>         }
>     }
> ```

It works! Thanks for your help, I appreciate it.
