### ISSUE TITLE
How to combine multiple shapes and apply Material ones

### ISSUE THREAD

**Issue by madhawa-se** [Rajawali/Rajawali#2191]
I'm trying to create a custom shape which is combination of multiple primitive shapes.for now let's assume this is the shape i want to build.

![image](https://user-images.githubusercontent.com/9608201/84584196-dd1ae280-ae1e-11ea-8b1d-93e16971615a.png)

now i'm doing it by using add child how every i have to apply material to all primitives.
```
        Object3D box1 = shape.getBox();
        Object3D box2 = shape.getBox();
        Object3D box3 = shape.getBox();

        box1.setMaterial(material);
        box2.setMaterial(material);
        box3.setMaterial(material);

        box1.addChild(box2);
        box1.addChild(box3);
```

Is there anyway to combine all geometries of this shape and apply Material ones? as you can see in above code i had to do it three times

**Comment by contriteobserver** [comment]
Not yet, there is some work on [GLES30 instancing](https://software.intel.com/content/www/us/en/develop/articles/opengl-es-30-instanced-rendering.html), which would get you there, but it is not ready yet.

FYI, recommend making the parent an empty `Object3D`, after adding the children, call `Object3D.setRenderChildrenAsBatch(true)`, as this will  improve performance and resource efficiency.

**Comment by madhawa-se** [comment]
@contriteobserver  thanks so much

**Comment by madhawa-se** [comment]
@contriteobserver  thanks so much
