### ISSUE TITLE
how to hightlight particular area in a 3D obj model, using Rajawali 3D android

### ISSUE THREAD

**Issue by mayank09** [Rajawali/Rajawali#2194]
i am using a Face 3D obj model, and animating on SurfaceView, how can we hightlight the eyes and mouth on that model, can anyone guide how to start with it

**Comment by mayank09** [comment]
i am using a Face 3D obj model, and animating on SurfaceView, how can we hightlight the eyes and mouth on that model, can anyone guide how to start with it

**Comment by contriteobserver** [comment]
Typically, an obj model consists of a family of surfaces, one for each material. Each member of the family has a name, so one can select a specific surface with the `Object3D.getChildByName()` method. Obtain the member's material with the `Object3D. getMaterial()` method, then, to highlight a specific material, call `Material.setColor()` and `Material.setColorInfluence()` methods.

**Comment by mayank09** [comment]
this sounds really helpful, let me try and let you know, Thanks!!

**Comment by mayank09** [comment]
But how i know, the name of child which is represnting the eyes area of the model?

**Comment by mayank09** [comment]
I have printed all the childs and subchilds like this

for(int i = 0; i < earthSphere.getNumChildren();i++){
                 Log.d("Child", earthSphere.getChildAt(i).getName());
                 Object3D obj = earthSphere.getChildAt(i);
                 for(int j = 0; j < obj.getNumChildren(); j++){
                     Log.d("SubChild", obj.getChildAt(j).getName());

                 }
             }


 Child: default
Child:  pSphere1
SubChild: left_eye
SubChild: right_eye

So, this way i got the eyes area, but now how i get the mouth area?

**Comment by contriteobserver** [comment]
Typically, models have different surfaces for the eyes and mouth, but maybe your model does not have a different material for the mouth. Either choose another model that has separated the mouth, or import your model into [Blender](https://www.blender.org/), highlight the mouth, change the material, and export the model.

**Comment by mayank09** [comment]
thanks buddy, i am really new in this,

Object3D obj = earthSphere.getChildByName("pSphere1").getChildByName("right_eye");
        Object3D obj1 = earthSphere.getChildByName("pSphere1").getChildByName("left_eye");
        /*DirectionalLight mLight = new DirectionalLight(-3,-6,-3);
        getCurrentScene().addLight(mLight);*/

        Material phong = new Material();
        phong.setColor(Color.RED);
        phong.setSpecularMethod(new SpecularMethod.Phong());
        phong.enableLighting(true);

        obj.setMaterial(phong);
        obj1.setMaterial(phong);

I am doing like this, but everytime the eye color gets changed, whenever i open it

Also, i try to do this with 3D animation class:

queue = new AnimationQueue();
        ColorAnimation3D anim = new ColorAnimation3D(Color.CYAN, Color.BLACK);
        Object3D obj = earthSphere.getChildByName("pSphere1").getChildByName("right_eye");
        anim.setTransformable3D(obj);
        anim.setDurationMilliseconds(5000);
        queue.addAnimation(anim);

Both the ways i am not able to get the desired output for eye hightlight

**Comment by contriteobserver** [comment]
By default, if a model has a texture, `LoaderOBJ parse()` will `Material.setColorInfluence(0)`, this means that the color is not added to the render, calling `Material.setColorInfluence(1)`, or any other desired value between 0 and 1 will proportionately add the color to the material.

**Comment by mayank09** [comment]
When i call material method of the child object it returns null

Material material = obj.getMaterial();  //return null
        material.setColorInfluence(1);

**Comment by mayank09** [comment]
I guess the model is not correctly defined, i will try with some other model and let you know

**Comment by contriteobserver** [comment]
That is odd, any object with geometry, like the eye, must have a material, or the renderer crashes.

**Comment by contriteobserver** [comment]
here is a simple textured cube to experiment with:
```
mtllib coloredcube01.mtl
o Cube
v 1 1 -1
v 1 -1 -1
v 1 1 1
v 1 -1 1
v -1 1 -1
v -1 -1 -1
v -1 1 1
v -1 -1 1
vt 0.625 0.500
vt 0.875 0.500
vt 0.875 0.750
vt 0.625 0.750
vt 0.125 0.500
vt 0.375 0.500
vt 0.375 0.750
vt 0.125 0.750
vt 0.375 0.000
vt 0.625 0.000
vt 0.625 0.250
vt 0.375 0.250
vt 0.625 1
vt 0.375 1
vn 0 1 0
vn 0 -1 0
vn -1 0 0
vn 1 0 0
vn 0 0 1
vn 0 0 -1
usemtl height
s off
f 1/1/1 5/2/1 7/3/1 3/4/1
f 6/5/2 2/6/2 4/7/2 8/8/2
usemtl width
f 8/9/3 7/10/3 5/11/3 6/12/3
f 2/6/4 1/1/4 3/4/4 4/7/4
usemtl depth
f 4/7/5 3/4/5 7/13/5 8/14/5
f 6/12/6 5/11/6 1/1/6 2/6/6
```
material file
```
# Material Count: 3

newmtl depth
Ns 225.000000
Ka 1.000000 1.000000 1.000000
Kd 0.000000 0.854993 0.000000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Ka depth.png
map_Kd depth.png

newmtl height
Ns 323.999994
Ka 1.000000 1.000000 1.000000
Kd 0.854993 0.000000 0.000000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Ka height.png
map_Kd height.png

newmtl width
Ns 225.000000
Ka 1.000000 1.000000 1.000000
Kd 0.000000 0.000000 0.854993
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2
map_Ka width.png
map_Kd width.png
```
textures below:
![width](https://user-images.githubusercontent.com/17471201/85498363-64d9bd00-b594-11ea-8e37-526f2c1b1cdd.png)
![depth](https://user-images.githubusercontent.com/17471201/85498434-863aa900-b594-11ea-8475-1cee6e569fa3.png)
![height](https://user-images.githubusercontent.com/17471201/85498338-58edfb00-b594-11ea-964a-bf0cdaeeafda.png)

**Comment by mayank09** [comment]
Thank you buddy this is really helpful i will try with this model

**Comment by mayank09** [comment]
[face.txt](https://github.com/Rajawali/Rajawali/files/4823177/face.txt)

I was using this model, 
By the way i have asked one designer to built a new model with eyes and mouth layers and material

**Comment by contriteobserver** [comment]
I cleaned up the UV mapping in the example, this shoud get you started:
```
        @Override
        protected void initScene() {
            try {
                LoaderOBJ loader = new LoaderOBJ(this, R.raw.coloredcube01_obj);
                loader.parse();
                Object3D obj = loader.getParsedObject();
                getCurrentScene().addChild(obj);

                Object3D height = obj.getChildByName("Cube");
                height.getMaterial().setColor(Color.YELLOW);
                height.getMaterial().setColorInfluence(1);

                DirectionalLight key = new DirectionalLight();
                key.setPosition(-3,-4,5);
                key.setPower(2f);
                key.setLookAt(obj.getPosition());
                getCurrentScene().addLight(key);

                DirectionalLight fill = new DirectionalLight();
                fill.setPosition(3,4,5);
                fill.setPower(2f);
                fill.setLookAt(obj.getPosition());
                getCurrentScene().addLight(fill);

                getCurrentScene().setBackgroundColor(Color.CYAN);
                getCurrentCamera().setPosition(3,-4,5);
                getCurrentCamera().setLookAt(obj.getPosition());

                Animation3D anim = new ColorAnimation3D(Color.YELLOW, Color.TRANSPARENT);
                anim.setTransformable3D(height);
                anim.setDurationMilliseconds(3000);
                anim.setRepeatMode(Animation.RepeatMode.INFINITE);
                getCurrentScene().registerAnimation(anim);
                anim.play();

            } catch (Exception e) {
                Log.d(getLocalClassName(), e.getMessage());
            }
        }
```
![2020-06-23](https://user-images.githubusercontent.com/17471201/85507015-69a76c80-b5a6-11ea-9c0c-1b3dbd8c2edd.gif)

**Comment by mayank09** [comment]
Thank you so much buddy, really appreciate the support and help you have done to solve this problem
