### ISSUE TITLE
How to create a Camera that rotates Around an Objects local Axis similar to ArcballCamera but not quite.

### ISSUE THREAD

**Issue by gulguruth** [Rajawali/Rajawali#2197]
Hi, I've been struggling almost 2 weeks to create a camera that rotates around an object local axis, I mean, swiping horizontally would rotate around the objects Up Axis always keeping it horizontal in view, and swiping vertically to affect the pitch of the Camera rotating around the objects Right Vector all the way up to a topDown view of the object, I have a plane object that can be in any position over a sphere (earth), always looking at (0,0,0) and I want the camera to keep the plane horizontal with earth down independently of the position (if its on the north pole, south pole, the plane should always be horizontal and the Earth bellow), and rotate Around the plane local Up Axis, I tried with ArcballCamera but it rotates always in the World axis giving some weird viewing angles, I tried modifying it but I couldn't manage to do it.
I also tried other approach where I would find a new position for the camera, then transform that position to the planes coordinate system calculating the difference between the World axis and the plane local Axis but it didn't work,
I'll highly appreciate any pointers into how to achieve this...

**Comment by contriteobserver** [comment]
does #2063 address this issue or is more information needed?

**Comment by gulguruth** [comment]
The TrukingCamera was not quite what I needed but it helped me figure out the problem in my custom camera Implementation, (i was not calling the cameras setUpAxis() properly so the camera was never horizontal to the plane, thank you very much for the reply, I'll try to post the final implementation of my OrbitalCamera for anyone in the future needs something similar.

**Comment by contriteobserver** [comment]
That would be great, contributions are always welcome.

**Comment by gulguruth** [comment]
Ok, I have something king of working now, What I needed was a Camera that rotated around the local Axis of an object, to keep it horizontal all the time even if the object rotated.

What I ended up doing was to build a 3x3 matrix with the dot products of the different axis to transform the new position of the camera to the local space of the object, (compute the rotation between the world axis vs local axis)
`        

`var localToWorldTransform = Matrix4()`

        localToWorldTransform.doubleValues[0] = XAxisWorld.dot(XAxisLocal)
        localToWorldTransform.doubleValues[1] = XAxisWorld.dot(YAxisLocal)
        localToWorldTransform.doubleValues[2] = XAxisWorld.dot(ZAxisLocal)
        localToWorldTransform.doubleValues[3] = 1.0

        localToWorldTransform.doubleValues[4] = YAxisWorld.dot(XAxisLocal)
        localToWorldTransform.doubleValues[5] = YAxisWorld.dot(YAxisLocal)
        localToWorldTransform.doubleValues[6] = YAxisWorld.dot(ZAxisLocal)
        localToWorldTransform.doubleValues[7] = 1.0

        localToWorldTransform.doubleValues[8] = ZAxisWorld.dot(XAxisLocal)
        localToWorldTransform.doubleValues[9] = ZAxisWorld.dot(YAxisLocal)
        localToWorldTransform.doubleValues[10] = ZAxisWorld.dot(ZAxisLocal)
        localToWorldTransform.doubleValues[11] = 1.0`

Then I get the xDegrees and yDegrees from swipe, use those angles to calculate a new position around the object:

```
       var camX = (mRadius * cos(yDegrees * DEG_TO_RAD) * sin(xDegrees * DEG_TO_RAD))
        var camY = (mRadius * sin(yDegrees * DEG_TO_RAD))
        var camZ = (mRadius * cos(yDegrees * DEG_TO_RAD) * cos(xDegrees * DEG_TO_RAD))
```

that position is in world coordinates so I use the matrix built with the dot products to transform this position:
`var transformedPosition = cameraLocalPosition.transform(localToWorldTransform)`

and finally I set the up vector of the camera to be the same as the up vector of the object I'm rotating around:
`currentCamera.setUpAxis(objUpAxis)`

if the object moves, you have to update the matrix.
