### ISSUE TITLE
Is there a way to make an object invisible but keep its's functionality? 

### ISSUE THREAD

**Issue by gulguruth** [Rajawali/Rajawali#2227]
I Have a Scene where I have a Sphere that acts as a helper to place some objects and move them (objects are child of sphere) I would like to disable the renderer but still have the invisible sphere usable, is there a way to accomplish this? I tried setVisible(false) but this turns it completely off, is there another way?

**Comment by contriteobserver** [comment]
Easiest way is to use a default `Object3D` as the parent. By default, an `Object3D` has no geometry and is not rendered.

**Comment by gulguruth** [comment]
Thanks! setting the material transparent and sphere.setTransparent(true) worked, look like a had a conflicting setting and was showing weird colors that why it didn't worked.
