### ISSUE TITLE
faces disappear when swiping

### ISSUE THREAD

**Issue by saugatrai33** [Rajawali/Rajawali#2260]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.970@aar

#### Device and Android Version
Andriod Studio 4.1.1,  POCOPHONE F1, Android 10, MIUI 12

#### Summary
It is a .OBJ model. When I swipe, the faces keeps disappearing like bubbles. This happens to all child object als. You can see in sample video too.

https://user-images.githubusercontent.com/22369188/104151641-a8e3c080-5405-11eb-82e3-fdf9abe4c411.mp4

#### Steps to Reproduce
[Describe reproducable steps and sample code]
I have tried Object3D methods setX, setY and setZ to different values.

double legLengthData = 0.05, legBreadthData = 0.05, legHeightData = 0.5;
double translateX = 0.3125f, translateZ = 0.3125f, translateY = -0.5;//0.3125;

        for (int i = 0; i < object3D.getNumChildren(); i++) {
            Object3D childObj = object3D.getChildAt(i);
            String childName = childObj.getName();
            if (childName.equalsIgnoreCase("main_design.015_Plane.031")) {
                childObj.setX(-1 * translateX * lengthData);
                childObj.setZ(-1 * translateZ * breadthData);
                childObj.setY(translateY * heightData);

            }
            else if (childName.equalsIgnoreCase("Pillow_02.002_Cube.007")) {
                childObj.setX(-1 * translateX * lengthData);
                childObj.setZ(-1 * translateZ * breadthData);
                childObj.setY(translateY * heightData);

            }
}

#### Trace or Log Output
No message in logcat.

**Comment by contriteobserver** [comment]
Fragments (pixels) are only drawn between the camera `NearPlane` (default 1.0) and  `FarPlane` (default 120.0).
Change them with `Camera.setNearPlane()` and `Camera.setFarPlane`

**Comment by saugatrai33** [comment]
> Fragments (pixels) are only drawn between the camera `NearPlane` (default 1.0) and `FarPlane` (default 120.0).
> Change them with `Camera.setNearPlane()` and `Camera.setFarPlane`

Thank you sir.
