### ISSUE TITLE
How to get the pivot point of a 3d model .obj file ?

### ISSUE THREAD

**Issue by saugatrai33** [Rajawali/Rajawali#2261]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.970@aar

#### Device and Android Version
Android Studio 4.1.1,  POCOPHONE F1, Android 10, MIUI 10

#### Summary
Get the center of a 3d object. 
object3D.getGeometry().getVertices();
This one gets the vertices.
Are there such method to get the center point of a 3d model. 
Or we have to calculate manually.

#### Steps to Reproduce
        for (int i = 0; i < object3D.getNumChildren(); i++) {
            Object3D childObj = object3D.getChildAt(i);
            String childName = childObj.getName();
            if (childName.equalsIgnoreCase("main_design.015_Plane.031")) {
                // get pivot point of here.

            }
            else if (childName.equalsIgnoreCase("Pillow_02.002_Cube.007")) {
                // Get pivot point here.

            }
}

**Comment by contriteobserver** [comment]
The pivot point of all objects parsed by `LoaderOBJ` are `Vector3.ZERO` relative to the parent.
More generally, the position of `Geometry.getBoundingSphere()` works.

**Comment by saugatrai33** [comment]
I got 0, 0, 0.

        for (int i = 0; i < object3D.getNumChildren(); i++) {
            Object3D childObj = object3D.getChildAt(i);
            String childName = childObj.getName();
            Log.d(TAG, "initScene: pivot point - "
                    +```
 childObj.getGeometry()
                    .getBoundingSphere().getPosition()
```);
}

**Comment by contriteobserver** [comment]
As posted, the pivot point of all objects parsed by `LoaderOBJ` are `Vector3.ZERO` relative to the parent.
For objects that are not loaded by `LoaderOBJ`, the position of Geometry.getBoundingSphere() works.

**Comment by saugatrai33** [comment]
https://user-images.githubusercontent.com/22369188/104151641-a8e3c080-5405-11eb-82e3-fdf9abe4c411.mp4

Currently, there are 8 groups of obj file. By chance, are there any method available in rajawali library to get the center point of each group of 3d obj ? Like mattress group, pillow group, etc. Is there any posibility to get the center point of a mattress group given its vertices ? Likewise for other groups as well. Calculating manually is overwhelming. So, looking for automatic methods.

For example, using mid-point formula, we can calculate the center of a rectangle given its vertices.
Similarly, I am looking to get mid-point or center point or pivot point of a 3d each group given its vertices.
I may also be mistaken.

Thank you sir.

**Comment by saugatrai33** [comment]
Faces keeps disappearing. So, inorder to solve it, I was thinking of different techniques. @contriteobserver you have already answered to #2260. So I will look for it.

Thank you sir @contriteobserver

**Comment by contriteobserver** [comment]
Are you looking for the centroid (average of all vertices) of each child?
```
                for(int i=0;i<obj.getNumChildren(); i++ ) {
                    float xyz[] = new float[3];
                    Vector3 centroid = new Vector3(0,0,0);
                    Object3D child = obj.getChildAt(i);
                    FloatBuffer buffer = child.getGeometry().getVertices();
                    while(buffer.hasRemaining()) {
                        buffer.get(xyz);
                        centroid.add(xyz[0], xyz[1], xyz[2]);
                    }
                    centroid.divide((float)child.getGeometry().getNumVertices());
                    Log.i(getLocalClassName(), "centroid=" + centroid.toString());
                }
```

**Comment by saugatrai33** [comment]
Thank you @contriteobserver  sir. Yes sir, it is. Sorry for my mistaken on my questions.
