### ISSUE TITLE
Animating 3D Object

### ISSUE THREAD

**Issue by saugatrai33** [Rajawali/Rajawali#2265]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.970@aar master

#### Device and Android Version
POCOPHONE F1, Android 10, MIUI 12, Android Studio 4.1.2

#### Summary
Its a double bed. I want to make it interactive like open and close of 2 drawers.
For example, I have placed a button and when this is pressed, the drawer of the bed should be open. 
When close button is pressed, the drawer closes.

https://user-images.githubusercontent.com/22369188/105681758-ad39ce80-5f19-11eb-8d10-abc5cd7d8c89.mp4

#### Steps to Reproduce
I am using RotateAroundAnimation3D.
I have also tried TranslateAnimation3D from https://github.com/Rajawali/Rajawali/wiki/v0.9-Tutorial-13-Animation-Classes.
I have tried following code.

    public void openDrawer() {

        Animation3D anim = new RotateAroundAnimation3D(
                Vector3.ZERO, Vector3.Axis.Z, 0.5
        );
        anim.setTransformable3D(sedDrawer1);
        anim.setDurationDelta(15);
        anim.setRepeatMode(Animation.RepeatMode.NONE);
        anim.play();
        getCurrentScene().registerAnimation(anim);

        Animation3D anim2 = new RotateAroundAnimation3D(
                Vector3.ZERO, Vector3.Axis.Z, 0.5);
        anim2.setTransformable3D(sedDrawer2);
        anim2.setDurationDelta(15);
        anim2.setRepeatMode(Animation.RepeatMode.NONE);
        anim2.play();
        getCurrentScene().registerAnimation(anim2);

    }

    public void closeDrawer() {
        Animation3D anim = new RotateAroundAnimation3D(Vector3.ZERO, Vector3.Axis.Z, 0.5);
        anim.setTransformable3D(sedDrawer1);
        anim.setDurationDelta(15);
        anim.setRepeatMode(Animation.RepeatMode.INFINITE);
        anim.play();
        getCurrentScene().registerAnimation(anim);

        Animation3D anim2 = new RotateAroundAnimation3D(Vector3.ZERO, Vector3.Axis.Z, 0.5);
        anim2.setTransformable3D(sedDrawer2);
        anim2.setDurationDelta(15);
        anim2.setRepeatMode(Animation.RepeatMode.INFINITE);
        anim2.play();
        getCurrentScene().registerAnimation(anim2);
    }

#### Trace or Log Output
No Logcats.

**Comment by contriteobserver** [comment]
`TranslateAnimation3D` should get you there:
```
    static class DrawerRenderer extends Renderer {

        public DrawerRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.GRAY);

                DirectionalLight key = new DirectionalLight(-4,-4,-4);
                key.setPower(5/4f);
                getCurrentScene().addLight(key);

                LoaderOBJ loader = new LoaderOBJ(this, R.raw.drawers_obj);
                loader.parse();
                Object3D obj = loader.getParsedObject();
                getCurrentScene().addChild(obj);

                Animation3D anim = new TranslateAnimation3D(Vector3.ZERO, Vector3.Y.multiply(3/4f));
                anim.setTransformable3D(obj.getChildByName("Middle.Drawer"));
                anim.setDurationDelta(3);
                anim.setRepeatMode(Animation.RepeatMode.REVERSE_INFINITE);
                anim.setInterpolator(new AccelerateDecelerateInterpolator());
                anim.play();
                getCurrentScene().registerAnimation(anim);

                getCurrentCamera().setUpAxis(Vector3.Axis.Z);
                getCurrentCamera().setPosition(-5,3,4);
                getCurrentCamera().setLookAt(obj.getPosition().add(0,0,2));
            } catch (Exception e) {
                Log.e(getClass().getSimpleName(), e.getMessage());
            }
        }

        @Override
        public void onOffsetsChanged(float v, float v1, float v2, float v3, int i, int i1) {

        }

        @Override
        public void onTouchEvent(MotionEvent motionEvent) {
        }
    }
```
![drawer](https://user-images.githubusercontent.com/17471201/105751319-b10a2880-5efa-11eb-9c4b-bdcadf2741cb.gif)

**Comment by saugatrai33** [comment]
@contriteobserver  Thank you so much sir.
