### ISSUE TITLE
improve object names generated by LoaderOBJ

### ISSUE THREAD

**Issue by contriteobserver** [Rajawali/Rajawali#2301]
#### Rajawali Version or Branch
Associations between sibling objects generated by `LoaderOBJ` are opaque. 
An improved naming scheme that simplifies the identification of how an object instance relates to the stored model is desired.

Related to issue #2294 

#### Device and Android Version
master

#### Summary
Rajawali implements one object per material, however, models containing many materials are not uncommon. When `LoaderOBJ` encounters an object displaying more than one material, it reconciles this conflict by separating the parent object into children, one for each material. However, identifying how this child geometry is associated with each material is problematic, as each child is given a randomly generated name.

#### Steps to Reproduce
```
        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.CYAN & Color.GRAY);

                DirectionalLight key = new DirectionalLight(-4,-4,-4);
                key.setPower(5/4f);
                getCurrentScene().addLight(key);

                LoaderOBJ loader = new LoaderOBJ(this, R.raw.posing1doll_obj);
                loader.parse();
                Object3D obj = loader.getParsedObject();
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                Log.i(getClass().getSimpleName() + ".InitScreen", "object graph\n" + loader.toString());

                getCurrentCamera().setUpAxis(Vector3.Axis.Y);
                getCurrentCamera().setPosition(3,2,1);
                getCurrentCamera().setLookAt(obj.getPosition().clone().add(0,1,0));
            } catch (Exception e) {
                Log.e(getClass().getSimpleName(), e.getMessage());
            }
        }
```

#### Current Log Output
```
CurrentRenderer.InitScreen: object graph
    -->GROUP default
    	-->Object5521
    	-->Object4497
    	-->Object1506
    	-->Object1356
    	-->Object1444
    	-->Standing_Pose
```

#### Desired Log Output
```
DesiredRenderer.InitScreen: object graph
    -->GROUP default
    	-->Arm.Left3549
    	-->Arm.Right4840
    	-->Leg.Left2670
    	-->Leg.Right4299
    	-->Head1699
    	-->Standing_Pose
```

**Comment by jonathanchh1** [comment]
Excellent. i see that you guys implemented it yesterday. Thats amazing. How can i start utilizing the changes?

**Comment by contriteobserver** [comment]
I just build the tree tip locally, but I understand it is also available from [jitpack](https://jitpack.io)

@hannesa2 understands jitpack better than I do, but one should be able to a `develop-SNAPSHOT`package from there.

**Comment by hannesa2** [comment]
`implementation 'com.github.rajawali:rajawali:develop-SNAPSHOT'` could be a solution.
Sometimes it's better to use a SHA1 instead a branch-SNAPSHOT , but this is your decision.

Btw, you can do it from your fork as well, then you have more control. eg
`implementation 'com.github.jonathanchh1:Rajawali:<SOMETHING>'` but your fork is outdated, that's why it's not working.
Please see details here https://jitpack.io/#jonathanchh1/Rajawali
