### ISSUE TITLE
libEGL: call to OpenGL ES API with no current context (logged once per thread)

### ISSUE THREAD

**Issue by jonathanchh1** [Rajawali/Rajawali#2310]
Hi, i have an issue that i have noticed on my two rajawali demos and it happens once the activity goes into background and comes back to foreground. Essentially, the application crashes and display's this message _**libEGL: call to OpenGL ES API with no current context (logged once per thread)**_  and i have checked my code. i am not accessing the opengl Thread in multiple places. can you guys assist with this? 

Regards. Thank you!

**Comment by contriteobserver** [comment]
are you calling `Renderer.onPause()` and `Renderer.onResume()` from the `Activity`?
```
    @Override
    protected void onPause() {
        super.onPause();
        renderer.onPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        renderer.onResume();
    }
```

**Comment by jonathanchh1** [comment]
Yes, i am. When i test it on the emulator and i don't see an issue but when i do on my pixel 3, thats when i notice it. 

this is what my set up looks like:

  ### override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
        binding?.main = this
        binding?.executePendingBindings()
        mToolbar = binding?.toolbar
        surfaceView = binding?.rajwaliSurface
        seekBar = binding?.seekBar
        surfaceView?.setEGLContextClientVersion(3)
        surfaceView?.setFrameRate(60.0)

        onStartRenderer()
}
### override fun onStartRenderer() {
            renderer = Object3DRenderer(this, R.raw.obj_skeleton_selectable)
            surfaceView?.setSurfaceRenderer(renderer)
            isSurfaceViewRendered.set(true)
            scaleGestureDetector = ScaleGestureDetector(this, ScaleListener())
            gestureDetector = GestureDetector(this, RotationListener())
            renderer?.sceneCachingEnabled = true
    }

###     override fun onStart() {
        super.onStart()
        //   onStartRenderer()
    }

###     override fun onResume() {
        super.onResume()
        if (surfaceView != null && isSurfaceViewRendered.get() == true) {
            renderer?.onResume()
        }
    }

###     override fun onPause() {
        super.onPause()
        if (surfaceView != null && isSurfaceViewRendered.get() == true) {
            renderer?.onPause()
        }
    }

**Comment by contriteobserver** [comment]
which version exhibits this behavior?

**Comment by jonathanchh1** [comment]
yes it does but i believe its because i was using the SurfaceView instead of the TexturedView.. when i switched everything seems to be fine.
