### ISSUE TITLE
Live Video Stream with 3d Model + OpenCV

### ISSUE THREAD

**Issue by crankdaworld** [Rajawali/Rajawali#264]
Hi,
I have been using min3d earlier in my augmented app and now planning to use Rajawali. My app is on Android , for markerless augmented reality. I have seen your sample application “RajawaliTransparentSurfaceActivity”. I would like to overlay live camera video stream on the “monkey_ser” 3d object. Specifically using Opencv.
Any pointers would be appreciated.

Regards
Imran

**Comment by smemamian** [comment]
hi

Do u find any solution?
