### ISSUE TITLE
Problem in landscape mode

### ISSUE THREAD

**Issue by sesese** [Rajawali/Rajawali#274]
When you run an example on RajawaliExample app in landscape mode, the LogCat write this:
12-19 19:57:51.311: D/OpenGLRenderer(17223): GL error from OpenGLRenderer: 0x501
12-19 19:57:51.311: E/OpenGLRenderer(17223):   GL_INVALID_VALUE
12-19 19:57:51.381: D/OpenGLRenderer(17223): GL error from OpenGLRenderer: 0x501
12-19 19:57:51.381: E/OpenGLRenderer(17223):   GL_INVALID_VALUE

................. many of these .........

12-19 19:57:59.831: D/OpenGLRenderer(17223): GL error from OpenGLRenderer: 0x501
12-19 19:57:59.831: E/OpenGLRenderer(17223):   GL_INVALID_VALUE

and when you tap back button to return in the example list
12-19 19:57:59.851: A/libc(17223): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 17223 (awali.tutorials)

Instead in my app when I rotate the tablet (Nexus 7), the app crashes with this error in LogCat:

A/libc(16874): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 16874

Edit: the problem occurs only when you rotate the device. If the app runs directly in landscape mode there isn't problem.

**Comment by drmarkpowell** [comment]
Wow thanks for that workaround, I also had to use android:hardwareAccelerated="false" for integrating v0.9 Rajawali into my app in my Activity. This setting avoids the seg fault on rotation as advertised.
