### ISSUE TITLE
Plane with a bitmap to fill the screen

### ISSUE THREAD

**Issue by sanjith11** [Rajawali/Rajawali#353]
Hello Everyone,

I am planning to have an image which fills up the background.For this I have a 3D plane
and I am adding a texture as the image. Now when I do this I find the plane is not filling up the screen it is always a square and it fills the screen partially.Below is the code snippet of what I am trying to do

	   
		SimpleMaterial smp = new SimpleMaterial();
		this.backGroundMaterial = smp;
		this.plane = new Plane(10, 15, 1, 1);
                plane.setZ(10.0f);
		plane.setRotZ(-90);
		plane.setMaterial(this.backGroundMaterial);
                addChild(plane);

Thanks!

**Comment by jwoolston** [comment]
Closing this issue as stale. ScreenQuads can provide this feature.
