### ISSUE TITLE
Make parsers thread safe

### ISSUE THREAD

**Issue by ToxicBakery** [Rajawali/Rajawali#370]
### Issue
It seems trying to parse in threads does not work properly. When this library was created devices mostly had only 1 core processors and it would have been pointless to try and thread something that is going to be maxing that core. Now that most devices are multi-core it may be useful to make model loading thread friendly. 

### Pros
* Potentially faster model loading
* A model manager for managing loading could permit additional optimizations to aid users.

### Cons
* Someone would have to do the work and we already have a pretty big back log
* Loading from the file system is expensive and multiple threads does not necessarily mean a speed gain would actually occur.
* This would add to the complexity of the model parsers which seem to already have enough problems without throwing more complexities at them.

Anyone have any thoughts on this?

**Comment by jwoolston** [comment]
#1388 implements the first required step for this. Additional steps are to allow for lazy material/texture/shader creation.
