### ISSUE TITLE
Memory growing tested! 

### ISSUE THREAD

**Issue by alenko** [Rajawali/Rajawali#391]
Ok, 
Today i used my livewallpaper for 10h, so i see what is and how is going on.

Wallpapers starts at 30MB of memory usage, after 10h of usage i got 38?
The reason? I dont know.

All what is in this live wallpaper is a constantly moving object around 1 axis, and traveling in circle

Animations are based on time handler that i already posted on 1 closed issue, and this shouldt be problem. Basicly only time handler that updates the scene each 16ms
like
3dObj.setRotZ(getRotZ()+0.01f)
mybe this 

or

mybe  what cause this "little grow" is the incresing time var?

its like only time += 0.001f;

but i rly doubt.

Tested the Island Night from Dav, and this issue is almost the same.
But it was from 32mb to 35 i think but in 30 min, i dont know if grow up more.

**Comment by FurknHypr** [comment]
Good job bro, 10h so crayz
