### ISSUE TITLE
Depth Sorting in the renderer

### ISSUE THREAD

**Issue by M0nk3yofdoom** [Rajawali/Rajawali#427]
I'm using the 2000Planes example and have been looking now at how to sort the images. I want to sort either by depth in relationship to the camera or by the size of the plane displayed so that the smaller/darker planes are covered up. I'm new to Rajawali and OpenGL so some direction would be great. I've looked inside the RajawaliRenderer and can see there seems to be a built in sort by z method which is enabled to true (mEnableDepthBuffer???) but I'm not sure how to access the stack of planes and what is the best way to sort them in relation to a moving camera.

**Comment by marjan89** [comment]
Hello, I would also like some help/direction on the issue. Thanks.

**Comment by jwoolston** [comment]
@marjan89 This issue is over 4 years old. Please create a new one detailing the support you need

**Comment by marjan89** [comment]
@jwoolston Will do, thanks.
