### ISSUE TITLE
Different render results on different GPUs

### ISSUE THREAD

**Issue by AndrewJo** [Rajawali/Rajawali#429]
So I am getting very close to putting finishing touches on my first live wallpaper and sent it to few of my friends for testing. Results came back very differently for each GPU models. Anyone know why this is happening?
## Mali-400 GPUs

Devices Tested: Samsung Galaxy S2, Samsung Galaxy S3

This is basically how it's supposed to look (as rendered on my Galaxy S3):
![Screenshot_2013-02-26-20-00-53](https://f.cloud.github.com/assets/3170805/197572/36f8f178-803e-11e2-9a4e-4efe222e3689.jpg) 
Nightside
![Screenshot_2013-02-26-19-52-22](https://f.cloud.github.com/assets/3170805/197575/3a975bda-803e-11e2-856e-41448d91e821.jpg)
## Adreno-320 GPUs

Devices Tested: LG Google Nexus 4, LG Optimus G

Adreno-320 GPUs have some weird issues where atmosphere cuts off abruptly. First I thought it was face culling issues. It's not since it happens even when I turn off culling.
![Screenshot_2013-02-23-19-11-15](https://f.cloud.github.com/assets/3170805/197609/8fce5e68-803f-11e2-9333-5cb9319971f4.jpg)
## Nvidia ULP GeForce (Tegra)

Devices Tested: Asus Google Nexus 7

It's similar to Adreno-320's case except it cuts off as white pixels instead of transparent pixels. All Nvidia based GPUs have same problems as below:
![Screenshot_2013-02-26-10-15-49](https://f.cloud.github.com/assets/3170805/197653/df5337f0-8040-11e2-986c-9b0f8f1db113.jpg)
## PowerVR SGX-540

Devices Tested: Samsung Galaxy Nexus, Samsung Galaxy Tab 2

SGX-540 GPUs just outright refuses to render the atmosphere completely:
![Screenshot_2013-02-26-10-00-09](https://f.cloud.github.com/assets/3170805/197591/e5c7b2b6-803e-11e2-937b-99c8c67c3db4.jpg)

I can't find it now but I know I read somewhere here in the issues list that for-loops aren't supported in GLSL shaders but I don't see why the results are so different (especially since it works fine on my phone)! One thing to note is that even though Adreno-320 doesn't render correctly, Adreno-200, 220, 225 GPUs render this completely fine as I tested on the HTC phones including older phones like Nexus One and Evo 4G.

I've been banging my head at this now for several hours. Someone else come across similar phenomena where different phones show completely different results? I guess this is something that iPhone developers never worry about.

The shader I'm using is pretty much identical to Sean O'Neil's atmosphere scattering GLSL shader on the GPU Gems 2 CD resources. They're just adapted for Rajawali's uniform variable names.

If anyone wants to test this on their phones with LogCat to see any shader errors, please e-mail me. I'll send you the APK. I really hope to publish this within a week or two.

**Comment by mousebird** [comment]
Pardon the comment on an ancient issue.  

I'm in the processing of implementing a standard outside-the-atmosphere shader in OpenGL ES 2.0.  I was wondering if the source code for the above shader was lying around anywhere.  I'd like to compare it to mine to avoid some of the same issues.
