### ISSUE TITLE
Null Pointer Exception when calculating bounding volume of a complex object

### ISSUE THREAD

**Issue by guavadrone** [Rajawali/Rajawali#442]
03-04 15:19:25.906: D/renderer(2226): just called collisionwithfloor
03-04 15:19:25.906: D/renderer(2226): objects not null
03-04 15:19:25.926: W/dalvikvm(2226): threadid=11: thread exiting with uncaught exception (group=0x41d4b930)
03-04 15:19:25.926: E/AndroidRuntime(2226): FATAL EXCEPTION: GLThread 5022
03-04 15:19:25.926: E/AndroidRuntime(2226): java.lang.NullPointerException
03-04 15:19:25.926: E/AndroidRuntime(2226):     at rajawali.bounds.BoundingBox.calculateBounds(BoundingBox.java:101)
03-04 15:19:25.926: E/AndroidRuntime(2226):     at rajawali.bounds.BoundingBox.<init>(BoundingBox.java:92)
03-04 15:19:25.926: E/AndroidRuntime(2226):     at rajawali.Geometry3D.getBoundingBox(Geometry3D.java:719)
03-04 15:19:25.926: E/AndroidRuntime(2226):     at rajawali.tutorials.MyRajawaliRenderer.collisionWithFloor(MyRajawaliRenderer.java:194)
03-04 15:19:25.926: E/AndroidRuntime(2226):     at rajawali.tutorials.MyRajawaliRenderer.onDrawFrame(MyRajawaliRenderer.java:142)
03-04 15:19:25.926: E/AndroidRuntime(2226):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
03-04 15:19:25.926: E/AndroidRuntime(2226):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
03-04 15:19:26.486: E/libEGL(2226): call to OpenGL ES API with no current context (logged once per thread)

The bits at the top are debug messages telling me that my collision detection method has been called and that the objects it has been called on are not null. The exception is coming from Rajawali code rather than from my code, but the object I'm trying to run the command on is one that has been taken from blender and exported using the methods detailed elsewhere. Is it possible at all to calculate the bounding volume of a complex object like this? Will I need to shove a transparent cuboid on top of my object and use that for collision detection?

**Comment by thkr91** [comment]
This is because rajawali only calculate geometry of one child in a model. So you have to reference only one child per bounding shape.
For example you have a car, having five children - car body and car tyres. You have to reference car body to define a box. So use

model name.getChildbyIndex(int).getGeometry().getBoundingBox()
 or 
modelName.getChildbyName(child name).getBoundingBox()

http://rugex.net/

**Comment by JehandadK** [comment]
@rugex How can I get one BoundingBox for a Object creating children? I have opened a new issue #1774. My object is correct unlike the author of this post.
