### ISSUE TITLE
When setting wallpaper the application crash - dequeueBuffer: SurfaceTexture has been abandoned!

### ISSUE THREAD

**Issue by asrep** [Rajawali/Rajawali#622]
I don't know what happened but now when ever I try to set a wallpaper on my tablet (from rajawali framework, it crash) - even wallpapers that worked before, crash now with this error (even when installing an old apk's from the past that had no problem at all)..

I even tried to download 
Asteroid Apophis LWP FREE
https://play.google.com/store/apps/details?id=com.tepeshakcode.asteroidsfree
and I get the same issue.

This the log cat:
04-28 16:06:08.719: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.719: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.719: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.719: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.719: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.719: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.719: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.719: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.719: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.719: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.719: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.729: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.729: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.729: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.729: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.729: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.729: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.729: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.729: E/SurfaceTexture(137): [com.tepeshakcode.asteroidsfree.Service] dequeueBuffer: SurfaceTexture has been abandoned!
04-28 16:06:08.729: E/[EGL-ERROR](1875): void __egl_platform_dequeue_buffer(egl_surface_):1234: failed to dequeue buffer from native window (0x196c310); err = -19, buf = 0x0
04-28 16:06:08.889: E/AndroidRuntime(1875): FATAL EXCEPTION: GLThread 186
04-28 16:06:08.889: E/AndroidRuntime(1875): java.lang.RuntimeException: eglSwapBuffers failed: EGL_BAD_ALLOC
04-28 16:06:08.889: E/AndroidRuntime(1875):     at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1229)
04-28 16:06:08.889: E/AndroidRuntime(1875):     at android.opengl.GLSurfaceView$EglHelper.swap(GLSurfaceView.java:1187)
04-28 16:06:08.889: E/AndroidRuntime(1875):     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1514)
04-28 16:06:08.889: E/AndroidRuntime(1875):     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1267)

**Comment by dantesrevelion** [comment]
hi everyone a just did this on my activity to stop trowing that log, videoR is my Render class

 @Override
    protected void onStop() {
        videoR.stopRendering();
        videoR.mediaPlayer.pause();
        super.onStop();
    }
