### ISSUE TITLE
Project Reorganization and Cleanup

### ISSUE THREAD

**Issue by AndrewJo** [Rajawali/Rajawali#624]
So right now, Rajawali framework itself, RajawaliExamples, and RajawaliWallpaperTemplates are all on separate repositories.

I think it would be easier for us to simultaneously update the examples if we bring all three of these into the single repo.

Maybe the structure can be something like this?
```
Project root
|__Rajawali
|__RajawaliExamples
|__RajawaliWallpaperTemplates
```

Usability-wise, I think this is better since the user can get all three with a single checkout and we'll only have to keep track of one Issues threads. Users are already reporting RajawaliExamples and WallpaperTemplate issues here for the library repository so I think this makes more sense.

What do you guys think?

**Comment by jwoolston** [comment]
Closing this issue as no longer relevant due to Android Studio. We should open a new issue to discuss in the new context.
