### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by jayschwa** [Rajawali/Rajawali#628]
RajawaliExamples has traditionally served as an informal way to test the framework. However, with the increased development activity and march towards a stable API, I think something a little more rigorous is desirable.

Ideally, the test suite should utilize as much of the standard Android testing stuff as possible, be easy to run, be easy to maintain, be as automated as possible, and give everyone a free pony.

I'll be having a little more time on my hands in a couple weeks (I hope so, anyway), so this is something I'll try to break some ground on.

**Comment by jwoolston** [comment]
Future development of testing will continue with the upcoming architecture overhaul.

**Comment by jwoolston** [comment]
This is an ongoing task in Camden Hells development, but the core foundation is in place.
