### ISSUE TITLE
Billboard a plane that always front of the camera

### ISSUE THREAD

**Issue by androidder** [Rajawali/Rajawali#681]
Face plane in front of the camera ever, but how? 

I tried mObj.setLookat(mCam.getPos...);

but not worked.

**Comment by flankechen** [comment]
@MasDennis thanks a lot for your code.
I try this and it seems that it just sets the plane lookat/face the camera, not moving with the camera. 

I am using RajawaliVR and wants a billboard always in front of the camera while the camera yaw, pitch and roll.

any idea about this?
