### ISSUE TITLE
Easier Serialization

### ISSUE THREAD

**Issue by ToxicBakery** [Rajawali/Rajawali#706]
So serialization is pretty inconvenient. As such I figured I would take a go at making life a little easier. 
## Github Repo

https://github.com/ToxicBakery/Rajawali-Serializer
## Play Store

Link will be live soon.
https://play.google.com/store/apps/details?id=com.ToxicBakery.apps.rajawaliserializer

**Comment by amolgupta** [comment]
@ToxicBakery  App not available in my country. Please update on play store if thats not a problem.

**Comment by ToxicBakery** [comment]
It is no longer available in any country. Use the Away3D tool for exporting objects to AWD whenever possible.
