### ISSUE TITLE
Camera.setFieldOfView() does not have an effect

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#712]
@androidder discovered in #709 that calling `Camera.setFieldOfView()` does not take effect immediately. The cause of this is nothing forcing the camera to update its projection matrix.

**Comment by drmarkpowell** [comment]
Until 1.0 is ready for production use, you can workaround this in 0.9 by calling this function to set the projection matrix after calling setFieldOfView():
```java```
  mCamera.setFieldOfView(45/mScaleFactor);
  mCamera.setProjectionMatrix(mSurfaceView.getWidth(), mSurfaceView.getHeight());
```

**Comment by jwoolston** [comment]
> Until 1.0 is ready for production use

Getting so close.
