### ISSUE TITLE
Problem with Ripple effect in Rajawali Examples

### ISSUE THREAD

**Issue by RoopKumarReddy** [Rajawali/Rajawali#748]
Hi,
I am trying to run Rajawali Examples. Everything works fine except the Ripple Effect example. I am getting the following error in logcat when I select the Touch Ripple Effect from the menu. " OpenGL Error: invalid operation".

How ever the when I downloaded the same example app from the play store, the same works fine. Anyhelp is greatly appreciated.

Thanks,
Roop

**Comment by ry-narola** [comment]
I have created custom render class which extends RajawaliRenderer  to create touch filter from old library code and written code inside initScene() method like below:

SimpleMaterial planeMat = new SimpleMaterial();

        Bitmap texture = null;

        if (bimtapFromActivity != null) {
            texture = bimtapFromActivity;
        } else if (ResourceId != 0) {
            texture = BitmapFactory.decodeResource(this.mContext.getResources(), ResourceId);
        }

      //  texture =  scaleCenterCrop(texture, Utility.getDeviceHeight(mContext),Utility.getDeviceWidth(mContext));
        planeMat.addTexture(this.mTextureManager.addTexture(texture));
        Plane plane = new Plane(3.0f, 3.0f, 1,1 );
        plane.setRotZ(-90.0f);
        plane.setScale(2.8f);
        plane.setMaterial(planeMat);
        addChild(plane);

        this.mFilter = new TouchRippleFilter();
        this.mFilter.setRippleSize(35.0f);

        //added by ry
        //this.mFilter.setRippleSpeed(10.0f);

        this.mPostProcessingRenderer.setQuadSegments(QUAD_SEGMENTS);
        this.mPostProcessingRenderer.setQuality(PostProcessingQuality.HIGH);
        addPostProcessingFilter(this.mFilter);

My bitmap which I am applying gets stretched..any solution I have tried changing the scale params as well..any suggestions will be really helpful
