### ISSUE TITLE
Rajawali Examples app Anchor Stream update

### ISSUE THREAD

**Issue by MasDennis** [Rajawali/Rajawali#750]
With the new release coming up it might be a good idea to think about the examples app as well.
There are quite a few examples now so it is time to better organize them. 

- [x] reorganize the examples and put them in categories
- [x] refactor class names. remove the "Rajawali" prefix
- [x] ~~support different resolutions by fully utilizing the "drawable-xxx" folders instead of just "drawable"~~
- [x] Replace old serialized models with other models.
- [ ] replace the Blender monkey with a Rajawali mascot
     - ~~@Davhed seems to be making good progress here.~~
     - ~~@Artimunor has found a model that looks nice and has contacted the creator for a license.~~ We were not able to gain a license for this model.
- [x] create a Rajawali mascot. Rajawali means "eagle" in Indonesian so I'm thinking in [this direction](https://www.google.co.uk/search?site=&tbm=isch&source=hp&biw=1456&bih=912&q=eagle+3d&oq=eagle+3d&gs_l=img.3..0l5j0i24l5.447.1503.0.1621.8.6.0.2.2.0.33.170.6.6.0...0.0...1ac.1.12.img.qadYum8ahAM#tbm=isch&sa=1&q=eagle+head&oq=eagle+head&gs_l=img.3..0l10.2120.2695.2.2773.5.4.0.1.1.0.71.160.4.4.0...0.0...1c.1.12.img.girzn5BVE9s&bav=on.2,or.r_cp.r_qf.&bvm=bv.46471029,d.d2k&fp=9552360830e83537&biw=1456&bih=912)
- [x] ~~have an thumbnail next to each example~~
- [x] link to the example on Github
- [x] a link to each team member's G+ account?
- [x] Rajawali news feed. We could use the [Rajawali community page](https://plus.google.com/u/0/communities/116529974266844528013) as a data source.
- [x] give some of the less sexy examples a bit of creative love
   - Possible #746 for animations?
- [x] Update wallpaper example and add to the examples app with settings.

Your input is very much appreciated, as always :ok_hand:

**Comment by jwoolston** [comment]
I am closing this issue now as I don't see anyone having the combination of time/expertise to create an eagle model. We will gladly take one if it becomes available.
