### ISSUE TITLE
Picking and Moving 3d Object

### ISSUE THREAD

**Issue by programmer5000** [Rajawali/Rajawali#753]
i modified Picking Example to move the object after picking it
to convert from Screen space to world space i tried RajawaliRenderer.UnProgect
but it gave me NaN for x,z,y
so i used the algorithm described in the following link after modified it to get z 
http://magicscrollsofcode.blogspot.com/2010/10/3d-picking-in-android.html
my problem now that after moving the object in any direction it goes too large (scaling problem)
how to move it and keep it in the same size ?
thanks in advance

**Comment by GeorgePractics23** [comment]
@Jhonnybsg I used the following class and it worked for me.

https://github.com/Rajawali/Rajawali/blob/master/examples/src/main/java/org/rajawali3d/examples/examples/interactive/TouchAndDragFragment.java
