### ISSUE TITLE
Update RajawaliRenderer log message

### ISSUE THREAD

**Issue by jwoolston** [Rajawali/Rajawali#794]
Just so we don't forget, I'm creating this issue for use to update the `RajawaliRenderer` startup log message.

**Comment by ToxicBakery** [comment]
Its like a year and a half late but finally! Nice work man.

**Comment by jwoolston** [comment]
Thanks. I've been pushing hard to get this done once and for all. Its pretty bad when I have dreams of what else needs to be done.
