### ISSUE TITLE
EllipticalOrbitAnimation3D only work at 0,0,0 focalpoint

### ISSUE THREAD

**Issue by androidder** [Rajawali/Rajawali#815]
EllipticalOrbitAnimation3D only work at 0,0,0 focalpoint

when I set to 0,1,-10 this is not working anymore

my object centerpoint at 0,1,-10, and I want a simple circle/rotatearound animation at Axis.Z distance 1.0, but this is not working. 
can somebody try it?

**Comment by TBog** [comment]
**EllipticalOrbitAnimation3D** does not honor **mNormal** when **mFocalPoint** is not (0, 0, 0)
This was tested on the latest master

One can fix this if one replaces
		mScratch2.setAll(normalCenter_x, normalCenter_y, normalCenter_z);
with
		mScratch2.setAll(mNormal);
