### ISSUE TITLE
Full screen scaling of a model causes performance issues on Samsung devices

### ISSUE THREAD

**Issue by peterskeetero** [Rajawali/Rajawali#817]
Has anyone else seen this issue - I thought I would raise it as a possible issue but not sure where to start..If I have a simple model and it is sized say half screen width, then changing between home screens and pulling the notification bar is fine, but as soon as I pinch zoom and make the model larger so it fills the screen I then get lag issues when navigating between home screens and pulling the notification bar down. This seems to happen on Samsung devices (tested on note 2 and SG3) but is fine on the Nexus 4 - full screen scale dosnt affect its performance...
Thanks,
Peter

**Comment by minimalviking** [comment]
I'm experiencing same issue with latest Master. I'm testing on 2 phones: Samsung Galaxy Note 4 and Xperia z3 Compact.
I create a sphere with 128*128 segments, applying material with texture and Lambert diffuse and then do touch rotation and scaling.
On samsung average fps is ~30 when the sphere is scaled to fill more than the screen, and ~59 when sphere is small. On the Xperia it's always ~59 no matter the scaling.

This must have something to do with the material - if I just set an empty material `mSphere.setMaterial(new Material());`
then fps is always ~59 on the samsung.

**Comment by ToxicBakery** [comment]
Its not surprising, the GPU appears to be fairly limited compared to other devices.

http://techreport.com/review/27539/samsung-galaxy-note-4-with-the-exynos-5433-processor/4

How large is the texture? A 128*128 sphere shouldn't be a problem but a large texture may be.
