### ISSUE TITLE
Dynamically Loading 3D model

### ISSUE THREAD

**Issue by nileshlg2003** [Rajawali/Rajawali#901]
Is it possible to download a 3D model from remote server on button click event in android and render it in real time using rajawali?
if it is possible can you please explain me how to do it?

**Comment by sanjhapps** [comment]
Gives me an Error :

E/Rajawali﹕ [org.rajawali3d.materials.Material] Could not compile fragment shader:
E/Rajawali﹕ Shader log: Fragment shader compilation failed.
