### ISSUE TITLE
Very strange behavior involving the default RajawaliRenderer camera. 

### ISSUE THREAD

**Issue by Farshooter92** [Rajawali/Rajawali#998]
This bug has me very flustered. I have a class that simply renders out a 3D object to the screen. I noticed that the camera ignored my object completely when I decided to change the position of the camera to be perfectly aligned on the Y axis above the object. I am using the same model that is featured in the RajawaliExamples project. I will give the details of two scenarios below. There is only a 0.1 difference in the camera's position between the two scenarios.

This is the first scenario which demonstrates the camera rendering properly.
The code:
```java
        Vector3 cameraTarget = new Vector3(0.0f, -5.0f, 0.0f);
		testModel.setPosition(cameraTarget);
		getCurrentCamera().setPosition(0.0f, 16f, 0.1f); // Notice the 0.1f in the Z coordinate

		// Print Data to make sure the camera is looking down
		Log.i(TAG, "Camera Pos: " + getCurrentCamera().getPosition().toString());
		Log.i(TAG, "Camera Rot: " + getCurrentCamera().getRotation().toString());
		Log.i(TAG, "Camera Target: " + cameraTarget.toString());
		getCurrentCamera().setLookAt(cameraTarget);
```
The LogCat:
08-01 20:55:25.460: I/MainRenderer(4720): Camera Pos: 0.0, 16.0, 0.1
08-01 20:55:25.460: I/MainRenderer(4720): Camera Rot: 0.0, 0.0, 0.0
08-01 20:55:25.460: I/MainRenderer(4720): Camera Target: 0.0, -5.0, 0.0

Screenshot:
![screenshot_2013-08-01-21-11-42](https://f.cloud.github.com/assets/4539982/898437/2614599e-fb11-11e2-9667-5a4169390097.png)

Finally, this is the scenario which fails to render properly:
The code:
```java
		Vector3 cameraTarget = new Vector3(0.0f, -5.0f, 0.0f);
		testModel.setPosition(cameraTarget);
		getCurrentCamera().setPosition(0.0f, 16f, 0.0f);// The 0.0f as the Z coordinate is the only change from the previous code

		// Print Data to make sure the camera is looking down
		Log.i(TAG, "Camera Pos: " + getCurrentCamera().getPosition().toString());
		Log.i(TAG, "Camera Rot: " + getCurrentCamera().getRotation().toString());
		Log.i(TAG, "Camera Target: " + cameraTarget.toString());
		getCurrentCamera().setLookAt(cameraTarget);
```
The only thing that has changed is the Z coordinate in the getCurrentCamera().setPosition(0.0f, 16f, 0.0f); statement.

The LogCat:
08-01 21:18:00.925: I/MainRenderer(5681): Camera Pos: 0.0, 16.0, 0.0
08-01 21:18:00.925: I/MainRenderer(5681): Camera Rot: 0.0, 0.0, 0.0
08-01 21:18:00.925: I/MainRenderer(5681): Camera Target: 0.0, -5.0, 0.0

Even though you can probably use your imagination, I included a screenshot below of the bug.
![screenshot_2013-08-01-21-23-15](https://f.cloud.github.com/assets/4539982/898455/4fefd0b2-fb12-11e2-8707-09d40f55e573.png)

Anyone have any ideas?

**Comment by jwoolston** [comment]
There has been a lot of work done on the orientation system. I am closing this issue for now as it is in reference to old code. If you can still reproduce this issue, please let me know.
